### ISSUE TITLE
No make file found while  build and install the Python wrapper

### ISSUE THREAD

**Issue by NickStrain** [google/sentencepiece#1000]
I am following these commands % git clone https://github.com/google/sentencepiece.git 
% cd sentencepiece
% mkdir build
% cd build
% cmake ..
% make -j $(nproc) // while doing these step "Makefile is not found "

Please HELP!

**Comment by taku910** [comment]
This steps is not for Python wrapper, but for C++ library.  It would be easy to install the Python module via pip command.
Anyway, if make command is not installed, you would like to install all the tools required to build the library.

````
% sudo apt-get install cmake build-essential pkg-config libgoogle-perftools-dev
````

**Comment by NickStrain** [comment]
thanks
