### ISSUE TITLE
Tokenize at the word level without spacers nor joiners

### ISSUE THREAD

**Issue by HURIMOZ** [google/sentencepiece#1001]
I want to tokenize at the word level without spacers nor joiners. Is that possible?
In fact, I want to leverage pretrained embeddings and Iʻm not able to leverage them when the tokens carry spacers and joiners.
Also, is it possible to keep joiners and spacers and still leverage embeddings effectively? My pretrained embeddings do not carry any spacers nor joiners.

**Comment by taku910** [comment]
How is the "word level" defined here?　The definition is not that clear when CJK is included. Specific examples would be helpful.

**Comment by HURIMOZ** [comment]
Donʻt worry, I was able to source subword pretrained embeddings.
Thank you.
