### ISSUE TITLE
Build sentencepiece with mingw

### ISSUE THREAD

**Issue by Kreijstal** [google/sentencepiece#1006]
How can we build sentencepiece with mingw, setup.py assumes windows==msvc

**Comment by taku910** [comment]
It seems that cmake supports mingw.   The following site might be useful.
https://stackoverflow.com/questions/59095842/cmake-mingw-compilation-on-windows-without-needing-the-g-mingw-makefiles-f

We do not officially support mingw, so this is all the information we can provide at this time. Any contribution is appreciated. Thank you.
