### ISSUE TITLE
Tokenization for phonetic languages

### ISSUE THREAD

**Issue by divyeshrajpura4114** [google/sentencepiece#1009]
Hi,

Is there any way we can define a set of sub-words to be not split but still considered for token generation. This is especially required for phonetically rich languages like Hindi.

Ex: मैं दिव्येश राजपुरा हूं  (I am Divyesh Rajpura)
In the above example, the sub-words such as, मैं (me), दि (di), व्ये (vye), पु (pu), रा (ra), हूं (hu) should never get split and should be considered as a single unit when generating BPE tokens

Thanks & Regards,
Divyesh Rajpura

**Comment by taku910** [comment]
In general, it is not possible to define the constraint not to split the token. For instance, we cannot merge all numeric characters e.g., 0-9 we will see infinite number of tokens with this merges rule after training.   Does this phonetic merge rule can generate infinite combinations of substrings?

**Comment by taku910** [comment]
Will close this issue on 5/31.

**Comment by divyeshrajpura4114** [comment]
Sure. I have figured another work around and it seems working fine as of now. Thanks!

**Comment by divyesh-r** [comment]
@taku910, I can see there are some new options are added regarding Subword Learning. 

```
seed_sentencepieces_file (string, default: "")
shrinking_factor (double, default: 0.75)
num_sub_iterations (int32, default: 2)
```

I feel these option can be used provide the initial subwords as describe in the previous message (मैं, दि, व्ये, पु, रा, हूं) 

Is my understanding correct?
