### ISSUE TITLE
Runtime error on iOS

### ISSUE THREAD

**Issue by l3utterfly** [google/sentencepiece#1010]
After building for iOS 17, I get this error when loading a model:
```
sentencepiece::SentencePieceProcessor srcSPM, destSPM;
    auto loadSrcStatus = srcSPM.Load(modelPathStr + "/source.spm");
    auto loadDestStatus = destSPM.Load(modelPathStr + "/target.spm");
```

Error:
```
[libprotobuf FATAL /Users/runner/work/1/b/ios_framework/intermediates/iphoneos_arm64/Release/_deps/protobuf-src/src/google/protobuf/stubs/common.cc:83] This program was compiled against version 3.14.0 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.21.12).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/Users/username/Documents/myprogram/cpp/sentencepiece/src/builtin_pb/sentencepiece_model.pb.cc".)
```

**Comment by taku910** [comment]
The error message describes the root cause.   incompatible protobuf library are used in *.cc and *.h. I guess this library is built with non-standard way.   Could you provide the details of how this SentencePiece library was built?

**Comment by l3utterfly** [comment]
I cloned the master branch, and generated the xcodeproj file via: `cmake .. -G Xcode -DCMAKE_TOOLCHAIN_FILE=../cmake/ios.toolchain.cmake -DPLATFORM=OS64`

That's it. I'm linking against the static library in my iOS project.

**Comment by l3utterfly** [comment]
I looked through the cmake file, by default sentencepiece uses the pre-built generated protobuf. It seems `SPM_PROTOBUF_PROVIDER=internal` by default. Is the generated protobuf files commited to this repo generated by protobuf 3.14?

**Comment by taku910** [comment]
> I looked through the cmake file, by default sentencepiece uses the pre-built generated protobuf. It seems `SPM_PROTOBUF_PROVIDER=internal` by default. Is the generated protobuf files commited to this repo generated by protobuf 3.14?

Right. SPM_PROTOBUF_PROVIDER=package will allow you to build the protobuf already installed on your system.

**Comment by l3utterfly** [comment]
@taku910 I'm not sure if I understand correctly. If I use `SPM_PROTOBUF_PROVIDER=internal`, shouldn't the built sentencepiece library use internally provided protobuf library included in this project? Why would it look for protobuf 3.14 that's installed in the iPhone?

**Comment by taku910** [comment]
It is possible that the linkage is mismatched: in the case of internal, sentencepiece is linking to the internal library. On the other hand, if the parent project (iPhone) is trying to link another version of the sentencepiece, duplication will occur.
SPM_PROTOBUF_PROVIDER=package does only find the sentencepiece package that is installed as a library on the standard linux system., i.e., *so, *h, *a files are all available.   Probably the libraries required to build sentence pieces are not available.

**Comment by iprovalo** [comment]
@l3utterfly were you able to find a work-around?  I am seeing the same issue.  

Thank you!

**Comment by l3utterfly** [comment]
@iprovalo I believe the issue was with iOS minimum version. I recently upgraded to support minimum version iOS 15.5 and the problem went away

**Comment by iprovalo** [comment]
@l3utterfly thank you very much!

**Comment by iprovalo** [comment]
@l3utterfly I am still running into this issue if I use a static xcframework.  

The way I am building it is by first adding this modification to CMakeList.txt:

```
if(CMAKE_SYSTEM_NAME STREQUAL "iOS")
    macro(set_xcode_property TARGET XCODE_PROPERTY XCODE_VALUE)
        set_property(TARGET ${TARGET} PROPERTY
                XCODE_ATTRIBUTE_${XCODE_PROPERTY} ${XCODE_VALUE})
    endmacro(set_xcode_property)
endif()
```

Then creating both a dynamic and static xcframework like so (I tried the deployment target 15.5, same results):

```
set -e

TEAM_ID="XXX"
DEPLOYMENT_CONFIG=Release
ARCH="arm64;x86_64"
DEPLOYMENT_TARGET="15.5"


SOURCE_DIR="src/"
SOURCE_3RD_PARTY_DIR="third_party/"
BUILD_DIR=build-ios
DEST_HEADER_DIR="${BUILD_DIR}/include"

rm -Rf "${BUILD_DIR}"

cmake -B${BUILD_DIR} -GXcode -DCMAKE_SYSTEM_NAME=iOS \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=$DEPLOYMENT_TARGET \
    -DCMAKE_XCODE_ATTRIBUTE_DEVELOPMENT_TEAM="$TEAM_ID" \
    -DCMAKE_OSX_ARCHITECTURES=$ARCH

mkdir -p "${DEST_HEADER_DIR}"

cd ${BUILD_DIR}

xcodebuild -configuration $DEPLOYMENT_CONFIG -sdk iphoneos -target sentencepiece
xcodebuild -configuration $DEPLOYMENT_CONFIG -sdk iphoneos -target sentencepiece-static

xcodebuild -configuration $DEPLOYMENT_CONFIG -sdk iphonesimulator -target sentencepiece
xcodebuild -configuration $DEPLOYMENT_CONFIG -sdk iphonesimulator -target sentencepiece-static

cd ../

find "${SOURCE_DIR}" -name '*.h' | while read -r header; do
    relative_dir=$(dirname "${header#${SOURCE_DIR}/}")
    echo "copying $header to ${DEST_HEADER_DIR}/$relative_dir"
    mkdir -p "${DEST_HEADER_DIR}/${relative_dir}"
    cp "${header}" "${DEST_HEADER_DIR}/${relative_dir}"
done
echo "Headers copied to ${DEST_HEADER_DIR}"

find "${SOURCE_3RD_PARTY_DIR}" -name '*.h' | while read -r header; do
    relative_dir=$(dirname "${header#${SOURCE_3RD_PARTY_DIR}/}")
    echo "copying $header to ${DEST_HEADER_DIR}/${SOURCE_3RD_PARTY_DIR}/$relative_dir"
    mkdir -p "${DEST_HEADER_DIR}/${SOURCE_3RD_PARTY_DIR}/${relative_dir}"
    cp "${header}" "${DEST_HEADER_DIR}/${SOURCE_3RD_PARTY_DIR}/${relative_dir}"
done
echo "Third party Headers copied to ${DEST_HEADER_DIR}"

DEVICE_DIR=${BUILD_DIR}/src/${DEPLOYMENT_CONFIG}-iphoneos
SIMULATOR_DIR=${BUILD_DIR}/src/${DEPLOYMENT_CONFIG}-iphonesimulator
XCFRAMEWORK_DIR=${BUILD_DIR}/${DEPLOYMENT_CONFIG}-universal

xcodebuild -create-xcframework \
    -library ${DEVICE_DIR}/libsentencepiece.a \
    -headers ${DEST_HEADER_DIR} \
    -library ${SIMULATOR_DIR}/libsentencepiece.a \
    -headers ${DEST_HEADER_DIR} \
    -output ${XCFRAMEWORK_DIR}-static/sentencepiece.xcframework


xcodebuild -create-xcframework \
    -library ${DEVICE_DIR}/libsentencepiece.0.0.0.dylib \
    -headers ${DEST_HEADER_DIR} \
    -library ${SIMULATOR_DIR}/libsentencepiece.0.0.0.dylib \
    -headers ${DEST_HEADER_DIR} \
    -output ${XCFRAMEWORK_DIR}/sentencepiece.xcframework

```

**Comment by iprovalo** [comment]
I ended up wrapping the static sentencepiece lib in an XCode Framework, and it worked.

**Comment by SabiQG** [comment]
> I ended up wrapping the static sentencepiece lib in an XCode Framework, and it worked.

Hi @iprovalo ,

Thanks for sharing that this approach worked for you! I'm glad to hear you were able to resolve the issue by wrapping the static `sentencepiece` library in an Xcode Framework.

I'm currently attempting the same thing, as I've been running into compilation errors trying to integrate `sentencepiece` directly.

Would you be able to share any details or steps on how you created the Xcode Framework wrapper for the static library? Any insights into your project setup or configuration would be greatly appreciated, as I'm a bit stuck on the compilation errors on XCode right now.

Thanks in advance for any guidance you can offer!

**Comment by SabiQG** [comment]
> > I ended up wrapping the static sentencepiece lib in an XCode Framework, and it worked.
> 
> Hi [@iprovalo](https://github.com/iprovalo) ,
> 
> Thanks for sharing that this approach worked for you! I'm glad to hear you were able to resolve the issue by wrapping the static `sentencepiece` library in an Xcode Framework.
> 
> I'm currently attempting the same thing, as I've been running into compilation errors trying to integrate `sentencepiece` directly.
> 
> Would you be able to share any details or steps on how you created the Xcode Framework wrapper for the static library? Any insights into your project setup or configuration would be greatly appreciated, as I'm a bit stuck on the compilation errors on XCode right now.
> 
> Thanks in advance for any guidance you can offer!

Just wanted to follow up—I was able to get it working as well!

Wrapping the static `sentencepiece` library in an Xcode framework did the trick.

**Comment by NathHorrigan** [comment]
@SabiQG - Could you share your xcframeowrk wrapper please?
