### ISSUE TITLE
Convert SentencePiece .vocab format to OpenNMT-py .onmt_vocab format

### ISSUE THREAD

**Issue by HURIMOZ** [google/sentencepiece#1016]
Hi, Iʻm looking for a Python script to convert SentencePiece .vocab files to OpenNMT-py .onmt_vocab format. SentencePiece vocab files have negative values and we need positive values for the frequency of the words when using OpenNMT-py.

**Comment by taku910** [comment]
The numerical values in the vocab files are the score of each token.  The definition depends on the model format.

- BPE:  merger preference
- Unigram:  log probability.  

exp(log prob) will be roughly equivalent to the frequency or occurrence prob.
