### ISSUE TITLE
I want to obtain a model file using my vocab!

### ISSUE THREAD

**Issue by scj0709** [google/sentencepiece#1017]
Hello!
I have my own vocab file.
For example, it looks like this:
![image](https://github.com/google/sentencepiece/assets/40060713/6d664d49-b575-456a-9496-3d5ca9eedead)
I want to get a .model file from this vocab file.
How should I do it?
Please help me.

**Comment by taku910** [comment]
We can write the model file manually. The model file is stored as protobuf.
However,  manual modificafiton/creation of model files is unsupported and please do at your own risk.

https://github.com/google/sentencepiece/issues/473
