### ISSUE TITLE
Training with a custom base vocabulary and handling reserved tokens

### ISSUE THREAD

**Issue by rteehas** [google/sentencepiece#1052]
Hi,

I am attempting to train a BPE-based sentencepiece model on a corpus with a custom base vocabulary (~32K tokens which I map to unicode before training). When training, I encounter this warning: 

```
Reserved chars are found. Skipped
```
Looking into the code, it seems like certain characters are reserved as `kUNKStr` (e.g. [here](https://github.com/google/sentencepiece/blob/master/src/trainer_interface.cc#L390)). Is there a way to reset these or to pass by custom base vocabulary so that these sentences are not skipped?

**Comment by taku910** [comment]
Currently no. Please fix the relevant code and then rebuild and try to get it working.
