### ISSUE TITLE
num_threads for spm_train

### ISSUE THREAD

**Issue by sooheon** [google/sentencepiece#109]
Even though the default num_threads is 16, the load on the CPU is mainly concentrated on one: 
<img width="1226" alt="screen shot 2018-06-18 at 1 15 27 pm" src="https://user-images.githubusercontent.com/302945/41517916-af2ea8dc-72f9-11e8-9400-1781a505dff4.png">

Is this just due to the type of load?

**Comment by taku910** [comment]
--num_threads is enabled only when SPM training with --model_type=unigram.  
spm_encode and spm_decode are executed with a single thread.
In addition, the number of threads is determined best-effort-basis, not guaranteed.
