### ISSUE TITLE
Bad alloc

### ISSUE THREAD

**Issue by mgrzeszczak** [google/sentencepiece#133]
Hello, when running the following on a file with over 5mln sentences

`spm.SentencePieceTrainer.Train('--input=... --model_prefix=prefix --vocab_size=50000')`

I'm getting this error:

`trainer_interface.cc(235) LOG(INFO) Done! 5175523 sentences are loaded
unigram_model_trainer.cc(117) LOG(INFO) Using 2000000 sentences for making seed sentencepieces
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
`

Is this memory issue? How much RAM do I need to execute this operation?

**Comment by taku910** [comment]
Yes, it is simply out-of-memory.  

SentencePiece loads entire lines into memory before training. 

You might want to try  --mining_sentence_size=1000000

If it doesn't work, you can make the value smaller.

**Comment by mgrzeszczak** [comment]
It worked! Thanks for the help.

**Comment by alejandrojcastaneira** [comment]
I got a similar error after this operation:

```
Final character coverage=0.999511
trainer_interface.cc(435) LOG(INFO) Done! preprocessed 8266227 sentences.
terminate called after throwing an instance of 'std::bad_alloc'
```
would be also requiring a larger amount of ram?

How could I prevent this?

Best regards
