### ISSUE TITLE
Decoding from ids with UNK tokens

### ISSUE THREAD

**Issue by mgrzeszczak** [google/sentencepiece#134]
The behaviour of the following function calls is strange:
```
>>> p.DecodeIds(p.EncodeAsIds('test ^^'))
'test  \u2047 '
```
If '^^' is unknown, why is it decoded as **\u2047** and not unk token ?

It's properly encoded into ids:
```
>>> p.EncodeAsIds('test ^^') 
[2528, 6, 0]
```

**Comment by taku910** [comment]
This is somehow expected. 

Short answer is that U+2047 https://www.compart.com/en/unicode/U+2047 is a sort of reserved token meaning unknown.

First, we no longer know the original surface string when converting the input into id sequences. 
So EncodeIds([0]) will not return "^^".

The workaround for this situation is either
1)  Decode 0 to  "<unk>"
2)  Decode 0 to empty string ""
3)  Decode 0 to other reserved string.

We don't want to show internal representation like <unk>, <s> as they are tricky for users. Returning empty string will make the debugging harder for developer.  So we now use a special token ?? which can be interpretable both for user and developer.

Any comments for this behavior are appreciated. 
It would be nicer to allow user change the behavior like --unk-surface=<unk>

Thank you.

**Comment by mgrzeszczak** [comment]
Thanks for clarifying.

I think that allowing the user to set this option would be great, but for now I can just replace it I guess. 

One more thing that is interesting for me is why is there a trailing space in the decoded result, and a double space between the first word and the **??** special token?

```
>>> p.DecodeIds(p.EncodeAsIds('test ^^'))
'test  \u2047 '
```

**Comment by taku910** [comment]
Added --unk_surface= flag to spm_train.

Note that this is not a flag of spm_encode, meaning that the `unk_surface` is embedded in the model file.
