### ISSUE TITLE
Do you have any pre-trained models?

### ISSUE THREAD

**Issue by solomatov** [google/sentencepiece#139]
I just want to have a good model for English and don't want to tr it myself. Is there any official models for this?

**Comment by elyase** [comment]
Take a look here:

https://github.com/bheinzerling/bpemb

**Comment by solomatov** [comment]
@elyase Thank you!

**Comment by taku910** [comment]
One note is that they are trained BPE mode, --model_type=bpe, which doesn't support subword sampling.
