### ISSUE TITLE
Is this the tokenizer used in the official Transformer implementation?

### ISSUE THREAD

**Issue by JulesGM** [google/sentencepiece#144]
Google's official Transformer implementation comes with a subtokenizer that appears to work extremely similarly to SentencePiece, breaking words into subwords and using _ added to tokens instead of whitespace, and training the vocab in an unsupervised fashion with a pre-fixed target vocab size (32k in the code). I was wondering if you guys knew if it was **actually SentencePiece** or otherwise, if you had a bit of context on the differences.

https://github.com/tensorflow/models/tree/master/official/transformer
https://github.com/tensorflow/models/blob/master/official/transformer/utils/tokenizer.py

Thanks a lot in advance.

**Comment by taku910** [comment]
It is not SentencePiece. Seems that it is based on byte-pair-encoding, BPE. But not sure which algorithm they are using. 

One practical advantage of SentencePiece is that it can work well for unsegmented languages, including Chinese/Japanese. In addition, it supports two subwording algorithms, BPE and unigram.

https://arxiv.org/abs/1804.10959

**Comment by SimlaBurcu** [comment]
Not in the link that you provided, but there is this famous implementation of Transformer where they use SentencePiece: 

https://github.com/OpenNMT/OpenNMT-py
