### ISSUE TITLE
Purpose of adding a dummy whitespace at the beginning of each line of sentence

### ISSUE THREAD

**Issue by frankxu2004** [google/sentencepiece#15]
I have seen in the help text of `spm_train` the following about the parameter:

`--add_dummy_prefix (Add dummy whitespace at the beginning of text)  type: bool  default: true`

Is there any explanation that why the default behavior is adding a prefix whitespace? I am just wondering what's the intention or advantages of doing this.

**Comment by taku910** [comment]
We would like to make the same treatment for the following two sentences

world
Hello world

Both are converted to

_world
_Hello_world

 "_world" tends to be extracted as one token by putting a dummy whitespace.

**Comment by frankxu2004** [comment]
Cool! that is actually intriguing!

**Comment by taku910** [comment]
Seems the issue was resolved. closing.
