### ISSUE TITLE
terminate called after throwing an instance of 'Darts::Details::Exception'

### ISSUE THREAD

**Issue by AlexanderCYchu** [google/sentencepiece#156]
After I train the model, and  load the model...
```
Python 3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> 
>>> sp = spm.SentencePieceProcessor()
>>> 
>>> sp.Load('m.model')
terminate called after throwing an instance of 'Darts::Details::Exception'
  what():  /sentencepiece/third_party/darts_clone/darts.h:1143: exception: failed to insert key: zero-length key
Aborted (core dumped)
```
What should I do?
Thank you.

**Comment by taku910** [comment]
Thank you for using SentencePiece

Seems the model accidentally contains an empty token, which is not allowed.

How did you make/train 'm.model'.   Could you upload 'm.model' so I can investigate the error?

**Comment by AlexanderCYchu** [comment]
Thank you for this amazing repo since it makes word segmentation on Cantonese much better and easier. It is really hard to find an unsupervised method that this good in terms of accuracy, speed, and low memory usage.

Attaching the model file.
[m3.model.zip](https://github.com/google/sentencepiece/files/2283272/m3.model.zip)

**Comment by taku910** [comment]
Thank you for uploading the model.

Seems the the model contains a null (\0) token, implying that the training corpus contains '\0'.  
One possibility is that the corpus is not encoded in utf-8. Trivial work around is to escape '\0' in the corpus into some safe character like ' '.

Anyway, I will put some workaround (or simply emitting an error) to prevent the model from having '\0'.

Thank you.

**Comment by AlexanderCYchu** [comment]
Thanks, I will first try to encode my corpus in utf-8. Will report back to here.

**Comment by taku910** [comment]
Updated the code to refuse null character.  Please try the latest spm_train.
