### ISSUE TITLE
The full alphabet is not preserved and the transformation is not reversible.

### ISSUE THREAD

**Issue by PiotrCzapla** [google/sentencepiece#175]
Hi,
Thank you for publishing such a great research!

After studying your docs we assumed that the default settings for training will retain the full alphabet so that the transformation is reversible.   Based on that assumption we build our model for polish NLP contest and we are now trying not to get disqualified :(, (I hope that the competition jury will reason with us.)

We tracked the issue down to the default setting of character_coverage which is set to 0.9995. 
I understand that normally this is recommended setting as the model may work better like that. But it would be good to add a mention of that setting in the docs so to help anyone that needs to have the transformation reversible.

I can submit PR to emphasize the fact that the default `character_coverage` is not 1.0 but I'm not sure how this parameter works.

For anyone that comes across this issue. Just train your model with `---character_coverage 1.0`.
In our case, the default coverage of 0.9995  removed as many as 4 characters from our alphabet of size 92. The characters were indeed least frequently used so I guess that the coverage means how much of the text is going to be restored after reversing the transformation but that just guessing.

Anyway, this is a super small issue, and the algorithm is very useful. Once again thank you for making the library public.

Regards,
Piotr

**Comment by taku910** [comment]
Thank you for the feedback.

I can really see the point -- character_coverage settings is confusing.

The background of this parameter was that we would like to train the model on Japanese/Chinese corpus where the number of characters amount to several thousands, and contain many rare and noisy characters. As long as we train the model on non-Japanese/Chinese,  character_coverage 1.0 should work. 

First, as you suggested,  we would like to mention this parameter more clearly. I would like to appreciate your PR for character coverage.

In addition,  we would like to introduce a kind of "adaptive" coverage selection.  The idea is that if the the number of unique characters is much less than vocab_size, which happens in Latin-based language in general, we can make character_coverage 1.0.
