### ISSUE TITLE
Windows Support

### ISSUE THREAD

**Issue by ArmenAg** [google/sentencepiece#178]
What's sentencepiece's story for windows support? Are there any future plans to support Windows?

Thank you.

**Comment by taku910** [comment]
Hi,

Although it is not officially announced, Windows support is almost completed and binary package including python-wheel is built on appveyor.

https://ci.appveyor.com/project/taku910/sentencepiece/build/job/dnw884tf3x590r7c/artifacts

If you want to build from source, this batch script will help
https://github.com/google/sentencepiece/blob/master/test.bat

I will keep you posted until the official binary package is released on github-release.

Thank you.

**Comment by ArmenAg** [comment]
Thank you for the quick response. Glad to hear Windows support is being actively worked on!

**Comment by taku910** [comment]
Windows binary and pip packages are available on the following github release page.
I will upload pip packages to pypi site soon.

https://github.com/google/sentencepiece/releases/tag/v0.1.4

**Comment by taku910** [comment]
uploaded

https://pypi.org/project/sentencepiece/#files
