### ISSUE TITLE
Symbols in sentencepieces

### ISSUE THREAD

**Issue by Xiaofeng83** [google/sentencepiece#183]
I am using sentencepieces in python and have a issue with user defined symbols.

For example, I trained with

"spm.SentencePieceTrainer.Train('--input=Stream.tsv --model_prefix=m.debug --vocab_size=1000 --input_sentence_size=100000000 --hard_vocab_limit=false --user_defined_symbols=<empty>,<
sep>,<pad>,<s>,</s>')"

and use 

```
>>> sp.EncodeAsIds('<s>')
[9, 1]
>>> sp.EncodeAsIds('<pad>')
[9, 5]
>>> sp.EncodeAsIds('a<pad>')
[25, 5]
```

it always adds "9" (which is "_") in the id list except "a<pad>".  Is it expected?  or Any way to remove the "_" id?

**Comment by taku910** [comment]
Hi, thank you for using sentencepiece.

The default behavior is always adding "_" to the begging of sentence. This is intended as we want to treat words independently from the positions ("foo" and "bar foo" are handled as "_foo" and "_bar_foo" and there are two "_foo").

You can suppress to add "_"  --add_dummy_prefix-=false to spm_train.

EncodeAs(Ids|Pieces) are the methods to tokenize the sentences. If you want to obtain the ids of bos/eos/pad, you might want to use unk_id(), bos_id(), eos_id(), pad_id() methods.

**Comment by Xiaofeng83** [comment]
I see. I will try the --add_dummy_prefix-=false.  Thank you very much
