### ISSUE TITLE
Segfault when importing alongside tensorflow.contrib or pytorch in python (Linux)

### ISSUE THREAD

**Issue by mmistele** [google/sentencepiece#186]
Python segfaults when the following code is run (on Ubuntu 16.04 with gcc 5.4.0):
```
import sentencepiece
import tensorflow.contrib
```
Note the segfault does not happen when they are imported in the reverse order.

Probable cause: the quay.io manylinux1 docker image used by the make_py_wheel.sh script has gcc 4.8 (and consequently so does sentencepiece Linux wheel on PyPI), which can be incompatible with binaries made using gcc > 4.9.2. Hence pulling sentencepiece into the same address space as binaries made using 4.9.2 may cause issues like segmentation faults.

More discussion in the pytorch repo (same issue encountered): https://github.com/pytorch/pytorch/issues/8358

The ideal solution seems to be to compile and release sentencepiece made with gcc 4.9. If you can update make_py_wheel.sh and/or upload a new version to PyPI, that would be awesome!

**Comment by mmistele** [comment]
Thanks for the quick response!

If we want to compile the wheel right now using latest build tools (for our own particular platform, not manylinux1), what do we need to do differently from what's laid out in python/make_py_wheel.sh?

I got most of the way to compiling the wheel with gcc 5.4 (Ubuntu) myself, but I ran into an import error when using the compiled result. In a docker container (Ubuntu 16.04 rather than the CentOS 5.11 one used by the script), I ran the C++ compilation steps from the repo README (including ldconfig -v), added "--plat [platform name]" to the auditwheel line, used the body of the "for i in /opt/python/*" loop rather than looping (since my file system doesn't have an /opt/python directory) with `python` instead of `$i/bin/python`, then ran
`$ make_py_wheel.py native ` successfully. This made a wheel that I can successfully install on another machine. But when I start up python and import sentencepiece on that machine, I get "ImportError: libsentencepiece.so.0: cannot open shared object file: No such file or directory". Seems like it has to do with needing a run of ` sudo ldconfig -v `, but I ran it in the docker container already and don't have sudo access in the machine I'm installing it on (and would prefer not to invoke it if possible). Any ideas?

**Comment by taku910** [comment]
Hi, I made a patch for protobuf, which replaces the std::call_once implementation with own one. Seems that the root cause of this crash was some incompatibility around pthread_once. In my experiments, the verification code you kindly showed is working.

**Comment by taku910** [comment]
Hi, I made a patch for protobuf, which replaces the std::call_once implementation with own one. Seems that the root cause of this crash was some incompatibility around pthread_once. In my experiments, the verification code you kindly showed is working.

**Comment by mmistele** [comment]
Fantastic! One hiccup is it doesn't seem to want to install for some reason:
`sentencepiece-0.1.4-cp35-cp35m-manylinux1_x86_64.whl is not a supported wheel on this platform.
`

It's in the same directory as a package I compiled, and the `pip3 install ___ --user` command works fine for that one. Environment specs: pip3 v18, python 3.6, Ubuntu 16.04.4

**Comment by mmistele** [comment]
All right: made a Python 3.5 environment, reproduced the segfault from the pypi package, and reproduced it working segfault-free with the wheel you posted here. Great fix!

**Comment by taku910** [comment]
Hi, pypi pre-release packages are available on github release.
I will upload them pypi soon.

https://github.com/google/sentencepiece/releases/tag/v0.1.4

**Comment by taku910** [comment]
uploaded

https://pypi.org/project/sentencepiece/#files

**Comment by lixin-meng** [comment]
Is there a way install SentencePiece on CentOS ?

**Comment by taku910** [comment]
We have a travis CI build rule for Fedora.

https://github.com/google/sentencepiece/blob/master/test.sh#L114
