### ISSUE TITLE
Version of protoc - which to use

### ISSUE THREAD

**Issue by smolendawid** [google/sentencepiece#190]
Running make gives the following output:

> user:~/sentencepiece/build$ make
> [  1%] Running C++ protocol buffer compiler on sentencepiece_model.proto
> [  2%] Running C++ protocol buffer compiler on sentencepiece.proto
> Scanning dependencies of target sentencepiece_train-static
> [  4%] Building CXX object src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o
> In file included from /home/user/sentencepiece/src/builder.h:22:0,
>                  from /home/user/sentencepiece/src/builder.cc:15:
> /home/user/sentencepiece/build/src/sentencepiece_model.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
>  #error This file was generated by a newer version of protoc which is
>   ^
> /home/user/sentencepiece/build/src/sentencepiece_model.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
>  #error incompatible with your Protocol Buffer headers.  Please update
>   ^
> /home/user/sentencepiece/build/src/sentencepiece_model.pb.h:14:2: error: #error your headers.
>  #error your headers.
>   ^
> In file included from /home/user/sentencepiece/src/builder.h:22:0,
>                  from /home/user/sentencepiece/src/builder.cc:15:
> /home/user/sentencepiece/build/src/sentencepiece_model.pb.h:23:35: fatal error: google/protobuf/arena.h: No such file or directory
> compilation terminated.
> src/CMakeFiles/sentencepiece_train-static.dir/build.make:78: recipe for target 'src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o' failed
> make[2]: *** [src/CMakeFiles/sentencepiece_train-static.dir/builder.cc.o] Error 1
> CMakeFiles/Makefile2:101: recipe for target 'src/CMakeFiles/sentencepiece_train-static.dir/all' failed
> make[1]: *** [src/CMakeFiles/sentencepiece_train-static.dir/all] Error 2
> Makefile:149: recipe for target 'all' failed
> make: *** [all] Error 2

Versions of my packages:

> user:~/sentencepiece/build$ sudo apt-get install cmake pkg-config libprotobuf9v5 protobuf-compiler libprotobuf-dev libgoogle-perftools-dev 
> Reading package lists... Done
> Building dependency tree       
> Reading state information... Done
> libprotobuf-dev is already the newest version (2.6.1-1.3).
> libprotobuf9v5 is already the newest version (2.6.1-1.3).
> pkg-config is already the newest version (0.29.1-0ubuntu1).
> protobuf-compiler is already the newest version (2.6.1-1.3).
> cmake is already the newest version (3.5.1-1ubuntu3).
> libgoogle-perftools-dev is already the newest version (2.4-0ubuntu5.16.04.1).
> 0 upgraded, 0 newly installed, 0 to remove and 160 not upgraded.

Unfortunately I don't understand which version of what package should I use. Maybe someone could help me with that?

**Comment by taku910** [comment]
This error usually happens when the protocol compiler (protoc) and the library header (/usr/include/google/protobuf) are inconsistent. 
When you are using the protoc installed with apt-get, it should be installed in /usr/bin.

```
% which protoc
/usr/bin/protoc
% /usr/bin/protoc --version
libprotoc 3.0.0
% grep GOOGLE_PROTOBUF_VERSION /usr/include/google/protobuf/stubs/common.h
#define GOOGLE_PROTOBUF_VERSION 300000
```

**Comment by smolendawid** [comment]
@taku910

I can see that the versions are compatible. The error still occurs

> user:~$ /usr/bin/protoc --version
> libprotoc 2.6.1
> user:~$ grep GOOGLE_PROTOBUF_VERSION /usr/include/google/protobuf/stubs/common.h
> #define GOOGLE_PROTOBUF_VERSION 2006001
>     GOOGLE_PROTOBUF_VERSION, GOOGLE_PROTOBUF_MIN_LIBRARY_VERSION,         \

**Comment by gaojxx** [comment]
@taku910 I am not the user of `root`, and the protoc is installed at my own dir.
So, could you know how to solve it?

**Comment by JiongJiongP** [comment]
> @taku910 I am not the user of `root`, and the protoc is installed at my own dir.
> So, could you know how to solve it? Thanks!

have you solved that problem i am same as you, not root user

**Comment by javyer** [comment]
Thanks Vikasvashisht  for this patch, it works fine. 
But even applying it, I run into same error on some exotic builds, building into extra long paths... So I have push an other solution, using  "for loop".

[cxx_arg_list_too_long_forloop.patch.txt](https://github.com/google/sentencepiece/files/3330004/cxx_arg_list_too_long_forloop.patch.txt)

**Comment by jiapei100** [comment]
@taku910 
Thank you very much.... Thanks ...
