### ISSUE TITLE
Core dump using tensorflow and SentencePiece when importing SentencePiece before 

### ISSUE THREAD

**Issue by JulesGM** [google/sentencepiece#191]
This has been reported by a few members of our team. If you use SentencePiece in a project with Tensorflow, there is a crash where the core is dumped if you import tensorflow after SentencePiece. 

An effect of this is that if you are in a script that itself doesn't use tensorflow but imports from modules that import tensorflow, if you import sentencepiece after importing the scripts using tensorflow, the core is dumped.

We are running Tensorflow 1.10.1 with python 2.7.15.

It's very easy to reproduce for us:
```bash
jules@server:~/$ python
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece
>>> import tensorflow
Segmentation fault (core dumped)

jules@server:~/$ python
Python 2.7.15 |Anaconda custom (64-bit)| (default, May  1 2018, 23:32:55)
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> import sentencepiece
>>> # this is fine
```

**Comment by taku910** [comment]
Thank you for using sentencepiece.

Please try the latest pip package (version 0.1.4), which is already available via pypi web site or "pip install" command.

FYI:  https://github.com/google/sentencepiece/issues/186

**Comment by JulesGM** [comment]
Oh, it works, my apologies.

Thank you.
