### ISSUE TITLE
self-prepared protobuf not found 

### ISSUE THREAD

**Issue by Tzawa** [google/sentencepiece#192]
I'm trying to compile the sentencepiece with the self-prepared protobuf. I followed the instructions in the README.md: exported 4 environmental variables and ran cmake, but the cmake couldn't find the protobuf with the following error messages.

`-- VERSION: 0.1.5
CMake Error at /mnt/orange/brew/data/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /mnt/orange/brew/data/Cellar/cmake/3.7.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /mnt/orange/brew/data/Cellar/cmake/3.7.2/share/cmake/Modules/FindProtobuf.cmake:393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  src/CMakeLists.txt:15 (find_package)

-- Configuring incomplete, errors occurred!
See also "/somewhere/sentencepiece/build/CMakeFiles/CMakeOutput.log".
See also "/somewhere/sentencepiece/build/CMakeFiles/CMakeError.log".`

P.S. Our server maintains all the tools including protobuf by jenkins.

**Comment by taku910** [comment]
Thank you for using sentencepiece.

```
% cd build
% cmake .. -DCMAKE_PREFIX_PATH=<path>
% make -j4
```

note that &lt;path&gt;/{bin,lib,include} contains the protobuf libraries, i.e., protobuf is installed with --prefix=&lt;path&gt;

Will update the document.

**Comment by Tzawa** [comment]
Thanks for your prompt reply. It works!!
