### ISSUE TITLE
Keeping reserved tokens while decoding

### ISSUE THREAD

**Issue by JulesGM** [google/sentencepiece#199]
Hello, 
We would need to be able to encode bos and eos tokens in the text to their appropriate ids. Is there a way to do this? Thanks,

**Comment by taku910** [comment]
You might want to try --user_defined_symbols.
SentencePiece tokenizes the text as-is even for the reserved symbols `<s>,</s>` .  The symbols specified with --user_defined_symbols are always segmented as a unique token, and this flag is valid for `<s>,</s>`

`% spm_train --input=... --model_prefix=... --user_defined_symbols=<s>,</s>`

FYI: https://github.com/google/sentencepiece/issues/102#issuecomment-397150427

**Comment by JulesGM** [comment]
thanks again
