### ISSUE TITLE
How to use maximum vocab size in SP

### ISSUE THREAD

**Issue by ArmenAg** [google/sentencepiece#200]
Instead of passing through a vocab size, for CHAR or WORD type SP models, is it possible for SP to use all the words or all the characters present. This will be especially useful for language modeling.

It would be possible to guess how many words there are and pass that through to SP, but I was wondering if theres anything in SP to do this.

**Comment by taku910** [comment]
I can see the points. It would be reasonable to add an option to use all tokens in CHAR/WORD model.
Though this feature is not available, let me implement this option. Thank you.

**Comment by taku910** [comment]
let me close this issue.
