### ISSUE TITLE
spm_train: command not found on ubuntu 16.0

### ISSUE THREAD

**Issue by yuimo** [google/sentencepiece#203]
hi, i has installed sentencepiece with "pip install sentencepiece", but reports "spm_train: command not found" when i execute "spm_train"
but the same instruction  executes well on mac
so, what's the reason? thanks a lot.

**Comment by taku910** [comment]
spm_train is not installed via pip. spm_train is only installed with the C++ instruction.
https://github.com/google/sentencepiece#c-from-source

If you want to train the model on python, try SentencePieceTrainer class, which is installed with pip.
https://github.com/google/sentencepiece/blob/master/python/README.md#model-training
