### ISSUE TITLE
Specifying --bos_id -1 results in "Unknown/Invalid flag bos_id"

### ISSUE THREAD

**Issue by emjotde** [google/sentencepiece#205]
Hi,
trying to disable any of the special vocabulary items per command line seems to fail. When I specify 
`spm_train --bos_id -1 ...` I get an `Unknown/Invalid flag bos_id` error. Works for other positive values as long as they are unique. Seems to be a command line parser issue. Same for `eos_id` and `unk_id`.
Code has been checked out yesterday from the main repository. 

Great tool, BTW.

**Comment by taku910** [comment]
Hi, Thank you for using sentencepiece.

Probably you might want to try` --bos_id=-1` instead of `--bos_id -1.`.
I will update the code of parameter parser so it can accept the style of --flag val.

**Comment by emjotde** [comment]
Ah, I was convinced I tried that too. Thanks!

**Comment by taku910** [comment]
I found that it is tricky error -- when flag starts with "-" it is handled as a new parameter.  The current flag parser fails to parse the value starting with "-".
