### ISSUE TITLE
double free or corruption error when running SentencePieceTrainer.Train

### ISSUE THREAD

**Issue by dust0x** [google/sentencepiece#206]
Running the SentencePieceTrainer.Train function for a large data-set (7,937,008 sentences from the German WIkipedia corpus) causes the following error:

```
/sentencepiece/src/unigram_model_trainer.cc(474) LOG(INFO) Starts training with : 
input: "./wikifile.txt"
model_prefix: "dewiki"
model_type: UNIGRAM
vocab_size: 25000
character_coverage: 1
unk_id: 0
bos_id: 2
eos_id: 3
pad_id: 1
.
.
.
/sentencepiece/src/trainer_interface.cc(197) LOG(WARNING) Empty string found. removed
/sentencepiece/src/trainer_interface.cc(197) LOG(WARNING) Empty string found. removed
/sentencepiece/src/trainer_interface.cc(190) LOG(INFO) Loading: ▁November▁1976▁statt▁und▁wurde▁von▁81▁der▁126▁Delegierten▁besucht.	size=7900000
/sentencepiece/src/trainer_interface.cc(197) LOG(WARNING) Empty string found. removed
/sentencepiece/src/trainer_interface.cc(197) LOG(WARNING) Empty string found. removed
/sentencepiece/src/trainer_interface.cc(211) LOG(INFO) Loaded 7936907 sentences
/sentencepiece/src/trainer_interface.cc(235) LOG(INFO) all chars count=785677220
/sentencepiece/src/trainer_interface.cc(242) LOG(INFO) Done: 100% characters are covered.
/sentencepiece/src/trainer_interface.cc(250) LOG(INFO) alphabet size=5000
/sentencepiece/src/trainer_interface.cc(281) LOG(INFO) Done! 7936907 sentences are loaded
/sentencepiece/src/unigram_model_trainer.cc(120) LOG(INFO) Using 2000000 sentences for making seed sentencepieces
/sentencepiece/src/unigram_model_trainer.cc(148) LOG(INFO) Making suffix array...
/sentencepiece/src/unigram_model_trainer.cc(152) LOG(INFO) Extracting frequent sub strings...
/sentencepiece/src/unigram_model_trainer.cc(203) LOG(INFO) Initialized 1000000 seed sentencepieces
/sentencepiece/src/trainer_interface.cc(287) LOG(INFO) Tokenizing input sentences with whitespace: 7936907
/sentencepiece/src/trainer_interface.cc(296) LOG(INFO) Done! 5078382
/sentencepiece/src/unigram_model_trainer.cc(495) LOG(INFO) Using 5078382 sentences for EM training
*** Error in `python': double free or corruption (!prev): 0x000000000179e130 ***
Aborted (core dumped)

```

The error goes away for a smaller vocabulary size but it also goes away when I run this step, with the same settings, from an interpreter. What could possibly cause this behaviour?

**Comment by taku910** [comment]
Seems that this error is raised inside python. I don't know the root cause but seems that this error happens when allocating large memory chunk.

Could you try the native C++ version (spm_train) for training?

**Comment by dust0x** [comment]
@taku910 a similar error is reported [here in TensorFlow](https://github.com/tensorflow/tensorflow/issues/6968). This has something specifically to do with the Ubuntu 14.04 distribution (which is also what I am using) -- jemalloc is the main suspect.

I have yet to try the workaround suggested [here](https://github.com/tensorflow/tensorflow/issues/8717#issuecomment-289828646), but I'll try it out and confirm whether it resolves this issue. I will also try the native C++ version as per your suggestion.

What I'm really interested in is finding out why executing the training step from the interpreter does not cause this error.

**Comment by dust0x** [comment]
Fix in link works. Closing.
