### ISSUE TITLE
Is the C++ API thread-safe?

### ISSUE THREAD

**Issue by emjotde** [google/sentencepiece#207]
Hi,
I am currently integrating SentencePiece with my C++ code and want to use the `SentenceProcessor::SampleEncode(...)` function to encode batches on the fly. Since there is random sampling going on I am wondering if this is thread-safe. I am assuming that some random number generator with a random state is used, so that would have persistent state?

Thanks for any hint.

**Comment by taku910** [comment]
It is thread safe. random number generator (mt19937) is managed by thread local storage. (threadlocal keyword or pthread_key_create depending on the availability)

https://github.com/google/sentencepiece/blob/master/src/util.cc#L221

Thank you

**Comment by emjotde** [comment]
Great, thanks again for this awesome work.
