### ISSUE TITLE
`nfkc_cf` and `nmt_nfkc_cf` normalization seem to be identical

### ISSUE THREAD

**Issue by rspeer** [google/sentencepiece#208]
The `nfkc_cf.tsv` and `nmt_nfkc_cf.tsv` files are identical. I believe that `nfkc_cf.tsv` was meant to leave out the additional normalizations such as converting line breaks to spaces.

I'd probably want to use `nmt_nfkc_cf` anyway, but I found this when I was running `diff -u nfkc_cf.tsv nmt_nfkc_cf.tsv` to check the differences.

**Comment by taku910** [comment]
Thank you for the report.
I've just uploaded a correct tsv file.
