### ISSUE TITLE
subword for English 

### ISSUE THREAD

**Issue by monsieurzhang** [google/sentencepiece#210]
Hi,

Could you give me some hint to train a English tokenizer with sentencepiece unigram model?
I tried with basic options like: 
  spm_train --input=$SRC --model_prefix=$SRCLAN --vocab_size=40000 --model_type unigram
  spm_encode --alpha 0.1 --model $SRCLAN.model --nbest_size 64 --vocabulary $SRCLAN.vocab --output $SRCLAN.out $SRC

And I found from the output file, all English words are tokenized into characters.
Any additional options are needed?
Many thanks.

**Comment by taku910** [comment]
Probably you might not need to use --alpha,--nbest_size, and --vocabulary flag to spm_encode. They are flags for some unusual cases. Could you try without these flags?
