### ISSUE TITLE
Training BPE on long sentences 

### ISSUE THREAD

**Issue by keotic** [google/sentencepiece#214]
Why is there a limit on the sentence length while training?
it seems that there is a hard coded sentence length limit in the code:
/Users/travis/build/google/sentencepiece/src/trainer_interface.cc(176) LOG(INFO) Too long lines (>=2048 bytes). Skipped.

**Comment by keotic** [comment]
So what will be a good strategy for training long documents without a language specific pre-processing? Just to randomly break the text to chunks?

**Comment by xuf12** [comment]
@taku910 Could you please explain which line you are suggesting to remove?

> Could you try the same command just removing this line?

**Comment by taku910** [comment]
Sorry for the confusion. Please remove the following if block and try the training again.

https://github.com/google/sentencepiece/blob/master/src/trainer_interface.cc#L186

**Comment by loretoparisi** [comment]
hey @taku910 is it possibile to set as option `kMaxLines`? So that there will be no need to build again like `--max_lines=4096`

Thank you!

**Comment by taku910** [comment]
added `--max_sentence_length=<INT>` flag. default value is 2048. Thanks.

**Comment by chagri** [comment]
I think this error still persist. I am getting the following error after installing this repo using pip:

RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/sentencepiece_processor.cc
