### ISSUE TITLE
De-normalization in decode(...)

### ISSUE THREAD

**Issue by emjotde** [google/sentencepiece#216]
Hi, a feature request:

It would be useful to be able to specify *.tsv files for decoding, too, to reverse certain operations introduced during normalization in encoding.

**Comment by taku910** [comment]
Thank you for the request.

Do we want to have a separated *.tsv file for detoeknization/decoding?
The normalization is not reversibly reproducible, so we cannot use the same *.tsv file for encoding/decoding.

**Comment by taku910** [comment]
Before deciding whether to implement this feature or not, I would like to know the actual use case of "denormalization", i.e., how they are general and useful.

**Comment by taku910** [comment]
The latest release add the feature of denormalization. You can specify the rule via ``--denormalization_rule_tsv=<file>`` flag

https://github.com/google/sentencepiece/releases/tag/v0.1.9
