### ISSUE TITLE
Uppercase custom defined symbols wouldn't work with nmt_nfkc_cf

### ISSUE THREAD

**Issue by winston-zillow** [google/sentencepiece#227]
Train with

```
$spm_train --input=sentence_piece_train/part-00000 --model_prefix=spm --vocab_size=10000 \
    --normalization_rule_name=nmt_nfkc_cf \
    --user_defined_symbols='<WWWADDR>,<INTEGER>'
```

then test encoding with the UDS produces:

```
$ echo 'some <INTEGER> value' \
    | spm_encode --model=spm.model 
▁some ▁ < in te ger > ▁value
```

The work around is to use lowercase UDS. Not a big deal, just noting this problem.

**Comment by taku910** [comment]
Thank you for the bug report.

As we can imagine, the normalization happens just before segmentation.
Let me check whether it can be fixed easily.

**Comment by taku910** [comment]
Fixed.

https://github.com/google/sentencepiece/pull/235
