### ISSUE TITLE
Is piece=id not working for decoding?

### ISSUE THREAD

**Issue by loretoparisi** [google/sentencepiece#229]
If I use `piece` as output and input format encoding and decoding work as expected:

```sh
$ echo "Hello World" | spm_encode --model=m.model --output_format=piece
▁ H e llo ▁ W or ld
$ echo "▁ H e llo ▁ W or ld" | spm_decode --model=m.model --input_format=piece
Hello World
```

When using `id` I get unrecognized token in the decoding:

```sh
$ echo "Hello World" | spm_encode --model=m.model --output_format=id
31963 0 31964 7651 31963 0 36 68
$ echo "31963 0 31964 7651 31963 0 36 68" | spm_decode --model=m.model --input_format=id
 ⁇ ello  ⁇ orld
```

**Comment by taku910** [comment]
This is an expected behavior. Please take a look at:

https://github.com/google/sentencepiece/issues/134

**Comment by loretoparisi** [comment]
@taku910 ok, could you please depict the case of using the `id` output/input, instead of `piece`, i.e. for mapping unique tokens purposes, etc.?
