### ISSUE TITLE
[Question] Custom defined rules for multiple line feed

### ISSUE THREAD

**Issue by loretoparisi** [google/sentencepiece#230]
I would like to use sentencepiece to encode a representation of my documents formatting.
In my dataset a line is a document. A document has single or multiple `\n` characters i.e. 

text can be split into paragraphs
```javascript
paragraph = text.split(/\n{2,2}/)[0]
```

and paragraphs into sentences
```javascript
sentence = paragraph.split(/\n{1,1}/)[0]
```

so something like the following:

```text
Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua.

Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi
ut aliquip ex ea commodo consequat.


Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur.
```

The text can be in any language (English, Japanese, Korean, Hindi, etc.).

Since `sentencepiece` can learn custom symbols I would like to define this rules

```tsv
0000000a 0xA
0000000a0000000a 0xA 0xA
```

and then using `--normalization_rule_tsv` for training of `spm_train`.
Can it be theoretically possible?

**Comment by taku910** [comment]
sentencepiece can only handle one-sentence-per-line format. Please see the following issue for more detail.

https://github.com/google/sentencepiece/issues/101
