### ISSUE TITLE
Option to use leading whitespaces to encode string in Python interface

### ISSUE THREAD

**Issue by thomasZen** [google/sentencepiece#236]
When using the EncodeAsPieces function in Python leading whitespaces are ignored by default:
`sp.EncodeAsPieces(' sentencepiece') = ['s', 'ent', 'ence', 'piece']`
Is it possible to add an option to use these whitespaces? E.g.:
`sp.EncodeAsPieces(' sentencepiece', trim_string=False) = ['▁sentence', 'piece']`

**Comment by taku910** [comment]
You can try --remove_extra_whitespaces=false during training

`% spm_train --input=...   --remove_extra_whitespaces=false`

Note that this option stops removing all redundant whitespaces (leading, trailing, and duplicate internal whitespaces).

The `remove_extra_whitespaces` flag is encoded in the model file. Please try the following command to edit the model file.

```
% cd <sentencepiece_path>/src/
% protoc --python_out=. sentencepiece_model.proto
% pip3 install protobuf --user
% python3
>>> import sentencepiece_model_pb2 as model
>>> m = model.ModelProto()
>>> m.ParseFromString(open('m.model', 'rb').read())
352301
>>> m.normalizer_spec.remove_extra_whitespaces
True
>>> m.normalizer_spec.remove_extra_whitespaces = False
>>> with open('m.model2', 'wb') as f:
...     f.write(m.SerializeToString())

```

**Comment by thomasZen** [comment]
Consider the following use case:
We want to force the network to output a special term within a sentence during inference. We already know the position when the term should be outputted,  but need the correct tokenization of it to feed it to the network. That way the network can continue to translate and finish the rest of the sentence. So the tokenization of the term should include a space, but otherwise should be exactly as seen during training (retraining the whole network is not an option, unfortunately).

I came across the workaround of adding a dummy character (e.g. "d ") and removing it again after the tokenization is done:
`s.EncodeAsPieces('d ' + 'sentencepiece')[1:] = ['d', '▁sentence', 'piece'][1:] = ['▁sentence', 'piece']`

Do you think that's a valid solution for the mentioned use case? Or can you think of situation were that workaround will break?

**Comment by taku910** [comment]
I could not clearly understand the behavior you mentioned first. This seems not a default behavior.

Could you double-check the command line of spm_train?
The followings are the behavior with different command line settings.

```
%./src/spm_train --model_prefix=m --input=../data/botchan.txt --vocab_size=1000   
% python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('m.model')
True
>>> sp.EncodeAsPieces('  make')
['▁make']
>>> sp.EncodeAsPieces('make')
['▁make']
>>> sp.EncodeAsPieces('d make')
['▁d', '▁make']
>>> 
```

We can see that the input sentence w/ and w/o preceding space are segmented in the same way.

I presume that you trained the sentencepiece model with `--add_dummy_prefix=false` (default setting is true).

```
%./src/spm_train --model_prefix=m --input=../data/botchan.txt --vocab_size=1000 ---add_dummy_prefix=false                                                                                   
% python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('m.model')
True
>>> sp.EncodeAsPieces('make')
['m', 'a', 'ke']
>>> sp.EncodeAsPieces(' make')
['m', 'a', 'ke']
>>> sp.EncodeAsPieces('d make')
['d', '▁make']
>>> 
```

We can use `-add_dummy_prefix` and `--remove_extra_whitespaces` at the same time.

```
%./src/spm_train --model_prefix=m --input=../data/botchan.txt --vocab_size=1000 ---add_dummy_prefix=false   --remove_extra_whitespaces=false
% python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('m.model')
True
>>> sp.EncodeAsPieces('make')
['m', 'ake']
>>> sp.EncodeAsPieces(' make')
['▁make']
>>> sp.EncodeAsPieces('d make')
['d', '▁make']
>>> 
```

**Comment by taku910** [comment]
Let me close this bug. Please feel free to reopen it if this issue has still persisted.

**Comment by thomasZen** [comment]
Thanks for your help! Your idea to statically set remove_extra_whitespaces to False helped a lot!
