### ISSUE TITLE
Possible bugs with setting vocabulary

### ISSUE THREAD

**Issue by matteosal** [google/sentencepiece#243]
https://github.com/google/sentencepiece/blob/99599059e87b6e2547973cc009858d61eb6f5a9c/src/sentencepiece_processor.cc#L142-L151

There are a couple of aspects of this code whose consequences are unclear to me and may represent unintended behaviour.

1) Line 147 is setting to `NORMAL` everything which is in the vocabulary or is a single character (as far as I understand). This means that pieces of type `CONTROL` and `UNKOWN` will also be set to `NORMAL` under the above circumstances. Is that intended?

2) Line 149 on the other hand sets everything to `UNUSED`. Again, it will overwrite types `UNKOWN` and `CONTROL`. One visible effect of this is that, when a vocabuary is used, adjacent unkown tokens are not encoded in a single id by `PopulateSentencePieceText` (because IsUnkown at line 322 returns False) despite the comment in line 343 saying so.

**Comment by taku910** [comment]
Thank you for the report. Your concern and analysis are correct. I will skip these code block for the special tokens (CONTROL/USER_DEFINED)

**Comment by taku910** [comment]
Fixed.

However, even with the old code, control/user defined symbols were not removed in the first place. I guess the behavior will not change.
