### ISSUE TITLE
Training sentencepiece on large corpora

### ISSUE THREAD

**Issue by raulpuric** [google/sentencepiece#245]
Hi, I tried training SentencePiece on a very large corpus of 550 million lines and got the following error:
`RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(61) [trainer_spec.input_sentence_size() >= 100 && trainer_spec.input_sentence_size() <= 100000000]`

Is there any way to get around this and force it to train on larger corpora? Training time and available memory isn't a concern for me.

**Comment by taku910** [comment]
Thank you for using sentencepiece.

We need to rewrite this code and rebuild the binary to increase the limitation.

However, there is a workaround. If your data is written in English-like segmented language, you can first tokenize data with whtespaces and make a TSV file like

```
word1 <tab> freq
word2 <tab> freq
...
```

freq is the rfeuency of word. Then, feed this input with 

`% spm_train --input=input --input_format=tsv ...`

**Comment by taku910** [comment]
Just removed the maximum size constraint for data.

https://github.com/google/sentencepiece/commit/f6229bfad55f28e6b35e6860d9c06a5ea9bd83c9

**Comment by raulpuric** [comment]
awesome thanks so much. 
Quick question about the tsv file method.
I'm assuming it can no longer do things like make New York it's own sentencepiece.
However, will it still break down words into one or more sentencepieces?

**Comment by taku910** [comment]
By default, sentencepiece splits the sentence with whitespace. so, "New York" will not be one word anyway. To extract pieces corssing multiple words, use `% spm_train --split_by_whitespace=false ...`

If you want to let some specific multi-word-expressions be one piece. You can make a TSV like

```
Hello <tab> 10
world <tab> 20
New York <tab> 30
```

You might need to run some preprocessor to extract "New York" as one word.
No need to run this preprocessor in the segmentation phase.

**Comment by MissMcFly** [comment]
Hi~I have trained SentencePiece on a very large Chinese  corpus. When I use very small corpus to train it, it could work. But no matter whether I use 100M data or 10G data I got an unrecoverable error.
Is there any way to solve the problem? Thank you very much.
