### ISSUE TITLE
cmake third_party issues

### ISSUE THREAD

**Issue by leezu** [google/sentencepiece#246]
When building a project with cmake that should link to sentencepiece, it would be nice to simply add this repository as a submodule and `add_subdirectory` it in the projects `CMakeLists.txt`. This currently mostly works, but the includes for the third-party projects used by sentencepiece are not correctly handled.

To illustrate, the optimal / expected result would be that:

```
cmake_minimum_required(VERSION 3.12)

project(myproject)
add_subdirectory(third_party/sentencepiece EXCLUDE_FROM_ALL)

[...]   # Set up the mytarget
target_link_libraries(mytarget PUBLIC sentencepiece)
```

However, this will fail due to missing includes for the `third_party/sentencepiece/third_party` directory. This can be fixed by manually setting `third_party/sentencepiece/` as an include directory of the `sentencepiece` target.

```
cmake_minimum_required(VERSION 3.12)

project(myproject)
add_subdirectory(third_party/sentencepiece EXCLUDE_FROM_ALL)
target_include_directories(sentencepiece PRIVATE third_party/sentencepiece/)

[...]   # Set up the mytarget
target_link_libraries(mytarget PUBLIC sentencepiece)
```

While the workaround is simple, I believe this should have been handled by https://github.com/google/sentencepiece/blob/master/CMakeLists.txt . This issue is both to make you aware of the problem, and in case you don't plan to fix it, for others to be aware of the workaround.

Thanks for developing this project!

**Comment by taku910** [comment]
Fixed. We can include sentencepiece with add_subdirectory function.
Here is the example.

```
cmake_minimum_required(VERSION 3.1 FATAL_ERROR)

project(test CXX)
add_subdirectory(sentencepiece)
include_directories(sentencepiece/src)
add_executable(foo main.cc)
target_link_libraries(foo sentencepiece-static)
```
