### ISSUE TITLE
Export vocabulary with term frequency

### ISSUE THREAD

**Issue by loretoparisi** [google/sentencepiece#248]
When training a new language model I will get a vocabulary for that language with emission log probabilities like:

```
▁your	-73
ck	-74
▁ha	-75
ut	-76
es	-77
▁go	-78
▁all	-79
▁for	-80
▁j	-81
id	-82
ight	-83
▁ba	-84
▁kn	-85
▁is	-86
▁can	-87
▁don	-88
```

And also when calling the export tool `spm_export_vocab`.
While training I can see the term frequency been calculated for each word like:

```sh
/Users/loretoparisi/Documents/Projects/AI/sentencepiece/src/bpe_model_trainer.cc(259) LOG(INFO) Added: freq=7288 size=1920 all=102732 active=5741 piece=▁san
/Users/loretoparisi/Documents/Projects/AI/sentencepiece/src/bpe_model_trainer.cc(259) LOG(INFO) Added: freq=7182 size=1940 all=103435 active=6444 piece=▁americ
/Users/loretoparisi/Documents/Projects/AI/sentencepiece/src/bpe_model_trainer.cc(259) LOG(INFO) Added: freq=7068 size=1960 all=104151 active=7160 piece=▁strength
/Users/loretoparisi/Documents/Projects/AI/sentencepiece/src/bpe_model_trainer.cc(259) LOG(INFO) Added: freq=6945 size=1980 all=104545 active=7554 piece=▁spent
/Users/loretoparisi/Documents/Projects/AI/sentencepiece/src/bpe_model_trainer.cc(259) LOG(INFO) Added: freq=6843 size=2000 all=104948 active=7957 piece=▁trick
```

So instead of having for term `victorian` the emission log probability 

```sh
ip-192-168-1-103:build loretoparisi$ cat /root/lyrics_spm.vocab | grep victorian
▁victorian	-31879
```

the vocabulary would have the term frequency here:
```
LOG(INFO) Added: freq=46 size=31880 all=298692 active=14877 piece=▁victorian
```

Is it possible then to export these term frequencies in the input corpus?

Thank you.

**Comment by taku910** [comment]
Thank you for the feedback.

The segmentation algorithm of BPE is based on the *ordered* tokens.  BPE simply applies the merge operation in that order.  Since we cannot define the order of two tokens with the same frequency, it is technically difficult to replace the BPE score with frequency, though the score only represents the order. We might need to emit both score and frequency, which might be confusing at this point.

If you want to know the frequency (probability), I'd rather recommend using the default "unigram" model.
The segmentation algorithm of unigram is based on the tokens with the emission probability -- emits the best tokens in which the product of emission probabilities is maximized.  `exp(score)` is proportion to the frequency in the corpus.

**Comment by loretoparisi** [comment]
@taku910 thank you, my idea is to replace `sentencepiece` with the current regex tokenizers I'm using my AI pipeline, so having a language model for each language, and applying it to be used in the spell check tools as well (SymSpell / HunSpell), and inference from Word2Vec language detection models, because there is an important counter-effect of bad / missing tokenization in grammar rules like verbs contractions, etc. So having the term frequency as output from `sentencepiece` would make its vocabulary compatible with these models in the pipeline.

**Comment by taku910** [comment]
Thank you for explaining the background.

As I said,  the score of unigram can be considered as a frequency. You can get the token, id and frequency at the same time with the following python code.

```
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> import math
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('m.model')
True
>>> sp.EncodeAsIds('Hello world')
[156, 86, 20, 891]
>>> [[id, sp.IdToPiece(id), math.exp(sp.GetScore(id))] for id in sp.EncodeAsIds('Hello world')]
[[156, '▁He', 0.0012037066069725277], [86, 'll', 0.002231398281928935], [20, 'o', 0.008976161605572562], [891, '▁world', 0.0001059205216512531]]
```

**Comment by taku910** [comment]
Seems that the probability score in unigram language model can be used as freq. Let me close this bug. Please feel free to reopen it if you have any questions.
