### ISSUE TITLE
‘::PROTOBUF_NAMESPACE_ID’ has not been declared

### ISSUE THREAD

**Issue by tramphero** [google/sentencepiece#249]
I'm trying to compile the sentencepiece with the self-prepared protobuf.  I run the cmake, and it works:
$cmake .. -DCMAKE_PREFIX_PATH=/home/sly.zsl/espnet/tools/protobuf
-- VERSION: 0.1.6
-- Found TCMalloc: /usr/local/lib/libtcmalloc_minimal.so
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sly.zsl/espnet/tools/sentencepiece/build

However, i have the following problem when i try to make the sentencepiece:
$make
[  1%] Building CXX object src/CMakeFiles/sentencepiece.dir/sentencepiece.pb.cc.o
In file included from /home/sly.zsl/espnet/tools/sentencepiece/build/src/sentencepiece.pb.h:31:0,
                 from /home/sly.zsl/espnet/tools/sentencepiece/build/src/sentencepiece.pb.cc:4:
/home/sly.zsl/espnet/tools/sentencepiece/build/src/sentencepiece.pb.h:215:3: error: ‘::PROTOBUF_NAMESPACE_ID’ has not been declared
   GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(SentencePieceText_SentencePiece)
   ^
/home/sly.zsl/espnet/tools/sentencepiece/build/src/sentencepiece.pb.h:215:3: error: expected ‘>’ before ‘_field_type’
   GOOGLE_PROTOBUF_EXTENSION_ACCESSORS(SentencePieceText_SentencePiece)

**Comment by taku910** [comment]
Just a confirmation

Does /home/sly.zsl/espnet/tools/protobuf/bin/protoc exists?

**Comment by tramphero** [comment]
Finally, it works by using the following commands:
<<
cd sentencepiece
cmake .   -DCMAKE_PREFIX_PATH=<prefix_path_to_protobuf>
make -j 32
sudo make install 
sudo ldconfig -v
>>

**Comment by taku910** [comment]
Great!
