### ISSUE TITLE
Computing representative vocabularies for multiple large files

### ISSUE THREAD

**Issue by emjotde** [google/sentencepiece#252]
Hi,
what's the current foolproof way to generate a single representative SentencePiece model from multiple large files that may be in different languages and may have different domains in specific regions of the files? I want to avoid the model to be biased to specific part of the file or language. 

I understand that for space-delimited languages the tsv-based solution from https://github.com/google/sentencepiece/issues/245 would give me a guarantee that no file-layout related issues bias the model. For the raw text version there seems to be no way to specify to consume the entire file apart from specifying large limits. 

However, even for the EM algorithm it seem the tool selects subsets to iterate on that might be biased?

I could of course concatenate and shuffle all my files, but it would be nice to be able to train without external manipulation. 
Thanks.

**Comment by taku910** [comment]
Thank you for the feedback.

The trainer simply loads the first N lines (10M by default) from the training data. So, if the training data is large enough, you might need to shuffle the sentence by lines in advance to prevent the bias. In addition, EM and seed vocab selection also don't use entire lines to prevent memory explosion.

Do you think it is reasonable to let the trainer shuffle the input with [Reservoir Sampling](https://en.wikipedia.org/wiki/Reservoir_sampling)?

Fixed random seed may allow to make this sampling deterministic, but the behavior will get a little unpredictable.

One FYI is that we can feed multiple files as TSV.  In this case, multiple files are simple concatenated and first N lines are loaded.

`% spm_train --input=foo.txt,bar.txt`

**Comment by taku910** [comment]
I can see that the current spec for size limitation is confusing. Trainer loads `--input_sentence_size` sentences to make the seed character and vocab, and `--training_sentence_size` sentences for EM training, but I know it is tricky.

How about making it simpler like?

- By default, trainer loads entire sentences.
- Trainer can accept `--input_sentence_size` to limit the training data. We only have this parameter to control the size. (no training data size/mining_data_size)
- User can choose the sampling strategies from "first N lines" or "randomly choose N lines".

**Comment by emjotde** [comment]
That sounds good. I have currently implemented a wrapper that behaves roughly the way you describe for Marian vocabularies: 

https://github.com/marian-nmt/marian-dev/blob/cleanup-vocab/src/data/sentencepiece_vocab.cpp#L141

**Comment by taku910** [comment]
Thank you. Will update.

**Comment by taku910** [comment]
Updated.

- spm_train loads all files/sentences by default
- `--input_sentence_size=N` lets spm_train load randomly shuffled N lines.
- `--shuffle_input_sentence=false` loads first N lines instead.
- `--mining_sentence_size` and `--training_sentence_size` are deprecated.

**Comment by SamueLacombe** [comment]
Hello,

What would be the recommendation, when you have a bunch of languages (I have a file for each language in my case) and they are all different size?  Some have Billions of lines and some has 30k lines.

I would technically have like to do weighted rater then just random. 

Could we make that random a little more intelligent so that it pick randomly in all file, but first split the input_sentence_size into  as many files as there is, but based on the number of line (or size) of each file?

Example:
so if you had 2 files:
- input_sentence_size = 5000
- file 1 has 10000 lines
- file 2 has 1000 lines.

it would randomly pick :
4545 (10000/(10000+1000)*5000) from the first file
455 (1000/(10000+1000)*5000) from the second file
