### ISSUE TITLE
Newline token and User defined symbol, how it work?

### ISSUE THREAD

**Issue by hadaev8** [google/sentencepiece#253]
I want to add a new line symbol to model input, as advised in another topic, I used flag --user_defined_symbols='\<n\>'
if I understood correctly, should always be encoded to one id, but I get this
sp.EncodeAsIds('\<n\>')
output:
[40, 17, 6, 15]

**Comment by taku910** [comment]
Could you check  *.vocab file?  Does the token <n> exist in the vocab?

**Comment by hadaev8** [comment]
Seems so
<unk>	0
<s>	0
</s>	0
'<n>'	0
.	-3.00536
,	-3.19431
n	-3.43317
▁the	-3.47864
’	-3.60395
s	-3.90017
▁to	-3.96813
▁a	-4.04053
▁and	-4.17076
▁her	-4.19813
▁she	-4.23621

**Comment by taku910** [comment]
Aha, the vocab contains the single quote.

If you are using the python module for training, you might not need to put the single quote.
`--user_defined_symbol=<n>`

However, that's not the case on CLI program (spm_train)

Thank you.

**Comment by hadaev8** [comment]
Thanks
