### ISSUE TITLE
replace <unk>  with custom unk token "xxunk"

### ISSUE THREAD

**Issue by kasparlund** [google/sentencepiece#255]
Hi i am using the excellent sentencepiece with ULMfit in fastai. In order to integrate the two libraries i want to replace unk,bos,eos,pad symbols with the symbols used in fastai.

So far i have passed the following to sentencepiece along with the rest of the required arguments --unk_id=0 --bos_id=-1 --eos_id=-1 --pad_id=-1 --control_symbols=xxbos,xxeos,xxpad,xxmaj,xxup,xxrep,xxwrep,xxfld --model_type=unigram ....

setting unk=-1 fails a described in the docs: https://github.com/google/sentencepiece/blob/7e5ef014e81f8f3b90c7fa7f7a4a6a4bba8903fb/src/sentencepiece_model.proto

I find the above solution problematic. It would be better that we were able to tell sentencepiece to use(deactivate the controls but with the symbols defined by fastai. fx symbols. ie something like: --unk_id=(xxunk)  --bos_id=(1,xxbos) --eos_id=(-1) --pad_id=(2,xxpad ) 

Notice:
-unk_id only includes the symbol because unk must always be active
-bos_id include id and symbol as defined by the user
-eos_id include id=-1 to deactivate the symbol
-pad_id include id and symbol as defined by the user

**Comment by taku910** [comment]
`<unk>, <s>, </s>` are now hardcoded.
I'm going to support to replace them like `--unk_piece=xxunk`

**Comment by kasparlund** [comment]
good solution  -thanks

**Comment by taku910** [comment]
Implemented

`--unk_piece=STR, --bos_piece=STR --eos_piece=STR --pad_piece=STR` are available.


https://github.com/google/sentencepiece/pull/256

**Comment by taku910** [comment]
Pip module will be updated at the next release (current release is v0.1.6).
https://github.com/google/sentencepiece/releases
Please build python package from source to use this feature.
https://github.com/google/sentencepiece/blob/master/python/README.md#build-and-install-sentencepiece

**Comment by hankcs** [comment]
Maybe my understanding is poor, I'm just curious why `unk` must be activated given that BPE or Unigram with `byte_fallback` will never emit an `unk`.
