### ISSUE TITLE
do not split by apostrophe character

### ISSUE THREAD

**Issue by EgorLakomkin** [google/sentencepiece#263]
Hi,

Thx for the great library! I am curious if it is possible to have \' (apostrophe) character as a part of a word-piece? I always have DON'T split as [_DON, \', T], while I would imagine to have N'T subword piece.

Thank you in advance!

**Comment by taku910** [comment]
By default,  the extracted tokens (pieces) need to const of single unicode script type, but you can disable it with `--split_by_unicode_script=false` flag of spm_train.

However, this flag is applied in best-effort-basis. In general, we cannot introduce a strict constraint to merge characters, as they will be increasing the vocab size. On the other hand, constraints to split tokens can be applied whenever possible.

**Comment by abdr17** [comment]
> By default, the extracted tokens (pieces) need to consist of single unicode script type, but you can disable it with `--split_by_unicode_script=false` flag of spm_train.
> 
> However, this flag is applied in best-effort-basis. In general, we cannot introduce a strict constraint to merge characters, as they will be increasing the vocab size. On the other hand, constraints to split tokens can be applied whenever possible.

What do you mean by 'single unicode script'? Could you please elaborate?
