### ISSUE TITLE
Accessing Alignment Information between Detokenised/User-Input text in Python

### ISSUE THREAD

**Issue by ET-Chan** [google/sentencepiece#266]
In C++ api, one can obtain alignment information by using ``util::Status Encode(util::min_string_view, SentencePieceText* )``. I was wondering is there any plan to expose this functionality in python?

**Comment by taku910** [comment]
Current Python API doesn't support alignment API.

I will add them in the next official release (v0.1.8).

**Comment by ET-Chan** [comment]
Thanks! Let me know if I can help in any way.

**Comment by taku910** [comment]
Added the API in HEAD.

The new API returns the serialized protocol buffer in Python's bytes object. 

First, install protobuf python module and generate sentencepiece_pb2.py.
```
% pip install protobuf
% cd python
% protoc -I../src --python_out=. ../src/sentencepiece.proto
```

Here's the sample code. `EncodeAsSerializedProto` returns the serialized protocol buffer. Then you can get the full proto by deserializing the bytes object.

Notes that the alignment information `begin/end` is the utf8-byte index, which are not always compatible with Python's Unicode string (especially on Python3). Please feel free to reopen the issue if the current API is not enough for you.

````
[Python 3.5.4rc1 (default, Jul 25 2017, 08:53:34) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sentencepiece as spm
>>> import sentencepiece_pb2
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('m.model')
True
>>> spt = sentencepiece_pb2.SentencePieceText()
>>> spt.ParseFromString(sp.EncodeAsSerializedProto('Hello world.'))
105
>>> spt
text: "Hello world."
pieces {
  piece: "\342\226\201He"
  id: 156
  surface: "He"
  begin: 0
  end: 2
}
pieces {
  piece: "ll"
  id: 86
  surface: "ll"
  begin: 2
  end: 4
}
pieces {
  piece: "o"
  id: 20
  surface: "o"
  begin: 4
  end: 5
}
pieces {
  piece: "\342\226\201world"
  id: 891
  surface: " world"
  begin: 5
  end: 11
}
pieces {
  piece: "."
  id: 4
  surface: "."
  begin: 11
  end: 12
}
````

The python module available with PyPI doesn't include this change yet. (will include it in the next official release).  You can make the wheel package from scratch with the following command (docker should be installed in advance)

```
% sudo sh python/make_py_wheel.sh x86_64
% ls python/dist/*
```

**Comment by ArbinTimilsina** [comment]
Hi @taku910,
Thanks a lot for this!
Any idea when the python module available with PyPI will include this change? 

Regards,
Arbin
