### ISSUE TITLE
Python wrapper from PyPi is incompatible with Python 3

### ISSUE THREAD

**Issue by noe** [google/sentencepiece#28]
Recently, a fix for the compatibility with Python 3 of the python wrapper [was committed](https://github.com/google/sentencepiece/commit/75695aa1e4309ff8ef84f5300c01498d7cc90fa7). However, the version of the python wrapper [uploaded to PyPi](https://pypi.python.org/pypi/sentencepiece/0.0.0) is from 2017-08-28 and does not contain the aforementioned recent fixes. Could you upload the newest version? (from the PiPy page I guess that @taku910 is the owner of the package)

**Comment by taku910** [comment]
Sorry for the late reply. I've updated the PiPy site. You will be download the latest package that supports Python3. Please let me know if you have any problem.
