### ISSUE TITLE
better candidate for `unk_surface`

### ISSUE THREAD

**Issue by ysmiraak** [google/sentencepiece#280]
the current default value for `unk_surface` is `" ⁇ "`, i understand the behavior from #134.

ideally `decode_ids` would be inverse to `encode_as_ids`, which is not possible due to unknown characters.  still it would be nice that after one round of encoding and decoding we could obtain the fixed point.  however the unicode character `"⁇"` is normalized as `"??"` namely two ascii question marks, which introduce an additional complication.

consider the string `"the King in Yellow"` and `"Y"` being an unknown character in my model, after one round of encoding and decoding, it becomes `"the King in  ⁇ ellow"` with the unicode `unk_surface`, and after another round it becomes `"the King in ?? ellow"` with two ascii question marks, which is finally the fixed point, however we lost `unk_surface` here.

i do like the unicode normalization behavior, but that means `⁇` is not the ideal candidate, neither is the usual replacement character `�`.  since i'm not familiar with the sentencepiece internal, could you suggest a better candidate?

on another matter, i don't understand why the heading/tailing spaces are necessary.  if the unknown token is an independent token, wouldn't it normally come with spaces or other punctuations?  adding those spaces would change the length of encoded sequence in the next round, since `unk_surface` would be mapped to `unk_id` and the two spaces to the id of `▁` or ignored depending on if there are more spaces around.  this behavior is quite complicated and also not ideal in my opinion considering how (de)tokenization should proceed for bleu evaluation.

btw thanks a lot for the awesome program!  it saves me so much trouble in text processing.

**Comment by taku910** [comment]
Current treatment for unknown token is just a reasonable workaround. I'd suggest making the model not to emit unknown tokens.

1. Uses `--character_coverage=1`.  (this might not be good for CJK languages)
2. When seeing UNK token, replace them with known tokens copied from the source sentence. We can use the attention weights to figure out the best-aligned source tokens.

As for the heading/tailing spaces, see https://github.com/google/sentencepiece/issues/282
