### ISSUE TITLE
pip release questions

### ISSUE THREAD

**Issue by szha** [google/sentencepiece#281]
Happy new year.
1. the new source dist seems to invalidate other binary releases and cause problem: 
![image](https://user-images.githubusercontent.com/2626883/51013795-4e16e600-1519-11e9-8beb-8a1f6232d4f9.png)
![image](https://user-images.githubusercontent.com/2626883/51013815-6ab31e00-1519-11e9-8028-8a79bd2e1c55.png)
2. I see [0.1.8](https://github.com/google/sentencepiece/releases/tag/v0.1.8) has been released. Is it planned upload to pypi?

**Comment by taku910** [comment]
Release v0.1.8
Previous source package has been removed.
