### ISSUE TITLE
leading space for the first token

### ISSUE THREAD

**Issue by monsieurzhang** [google/sentencepiece#282]
I notice there is a leading space for the first token in the output.
e.g. ['▁', 'New', '▁York']

Can I ask what is the purpose of the first spacer?
It seams there is no extra benefit.
Thank you.

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L201

You can disable the dummy prefix with `--add_dummy_prefix=false` of `spm_train`.
