### ISSUE TITLE
word length limit

### ISSUE THREAD

**Issue by monsieurzhang** [google/sentencepiece#284]
Hi,

I'm trying to train a  sentencepiece model for Chinese.
Since I use a lot Chinese data, the generated vocab contains some tokens which are relatively long.
e.g.   我们是一个非常好的
there are 9 characters inside one token.
I understand this is because such token exist many times in the training corpus.
However,
Is there any parameter to restrict the maximum length for each token?
Thanks.

**Comment by taku910** [comment]
You can try `--max_sentencepiece_length=<SIZE>` option to restrict the size of piece.

```
% spm_train --input ... --model_prefix=... --max_sentencepiece_length=3
````
