### ISSUE TITLE
TrainerInterface::LoadSentences() vocab_size validation should be CHECK_LE_OR_RETURN

### ISSUE THREAD

**Issue by combacsa** [google/sentencepiece#286]
Problem
======

```
trainer_interface.cc(403) LOG(INFO) Alphabet size=136
trainer_interface.cc(404) LOG(INFO) Final character coverage=1
Traceback (most recent call last):
```
(omitted)
```
RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/trainer_interface.cc(428) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) < (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 139 vs 139. Increase vocab_size or decrease character_coverage with --character_coverage option.
```

Reasoning
========

Let's take a look into source code.

https://github.com/google/sentencepiece/blob/552937ed85902afc4bf450882ee653f5113688be/src/trainer_interface.cc#L425

When there are 136 alphabets, with 3 more meta-alphabets, 139 would be enough, doesn't it? But it tries to compare using `CHECK_LT_OR_RETURN` instead of `CHECK_LE_OR_RETURN` so the error message becomes `Vocabulary size is smaller than required_chars. 139 vs 139.`.

Please do not hesitate to let me know if I'm thinking in the wrong way.

**Comment by taku910** [comment]
Thank you for the feedback.

Right, this should be CHECK_LE_OR_RETURN. Fixed in the HEAD.
