### ISSUE TITLE
Inference time cost

### ISSUE THREAD

**Issue by samhavens** [google/sentencepiece#288]
Is inference time cost proportional to max_sentence_length or to the given input sentence length? Thank you :)

**Comment by taku910** [comment]
max_sentence_length is the parameter for training. 

The inference cost is roughly defined as:

- O(N)   (--model_type=unigram)
- O(N * log(N))  (--model_type=bpe)

where N is the sentence length.

When training with --split_by_whtespace=true (the default setting is true),  BPE cost can be reduced to
- O(M log(M) * K|)

where  M is the average word length and K is the number of words in a sentence, which is usually smaller than the cost of unigram mode.
