### ISSUE TITLE
handling of special symbols: this is a question not an issue :)

### ISSUE THREAD

**Issue by kasparlund** [google/sentencepiece#289]
Hi Taku thx for this wonderfull lib. I'am starting to get good results with the integration of sentencepiece and fastai/pytorch.

I am working with a dump of the english wikipedia processed by wikipedia extractor and then a lot of extra algos to extract sentences that are primarily (66%) composed of [A-Za-z] characters. 

I found that it was help full to enforce that the following characters are independent, by putting them in userdefined symbols: "0","1","2","3","4","5","6","7","8","9", "°","%","$","§","£","€","(",")","<",">","\"","\'","“","”","‘","’","!",",",";",":",".","•","—","\\", "/","*","+","-","=","⁄","|","′","_","#","&","?"
thus avoiding tokens for ""),",  ").",  "1090" etc. because i would consider ") as unstable because " ) is seen just as often.

**However my impression is that so may userdefined symbols is not really what userdefined symbols was designed for ? or was it?.** 

It would be perfectly ok that sentencepiece allocated less priority to these symbols as long as they do not start to merge them with other symbols. What is your advice on this approach ?

**Comment by taku910** [comment]
Thank you for using SentencePiece.

I think we can use the userdefine symbols though the original purpose is slightly different.  userdefined symbols can be used If we want to segment specific sequence of characters as one token.

Sentencepiece will not extract pieces consisting of multiple Unicode script types by default. For instance, ABC123 will not be extracted (mixture of Alphabet and numbers). However, we will see the pieces like 123.

**Comment by kasparlund** [comment]
Thx 
The first issue was that SP included many number like 1901 2000 .49% when trained on wikipedia. Having separate number 0,1,2 generalizes better to classification of imdb reviews .
I will continue to use the userdefine as above
