### ISSUE TITLE
undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

### ISSUE THREAD

**Issue by ramreddyyasa** [google/sentencepiece#293]
Hi ,
When I am  trying to import "tf_sentencepiece" . I am getting following error:

NotFoundError                             Traceback (most recent call last)
<ipython-input-1-7f167e7476bd> in <module>
 import tf_sentencepiece as tfs

~/.conda/envs/tf_gpu/lib/python3.6/site-packages/tf_sentencepiece/__init__.py in <module>
 from __future__ import print_function
 from tf_sentencepiece.sentencepiece_processor_ops import *
~/.conda/envs/tf_gpu/lib/python3.6/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py in <module>
 _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
~/.conda/envs/tf_gpu/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py in load_op_library(library_filename)
RuntimeError: when unable to load the library or get the python wrappers.
 """
 lib_handle = py_tf.TF_LoadLibrary(library_filename)
op_list_str = py_tf.TF_GetOpList(lib_handle)
NotFoundError: /home/user/.conda/envs/tf_gpu/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.12.0: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

Help me out in resolving this issue.
Thanks in advance.

**Comment by taku910** [comment]
tf_sentencepiece is built with the official [tensorflow pypi package](https://pypi.org/project/tensorflow/).  The latest version is 1.12.0.

Seems that the tensorflow you are using now is not the official pypi release.  How did you install tensorflow?

**Comment by ramreddyyasa** [comment]
I have installed tensorflow using below command
" conda install tensorflow-gpu "

**Comment by veqtor** [comment]
I've made some more research into this and it seems you need to install the specific build (arch, GCC-ver etc) for sentencepiece to work.
I'm out of luck since I'm using to Azure
Think we will have to switch to PyTorch, not giving in to Google's enforcement to use their cloud infrastructure just to get encoders to work :/

**Comment by shuiruge** [comment]
I got the same problem. My TF version is 1.13.1, installed by `conda install tensorflow`. My Python version is 3.6.0, anaconda on Centos 7. Is there any help?

**Comment by shuiruge** [comment]
I have solved this problem with the aid of Docker, simply using an official tensorflow runtime as a parent image. Explicitly, within the Dockerfile, write `FROM tensorflow/tensorflow:latest-py3`.

**Comment by DebanjanaKar** [comment]
@ramreddyyasa Did you find a solution? I am stuck with the same problem.

**Comment by redsk** [comment]
I have the same problem. tensorflow-gpu, sentencepiece and tf-sentencepiece installed from pip. Python 3.7. I tried with both tensorflow-gpu==1.13.1 and tensorflow-gpu==1.14.0.

**Comment by redsk** [comment]
I was able to make it work by setting `-D_GLIBCXX_USE_CXX11_ABI=1` in `make_py_wheel.sh`.

**Comment by srlemon** [comment]
i have the same proplem , should be tesorflow environmental factors

**Comment by srlemon** [comment]
I solved the problem and changed the python version to 3.6.9.

**Comment by taku910** [comment]
Just updated tf_sentencepiece. You can install it via pip install tf_sentencepiece.

https://github.com/google/sentencepiece/releases/tag/v0.1.83

**Comment by mhajiaghayi** [comment]
@taku910 , I just got the latest tf_sentencepiece and the the above problem still exists. i'm running py 3.6.9 and tf 1.14 on linux

**Comment by mhajiaghayi** [comment]
> I solved the problem and changed the python version to 3.6.9.

how did you exactly solve this issue? are you using tf 1.14?

**Comment by urekalion** [comment]
@mhajiaghayi 
I had the same problem, ubuntu 16.04, 
my problem is mismatched gcc version between tensorflow(conda) and tf-sentencepiece.
ubuntu gcc version 5.4.0, conda gcc version is higher than ubuntu gcc version.

I solved the problem by this flow 
1. i removed conda3 and i installed anaconda2
2. conda activate and conda install tensorflow-gpu (because install dependency) 
3. pip install tensorflow-gpu (overwrite)
4. pip install sentencepiece tf-sentencepiece

**Comment by dsunjka** [comment]
Had the same problem today and solved it by:

	conda create -n "tensorflow" **python=3.6.9**
	conda activate tensorflow
	conda install pip
	pip install tensorflow-gpu
	pip install sentencepiece tf-sentencepiece tensorflow-hub

Setting python=3.6.9 was the most important thing. Changing versions of the libraries did not help, as some others reported already.

**Comment by Miraclemarvel55** [comment]
那是conda 的问题,我换成pip 安装 tensorflow 就没问题.

**Comment by taichuai** [comment]
> 那是conda 的问题,我换成pip 安装 tensorflow 就没问题.

me too。。

**Comment by Heeyyy** [comment]
> 那是conda 的问题,我换成pip 安装 tensorflow 就没问题.

哇谢谢老哥，解决了！

**Comment by sergiomora03** [comment]
> @taku910 , I just got the latest tf_sentencepiece and the the above problem still exists. i'm running py 3.6.9 and tf 1.14 on linux

@taku910 Actually i´m running in Google Colab and I get the same issue. Can you help me?

**Comment by asunyz** [comment]
> 那是conda 的问题,我换成pip 安装 tensorflow 就没问题.

Thanks so much!

**Comment by Jijun** [comment]
thanks , conda 误我
