### ISSUE TITLE
error!!!

### ISSUE THREAD

**Issue by amirakazadeh** [google/sentencepiece#297]
hi 
I try this:

import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=farhang.txt --model_prefix=m --vocab_size=1000')

and this error occurred:

RuntimeError                              Traceback (most recent call last)
<ipython-input-50-ec9a38270818> in <module>()
      5 
      6 import sentencepiece as spm
----> 7 spm.SentencePieceTrainer.Train('--input=farhang.txt --model_prefix=m --vocab_size=1000')

RuntimeError: Internal: C:\projects\sentencepiece\src\trainer_interface.cc(468) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] 

how can I fix it?
tnx

p.s : I've just install it by PIP not from source

**Comment by taku910** [comment]
Please try `--hard_vocab_limit=false`.

Details:  https://github.com/google/sentencepiece/issues/226

**Comment by amirakazadeh** [comment]
thank you for fast answering :)

I try this: 

import sentencepiece as spm
sp = spm.SentencePieceProcessor()

fout_path = "C:/Users/Azadeh/Desktop/FNLI/book/aa.txt"
num_vocab = 40000
spm.SentencePieceTrainer.Train('--input={} --model_prefix=wikijp_model --vocab_size={} --character_coverage=0.9995 --model_type=bpe --input_sentence_size=10000000 --hard_vocab_limit=false '.format(fout_path,num_vocab))

and it returns : True

I want to build a language model for persian language.
how can I build and export and train it?

tnx alot for your help

**Comment by taku910** [comment]
LM training is not a scope of sentencepiece.
You might want to feed the segmented sentences to language model training systems.

**Comment by romanegloo** [comment]
> Please try `--hard_vocab_limit=false`.
> 
> Details: #226

Can anyone explain what was causing the error message and what this additional option is doing?

**Comment by Yeo0** [comment]
> 
> 
> Please try `--hard_vocab_limit=false`.
> 
> Details: #226

I had same problem and tried that option `--hard_vocab_limit=false`. and it works like exception handler. just ignore error and return so I can't train model more than twice. Is there any practical solution for this problem? T.T
