### ISSUE TITLE
python wrapper export vocabulary list

### ISSUE THREAD

**Issue by xinsu626** [google/sentencepiece#299]
Hello,
I am using python wrapper to train the model. My questions are:

- Is there any way I can export the vocabulary list after using python wrapper train the model?
- Can you please give me the directory where trained model saved?

Thanks a lot.

**Comment by taku910** [comment]
The vocab list can be obtained with the following code.

````
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('test_model.model')
True
>>> vocabs = [sp.IdToPiece(id) for id in range(sp.GetPieceSize())]
````

The model file is stored in the `<prefix>.model`. The prefix is specfied with `--model_prefix` parameter in training

**Comment by xinsu626** [comment]
Thank you so much for answering my question!
