### ISSUE TITLE
Request: sentencepiece_processor_ops.so for tensorflow 1.13.1

### ISSUE THREAD

**Issue by wjywbs** [google/sentencepiece#300]
Could you update the tf_sentencepiece library to include tensorflow 1.13.1 support? Thanks.

**Comment by taku910** [comment]
Updated.

You can update the latest version via pip shortly.

https://github.com/google/sentencepiece/releases/tag/v0.1.81

**Comment by unoexperto** [comment]
@taku910 Sorry for reviving this issue but I have related issue. Shall I create new ticket ?

I'm on following version under TF 1.13.1 GPU

```
Name: tf-sentencepiece
Version: 0.1.82
Summary: SentencePiece Encode/Decode ops for TensorFlow
Home-page: https://github.com/google/sentencepiece
Author: Taku Kudo
Author-email: taku@google.com
License: Apache
Location: /home/expert/.local/lib/python3.7/site-packages
```

Runtime error I get is

```
  File "/home/expert/work/sideprojects/python_test/xling_test.py", line 4, in <module>
    import tf_sentencepiece
  File "/home/expert/.local/lib/python3.7/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/home/expert/.local/lib/python3.7/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 43, in <module>
    _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
  File "/home/expert/.local/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/expert/.local/lib/python3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.13.1: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs
```

**Comment by DebanjanaKar** [comment]
@unoexperto  Did you find a solution to your problem?

**Comment by DebanjanaKar** [comment]
@wjywbs  Did it work? I seem to be using the provided wheel in my Linux (Ububtu 16) subsystem with Tensorflow version 1.13.1  but it lands with the same error as reported by @unoexperto . 
```>>> import tf_sentencepiece
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/gsoc19/lib/python3.6/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/home/user/anaconda3/envs/gsoc19/lib/python3.6/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 43, in <module>
    _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
  File "/home/user/anaconda3/envs/gsoc19/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/user/anaconda3/envs/gsoc19/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.13.1: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

**Comment by DebanjanaKar** [comment]
In my case, the issue was : I had installed tensorflow using conda and tf_sentencepiece using pip. That caused incompatibility. It's solved now, thanks.

**Comment by redsk** [comment]
I have the same problem. `tensorflow-gpu`, `sentencepiece` and `tf-sentencepiece` installed from pip. Python 3.7. I tried with both `tensorflow-gpu==1.13.1` and `tensorflow-gpu==1.14.0`.

**Comment by perone** [comment]
Same issue as well, found that the error is related to a missing tensorflow lib: `libtensorflow_framework.so.1 => not found` which is referenced by `_sentencepiece_processor_ops.so.1.14.0`

**Comment by zkmake520** [comment]
> Same issue as well, found that the error is related to a missing tensorflow lib: `libtensorflow_framework.so.1 => not found` which is referenced by `_sentencepiece_processor_ops.so.1.14.0`
> 
> Tried already using only conda, only pip, making a symbolic link to the missing shared library, etc, and it seems that the symbol `_ZN10tensorflow12OpDefBuilder4AttrESs` (`tensorflow::OpDefBuilder::Attr(std::string)` isn't on the tensorflow library `libtensorflow_framework.so.1`.

Hi could you describe how to make a symbolic link to the missing shared library? Thanks

**Comment by perone** [comment]
The symbolic link won't work, it seems that it is an issue with the ABI of the library.
