### ISSUE TITLE
Forcing a 'white_space' token

### ISSUE THREAD

**Issue by bernardohenz** [google/sentencepiece#302]
Hi,

I have a Speech Recognition implementation that uses a Language Model (word based). This Language Model is only called whenever it is evaluating a white_space label (meaning the end of a word). I am trying to change our alphabet to a word-piece model such as the one on this repo, but I do not know how to handle this case. Is there a way to force the whitespace as a label/token?

**Comment by taku910** [comment]
You may want to enforce the space marker `▁` to be treated as user defined symbol.

```
spm_train --input=.. --model_prefix= ..   --user_defined_symbol=▁  --add_dummy_prefix=false
```

`--add_dummy_prefix=false` is added not to add this whtespace marker at the BOS.

Then all spaces are treated as one independent token.

**Comment by bernardohenz** [comment]
Thanks, it adds a single token for white-space, but the whitespace can still be found on another pieces. Nonetheless, I'm just running a find on  the string for the ▁ to know whether a new word has been formed.
