### ISSUE TITLE
Problem recognizing end of string

### ISSUE THREAD

**Issue by bernardohenz** [google/sentencepiece#304]
Hi,

I was able to train a model and use it in a dummy code in C++ (left image). Unfortunately, when I try to compile and run the same code into a greater project, my code seems to fail on recognizing the end of string (right image). Next I show the output of both codes. On them I am just getting a piece for a single ID ( 140 -> ▁seis) and printing the size of the string. Note how the output on the right gets the string-size wrong, even when outputting the entire string. Right below I tried to output the int for each position of the string for the first 10 positions (showing that they are getting similar objects from the IdToPiece(int)).

![image](https://user-images.githubusercontent.com/810340/54281106-c597de80-4577-11e9-8e0c-69a04e88dbf4.png)

Is this something related to encoding or compiler settings?

**Comment by taku910** [comment]
My feeling is that the client code is touching uninitialized memory regions accidentally. You might want to try valgrind to find memory errors.

**Comment by taku910** [comment]
Let me close this bug as no similar bugs are reported so far. Please feel free to reopen it if you find this bug again.
