### ISSUE TITLE
The tokenizer always append a ▁ token for tokenizing a sentence

### ISSUE THREAD

**Issue by weiczhu** [google/sentencepiece#305]
Loaded a trained SentencePiece model.
['▁', 'あ', 'と', '、', '梱包', 'に', '関', 'して', 'は', '、', '塩', 'が', '袋', 'から', '少し', '漏', 'れ', '出', 'て', 'いた', 'ので', '少し', '雑', 'な', '印', '象', 'を', '受', 'け', 'ました', '。']

**Comment by weiczhu** [comment]
Here at the beginning of the sentence the output has an extra ▁ which should not exist

**Comment by taku910** [comment]
This is expected.  By adding _ at the beginning, we can treat the "Hello" in the following two sentences in the same way.

```
Hello world.
ABC Hello
```

You can turn off this mode with `--add_dummy_prefix=false` 

```
% spm_train --input=... --model_prefix=m --add_dummy_prefix=false
```
