### ISSUE TITLE
Vocabulary restriction in python binding

### ISSUE THREAD

**Issue by lzhang10** [google/sentencepiece#307]
I got the Python binding to work via `pip`. Now I see the command line binary actually supports vocabulary restriction: https://github.com/google/sentencepiece#vocabulary-restriction

Is there a way to do the same thing in Python? Even if I create language specific vocabulary with the binary, the Python API does not seem to support loading a vocabulary.

**Comment by taku910** [comment]
Python module does support vocab restriction.
Please let me know if the current API is not enough.

https://github.com/google/sentencepiece/issues/250
