### ISSUE TITLE
sentencepiece_processor_ops.so Not Found

### ISSUE THREAD

**Issue by khemon** [google/sentencepiece#309]
I get an error while importing tf_sentencepiece, tensorflow claiming is not able to find the library file : _sentencepiece_processor_ops.so 
whereas the path file actually exists.. 

NotFoundError: [...]\anaconda3\lib\site-packages\tf_sentencepiece\_sentencepiece_processor_ops.so 

versions: 
* tensorflow version : 1.13
* tf_sentencepiec: 0.1.3

OS: windows 10

**Comment by taku910** [comment]
This is expected. tf_sentencepiece is not supported on Windows now.

It would be possible to make ops on windows, but it is not that easy.
https://github.com/tensorflow/models/issues/1103

**Comment by YueCongPKU** [comment]
I was in Linux, and encountered the same problem.
**tensorflow.python.framework.errors_impl.NotFoundError: /data/users/congyue/anaconda2/envs/python2/lib/python2.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.10.0: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceENS_11StringPieceEPSs**

![image](https://user-images.githubusercontent.com/5901729/56561045-a6f62000-65d8-11e9-8b31-44c615144292.png)

Version

- tensorflow: 1.10.0

- tf-sentencepiece: 0.1.82
OS: Ubuntu 14.04.5 LTS

**Comment by YueCongPKU** [comment]
and I upgraded tensorflow's version to 1.13.1, and the problem still exists.
How may I fix it? @taku910

**Comment by Yusifu** [comment]
> and I upgraded tensorflow's version to 1.13.1, and the problem still exists.
> How may I fix it? @taku910

Have you fix it?
I encountered the same problem.

**Comment by RogerChu8** [comment]
I encounter the same problem with error message:

dlopen(/Users/...../site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.so.2.0.0, 6): image not found

Version installed within virtualenv:
- TensorFlow: 2.1.0
- tf-sentencepiece 0.1.85

OS: MacOS 10.15.2
