### ISSUE TITLE
For languages that not share an alphabet, like chinese and english,  should I train the shared spm model or train their own spm model separately?

### ISSUE THREAD

**Issue by luckysofia** [google/sentencepiece#310]

**Comment by taku910** [comment]
It depends on the application and tasks, but in neural machine translation, the quality of shared/separated spms are almost comparable, but shared spms are much easier to maintain.

In addition, you can use the vocab restriction feature in shared vocab to avoid decoder from generating invalid characters which should not appear in the target language.

https://github.com/google/sentencepiece#vocabulary-restriction
