### ISSUE TITLE
erros while installing  protocol-buffer known as SentencePiece 

### ISSUE THREAD

**Issue by HoussBz** [google/sentencepiece#311]
Hello , im trying to install a protocol-buffer known as SentencePiece too, to alleviate the open vocabulary problems in neural machine translation .

I used this command as suggested on github documentation :

sudo apt-get install cmake build-essential pkg-config libgoogle-perftools-dev

it gives an error :

eventhough I have cuda10.1 installed .

any ideas ?
![quest1](https://user-images.githubusercontent.com/37712301/55002175-6f468900-4fd6-11e9-8f3c-9b1433c6ef3f.png)
![rep1](https://user-images.githubusercontent.com/37712301/55002176-6f468900-4fd6-11e9-86d6-0a4ca2dd8ba5.png)

**Comment by taku910** [comment]
It seems that they are not real errors but warnings. All required packages seems to be already installed.
Could you try the command lines to build & install sentencepiece?

https://github.com/google/sentencepiece#build-and-install-sentencepiece

**Comment by HoussBz** [comment]
![no](https://user-images.githubusercontent.com/37712301/55024117-826d4f00-4ffe-11e9-9515-e37171b3301a.png)
that means sentencepiece is not installed no ? therefore i cant run the mentionned commands suggested by you . correct ?

**Comment by taku910** [comment]
"sentencepiece" command is not installed. the tool name will be spm_*. Please take a look at the following documentation.

https://github.com/google/sentencepiece#end-to-end-example
