### ISSUE TITLE
Expected behavior of Python bindings `is_unknown`

### ISSUE THREAD

**Issue by DavidHarrison** [google/sentencepiece#315]
The Python bindings currently defined [`is_unknown`](https://github.com/google/sentencepiece/blob/271431b5a621c2a4931c92f62aad10622ac74b66/python/sentencepiece.i#L257) the same as `is_unused`. Is this the intended behavior?

**Comment by taku910** [comment]
No, it's a bug. Thank you for the feedback. will fix it soon.

**Comment by taku910** [comment]
Fixed.

**Comment by DavidHarrison** [comment]
Thanks!
