### ISSUE TITLE
Using a comma in --user_defined_symbols

### ISSUE THREAD

**Issue by shane-carroll** [google/sentencepiece#317]
Since `--user_defined_symbols` is a comma-separated list, it seems that there is no way to use a comma as a defined symbol. 

I have tried:
1. Escaping it with `\`:  `--user_defined_symbols='a,b,\,,c'`
(results in `\` becoming a defined symbol)
2. Not escaping it:  `--user_defined_symbols='a,b,,,c'`
(results in only `a`, `b`, and `c` as defined symbols)
3. Using Python and C++ training interfaces
4. With and without single and double quotes around the RHS argument

Anything I missed?

**Comment by taku910** [comment]
Right, we cannot set comma in the command line flags, as the command line parser simply splits the fields with comma. 

You can use the C++ API with TrainerSpec proto.

API entry point.
https://github.com/google/sentencepiece/blob/master/src/sentencepiece_trainer.h#L30

The function to parse --key=value flag into TrainerSpec.
https://github.com/google/sentencepiece/blob/master/src/spec_parser.h#L71
https://github.com/google/sentencepiece/blob/master/src/spec_parser.h#L254

**Comment by shane-carroll** [comment]
OK, thanks. My takeaway is that there is no trivial way to do it, so I will just let the model learn it on it's own (commas are common enough to generate it's own token, anyway).

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/issues/467
