### ISSUE TITLE
'spm_train' is not recognized.

### ISSUE THREAD

**Issue by opennmt91** [google/sentencepiece#319]
Hello Dears,

I am working with conda package and TensorFlow environment, When I installed the 'sentencepiece-master' from the command 'pip install sentencepiece' they show me I installed the library well but when I started to train my corpus through the command **'spm_train --input=src-train --model_prefix=src-vocab --vocab_size=32000 --character_coverage=0.9995 --model_type=word'** I got that error **'spm_train' is not recognized** could anyone help me and tell me what is the problem ??

**Comment by taku910** [comment]
spm_train is not installed with pip command. You might want to go through the following document to install spm_train.
https://github.com/google/sentencepiece#c-from-source

Python module also provides the training API.  Basically we pass the same command line options to SentencePieceTrainer.Train() function.
https://github.com/google/sentencepiece/blob/master/python/README.md#model-training

**Comment by opennmt91** [comment]
Thanks for you support, I really appreciate it. I already looked at the documentation and help but I have another question does the package work with Windows or it only works with Linux and  macOS ??

**Comment by opennmt91** [comment]
Also I have another question, If i installed the package at Linux and prepared the files then moved them to windows and start to train them(as I already installed OpenNMT at windows) will that step will be a correct one or it will be not and affect the quality ??
