### ISSUE TITLE
Training from tempfile gives "RuntimeError: Internal.."

### ISSUE THREAD

**Issue by ben0it8** [google/sentencepiece#320]
Hello,

I was trying to train a sentencepiece model with the Python wrapper, passing a tempfile the following way:

```python
import tempfile
tmp = tempfile.NamedTemporaryFile()

with open(tmp.name, 'wt') as f:
    f.writelines(line+'\n' for line in texts)
    train_cmd = f"--input={tmp.name} --model_prefix=spm"
    ret = spm.SentencePieceTrainer.Train(train_cmd)
```
where `texts` is a list of strings but I got:
 

> RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(498) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())]  
> RuntimeError                              Traceback (most recent call last)
> <ipython-input-141-fa4e1723b716> in <module>
>       8     f.writelines(line+'\n' for line in texts)
>       9     train_cmd = f"--input={tmp.name} --model_prefix=spm"
> ---> 10     ret = spm.SentencePieceTrainer.Train(train_cmd)
> 
> RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(498) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] 

any idea how to do this without having to write to disk? :)

**Comment by taku910** [comment]
Please see
https://github.com/google/sentencepiece/issues/297
