### ISSUE TITLE
how are unknown characters in a sequence handled?

### ISSUE THREAD

**Issue by frankseide** [google/sentencepiece#322]
Hi, would you mind clarifying how unknown characters are handled if they occur in side a sequence?

Consider a continuous segment of Japanese characters `ABCD` where `C` is a rare character that did not make it into piece inventory. Would this be segmented as

* `<unk/>`
--or--
* `AB` `<unk/>` `D`

(Let's assume for this example that AB is a frequent pair.)

It would also be great to clarify this in the documentation (if it's not already there).

Thanks!

**Comment by taku910** [comment]
The output should be AB <unk/> D. 

SentencePiece preserves all the symbols/chars in the input except for unknown symbols, so AB and D will remain.
