### ISSUE TITLE
How can i add character to existing model?

### ISSUE THREAD

**Issue by misssprite** [google/sentencepiece#323]
I have trained a sp model on a large corpus with fixed vocabulary(in chinese) and then trained language model with this tokenizer.

Then I finetune th language model on a smaller corpus and find that there're many oov characters.
I don't wanna include all characters in the large corpus because it'll be too large to handle. 

How can I simply add oov characters in the small corpus to the sp model to avoid frequent oov occurrence?

**Comment by misssprite** [comment]
Or how to train sp model on utf-8 bytes like in gpt2, avoiding oov problem and treating the oov character as predicting byte sequence?

**Comment by taku910** [comment]
You can edit the model file manually to add new symbols.

The model file is stored as protocol buffer. Here you can find how to manipulate the proto.
https://github.com/google/sentencepiece/issues/121

The repeated fields "pieces" store the vocab. You can add new characters with minimum score.
https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L261

**Comment by dszhengyu** [comment]
> You can edit the model file manually to add new symbols.
> 
> The model file is stored as protocol buffer. Here you can find how to manipulate the proto. #121
> 
> The repeated fields "pieces" store the vocab. You can add new characters with minimum score. https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L261

Hi @taku910, sorry to bother you, could you elaborate on the "add new characters with minimum score" statement? Do you mean all the added new characters should have lower score than all the previous tokens? Why?
