### ISSUE TITLE
Question: Corpus with many short sentences

### ISSUE THREAD

**Issue by villmow** [google/sentencepiece#324]
I have a corpus with many very short sentences (sometimes a sentence is just a token). What is the best approach to train a sentencepiece model on that? I'd like to train on as many sentences as possible.

When I write every sentence in a new line it gives me the following warning:
```
trainer_interface.cc(114) LOG(WARNING) Too many sentences are loaded! (33634124), which may slow down training.
trainer_interface.cc(116) LOG(WARNING) Consider using --input_sentence_size=<size> and --shuffle_input_sentence=true.
```

I tried experimenting with grouping them together in a single line seperated with BOS and EOS symbols:
```
<s>token1</s><s>token2</s> ...
<s>token</s><s>token token</s> ...
```
Is that a valid approach? How would you train on that corpus?

**Comment by taku910** [comment]
No, you don't want to add BOS/EOS symbols.  You can simply ignore the error message. No need to change the command line.

If you can make a TSV files where the first column is the sentence and the second column is the frequency,
you can make the training a little faster. You need to run spm_train with --input_format=tsv flag.
