### ISSUE TITLE
java support

### ISSUE THREAD

**Issue by levyfan** [google/sentencepiece#326]
Hi, I would like to write and contribute a simple JNI wrapper. And I am asking if it is OK to create a PR and add my code here (maybe under a folder ./java)? Or I should separate and manage our own java codebase?

**Comment by taku910** [comment]
Thank you for the contribution and PR.

However, we would not like to include Java port in the main sentencepiece directory. To do so, we have 
to manage the CI (travis CI) and testing rule and keep the test/break green, which will take additional bandwidth. It would be great if you make a new repository.

**Comment by levyfan** [comment]
Thanks @taku910, I create a seperate repository here https://github.com/levyfan/sentencepiece-jni
