### ISSUE TITLE
Generate vocabulary with python wrapper

### ISSUE THREAD

**Issue by ArbinTimilsina** [google/sentencepiece#332]
Is there a way to generate vocabulary with python wrapper and use this vocabulary while encoding? Something similar to the code below but with python wrapper? 

Thanks!
```
% spm_train --input=train --model_prefix=spm --vocab_size=8000 --character_coverage=0.9995
% spm_encode --model=spm.model --generate_vocabulary < {train_file}.L1 > {vocab_file}.L1
% spm_encode --model=spm.model --generate_vocabulary < {train_file}.L2 > {vocab_file}.L2
```

```
% spm_encode --model=spm.model --vocabulary={vocab_file}.L1 --vocabulary_threshold=50 < {test_file}.L1 > {test_file}.seg.L1
% spm_encode --model=spm.model --vocabulary={vocab_file}.L2 --vocabulary_threshold=50 < {test_file}.L2 > {test_file}.seg.L2
```

**Comment by taku910** [comment]
See the "Vocabulary restriction" section of the following colab.

https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb

You can count the frequency of each vocab in source/target corpus and filter the vocab with python code.  Then, call set_vocabulary() method to restrict the vocab.
