### ISSUE TITLE
Mapping char index in original text to index in sentencepiece-bpe?

### ISSUE THREAD

**Issue by jordiae** [google/sentencepiece#334]
Hello there! Is there any built-in procedure for getting the original character index? Otherwise, do you have any indication on how to map the char index in the original text to the char index in the resulting sentencepiece-bpe?

For instance:
-Original text: 'Besides this, aagam worship, star worship, fasting, etc can be seen being performed both inside and outside homes.'
-Sentencepiece (BPE): '▁B es ides ▁this , ▁a ag am ▁w or sh ip , ▁st ar ▁w or sh ip , ▁f ast ing , ▁ et c ▁can ▁be ▁se en ▁being ▁per form ed ▁both ▁in side ▁and ▁out side ▁h om es .'

{0:  1, 1: 3,...} # 'B' is in position 0 in the original text and in position 1 in the resulting text etc

I think that it's not a trivial procedure, mainly because apart from breaking words into pieces, sentencepiece performs Unicode normalization. In particular, although being based in NFKC, I believe that the sentencepiece's normalization procedure is not exactly NFKC, or at least I'm not getting the same results when applying NKFC with Python's unicodedata library.

Anyway, any suggestions would be much appreciated. Thanks in advance.

**Comment by taku910** [comment]
Please see the last "Getting byte offsets of tokens" of the following colab.

https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb

SentencePiece implements custom NFKC normalizer in order to get the character alignment.

**Comment by jordiae** [comment]
@taku910 Thanks!

**Comment by dallal9** [comment]
I have a problem installing sentencepiece_pb2
The link https://raw.githubusercontent.com/google/sentencepiece/master/python/sentencepiece_pb2.py is not working.
