### ISSUE TITLE
Training is slow

### ISSUE THREAD

**Issue by eric-haibin-lin** [google/sentencepiece#336]
Training a unigram model on a large corpus is slow. I am using the pip package and the cpu is utilizing only 1 core most of the time. Is that expected?

**Comment by taku910** [comment]
Could you elaborate the environment?

- args passed to train method
- The number of lines for training
- What happens if you use C++ CLI command (spm_train)

In addition, you might want to explicitly set --num_threads=8 in training.

**Comment by eric-haibin-lin** [comment]
I'm using ` ....files....  --vocab_size=30000 --model_type=BPE --max_sentence_length=800000 --num_threads=64`. setting `num_threads` helps :)
