### ISSUE TITLE
Option to quite LOG(INFO) and LOG(WARNING) messages

### ISSUE THREAD

**Issue by ArbinTimilsina** [google/sentencepiece#338]
Is there an option to quiet all the LOG(INFO) and LOG(WARNING) messages (like the ones below) from SentencePiece? If not, will it be possible to add one? I think these messages are useful during the initial testing phase, but an option to quite them during the production run will be very helpful. 

```
trainer_interface.cc(139) LOG(INFO) Loaded 63000000 lines
```

```
trainer_interface.cc(287) LOG(WARNING) Found too long line (7629 > 4192).
```

```
unigram_model_trainer.cc(486) LOG(INFO) EM sub_iter=0 size=294631 obj=12.7985 num_tokens=1729751 num_tokens/piece=5.87091
```

**Comment by taku910** [comment]
Are you using CLI tool spm_train or python wrapper?

If using spm_trian, you can suppress the error message by redirecting them to /dev/null

```
% spm_train --input=... >/dev/null 2>&1
```

Python wrapper has no option to suppress the error message at this moment.

**Comment by ArbinTimilsina** [comment]
I am using the python wrapper. Btw, is there a plan to add this feature in the near future?

**Comment by taku910** [comment]
We are working on big code refactoring internally and will replace logging library with glog. glog will provide features to suppress the logging info.

Not sure when we can finish the refactoring. will keep you posted.

**Comment by ArbinTimilsina** [comment]
Ok, thanks for letting us know.

**Comment by ArbinTimilsina** [comment]
@taku910, is there any update regarding this?

**Comment by tzhma** [comment]
I also faced the same issue, would love to have this feature implemented.
