### ISSUE TITLE
What's the difference between wordpiece and sentencepiece?

### ISSUE THREAD

**Issue by iamxiaoyubei** [google/sentencepiece#339]
I have seen many blogs online about wordpiece. Such as:
- https://www.cnblogs.com/huangyc/p/10223075.html
- https://xinghanzzy.github.io/2019/03/08/Subword%20BPE%20%E7%90%86%E8%A7%A3&sentence%20piece/#Word-piece
- https://arxiv.org/pdf/1609.08144.pdf
...

I found that the wordpiece training and the sentencepiece training in the blog are almost the same. So, Can I think of a sentencepiece as a wordpiece? If not, what is the difference between the two?

Thank you !!

**Comment by ArbinTimilsina** [comment]
My understanding is that WordPiece is the closed source version (Google internal) used for training BERT. You can find the exact comparison between SentencePiece, WordPiece, and subword-nmt in the **Comparisons with other implementations** section of https://github.com/google/sentencepiece.

**Comment by iamxiaoyubei** [comment]
Thank you. I have seen it  in the #Comparisons with other implementations# section of https://github.com/google/sentencepiece. However, I want to train a wordpiece vocabulary with my own copus, so I wanna know whether the sentencepiec can replace it.

**Comment by taku910** [comment]
my EMNLP paper may also help
https://www.aclweb.org/anthology/D18-2012

**Comment by iamxiaoyubei** [comment]
Thank you~ I will have a try.
