### ISSUE TITLE
Ram needed for training unigram model? 

### ISSUE THREAD

**Issue by alejandrojcastaneira** [google/sentencepiece#341]
How much RAM is needed to run a Unigram model on English Wikipedia. Actually is around 6000000 sentences if I retain each article as a single sentence. I'm training with 24gb of Ram, I'm getting:

> trainer_interface.cc(435) LOG(INFO) Done! preprocessed 6095749 sentences.
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc

This is the training command  from Python inteface:

`spm.SentencePieceTrainer.Train('--input=/wikipedia_corpus_english.txt --model_prefix=/en_wiki --vocab_size=500000 --max_sentence_length=500000 --num_threads=20')`

Maybe I'm not doing the right configuration?
Best Regards

**Comment by benywon** [comment]
The same error occurs for me

**Comment by taku910** [comment]
Try --input_sentence_size=1000000 (or smaller) which allows to sample sentences before training. 
Generally speaking, 1M-10M sentences are enough for training reasonably good model.
