### ISSUE TITLE
Bazel error: name 'py_proto_library' is not defined (did you mean 'cc_proto_library'?)

### ISSUE THREAD

**Issue by lioutasb** [google/sentencepiece#342]
I'm trying to build from source using Bazel following the README instructions and I'm getting the following error:

> lioutasb@lioutasb-pc:~/sentencepiece$ bazel build src:all
> Starting local Bazel server and connecting to it...
> ERROR: /home/lioutasb/sentencepiece/src/BUILD:33:1: name 'py_proto_library' is not defined (did you mean 'cc_proto_library'?)
> ERROR: error loading package 'src': Package 'src' contains errors
> INFO: Elapsed time: 1.585s
> INFO: 0 processes.
> FAILED: Build did NOT complete successfully (1 packages loaded)

**Comment by chitwansaharia** [comment]
I am also getting the exact same error. Were you able to resolve it somehow ?

**Comment by wildgeece96** [comment]
I added  `load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")` to the top of BUILD file.
But, a different error has occurred.

```
➜  sentencepiece bazel build src:all
ERROR: /home/jupyter/jupyter-working/src/sentencepiece/src/BUILD:34:1: //src:sentencepiece_py_pb2: no such attribute 'api_version' in 'py_library' rule
ERROR: error loading package 'src': Package 'src' contains errors
INFO: Elapsed time: 0.043s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
```
I want to know the solution, too.

**Comment by lioutasb** [comment]
I managed to build from source by doing the following changes:

Add the following at the end of `WORKSPACE` file
```
http_archive(
    name = "six_archive",
    build_file = "@com_google_protobuf//:six.BUILD",
    sha256 = "105f8d68616f8248e24bf0e9372ef04d3cc10104f1980f54d57b2ce73a5ad56a",
    urls = ["https://pypi.python.org/packages/source/s/six/six-1.10.0.tar.gz"],
)

bind(
    name = "six",
    actual = "@six_archive//:six",
)
```

Add the following at the beginning of `src/BUILD` file:

`load("@com_google_protobuf//:protobuf.bzl", "py_proto_library")`

and replace `py_proto_library` on the same file with this:
```
py_proto_library(
    name = "sentencepiece_py_pb2",
    srcs = ["sentencepiece.proto"],
    visibility = ["//visibility:public"],
)
```

This update though introduced other problems also with the actual implementation. The compiled executable doesn't read the input file parameter that I'm giving to it with the following error:

> billiout@billiout-nitro:~/sentencepiece/sentencepiece/bazel-bin$ ./src/spm_train --input=data/botchan.txt --model_prefix=m --vocab_size=1000
> WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0606 22:59:28.134057 21858 sentencepiece_trainer.cc:52] Starts training with : 
> TrainerSpec {
>   input_format: 
>   model_prefix: m
>   kModelType_Map: UNIGRAM
>   vocab_size: 1000
>   self_test_sample_size: 0
>   character_coverage: 0.9995
>   input_sentence_size: 0
>   shuffle_input_sentence: 1
>   seed_sentencepiece_size: 1000000
>   shrinking_factor: 0.75
>   max_sentence_length: 4192
>   num_threads: 16
>   num_sub_iterations: 2
>   max_sentencepiece_length: 16
>   split_by_unicode_script: 1
>   split_by_number: 1
>   split_by_whitespace: 1
>   treat_whitespace_as_suffix: 0
>   vocabulary_output_piece_score: 1
>   hard_vocab_limit: 1
>   use_all_vocab: 0
>   unk_id: 0
>   bos_id: 1
>   eos_id: 2
>   pad_id: -1
>   unk_piece: <unk>
>   bos_piece: <s>
>   eos_piece: </s>
>   pad_piece: <pad>
>   unk_surface:  ⁇ 
> }
> NormalizerSpec {
>   name: nmt_nfkc
>   add_dummy_prefix: 1
>   remove_extra_whitespaces: 1
>   escape_whitespaces: 1
>   normalization_rule_tsv: 
> }
> F0606 22:59:28.134301 21858 spm_train_main.cc:183] Check failed: _status.ok() Internal: src/trainer_interface.cc(54) [(trainer_spec.input().size()) > (0)] 
> *** Check failure stack trace: ***
> Aborted (core dumped)

**Comment by fozziethebeat** [comment]
Yes, this is temporarily disabled.  We're working on unifying the open source codebase and the Google internal codebase to simplify maintenance.  For a short period of time, a few features will be missing and/or broken.

I'll have a long term fix for this shortly

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
