### ISSUE TITLE
Tensorflow Support

### ISSUE THREAD

**Issue by danilotorrisi** [google/sentencepiece#344]
From the README:

> We will be no longer supported direct integration with Tensorflow. Tensorflow users are suggested to adopt the new Tokzenization ops published as part of TF.Text. Those ops will soon support running pre-trained SentencePiece models.

From what I understand, the tf_sentencepiece module is deprecated, and we should use the [tf.text](https://www.tensorflow.org/beta/tutorials/load_data/text) tokenization ops to integrate SentencePiece models with TF. 

Where can I start? Is there a reference where can I find how to integrate SentencePiece with TF?

**Comment by fozziethebeat** [comment]
This support isn't 100% ready yet.  The rough plan is to:
  - Restore and refine our python bindings
  - Make tf.text depend upon sentencepiece as a Bazel dependency
  - Add a new tokenizer op that wraps the SentencepieceProcessor

You'll still need to pre-train a model separately outside of TF.Text but applying the op will work similarly to their new wordpiece based tokenization, simply with a SPM model instead.

**Comment by taku910** [comment]
tf.text now support sentencepiece.

https://github.com/google/sentencepiece/tree/master/tensorflow
