### ISSUE TITLE
Possible to have arm support for Android?

### ISSUE THREAD

**Issue by gitathrun** [google/sentencepiece#346]
Hello, Is it possible to have armeabi or other arm version library other than x86? This could help developers to work on Android application using SentencePiece ?

**Comment by taku910** [comment]
I think the current C++ library can be built on arm. I could compile C++ library on raspberry pi actually.

However, in order to support arm, we would like to have an automated CI environment (e.g. travis CI). 
Of course travis doesn't support native arm build, so we have to set up some cross-build environment.
Do you know how to build arm binary on a vanilla x86 ubuntu?

**Comment by gitathrun** [comment]
@taku910 I figured out how to cross-compile the arm version C++ library, it is done in a docker container with Android SDK + NDK. The library actually works in my case on an Android platform.

**Comment by gitathrun** [comment]
According to [developer levyfan's advice](https://github.com/levyfan/sentencepiece-jni/issues/3), It is now possible for Android app to load the model file from Assets directory and inference. 
The essential for the solution is to:
1.  load the pre-trained model file and convert the content as byte array.
2.  pass this byte[] object to JNI method that invoke the function:  ```sentencepieceprocessor.loadFromSerializedProto(byte[] content)```

Using MappedByteBuffer is recommended.

**Comment by aldermann** [comment]
Hello, I am also working on this problem but I can't build the library. Can you guys show me the config of your project.

**Comment by windmaple** [comment]
@gitathrun can you share the docker img so that we don't have to reinvent the wheel?

**Comment by gitathrun** [comment]
Hi, @aldermann @windmaple Sorry for the late reply, the docker image I used is [here](https://hub.docker.com/r/tftwdockerhub/android_jni_lib_build). 

There are some tricks in setting path for CMake between sentencepiece and its dependencies as I remember, and it currently only support loading .model file process, it works with ALbert's tokenisation model as well. 

I will review my process and create a repo for the process asap, if it is done, I shall let you know.

**Comment by windmaple** [comment]
@gitathrun much appreciated!

**Comment by jipson7** [comment]
> Hi, @aldermann @windmaple Sorry for the late reply, the docker image I used is [here](https://hub.docker.com/r/tftwdockerhub/android_jni_lib_build).
> 
> There are some tricks in setting path for CMake between sentencepiece and its dependencies as I remember, and it currently only support loading .model file process, it works with ALbert's tokenisation model as well.
> 
> I will review my process and create a repo for the process asap, if it is done, I shall let you know.

@gitathrun much appreciated. I was trying to get alberts tokenization to work to [support this model on android](https://tfhub.dev/tensorflow/albert_lite_base/1). Did you every write about the process you used?

**Comment by gitathrun** [comment]
> > Hi, @aldermann @windmaple Sorry for the late reply, the docker image I used is [here](https://hub.docker.com/r/tftwdockerhub/android_jni_lib_build).
> > There are some tricks in setting path for CMake between sentencepiece and its dependencies as I remember, and it currently only support loading .model file process, it works with ALbert's tokenisation model as well.
> > I will review my process and create a repo for the process asap, if it is done, I shall let you know.
> 
> @gitathrun much appreciated. I was trying to get alberts tokenization to work to [support this model on android](https://tfhub.dev/tensorflow/albert_lite_base/1). Did you every write about the process you used?

Positive, I am trying to get solution ready as I am trying to embed this solution with React Native as a RN library. Sorry for the slow progress since this is not my first priority in my task list. 

Good news is, I have already done the joint usage of this JNI library with albert.tflite runing on Android platform, it definitly work. But albert is really slow on Android, for my old spec testing phone (2016 version mid class phone), it took ~5s for the model inference.

Here is the basic step:
1. create the .java file and add contention of SentencePiece JNI as I mentioned in [developer levyfan's advice](https://github.com/levyfan/sentencepiece-jni/issues/3)
2. use ___javah__ cmd to create the jni for cpp header file (.h)
3. create a .cpp file along with .h file
4. create a CMakeLists.txt with following content
```
cmake_minimum_required(VERSION 3.1)
project(sentencepiece-jni)


set(CMAKE_CXX_STANDARD 11)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)


message(STATUS "CMAKE setting is done")

set(SPP_BASE_STATIC_LIBRARIES /app/demo_jni/jni/libsentencepiece.a)
message(STATUS "spp base library path is set: " ${SPP_BASE_STATIC_LIBRARIES})


set(SPP_BASE_INCLUDE_DIRS ${PORJECT_SOURCE_DIR})
message(STATUS "spp base header include path is set: " ${SPP_BASE_INCLUDE_DIRS})


# create the main library TARGET
add_library(sentencepiece_jni SHARED com_teleware_sentencepiece_SentencePieceJNI.cpp)
message(STATUS "JNI library TARGET is added with add_library")

# link the header file to target
target_include_directories(sentencepiece_jni PUBLIC ${SPP_BASE_INCLUDE_DIRS})

message(STATUS "header files are add with target_include_directories")

# link the base library with the JNI library
target_link_libraries(sentencepiece_jni ${SPP_BASE_STATIC_LIBRARIES})
message(STATUS "final link jni with base static library")
```
5. Then compile and build the dynamic library for Android usage, use the same cmdline in building .a static library file
```
(base) root@f9027db54d2a:/app/demo_jni/jni# rm -rf ./build && mkdir build && cd build
(base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake \
> -G Ninja \
> -DANDROID_ABI=armeabi-v7a \
> -DANDROID_NDK=/opt/android-sdk-linux/ndk-bundle \
> -DCMAKE_BUILD_TYPE=Debug \
> -DCMAKE_MAKE_PROGRAM=/opt/android-sdk-linux/cmake/3.10.2.4988404/bin/ninja \
> -DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk-bundle/build/cmake/android.toolchain.cmake \
> -DANDROID_NATIVE_API_LEVEL=21 \
> -DANDROID_TOOLCHAIN=clang \
> -DANDROID_LINKER_FLAGS="-landroid -llog" ..
-- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CMAKE setting is done
-- spp base library path is set: /app/demo_jni/jni/libsentencepiece.a
-- spp base header include path is set:
-- JNI library TARGET is added with add_library
-- header files are add with target_include_directories
-- final link jni with base static library
-- Configuring done
-- Generating done
-- Build files have been written to: /app/demo_jni/jni/build
(base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake --build .
[2/2] Linking CXX shared library libsentencepiece_jni.so
```
6. Verify it is for ARM, use __file__ linux cmd, must be __ ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked __
```
(base) root@f9027db54d2a:/app/demo_jni/jni/build# file libsentencepiece_jni.so
libsentencepiece_jni.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=cf767a7645283d97b743bec779d14e87e217ac7b, not stripped
```
7. You shall see the built .so file and copy/paste it out of docker.
![image](https://user-images.githubusercontent.com/22137687/86414207-3312d580-bcbb-11ea-815a-73cd63f12579.png)

I think this is the rough sequences, the rest of the work is to get JNI work on Android.
1. For the SentencePiece .model file, you can consider the token.model as the tflite file, and copy/paste it into src/main/assets directory.
2. Add noCompress with ".model"
3. Load the sp model into memory and use sp.loadmodel() to get the sp object ready for tokenization.
```
    /** Memory-map the model file in Assets. */
    private MappedByteBuffer loadModelFile(Activity activity) throws IOException {
        AssetFileDescriptor fileDescriptor = activity.getAssets().openFd("albertToken.model");
        FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
        FileChannel fileChannel = inputStream.getChannel();
        long startOffset = fileDescriptor.getStartOffset();
        long declaredLength = fileDescriptor.getDeclaredLength();
        return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
    }
```

4. use the __encoder__ function of SentencePiece for string tokenization.

Hopefully this helps, I will add more details later on.

**Comment by gitathrun** [comment]
@jipson7 The following content is slightly off-topic, but I think it worth mention.
I would recommend use transformers library's [TFAlbertModel class](https://huggingface.co/transformers/v2.2.0/model_doc/albert.html#tfalbertmodel) for tflite model conversion rather than tensorflow hub, since the tf version in tf hub is really chaos, unless you are very familiar with SavedModel format and hub module, otherwise it causes many unexpected errors, such as:
1. unsuported hub model to tflite conversion, with assets (usually the tokenizer .model file, such as albert) warpped in hub model.
2. hub module name is not in a correct format, according to tf version change.
...etc...long story...
Hopefully this could help you save sometime.

**Comment by imranrana07** [comment]
@gitathrun I am trying to integrate sentencepiece to my android project. tried by pasting the source code of sentencepiece from github like cpp file/library but it is not working. I pasted all the code as it is, But it showing error **https://stackoverflow.com/questions/75916026/how-to-integrate-sentencepiece-protobuf-into-existing-android-project-correctly** .  Could you please help me to integrate sentencepiece in android please

**Comment by siy415** [comment]
> > > Hi, @AlderMann @windmaple Sorry for the late reply, the docker image I used is [here](https://hub.docker.com/r/tftwdockerhub/android_jni_lib_build).
> > > There are some tricks in setting path for CMake between sentencepiece and its dependencies as I remember, and it currently only support loading .model file process, it works with ALbert's tokenisation model as well.
> > > I will review my process and create a repo for the process asap, if it is done, I shall let you know.
> > 
> > 
> > @gitathrun much appreciated. I was trying to get alberts tokenization to work to [support this model on android](https://tfhub.dev/tensorflow/albert_lite_base/1). Did you every write about the process you used?
> 
> @AlderMann @windmaple @jipson7 Positive, I am trying to get solution ready as I am trying to embed this solution with React Native as a RN library. Sorry for the slow progress since this is not my first priority in my task list.
> 
> Good news is, I have already done the joint usage of this JNI library with albert.tflite runing on Android platform, it definitly work. But albert is really slow on Android, for my old spec testing phone (2016 version mid class phone), it took ~5s for the model inference.
> 
> Here is the basic step:
> 
> 1. create the .java file and add contention of SentencePiece JNI as I mentioned in [developer levyfan's advice](https://github.com/levyfan/sentencepiece-jni/issues/3)
> 2. use _**javah** cmd to create the jni for cpp header file (.h)
> 3. create a .cpp file along with .h file
> 4. create a CMakeLists.txt with following content
> 
> ```
> cmake_minimum_required(VERSION 3.1)
> project(sentencepiece-jni)
> 
> 
> set(CMAKE_CXX_STANDARD 11)
> set(CMAKE_CXX_STANDARD_REQUIRED ON)
> set(CMAKE_POSITION_INDEPENDENT_CODE ON)
> 
> 
> message(STATUS "CMAKE setting is done")
> 
> set(SPP_BASE_STATIC_LIBRARIES /app/demo_jni/jni/libsentencepiece.a)
> message(STATUS "spp base library path is set: " ${SPP_BASE_STATIC_LIBRARIES})
> 
> 
> set(SPP_BASE_INCLUDE_DIRS ${PORJECT_SOURCE_DIR})
> message(STATUS "spp base header include path is set: " ${SPP_BASE_INCLUDE_DIRS})
> 
> 
> # create the main library TARGET
> add_library(sentencepiece_jni SHARED com_teleware_sentencepiece_SentencePieceJNI.cpp)
> message(STATUS "JNI library TARGET is added with add_library")
> 
> # link the header file to target
> target_include_directories(sentencepiece_jni PUBLIC ${SPP_BASE_INCLUDE_DIRS})
> 
> message(STATUS "header files are add with target_include_directories")
> 
> # link the base library with the JNI library
> target_link_libraries(sentencepiece_jni ${SPP_BASE_STATIC_LIBRARIES})
> message(STATUS "final link jni with base static library")
> ```
> 
> 5. Then compile and build the dynamic library for Android usage, use the same cmdline in building .a static library file
> 
> ```
> (base) root@f9027db54d2a:/app/demo_jni/jni# rm -rf ./build && mkdir build && cd build
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake \
> > -G Ninja \
> > -DANDROID_ABI=armeabi-v7a \
> > -DANDROID_NDK=/opt/android-sdk-linux/ndk-bundle \
> > -DCMAKE_BUILD_TYPE=Debug \
> > -DCMAKE_MAKE_PROGRAM=/opt/android-sdk-linux/cmake/3.10.2.4988404/bin/ninja \
> > -DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk-bundle/build/cmake/android.toolchain.cmake \
> > -DANDROID_NATIVE_API_LEVEL=21 \
> > -DANDROID_TOOLCHAIN=clang \
> > -DANDROID_LINKER_FLAGS="-landroid -llog" ..
> -- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
> -- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
> -- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMAKE setting is done
> -- spp base library path is set: /app/demo_jni/jni/libsentencepiece.a
> -- spp base header include path is set:
> -- JNI library TARGET is added with add_library
> -- header files are add with target_include_directories
> -- final link jni with base static library
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /app/demo_jni/jni/build
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake --build .
> [2/2] Linking CXX shared library libsentencepiece_jni.so
> ```
> 
> 6. Verify it is for ARM, use **file** linux cmd, must be __ ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked __
> 
> ```
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# file libsentencepiece_jni.so
> libsentencepiece_jni.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=cf767a7645283d97b743bec779d14e87e217ac7b, not stripped
> ```
> 
> 7. You shall see the built .so file and copy/paste it out of docker.
>    ![image](https://user-images.githubusercontent.com/22137687/86414207-3312d580-bcbb-11ea-815a-73cd63f12579.png)
> 
> I think this is the rough sequences, the rest of the work is to get JNI work on Android.
> 
> 1. For the SentencePiece .model file, you can consider the token.model as the tflite file, and copy/paste it into src/main/assets directory.
> 2. Add noCompress with ".model"
> 3. Load the sp model into memory and use sp.loadmodel() to get the sp object ready for tokenization.
> 
> ```
>     /** Memory-map the model file in Assets. */
>     private MappedByteBuffer loadModelFile(Activity activity) throws IOException {
>         AssetFileDescriptor fileDescriptor = activity.getAssets().openFd("albertToken.model");
>         FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
>         FileChannel fileChannel = inputStream.getChannel();
>         long startOffset = fileDescriptor.getStartOffset();
>         long declaredLength = fileDescriptor.getDeclaredLength();
>         return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
>     }
> ```
> 
> 4. use the **encoder** function of SentencePiece for string tokenization.
> 
> Hopefully this helps, I will add more details later on.

I just build following yours, but I have error bellow.

/home-mc/inyong.shim/Android/Sdk/cmake/3.22.1/bin/cmake --build .
[1/1] Linking CXX shared library libsentencepiece_jni.so
FAILED: libsentencepiece_jni.so 
: && /home-mc/inyong.shim/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi21 --sysroot=/home-mc/inyong.shim/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-security   -fno-limit-debug-info  -landroid -llog -static-libstdc++ -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--no-undefined-version -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -shared -Wl,-soname,libsentencepiece_jni.so -o libsentencepiece_jni.so CMakeFiles/sentencepiece_jni.dir/com_example_myapplication_jni_SentencePieceJNI.cc.o  -Wl,-Bstatic  -lsentencepiece  -Wl,-Bdynamic  -latomic -lm && :
ld.lld: error: unable to find library -lsentencepiece
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


What's the cause of this issue?

**Comment by hui-li-xf** [comment]
> > > Hi, @AlderMann @windmaple Sorry for the late reply, the docker image I used is [here](https://hub.docker.com/r/tftwdockerhub/android_jni_lib_build).
> > > There are some tricks in setting path for CMake between sentencepiece and its dependencies as I remember, and it currently only support loading .model file process, it works with ALbert's tokenisation model as well.
> > > I will review my process and create a repo for the process asap, if it is done, I shall let you know.
> > 
> > 
> > @gitathrun much appreciated. I was trying to get alberts tokenization to work to [support this model on android](https://tfhub.dev/tensorflow/albert_lite_base/1). Did you every write about the process you used?
> 
> @AlderMann @windmaple @jipson7 Positive, I am trying to get solution ready as I am trying to embed this solution with React Native as a RN library. Sorry for the slow progress since this is not my first priority in my task list.
> 
> Good news is, I have already done the joint usage of this JNI library with albert.tflite runing on Android platform, it definitly work. But albert is really slow on Android, for my old spec testing phone (2016 version mid class phone), it took ~5s for the model inference.
> 
> Here is the basic step:
> 
> 1. create the .java file and add contention of SentencePiece JNI as I mentioned in [developer levyfan's advice](https://github.com/levyfan/sentencepiece-jni/issues/3)
> 2. use _**javah** cmd to create the jni for cpp header file (.h)
> 3. create a .cpp file along with .h file
> 4. create a CMakeLists.txt with following content
> 
> ```
> cmake_minimum_required(VERSION 3.1)
> project(sentencepiece-jni)
> 
> 
> set(CMAKE_CXX_STANDARD 11)
> set(CMAKE_CXX_STANDARD_REQUIRED ON)
> set(CMAKE_POSITION_INDEPENDENT_CODE ON)
> 
> 
> message(STATUS "CMAKE setting is done")
> 
> set(SPP_BASE_STATIC_LIBRARIES /app/demo_jni/jni/libsentencepiece.a)
> message(STATUS "spp base library path is set: " ${SPP_BASE_STATIC_LIBRARIES})
> 
> 
> set(SPP_BASE_INCLUDE_DIRS ${PORJECT_SOURCE_DIR})
> message(STATUS "spp base header include path is set: " ${SPP_BASE_INCLUDE_DIRS})
> 
> 
> # create the main library TARGET
> add_library(sentencepiece_jni SHARED com_teleware_sentencepiece_SentencePieceJNI.cpp)
> message(STATUS "JNI library TARGET is added with add_library")
> 
> # link the header file to target
> target_include_directories(sentencepiece_jni PUBLIC ${SPP_BASE_INCLUDE_DIRS})
> 
> message(STATUS "header files are add with target_include_directories")
> 
> # link the base library with the JNI library
> target_link_libraries(sentencepiece_jni ${SPP_BASE_STATIC_LIBRARIES})
> message(STATUS "final link jni with base static library")
> ```
> 
> 5. Then compile and build the dynamic library for Android usage, use the same cmdline in building .a static library file
> 
> ```
> (base) root@f9027db54d2a:/app/demo_jni/jni# rm -rf ./build && mkdir build && cd build
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake \
> > -G Ninja \
> > -DANDROID_ABI=armeabi-v7a \
> > -DANDROID_NDK=/opt/android-sdk-linux/ndk-bundle \
> > -DCMAKE_BUILD_TYPE=Debug \
> > -DCMAKE_MAKE_PROGRAM=/opt/android-sdk-linux/cmake/3.10.2.4988404/bin/ninja \
> > -DCMAKE_TOOLCHAIN_FILE=/opt/android-sdk-linux/ndk-bundle/build/cmake/android.toolchain.cmake \
> > -DANDROID_NATIVE_API_LEVEL=21 \
> > -DANDROID_TOOLCHAIN=clang \
> > -DANDROID_LINKER_FLAGS="-landroid -llog" ..
> -- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
> -- Check for working C compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
> -- Check for working CXX compiler: /opt/android-sdk-linux/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- CMAKE setting is done
> -- spp base library path is set: /app/demo_jni/jni/libsentencepiece.a
> -- spp base header include path is set:
> -- JNI library TARGET is added with add_library
> -- header files are add with target_include_directories
> -- final link jni with base static library
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /app/demo_jni/jni/build
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# /opt/android-sdk-linux/cmake/3.10.2.4988404/bin/cmake --build .
> [2/2] Linking CXX shared library libsentencepiece_jni.so
> ```
> 
> 6. Verify it is for ARM, use **file** linux cmd, must be __ ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked __
> 
> ```
> (base) root@f9027db54d2a:/app/demo_jni/jni/build# file libsentencepiece_jni.so
> libsentencepiece_jni.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, BuildID[sha1]=cf767a7645283d97b743bec779d14e87e217ac7b, not stripped
> ```
> 
> 7. You shall see the built .so file and copy/paste it out of docker.
>    ![image](https://user-images.githubusercontent.com/22137687/86414207-3312d580-bcbb-11ea-815a-73cd63f12579.png)
> 
> I think this is the rough sequences, the rest of the work is to get JNI work on Android.
> 
> 1. For the SentencePiece .model file, you can consider the token.model as the tflite file, and copy/paste it into src/main/assets directory.
> 2. Add noCompress with ".model"
> 3. Load the sp model into memory and use sp.loadmodel() to get the sp object ready for tokenization.
> 
> ```
>     /** Memory-map the model file in Assets. */
>     private MappedByteBuffer loadModelFile(Activity activity) throws IOException {
>         AssetFileDescriptor fileDescriptor = activity.getAssets().openFd("albertToken.model");
>         FileInputStream inputStream = new FileInputStream(fileDescriptor.getFileDescriptor());
>         FileChannel fileChannel = inputStream.getChannel();
>         long startOffset = fileDescriptor.getStartOffset();
>         long declaredLength = fileDescriptor.getDeclaredLength();
>         return fileChannel.map(FileChannel.MapMode.READ_ONLY, startOffset, declaredLength);
>     }
> ```
> 
> 4. use the **encoder** function of SentencePiece for string tokenization.
> 
> Hopefully this helps, I will add more details later on.

How did the libsentencepiece.a file come from?

**Comment by AiTester950** [comment]
I am getting this error:
saidmasoom@saidmasoom:~/sentencepiece/build$ cmake   -G Ninja   -DANDROID_ABI=armeabi-v7a   -DANDROID_NDK=/home/saidmasoom/Android/Sdk/ndk/27.0.12077973   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_TOOLCHAIN_FILE=/home/saidmasoom/Android/Sdk/ndk/27.0.12077973/build/cmake/android.toolchain.cmake   -DANDROID_NATIVE_API_LEVEL=21   -DANDROID_TOOLCHAIN=clang   -DANDROID_LINKER_FLAGS="-landroid -llog" ..
-- VERSION: 0.2.1
-- Not Found TCMalloc: TCMALLOC_LIB-NOTFOUND
-- CMAKE setting is done
-- spp base library path is set: /app/demo_jni/jni/libsentencepiece.a
-- spp base header include path is set: 
-- JNI library TARGET is added with add_library
-- header files are add with target_include_directories
-- final link jni with base static library
-- Configuring done
CMake Error at CMakeLists.txt:217 (add_library):
  Cannot find source file:

    com_teleware_sentencepiece_SentencePieceJNI.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .mpp .m .M .mm .ixx .cppm .h
  .hh .h++ .hm .hpp .hxx .in .txx .f .F .for .f77 .f90 .f95 .f03 .hip .ispc


CMake Error at CMakeLists.txt:217 (add_library):
  No SOURCES given to target: sentencepiece_jni


CMake Generate step failed.  Build files cannot be regenerated correctly.
saidmasoom@saidmasoom:~/sentencepiece/build$ 



It cannot find the com_teleware_sentencepiece_SentencePieceJNI.cpp
