### ISSUE TITLE
protobuf.bzl has errors

### ISSUE THREAD

**Issue by Kabur** [google/sentencepiece#347]
**Hey folks, The error is down below, but basically: protobuf.bzl has errors. I've read through the issues and see that it's getting replaced -> is there maybe a different commit that works? Or any way around it?** 

I need sentencepiece for [this Listen, Attend and Spell package](https://github.com/Alexander-H-Liu/Listen-Attend-and-Spell-Pytorch), but even when I use the tip in the error and install sentencepiece with `bazel build src:all --incompatible_disable_deprecated_attr_params=false`, the installation goes through, but running the LAS package it says "spm_train" not found therefore I assume sentencepiece was not correctly installed.

```
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: /home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):
	File "/home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/com_google_protobuf/protobuf.bzl", line 125
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
INFO: Call stack for the definition of repository 'com_google_googletest' which is a http_archive (rule definition at /home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /home/kabur/ds_dependencies/sentencepiece/WORKSPACE:63:1
INFO: Call stack for the definition of repository 'com_google_glog' which is a http_archive (rule definition at /home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /home/kabur/ds_dependencies/sentencepiece/WORKSPACE:70:1
INFO: Call stack for the definition of repository 'com_google_absl' which is a http_archive (rule definition at /home/kabur/.cache/bazel/_bazel_kabur/b660574f6e74aeace0c92912c71daa8c/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /home/kabur/ds_dependencies/sentencepiece/WORKSPACE:41:1
ERROR: /home/kabur/ds_dependencies/sentencepiece/src/BUILD:21:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
ERROR: Analysis of target '//src:sentencepiece_model_cc_proto' failed; build aborted: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 4.638s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (14 packages loaded, 30 targets configured)
    currently loading: @com_google_protobuf//
    Fetching @local_config_cc; fetching

```

**Comment by lioutasb** [comment]
Until the unification of the open source codebase and the Google internal codebase is completed (see #342), I use the version from this [commit](https://github.com/google/sentencepiece/tree/d4dd947fe71c4fa4ee24ad8297beee32887d8828).

**Comment by Kabur** [comment]
> Until the unification of the open source codebase and the Google internal codebase is completed (see #342), I use the version from this [commit](https://github.com/google/sentencepiece/tree/d4dd947fe71c4fa4ee24ad8297beee32887d8828) which uses cmake.

That worked! Thank you!

**Comment by loveJasmine** [comment]
ub16hp@UB16HP:~/sentencepiece$ git checkout d4dd947fe71c4fa4ee24ad8297beee32887d8828
Note: checking out 'd4dd947fe71c4fa4ee24ad8297beee32887d8828'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at d4dd947... Merge pull request #333 from guillaumekln/patch-1
ub16hp@UB16HP:~/sentencepiece$

ub16hp@UB16HP:~/sentencepiece$ bazel build src:all
ERROR: The 'build' command is only supported from within a workspace (below a directory having a WORKSPACE file).
See documentation at https://docs.bazel.build/versions/master/build-ref.html#workspace
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ub16hp@UB16HP:~/sentencepiece$
