### ISSUE TITLE
Python documentation?

### ISSUE THREAD

**Issue by shervin64** [google/sentencepiece#349]
It looks like the Python documentation was deleted? All the links are broken.

**Comment by windweller** [comment]
Yesterday I found a helpful issue where it pointed me to a commit that still has Python documentation and examples:

https://github.com/google/sentencepiece/tree/d4dd947fe71c4fa4ee24ad8297beee32887d8828

Also note that the current master branch bazel build is broken...this older commit uses cmake which works like a charm!

**Comment by shervin64** [comment]
Thanks, this is very helpful!

Hopefully someone will address this in the master branch as well.

**Comment by taku910** [comment]
We've decided to rollback the recent bazel stuff and moved it to new bazel branch.
We will start the migration once bazel branch gets stable.

We will keep this issue opened just for the reference of bazel branch. Thank you.

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
