### ISSUE TITLE
Support for tf_sentencepiece under Windows

### ISSUE THREAD

**Issue by MajorMajorMajorMajor** [google/sentencepiece#350]
I noticed that tf_sentencepiece is not supported under Windows.

According to issue #337, this is intentional.

May I ask why this decision was made and if there is anything that would reverse it?

There are a number of modules on tf-hub that rely on this. (e.g. https://tfhub.dev/google/universal-sentence-encoder-xling/en-fr/1)

**Comment by taku910** [comment]
Simply building Windows library requires special environment, knowledge and maybe workaround. I'm not familiar with them.
I appreciate your contribution.

**Comment by aloosley** [comment]
I wouldn't know where to start to contribute such support, but would also love to see tf_sentencepeice work on Windows.  Best.
