### ISSUE TITLE
IsValidSentencePiece() will filter substring which end with ▁, by design?

### ISSUE THREAD

**Issue by zxysnow** [google/sentencepiece#351]
Such as input:

> This is a
> This is b
> 

Suffix tree will generate "is▁a....", "is▁b...."
The LCP is "is▁", but in IsValidSentencePiece(), it will filter out the LCP which end with "▁", then "is▁" won't be in seed_sentencepieces, is this correct?

The comments in trainer_interface.cc is here, why not allow whitespaces in the end of strings?

>       // Only allows whitespace to appear as a prefix of piece.
>       // When split_by_whitespace is false, we allow whitespaces to
>       // appear in the middle, "foo_bar", but do not allow them
>       // to appear as suffix, "foo_bar_".
>       // Regardless of the setting of split_by_whitespace,
>       // whitespace is treated as a prefix/infix of symbol or
>       // independent symbol.

**Comment by taku910** [comment]
This constraints comes from the original wordpiece model.

It is my guess but we can explicitly identify the stem of words by adding _ as a prefix.  Generally speaking, the stem of words (the most important part of the word) will appear as prefix, not a suffix.

--treat_whitespace_as_suffix=true lets you extract _ as suffix, but prefix and suffix are exclusive.
