### ISSUE TITLE
spm_train: command not found

### ISSUE THREAD

**Issue by loveJasmine** [google/sentencepiece#352]
DEFINE_CHECK_OP_IMPL(Check_EQ, ==)  // Compilation error with CHECK_EQ(NULL, x)?
 ^
INFO: From Compiling src/unigram_model_test.cc:
src/unigram_model_test.cc: In member function 'virtual void sentencepiece::unigram::LatticeTest_SampleTest_Test::TestBody()':
src/unigram_model_test.cc:287:21: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
   for (int i = 0; i < kTheta.size(); ++i) {
                     ^
INFO: Elapsed time: 593.941s, Critical Path: 26.17s
INFO: 451 processes: 451 local.
INFO: Build completed successfully, 604 total actions

ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$ 
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$ 
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$ 5e04e79203b7/ub16_prj/sentencepiece$ 
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$ spm_train   --input=/home/ub16c9/data/all_file_merge.copyblock_notitle_linesplit.txt   --model_prefix=all_file_merge   --vocab_size=80000   --character_coverage=0.9995   --model_type=unigram
spm_train: command not found
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$

**Comment by fozziethebeat** [comment]
We need to fix the documentation.

The binary is now in 
  ./bazel-bin/src/spm_train

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
