### ISSUE TITLE
the python lib link is gone

### ISSUE THREAD

**Issue by loveJasmine** [google/sentencepiece#353]
https://github.com/google/sentencepiece/blob/master/python/README.md

**Comment by shervin64** [comment]
See #349

**Comment by taku910** [comment]
We've decided to rollback the recent bazel stuff and moved it to new bazel branch.
We will start the migration once bazel branch gets stable.

We will keep this issue opened just for the reference of bazel branch. Thank you.

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
