### ISSUE TITLE
bazel build src:all  issue

### ISSUE THREAD

**Issue by loveJasmine** [google/sentencepiece#354]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$ bazel build src:all 
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: /home/ub16c9/.cache/bazel/_bazel_ub16c9/56179d28f15b0b4d0376173f0f560167/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):
	File "/home/ub16c9/.cache/bazel/_bazel_ub16c9/56179d28f15b0b4d0376173f0f560167/external/com_google_protobuf/protobuf.bzl", line 125
		rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
	File "/home/ub16c9/.cache/bazel/_bazel_ub16c9/56179d28f15b0b4d0376173f0f560167/external/com_google_protobuf/protobuf.bzl", line 130, in rule
		attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: /media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece/src/BUILD:21:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
ERROR: Analysis of target '//src:sentencepiece_model_cc_proto' failed; build aborted: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 0.737s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (3 packages loaded, 20 targets configured)
    currently loading: @com_google_protobuf// ... (3 packages)
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/sentencepiece$

**Comment by romanegloo** [comment]
having the same issue

**Comment by tilneyyang** [comment]
As the error message implied, have you tried  `bazel build src:all --incompatible_disable_deprecated_attr_params=false`?

**Comment by loveJasmine** [comment]
yes, I had tried. but got the same error

**Comment by 3NFBAGDU** [comment]
//src:bpe_model_trainer_test                                             FAILED in 0.5s                                                                                                                              /home/ubuntu/.cache/bazel/_bazel_ubuntu/dc578eeb0aa2fd7a8f1006d532e9eddc/execroot/com_google_sentencepiece/bazel-out/k8-fastbuild/testlogs/src/bpe_model_trainer_test/test.log                                   //src:builder_test                                                       FAILED in 0.2s                                                                                                                              /home/ubuntu/.cache/bazel/_bazel_ubuntu/dc578eeb0aa2fd7a8f1006d532e9eddc/execroot/com_google_sentencepiece/bazel-out/k8-fastbuild/testlogs/src/builder_test/test.log                                             //src:unigram_model_trainer_test                                         FAILED in 0.1s                                                                                                                              /home/ubuntu/.cache/bazel/_bazel_ubuntu/dc578eeb0aa2fd7a8f1006d532e9eddc/execroot/com_google_sentencepiece/bazel-out/k8-fastbuild/testlogs/src/unigram_model_trainer_test/test.log

have this error on bazel test src:all. 
 an also spm_train not recognized.

**Comment by loveJasmine** [comment]
'spm_train not recognized 'means the installation is failed

**Comment by romanegloo** [comment]
I have the same issue with an explicit error message:

> error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors

which I do not know what to do about it.

**Comment by 3NFBAGDU** [comment]
> 'spm_train not recognized 'means the installation is failed

and what can i do to solve this ?

**Comment by stefan-it** [comment]
I hope the maintainer team can explain, why `bazel` is now the default here.

Meanwhile: I could get the build working using the following `bazel` installation:

```bash
wget "https://github.com/bazelbuild/bazel/releases/download/0.27.0/bazel-0.27.0-installer-linux-x86_64.sh"
```

Configure this `bazel` tool:

```bash
chmod +x bazel-0.27.0-installer-linux-x86_64.sh
./bazel-0.27.0-installer-linux-x86_64.sh --user
export PATH="$PATH:$HOME/bin"
```

To build the project successfully I used the following command:

```bash
bazel build src:all --incompatible_disable_deprecated_attr_params=false
```

I tested it with commit 302b95edbabac2edb6a7db6a9cec82b45eafa36c

**Comment by stefan-it** [comment]
And if you're looking for the `spm_train` command (that is btw. referenced in the  XLNet repo): it now located under: `./bazel-bin/src/spm_train`

**Comment by taku910** [comment]
We've decided to rollback the recent bazel stuff and moved it to new bazel branch.
We will start the migration once bazel branch gets stable.

We will keep this issue opened just for the reference of bazel branch. Thank you.

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
