### ISSUE TITLE
after build the project, run spm_train which doesn't find the input

### ISSUE THREAD

**Issue by liuhd1992** [google/sentencepiece#356]
When I build the sentencepiece, and run the spm_train, which doesn't read the input file name
I add the code in src/spm_train_main.cc 
SetRepeatedTrainerSpecFromFlag(input);

It works for me.

**Comment by akalino** [comment]
I am having the same issue. I added this to the code, do I need to rebuild after adding?

**Comment by taku910** [comment]
Fixed. Could you try the latest release?
