### ISSUE TITLE
Installation Error 

### ISSUE THREAD

**Issue by zendevil** [google/sentencepiece#357]
WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".
ERROR: /home/psharma/.cache/bazel/_bazel_psharma/b6210b3a525a884b8c1c78dcf0fc64a7/external/com_google_protobuf/protobuf.bzl:130:19: Traceback (most recent call last):
        File "/home/psharma/.cache/bazel/_bazel_psharma/b6210b3a525a884b8c1c78dcf0fc64a7/external/com_google_protobuf/protobuf.bzl", line 125
                rule(attrs = {"srcs": attr.label_list...()}, <2 more arguments>)
        File "/home/psharma/.cache/bazel/_bazel_psharma/b6210b3a525a884b8c1c78dcf0fc64a7/external/com_google_protobuf/protobuf.bzl", line 130, in rule
                attr.label(cfg = "host", executable = True, sin..., ...)
'single_file' is no longer supported. use allow_single_file instead. You can use --incompatible_disable_deprecated_attr_params=false to temporarily disable this check.
ERROR: /home/psharma/sentencepiece/src/BUILD:21:1: every rule of type proto_library implicitly depends upon the target '@com_google_protobuf//:protoc', but this target could not be found because of: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
ERROR: Analysis of target '//src:sentencepiece_model_cc_proto' failed; build aborted: error loading package '@com_google_protobuf//': Extension file 'protobuf.bzl' has errors
INFO: Elapsed time: 0.953s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (4 packages loaded, 20 targets configur\
ed)
    currently loading: @com_google_protobuf// ... (2 packages)

**Comment by stefan-it** [comment]
@zendevil Just use the following line to compile it:

```bash
bazel build src:all --incompatible_disable_deprecated_attr_params=false
```

**Comment by taku910** [comment]
Let me close this bug as we now use CMake.
