### ISSUE TITLE
can't install spm_train

### ISSUE THREAD

**Issue by 3NFBAGDU** [google/sentencepiece#358]
I cloned this repository in my ubuntu server Ubuntu 16.04.6 LTS. I have installed bazel. When I  run bazel build src:all I get the following message:
 """"WARNING: --batch mode is deprecated. Please instead explicitly shut down your Bazel server using the command "bazel shutdown".                                                                                                    INFO: Invocation ID: 86e5a91e-12f0-4c7f-9b4a-37529e017bcd                                                        INFO: Analysed 32 targets (41 packages loaded, 1358 targets configured).                                         INFO: Found 32 targets...                                                                                        INFO: Elapsed time: 6.727s, Critical Path: 0.67s                                                                 INFO: 0 processes.                                                                                               INFO: Build completed successfully, 1 total action """" ,

meaning that spm_train is not available. Can you help me install spm_train in my ubuntu server?

**Comment by fozziethebeat** [comment]
We need to fix the documentation.

The binary is now in 
  ./bazel-bin/src/spm_train

**Comment by 3NFBAGDU** [comment]
Thank You, i found spm_train.
When i run this command
./bazel-bin/src/spm_train --input=/home/ubuntu/xlnet/giorgi.txt --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995   --shuffle_input_sentence --input_sentence_size=100
I have error: """"./bazel-bin/src/spm_train --input=/home/ubuntu/xlnet/giorgi.txt --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995   --shuffle_input_sentence --input_sentence_size=10                                                                                                         WARNING: Logging before InitGoogleLogging() is written to STDERR                                                 I0628 08:51:36.717789  5255 sentencepiece_trainer.cc:52] Starts training with :                                  TrainerSpec {                                                                                                      input_format:                                                                                                    model_prefix: sp10m.cased.v3                                                                                     kModelType_Map: UNIGRAM                                                                                          vocab_size: 32000                                                                                                self_test_sample_size: 0                                                                                         character_coverage: 0.99995                                                                                      input_sentence_size: 10                                                                                          shuffle_input_sentence: 1                                                                                        seed_sentencepiece_size: 1000000                                                                                 shrinking_factor: 0.75                                                                                           max_sentence_length: 4192                                                                                        num_threads: 16                                                                                                  num_sub_iterations: 2                                                                                            max_sentencepiece_length: 16                                                                                     split_by_unicode_script: 1                                                                                       split_by_number: 1                                                                                               split_by_whitespace: 1                                                                                           treat_whitespace_as_suffix: 0                                                                                    vocabulary_output_piece_score: 1                                                                                 hard_vocab_limit: 1                                                                                              use_all_vocab: 0                                                                                                 unk_id: 0                                                                                                        bos_id: 1                                                                                                        eos_id: 2                                                                                                        pad_id: -1                                                                                                       unk_piece: <unk>                                                                                                 bos_piece: <s>                                                                                                   eos_piece: </s>                                                                                                  pad_piece: <pad>                                                                                                 unk_surface:  ⁇                                                                                                }                                                                                                                NormalizerSpec {                                                                                                   name: nmt_nfkc                                                                                                   add_dummy_prefix: 1                                                                                              remove_extra_whitespaces: 1                                                                                      escape_whitespaces: 1                                                                                            normalization_rule_tsv:                                                                                        }                                                                                                                F0628 08:51:36.717953  5255 spm_train_main.cc:183] Check failed: _status.ok() Internal: src/trainer_interface.cc(54) [(trainer_spec.input().size()) > (0)]                                                                        *** Check failure stack trace: ***                                                                               Aborted (core dumped)""".

What type of extension should the --input file have?

**Comment by taku910** [comment]
We've decided to rollback the recent bazel stuff and moved it to new bazel branch.
We will start the migration once bazel branch gets stable.

We will keep this issue opened just for the reference of bazel branch. Thank you.

**Comment by 3NFBAGDU** [comment]
Thank you for attention, i have tried this with python sentencepiece.
`import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=bpe.input --model_prefix=sp10m.cased.v3 --vocab_size=32000 --character_coverage=0.99995 --model_type=unigram --control_symbols=<cls>,<sep>,<pad>,<mask>,<eod> --user_defined_symbols=<eop>,.,(,),",-,–,£,€ --shuffle_input_sentence --input_sentence_size=10000000')` and now i can train it, but i have error `RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(540) [output->WriteLine(os.str())]`.
