### ISSUE TITLE
Split numbers into constituent digits

### ISSUE THREAD

**Issue by adityanshastry** [google/sentencepiece#360]
Dealing with numbers in MT (and possibly other NLP) tasks is quite a pain. Most often, the numbers in the source would simply need to be copied in the target. But networks would have to see each occurrence of numbers in the vocabulary quite a few times to learn to copy them. As this is not usually possible, they end up hallucinating some numbers in the target.

But if the numbers were to be split into its constituent digits, then the network would have more occurrences of each digit, allowing much better learning.

Example:
`Its over 9000` would result in `Its _over _9 0 0 0`

**Comment by taku910** [comment]
try `--user_defined_symbols=0,1,2,3,4,5,6,7,8,9` which enforces the numbers into digits.

By the way, you might want to try shared vocab where we train unified single sentencepiece model from source and target sentences. Then, source and target numbers are segmented in the same way so we may see less hallucination.
