### ISSUE TITLE
Not found mining_sentence_size

### ISSUE THREAD

**Issue by vanh17** [google/sentencepiece#363]
I tried to run the sentenpiece with the corpus of around 45M sentences. It is quite large so that I want to use mining_sentence_size=1000000 as suggested in #133. I used python wrapper by typing in ``pip install sentencepiece`` in the cmd
Then implemented the python code like this
```````
SPM_COMMAND = ('--input={} --model_prefix={} '
                       '--vocab_size={} --input_sentence_size={} '
                       '--shuffle_input_sentence=true --mining_sentence_size=1000000 ' 
                       '--bos_id=-1  --eos_id=-1').format(
               args.input, MODEL_PREFIX,
               VOC_SIZE - NUM_PLACEHOLDERS, SUBSAMPLE_SIZE)
        spm.SentencePieceTrainer.Train(SPM_COMMAND)
```````
However, when I ran the code, it gave me the error:
````````
sentencepiece_trainer.cc(116) LOG(INFO) Running command: --input=/net/vaosl01/opt/NFS/mimic_hv4/data/NOTEEVENTS_BERT_FORMARTTED.csv --model_prefix=tokenizer --vocab_size=63744 --input_sentence_size=44490364 --shuffle_input_sentence=true --mining_sentence_size=1000000 --bos_id=-1  --eos_id=-1
Traceback (most recent call last):
  File "build_vocabulary.py", line 30, in <module>
    main()
  File "build_vocabulary.py", line 27, in main
    spm.SentencePieceTrainer.Train(SPM_COMMAND)
OSError: Not found: unknown field name "mining_sentence_size" in TrainerSpec.
````````

**Comment by taku910** [comment]
`--mining_sentence_size` is deprecated. Please use `--input_sentence_size`.

**Comment by xiongzhp** [comment]
Doesn't it harm the accuracy of tokenization if we set the number of input sentences small? I could always get the same memory error even with only 10% of the whole corpus. Is there a way to avoid so heavy memory usage even when handling large corpus?
