### ISSUE TITLE
Tokenize the sentence 

### ISSUE THREAD

**Issue by 3NFBAGDU** [google/sentencepiece#365]
I have made spm_train. 
i want to load the sentencepiece model and tokenize some sentence. How can i do this with python code?
"hello i am begginer"  ----> ['hello', 'i', 'am'., 'begginer']
`import sentencepiece as spm
from prepro_utils import preprocess_text, encode_ids

# some code omitted here...
# initialize FLAGS

text = "hello i am Begginer"

sp_model = spm.SentencePieceProcessor()
sp_model.Load('/home/ubuntu/giorgi/sp10m.cased.v3.model')
text = preprocess_text(text, lower=False)
ids = encode_ids(sp_model, text)

print(ids)
`

**Comment by taku910** [comment]
Please take the following page.

https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
