### ISSUE TITLE
Releasing tf_sentencepiece recent version as source code

### ISSUE THREAD

**Issue by mboisson** [google/sentencepiece#367]
Hi,
We are trying to install tf_sentencepiece on a system that has a kernel 2.6.32, and does not support GLIBC 2.27. You only provide binary wheels (manylinux) for tf_sentencepiece, which requires GLIBC 2.27. 

Can you please release a source version of tf_sentencepiece on pypi, so that we can build our own wheel, linked against GLIBC 2.24 ?

Thanks

**Comment by mboisson** [comment]
So, closing without a fix or comment ?

**Comment by taku910** [comment]
Sorry, reopen the bug, but at this moment, we will not release source version of tf-sentencepiece as the building ops is too complicated (need to build static library of sentencepiece, etc) and building it on the official docker image is the primal and stable way at this moment.

https://github.com/google/sentencepiece/blob/master/tensorflow/make_py_wheel.sh

I appreciate your help to make source package.

**Comment by mboisson** [comment]
Can you build the manylinux wheel using GLIBC 2.24 then, so that it works on older platforms ?

**Comment by taku910** [comment]
It is recommended to use the custom-op docker image to build tf ops and whl package https://github.com/tensorflow/custom-op

We don't have any plan to build ops other than this environment. I think releasing src package could be better for fixing the original issue.

**Comment by mhbkb** [comment]
Any update on this? We also want the source dist to consume the pakcage.

**Comment by taku910** [comment]
Let me close this bug. tf_sentencepiece is going to be deprecated as tf.text supports sentencepiece. We will not have plan to release source package because of complexity.

https://github.com/google/sentencepiece/tree/master/tensorflow
