### ISSUE TITLE
How to create a static version of sentencepiece_processor_ops?

### ISSUE THREAD

**Issue by bsod90** [google/sentencepiece#369]
Sorry for the noob question, I really don't know much about c++

I'm trying to use the sentencepiece with tensorflow_serving and apparently, it requires tensorflow_serving to be rebuilt and staticlly linked with the op in order to work. As far as I understand, I need to provide a "sentencepiece_processor_ops.a" file in the ts_serving Bazel script and I'm figuring out how can I build one? I found a command that builds sentencepiece_processor_ops.so but what should I change in it to build .a file?

Thanks for any help!

**Comment by chiragjn** [comment]
I am also interested in this. I tried to do this few months ago, but was not able to get any results

As this comment mentions, the op needs to be built with bazel https://github.com/google/sentencepiece/issues/325#issuecomment-517359346

There is already a WIP bazel branch here: https://github.com/google/sentencepiece/blob/bazel/src/BUILD

I think the way to statically link is to pass `alwayslink = 1` to `cc_library` in the BUILD file above as shown here https://github.com/tensorflow/serving/blob/master/tensorflow_serving/g3doc/custom_op.md, but I maybe wrong

**Comment by stefanondisponibile** [comment]
hey @bsod90, I wonder if you made it in the end?
I described the process I followed (with no success) [here](https://github.com/google/sentencepiece/issues/325#issuecomment-538957833) (#325) .

**Comment by bsod90** [comment]
Hey, @stefanondisponibile 
Actually, we just gave up on tf serving and replaced it with a similar tool that doesn't require static linking. Check out this blog post: https://blog.onebar.io/building-a-semantic-search-engine-using-open-source-components-e15af5ed7885
It's a bit broader but mentions the issue in the second half.

**Comment by stefanondisponibile** [comment]
thank you @bsod90, I had seen that nice post already, and I've been pretty much following the same path with [simple tensorflow serving](https://github.com/tobegit3hub/simple_tensorflow_serving), but I'd rather use tf serving if possible :)

**Comment by taku910** [comment]
tf-sentencepiece is removed from the repos, as tf.text supports sentencepiece. let me close this bug.
