### ISSUE TITLE
Multilingual model - tf_sentencepiece symbol errors

### ISSUE THREAD

**Issue by chewbecca-80** [google/sentencepiece#370]
When trying to replicate the Universal Sentence Encoder Multilingual tool example (https://colab.research.google.com/github/tensorflow/hub/blob/master/examples/colab/cross_lingual_similarity_with_tf_hub_multilingual_universal_encoder.ipynb) in a conda and virtual environment, symbol errors arise when importing tf_sentencepiece. I have attached several conda environment yml files to this ticket, all of which produce the same error when importing tf_sentencepiece. 
[use_ml_environments.zip](https://github.com/google/sentencepiece/files/3453486/use_ml_environments.zip)

To reproduce the error:
1. Create a conda environment using one of the environment yml files with the command:
`conda env create -f filename`
where filename is the name of file. 
2. Activate the conda environment
`conda activate environment-name`
where environment-name is the name of the environment (you can see the environment name after creating it, or seeing a list of environments with the command "conda info --envs")
3. Open a python shell
`python`
4. Import tensorflow
`import tensorflow as tf`
5. Import tf_sentencepiece
`import tf_sentencepiece`
6. View the error

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rservaites/miniconda/envs/tf-test-gpu-1-14/lib/python3.7/site-packages/tf_sentencepiece/__init__.py", line 5, in <module>
    from tf_sentencepiece.sentencepiece_processor_ops import *
  File "/home/rservaites/miniconda/envs/tf-test-gpu-1-14/lib/python3.7/site-packages/tf_sentencepiece/sentencepiece_processor_ops.py", line 43, in <module>
    _gen_sentencepiece_processor_op = tf.load_op_library(so_file)
  File "/home/rservaites/miniconda/envs/tf-test-gpu-1-14/lib/python3.7/site-packages/tensorflow/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/rservaites/miniconda/envs/tf-test-gpu-1-14/lib/python3.7/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.1.14.0: undefined symbol: _ZN10tensorflow12OpDefBuilder4AttrESs

I originally tried the pip install of tensorflow and tf_sentencepiece, but when doing that I got a tensorflow import error. 

> (tf-test-baseline) rservaites@t2000:/data2/home/rservaites$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
> import tensorflow as tf
Traceback (most recent call last):
  File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory

> During handling of the above exception, another exception occurred:

> Traceback (most recent call last):
> 
>   File "<stdin>", line 1, in <module>
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
>     from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
>     from tensorflow.python import pywrap_tensorflow
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
>     raise ImportError(msg)
> ImportError: Traceback (most recent call last):
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
>     from tensorflow.python.pywrap_tensorflow_internal import *
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
>     _pywrap_tensorflow_internal = swig_import_helper()
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
>     _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/imp.py", line 242, in load_module
>     return load_dynamic(name, filename, file)
>   File "/home/rservaites/miniconda/envs/tf-test-baseline/lib/python3.7/imp.py", line 342, in load_dynamic
>     return _load(spec)
> ImportError: libcublas.so.10.0: cannot open shared object file: No such file or directory
> 
> 
> Failed to load the native TensorFlow runtime.
> 
> See https://www.tensorflow.org/install/errors
> 
> for some common reasons and solutions.  Include the entire stack trace
> above this error message when asking for help.
> >>>

I also compiled the tf_sentencepiece code from source and got the same errors.

**Comment by taku910** [comment]
Recent;y, tensorflow team has released an official docker image to build custom-op. I've rebuild tf_sentencepiece with this docker image and released it as v0.1.83. You can install the latest one via "pip install tf_sentencepiece".

https://github.com/google/sentencepiece/releases/tag/v0.1.83
