### ISSUE TITLE
Subword regularization on BPE models

### ISSUE THREAD

**Issue by nicolaspanel** [google/sentencepiece#371]
As described by @eric-haibin-lin in https://github.com/google/sentencepiece/issues/335 it is currently not possible to use `SampleEncodeAsPieces`, `SampleEncodeAs{Pieces,Ids}` on a BPE model (displays `model_interface.h(85) LOG(ERROR) Not implemented.` error and returns an empty list).

Do you plan to support it in the near futur ?

(and thank you for this great tool BTW!)

**Comment by taku910** [comment]
BPE is not based on probabilistic language model, so it is theoretically impossible to support sampling and nbest output.

Details:

https://aclweb.org/anthology/P18-1007

**Comment by nicolaspanel** [comment]
Thank you @taku910 for the quick reply
I was just wondering if there was a way to simulate it even if it is not probability based.
For example, let say the vocab contains tokens {`_hello`, `_world`, `_hell`, `o`, `_he`,`llo`, `_w`, `orld`}
decoding sentence `hello world` will then lead to `['_hello', '_world']`
Now, we could provide some subword regularization following pseudo algorithm below:
```python
text = 'hello world'
pieces = vocab.EncodeAsPieces(text)  # => ['_hello', '_world']
def maybe_regularize(piece, threshold=0.5):
  reg_prob = rand()  # some threshold
  if p < threshold:
     return token  # no regularization
  sub_pieces = ... # find sub pieces of `piece` assuming `piece` is not in vocabulary
  return [maybe_regularize(p) for p in sub_pieces]
reg_pieces = [maybe_regularize(p) for p in pieces]
```

producing something like:
```python
SampleEncodeAsPiece(text) # => ['_hello', '_world']
SampleEncodeAsPiece(text) # => ['_he', 'llo', '_world']
SampleEncodeAsPiece(text) # => ['_hell', 'o', '_w', 'orld']
...
```

what do you think ?

**Comment by taku910** [comment]
As shown in the paper, subowrd regularization is sensitive to the regularization parameter. It will not work on the completely random sequence. BPE is an incremental algorithm so the subtle difference in the current decisions will change the segmentation largely.

I cannot find any strong reason to support sampling in BPE as unigram model can do it with a theoretical justification.

**Comment by snakers4** [comment]
> BPE is not based on probabilistic language model, so it is theoretically impossible to support sampling and nbest output.

Well, technically you are right.

But looks like these [guys](http://arxiv.org/abs/1910.13267) modify the BPE algorithm a bit 
![image](https://user-images.githubusercontent.com/12515440/68080084-232db380-fe05-11e9-854a-06b7d64488f8.png)

I cannot verify their results, I do STT (not NMT). But for me BPE tokens worked best so far.
I am testing BPE vs unigram model with some sampling temperature now.

**Comment by taku910** [comment]
Thank you for the info. It looks very interesting and simple. I will implement it soon.

**Comment by snakers4** [comment]
Many thanks.
Would be very nice to test it against unigram model for subword regularization.
So far I tried `bpe` vs `unigram` with subword regularization in my domain (STT) and subword regularization did not really help.
But in my domain `bpe` makes much more sense (in Russian sounds that are pronounced together will form nice BPE tokens).

**Comment by rudvlf0413** [comment]
@taku910 Hello, did you implement BPE-dropout?
I also look forward to using BPE-dropout in the sentencepiece library

**Comment by taku910** [comment]
Sorry for the late response.

Implemented BPE-dropout in the latest release.
https://github.com/google/sentencepiece/releases/tag/v0.1.9

**Comment by snakers4** [comment]
Nice!

So do I understand correctly, that after updating to the latest versions, in the Python API I can train my model as usual, but now I can also have `alpha` during sampling?

**Comment by snakers4** [comment]
I installed the new version (1.9) from source and trained a new model.
Am I doing something wrong?

![image](https://user-images.githubusercontent.com/12515440/81777009-a0df2400-94f8-11ea-895f-f8b3fd98b167.png)

>   // - BPE (--model_type=bpe):
>   // `alpha` is the merge probability `p` in https://arxiv.org/abs/1910.13267
>   // when alpha<=0, no sampling is performed but the best segmentation is
>   // returned. Nbest-based sampling is not supported so you need to specify
>   // nbest_size = 0 in BPE.

Looks like you nned to call sampling methods with nbest_size = 0 and alpha > 0?

**Comment by taku910** [comment]
Hi, oh sorry. the comment is incorrect. We have to specify nbest_size=-1. We will fix the behavior

**Comment by taku910** [comment]
Fixed the issue in the head. (0.1.91). Will release it soon.

**Comment by snakers4** [comment]
I do confrm that it works now
![image](https://user-images.githubusercontent.com/12515440/82533122-59d1de00-9b4b-11ea-92b6-02fd7bb47c4a.png)
