### ISSUE TITLE
Disabling space, EOS, BOS characters

### ISSUE THREAD

**Issue by tawe141** [google/sentencepiece#373]
Is there a way to leave these characters out?

**Comment by taku910** [comment]
Uses the flag `--eos_id=-1 --bos_id=-1` when running spm_train. Disabling space is not possible but there is a workaround.

```
% sed 's/ /<unk>/g' < input > input2
%  spm_train ... --input=input2 --user_defined_symbols='<unk>' ... 
```

First line replaces the space into '<unk>', and then train the model with user defined symbols. Then all spaces are handled as unknown token.
