### ISSUE TITLE
It does not work with tensorflow 2.0.0rc0

### ISSUE THREAD

**Issue by DanielWicz** [google/sentencepiece#382]
Hello, the code does not work with tensorflow2.0.0rc0. After importing tf_sentencepiece it states that the package is not compatible.

**Comment by taku910** [comment]
Please try tensorflow 2.0.0-beta0

**Comment by DanielWicz** [comment]
> 
> 
> Please try tensorflow 2.0.0-beta0

Yet the beta0 and beta1 do not want to work with my model, thus I am caught between a rock and a hard place.
