### ISSUE TITLE
sentencepiece and tensorflow protoc conflict

### ISSUE THREAD

**Issue by o-90** [google/sentencepiece#383]
I appreciate the quick turnaround on [#379](https://github.com/google/sentencepiece/issues/379).

We have a custom ops repo where your sentencepiece code is built (with bazel)
against other ops and then compiled with tensorflow serving.  When trying to
upgrade our build to tensorflow serving 1.14 we ran into this issue:  The
build completes but when we try to run the docker container we get the message:
```bash
[libprotobuf FATAL third_party/protobuf-lite/common.cc:69]
This program requires version 3.7.0 of the Protocol Buffer runtime library,
but the installed version is 3.6.1.  Please update your library.  If you
compiled the program yourself, make sure that your headers are from the same
version of Protocol Buffers as your link-time library.  (Version verification
failed in "external/protobuf_archive/src/google/protobuf/wrappers.pb.cc".)
terminate called after throwing an instance of
'google::protobuf::FatalException'
```
This appears to be from [this line](https://github.com/google/sentencepiece/blob/d4dd947fe71c4fa4ee24ad8297beee32887d8828/third_party/protobuf-lite/common.cc#L68) in the static proto files copied into `third_party/protobuf-lite/`.  Futher investigation suggests that [protoc version 3.6.1](https://github.com/google/sentencepiece/blob/d4dd947fe71c4fa4ee24ad8297beee32887d8828/third_party/protobuf-lite/google/protobuf/stubs/common.h#L104) is pinned.  This seems to conflict with what is used in tensorflow

```bash
$ cd /path/to/python/lib/python3.6/site-packages/tensorflow
$ python -c "import tensorflow as tf; print(tf.__version__)"
1.14.0

$ ack '3006001'
# ... nothing

$ ack '3007000'
# ... lots of stuff
include/google/protobuf/stubs/common.h
92:static const int kMinHeaderVersionForLibrary = 3007000;
```

When I change and explicitly install protoc/protobuf 3.7.0 and rebuild,
tensorflow server crashes.  Interactively running the image gives:
```bash
root@hash:/tensorflow-serving# gdb /usr/bin/tensorflow_model_server
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Reading symbols from /usr/bin/tensorflow_model_server...done.
(gdb) run
Starting program: /usr/bin/tensorflow_model_server
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000056078ecf9e4e in google::protobuf::RepeatedField<int>::Reserve(int) ()
```
Would it be possible to reconcile the sentencepiece proto to be compatible
with tensorflow and tensorflow serving v1.14?

Environment information:
```text
ubuntu 16.04
gcc 5.4.0
python 3.6.8
tensorflow 1.14.0
tensorflow serving r1.14
bazel 0.26.1
```

Possibly related issues:
https://github.com/google/sentencepiece/issues/381
https://github.com/google/sentencepiece/issues/382

Thanks!

**Comment by gobrewers14** [comment]
Any update on this?

**Comment by sooneecheah** [comment]
Not sure if this helps, but here is a workaround for this problem:
https://github.com/google/sentencepiece/issues/325#issuecomment-546789546
