### ISSUE TITLE
Feature Request: Python Executables for training, encoding and decoding

### ISSUE THREAD

**Issue by bricksdont** [google/sentencepiece#385]
It would be helpful if installing the Python package via pip would also install Python binaries. What I mean is that the following should be possible:

    pip install sentencepiece
    spm_train --input data.txt --model-prefix sp

This would make the package much more usable out of the box.

Compiling the source code leads to such binaries, but has many dependencies that are trickier to install.

Thanks for considering!

**Comment by taku910** [comment]
Isn't it enough to use Python API? They support all the features of spm_train and spm_encode.

```
>>> import sentencepiece as spm
>>> spm.SentencePieceTrainer.Train('--input=test/botchan.txt --model_prefix=m --vocab_size=1000')
```

**Comment by bricksdont** [comment]
That is also useful, I am just saying that a Python executable would make the library even more accessible, because there would be no need to check carefully which functions in

https://github.com/google/sentencepiece/blob/master/python/sentencepiece.py

are equivalent to a call to, for instance, `spm_encode`

**Comment by taku910** [comment]
spm_{train,endode} are pure C++ program/binary so we should not release them as  Python packages. If we really want to have them, we would like to re-implement these tools in python and sentencepiece python wrapper.

**Comment by bricksdont** [comment]
Thank you for your answer - and feel free to close the issue if this is not feasible or reasonable.

**Comment by taku910** [comment]
If we decide to release these command line tools, we want to introduce py_spm_train or py_spm_encode, which are re-implementation of C++ library and installed under python site-package directory. 

We don't have enough bandwidht for working it. Any contributions are appreciated.

**Comment by taku910** [comment]
Let me close this bug as there are no further discussions.
