### ISSUE TITLE
How to pickle a SentencePiece model

### ISSUE THREAD

**Issue by ArbinTimilsina** [google/sentencepiece#387]
Hi,
I have a SentencePiece model that I want to save together with my trained translation model. When I try to pickle it as
```
import pickle
import sentencepiece

sp_processor = sentencepiece.SentencePieceProcessor()
sp_processor.load(path_to_my_model)

pickle.dump(sp_processor, open( "sp_processor.p", "wb" ))
```

I get the following error
```
TypeError: can't pickle SwigPyObject objects
```

Is there a way I can make it work? How have others handled such cases before?

**Comment by gpengzhi** [comment]
@ArbinTimilsina You can wrap `sp_processor` in a class and define `__getstate__` and  `__setstate__`. An example is [here](https://github.com/asyml/texar-pytorch/blob/master/texar/torch/data/tokenizers/pretrained_xlnet_tokenizer.py#L111).

**Comment by ArbinTimilsina** [comment]
Awesome! Thanks, @gpengzhi.
