### ISSUE TITLE
Ignoring all special characters other than . and comma.

### ISSUE THREAD

**Issue by akanyaani** [google/sentencepiece#389]
Hi,

It is ignoring all these special characters even these characters appearing a hundred thousand times in corpus.

```
txt = "+ + : ; @ ? # $"
print(sp.encode_as_pieces(txt))
print(sp.encode_as_ids(txt))

['▁', '+', '▁', '+', '▁', ':', '▁', ';', '▁', '@', '▁', '?', '▁', '#', '▁', '$']
[31958, 1, 31958, 1, 31958, 1, 31958, 1, 31958, 1, 31958, 1, 31958, 1, 31958, 1]
```

**Comment by taku910** [comment]
Could you elaborate the issue? How did you train the model, including the debug message and command line flags.

**Comment by akanyaani** [comment]
Hi,
@taku910 I was trying to train BPE on my data but model is ignoring special characters even present in corpus. As i have mentioned in first comment model is encoding those special characters as unknow character.

**Comment by ahs8w** [comment]
I have the same issue for symbols such as: ` ;+=@#$%^&*[]`.  I can add in these tokens explicitly via  '--user_defined_symbols' but that seems redundant when tokens already exist in the corpus.

**Comment by taku910** [comment]
Please try `--character_coverage=1.0` that enforces to include all chars in the corpus as vocab.

--character_coverage: amount of characters covered by the model, good defaults are: 0.9995 for languages with rich character set like Japanse or Chinese and 1.0 for other languages with small character set.
