### ISSUE TITLE
have installed and can not using a spm_encode. I Have try using sudo ldconfig -v

### ISSUE THREAD

**Issue by PlayDeep** [google/sentencepiece#391]
My system is cent os. and can not using apt-get to install dependency library.

the install error log
```
ldconfig: Can't stat /libx32: No such file or directory
ldconfig: Path `/usr/lib' given more than once
ldconfig: Path `/usr/lib64' given more than once
ldconfig: Can't stat /usr/libx32: No such file or directory
```

using spm_encode and report error as follow log
```
spm_encode: error while loading shared libraries: libsentencepiece.so.0: cannot open shared object file: No such file or directory
```

**Comment by taku910** [comment]
Please add /usr/local/lib to  /etc/ld.so.conf and execute ldconfig -v again.

**Comment by md975** [comment]
Hi,

@taku910 how can I do this step if I'm installing the lib locally? (I can't change /etc/ld.so.conf)

Thanks!
