### ISSUE TITLE
How to prepare data for embedding layer?

### ISSUE THREAD

**Issue by rishabhsahrawat** [google/sentencepiece#393]
I want to use `SentencePiece`, I have achieved to train the model on `botchan.txt` then tokenize and encode a little example in the following way-

````
#!pip3 install sentencepiece
#!wget https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt

import sentencepiece as spm
import random
spm.SentencePieceTrainer.train('--model_prefix=m --input=botchan.txt --vocab_size=2000 --bos_id=-1 --eos_id=-1')
sp = spm.SentencePieceProcessor()
sp.Load('m.model')
print (sp.EncodeAsIds('This is a test'))
# This prints 5 ids.
````
Now the problem is if I want to feed this to an embedding layer but the outputs sizes are not fixed. SO how does one can fix the encoded outputs for feeding to the embedding layers which requires fixed length inputs.

**Comment by taku910** [comment]
Sorry, this question is out-of-scope of sentencepiece as we are not aware of the NN structures nor NN framework. Let me close this bug.
