### ISSUE TITLE
vocab size

### ISSUE THREAD

**Issue by zhangguanheng66** [google/sentencepiece#394]
New to spm. Just wondering if there are some studies related to the vocab size. Of course it is related to the actual problem but are there recommendations for the vocab size? Thanks.

**Comment by francoishernandez** [comment]
Hi @zhangguanheng66 
You might want to have a look [there](https://github.com/google/sentencepiece/blob/master/doc/experiments.md).
Also, I think this is highly dependent on the task / corpus.
