### ISSUE TITLE
Question about user_defined_symbols

### ISSUE THREAD

**Issue by francoishernandez** [google/sentencepiece#396]
Hi guys,

I'm trying to build some sentencepiece model on top of a first pretokenization step. Basically, I already have a list of tokens (with either '▁' spacer annotation or not), that I want to preserve.
I'd like to use the `--user_defined_symbols` option for that, but I'm struggling to find an appropriate configuration.

Here is an easily reproducible example to illustrate.

## Corpus
```
tototatatititotoo
```

## Cases

The 'result' column is the result of spm_encode of this input:
```
▁tototatatititotoo
```

| #  | `--user_defined_symbols` | `--vocab_size` | result                            |
|----|--------------------------|----------------|-----------------------------------|
|  1 | `▁toto`                  | 9              | `▁toto t a t a t it it o t o o`   |
| 2  | `▁toto,toto`             | 9              | `▁toto t a t a t i t i toto o`    |
| 3  | `▁toto,toto,o`           | 9              | `▁toto t a t a t i t i toto o`    |
| 4  | `▁toto,toto,t`           | 9              | `▁toto t a t a t i t i toto o`    |
| 5  | `▁toto,toto,t,o`         | 9              | `▁toto t a t a t i t i t o t o o` |

I'm not sure to understand the last case, 5. When `t` and `o` are both part of the `user_defined_symbols`, it seems they are preferred to the longest piece (`toto`). Yet, the vocab is the same in this last case as in the penultimate one, where `o` is 'found' during `spm_train`.

| # | vocab                                                                                                                |
|---|----------------------------------------------------------------------------------------------------------------------|
| 4 | `<unk>    0 / <s>    0 / </s>    0 / ▁toto    0 / toto    0 / t    0 / a    -0.336112 / i    -1.92897 / o    -2.92897` |
| 5 | `<unk>    0 / <s>    0 / </s>    0 / ▁toto    0 / toto    0 / t    0 / o    0 / a    -0.211112 / i    -1.92897` |

Is this expected behaviour? 
Also, I'm not sure whether my corpus should already be 'pretokenized' based on my 'known' symbols or not (though some tests lead me to think it should not).

Thanks!

**Comment by taku910** [comment]
Thank you for the report. I could reproduce the bug and I think this is a bug.

I fixed it in the HEAD (v0.1.87) release. Could you check?
