### ISSUE TITLE
How to change the user defined symbols without training a vocab model from scratch ?

### ISSUE THREAD

**Issue by wxiaopei** [google/sentencepiece#398]
I have trained a vocab file with a few user defined symbols. Some of these symbols are non-meaningful tokens, e.g `reserved_01, reserved_02`. I want to use them to keep the ids for future use. 
I wonder if I can change these reserved tokens to the real useful tokens without training the vocab files. 

Thanks

**Comment by taku910** [comment]
The model file is stored as serialized protobuf, and you can edit them manually.
https://github.com/google/sentencepiece/issues/121
https://github.com/google/sentencepiece/issues/323
