### ISSUE TITLE
protobuf issues when installing

### ISSUE THREAD

**Issue by rpryzant** [google/sentencepiece#40]
When I run `./configure` during installation, I get the following error:
```
./configure: line 17069: syntax error near unexpected token `PROTOBUF,'
./configure: line 17069: `PKG_CHECK_MODULES(PROTOBUF, protoc >= 2.4.0)'
```

If I comment out the offending line `configure` passes, but I receive the following error during `make`:
```
Undefined symbols for architecture x86_64:
  "google::protobuf::Message::Utf8DebugString() const", referenced from:
      std::__1::__function::__func<main::$_2, std::__1::allocator<main::$_2>, void (std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)>::operator()(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in spm_encode_main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [spm_encode] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I am running macOS 10.13.1 and libprotoc 3.5.0

**Comment by datavizweb** [comment]
I assume your were able to fix the issue and install package. If not following step helped me to get pass the error

ACLOCAL_AMFLAGS = -I /usr/local/share/aclocal to Makefile.am (remove the old flag which sets to thirdparty).
Have a clean dir (better to start in new dir, running on old dir might give you some weird error. Follow the installation step.

**Comment by taku910** [comment]
You might need to install pkg-config which detects the library path of protobuf. Please try the following command line

% brew update
% brew install pkg-config
% brew install protobuf || brew link --overwrite protobuf

**Comment by taku910** [comment]
Please reopen this bug if this error persists.
