### ISSUE TITLE
How to apply subword regularization(sampling) to training NMT?

### ISSUE THREAD

**Issue by minstar** [google/sentencepiece#402]
Hi, first of all, thank you for your great library.

I'm currently trying to train my NMT model (pytorch/fairseq) with subword regularization method.(sampling)

I'm having hard time applying this method to training NMT model. Is there any example or tutorial link that I can reference? 

Also, do I need to sample every epoch? (your paper states that you sampled segments every parameter update. is sampling every epoch enough?)

Again, thanks for your great work.

**Comment by taku910** [comment]
We don't any tutorial. 

Probably your system runs sentence -> id conversion as preprocessing. You can run this preprocessing at the begging of every epoch. This would not need to change the code drastically.

Another simpler way is to augment training data. You can run sentence->id convesion on the training data multiple times and simply concatenate them to make new one big data.
