### ISSUE TITLE
Trying to understanding symbol "▁" (U+2581) at the start of the Japanese sentences

### ISSUE THREAD

**Issue by weiyengs** [google/sentencepiece#404]
Hi, 
I noticed that there are symbol "▁" (U+2581) at the start of most Japanese sentences. I thought that this might be related to: #15 

It seems that the example that was illustrated for cases like:
sp.EncodeAsPieces("県仏教会(岐阜市)は16日、混乱が続いている中国のチベット問題について、「平和的な解決を願う」とした宣言を採択したと発表した。。同仏教会は県内約2千の寺院が宗派を超えて加盟してい。")

>> ['▁県', '仏', '教', '会', '(', '岐阜市',..and so on
where the symbol is prefix to the character and I can understand that we want to same treatment as the whitespace counterpart.

But what I'm see-ing on my end is: 
sp.EncodeAsPieces("容認の閣議決定の撤回を目指すことなどで合意できれば、党本部の方針に基づき、党の独自候補を取り下げる。。その上で、民主新顔で元TBS報道局解説・専門記者室長の杉尾秀哉氏(58)を野党統一候補として支援するとしている。")

>> ['▁', '容認', 'の', '閣議決定', 'の', '撤回',..and so on
where the symbol lives as a character on its on.

Is there a reason why the difference in behaviour?

Thanks!

**Comment by taku910** [comment]
If 県 tend to appear at the begging of sentence, ▁県 will be more likely extracted.  It depends on the frequency of individual characters.
