### ISSUE TITLE
Encode() in sentencePieceProcessor doesn't take unicode strings as input

### ISSUE THREAD

**Issue by NewInfinite007** [google/sentencepiece#41]
Hi,
      The `Encode()` function in the `sentencePieceProcessor` module doesn't take unicode strings as inputs. Could anyone please suggest an alternative way?

p.s. I am using the python wrapper of sentencepiece.

Thanks in advance.

**Comment by taku910** [comment]
Thank you for the report.

Updated the python module to support both Unicode and legacy byte string.
For more detail, please see the following document.

https://github.com/google/sentencepiece/tree/master/python

Will update pip package soon.

**Comment by taku910** [comment]
pip package is also available.

https://pypi.python.org/pypi/sentencepiece/0.0.3

**Comment by NewInfinite007** [comment]
Thanks @taku910  :)
