### ISSUE TITLE
Fails to load latest version of .so when module installed in user dir

### ISSUE THREAD

**Issue by mikaelhg** [google/sentencepiece#410]
In `sentencepiece_processor_ops.py`, row 47

```python
_gen_sentencepiece_processor_op = tf.load_op_library(so_file)
```

attempts to load the latest shared library.

However, the 2.0.0 library hasn't been published yet, so the row tries to load the 2.0.0-beta1 .so.

When the `tf_sentencepiece` package has been installed in the user directory with the command

```
pip3 install --user tf_sentencepiece
```

the install path unfortunately has the Python version number in it, so the row 38 of `sentencepiece_processor_ops.py`

```python
      re.search('[0-9]+\.[0-9\.]+.*$', n).group(0)
```

grabs something like `$HOME/.local/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0-beta1`, which won't resolve to a .so.

If you replace that row with a slightly friendlier

```python
      re.search('so.([0-9]+\.[0-9\.]+.*)$', n).group(1)
```

things go smoothly once again.

(Well, the execution ended up in a SIGSEGV, but at least that happened somewhere else, and the .so was loaded.)

**Comment by taku910** [comment]
Thank you for the report. Merged the fix in v0.1.85
