### ISSUE TITLE
Regarding `character_coverage`

### ISSUE THREAD

**Issue by ArbinTimilsina** [google/sentencepiece#412]
I am trying to understand the default value of **0.9995** for `character_coverage`. If I have 100 unique characters, what fraction would be covered by this number? Or in another word, what is the difference between using **0.9995** vs. **0.9998**?

Thanks in advance.

**Comment by taku910** [comment]
When the training corpus has N characters (not a unique chars, but total # of chars).  (1 - p) * N chars are treated as UNK, where p is character coverage.

**Comment by Arjun2905** [comment]
Can character coverage be used as factor to get rid of unwanted characters from the vocab?
