### ISSUE TITLE
ERR on windows   when pip install sentencepiece  

### ISSUE THREAD

**Issue by zhengya01** [google/sentencepiece#413]
I got a error when pip install sentencepiece, and my OS is windows, 
sentencepiece python API  not support windows ??

File "setup.py", line 29, in <module>
  with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8')  as f:
File "C:\Python35\lib\codecs.py" line 895, in open
  file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Error 2] No such file or directory: '..\\VERSION'

**Comment by DomHudson** [comment]
See
https://github.com/google/sentencepiece/issues/386

**Comment by taku910** [comment]
#386 is fixed. let me close this issue.
