### ISSUE TITLE
Optimal vocabulary size

### ISSUE THREAD

**Issue by venkatesh-parvathala** [google/sentencepiece#415]
what might be the optimal vocabulary size for a raw text file with 50,000 unique words in it

**Comment by taku910** [comment]
Optimal vocab size is totally task dependent. However, we empirically found that 32k is reasonable choice for neural machine translation. If the corpus is small, 8k or 16k could be okay.

**Comment by loretoparisi** [comment]
@taku910 thanks for these details. I had the same question, how to scale from 8K to 32K in terms of the input dataset size?

**Comment by loretoparisi** [comment]
Not sure, but maybe this could be a hint:

<img width="580" alt="Schermata 2019-12-04 alle 16 37 29" src="https://user-images.githubusercontent.com/163333/70156550-64d7a580-16b4-11ea-9c3f-cb22132bbcf7.png">

From: [Neural Machine Translation of Rare Words with Subword Units](https://www.aclweb.org/anthology/P16-1162.pdf)

**Comment by spate141** [comment]
@loretoparisi Thanks for the paper link! I also find this which kind of make sense to keep the vocabulary size to a level which also don't put too much overhead on downstream network! 
```
Because subword representations are less sparse, reducing the size of the network vocabulary, and
representing more words via subword units, can lead to better performance.
```

@taku910 @loretoparisi:
On the other hand, I was wondering what could be the optimal size for the data pool to train a tokenizer with fixed vocab? Let's say I have access to 1 billion rows of ngrams with mean length of 7 words. Would randomly selected 50M lines produce more optimal tokenizer? We are keeping the vocab size constant here; for instance 50K vocab size. Any papers that I can look into?
