### ISSUE TITLE
SentencePieceTrainer.Train does not work with filepaths containing blank spaces

### ISSUE THREAD

**Issue by tony-lung-centric** [google/sentencepiece#419]
On 11/6/2019 I did a pip install sentencepiece from the Anconda distribution 3.7.4. The following line of code (I know it's incomplete, but it's enough to illustrate and replicate the command parsing issue.):

`sentencepiece.SentencePieceTrainer.Train('--input=MY FILE.TXT')`

results in the following error:
> OSError: Not found: unknown field name "FILE.TXT" in TrainerSpec.

I tried embedding quotes around the filepath like this:
`sentencepiece.SentencePieceTrainer.Train('--input="MY FILE.TXT"')`

resulting in the following error (note the embedded trailing double-quote is treated as part of string):
> OSError: Not found: unknown field name "FILE.TXT"" in TrainerSpec.

I had similar results using various other attempts to embed escaped and unescaped delimiters around the filename.

**Comment by taku910** [comment]
Please remove the whitespace from the filename at this moment. Use C++ spm_train as CLI if you wan to use these files. Thanks.

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/issues/450
Thank you.
