### ISSUE TITLE
Slow computing time using BPE+Seq2Seq model

### ISSUE THREAD

**Issue by Lvby** [google/sentencepiece#420]
Thanks for your excellent work! One thing I would like to check with you is that the model computing time difference between sentencepiece vs. normal tokenization method such as Keras tokenizer. Using a traditional tokenization method, the training time takes maybe 10 minutes. Using BPE, it does not take long to train the text corpus from scratch. However, the modeling time takes appr. 5 hours for one epoch. Did I do anything wrong when combining BPE + seq2seq model? Any comments? Thank you in advance!

You can view my code from the following links:

https://github.com/Lvby/amazon/blob/master/amazonFood.ipynb 
or
https://nbviewer.jupyter.org/github/Lvby/amazon/blob/master/amazonFood.ipynb

**Comment by taku910** [comment]
We are afraid that there is nothing we can do to help since this is an environment-dependent issue. if there is no further update, let me close this issue by the end of Aug.
