### ISSUE TITLE
how to save sentencepiece model (except training time)

### ISSUE THREAD

**Issue by eagle705** [google/sentencepiece#422]
hi, 

As I know, spm is saved when I train the model.

but except that case,  I wonder how to save sentencepiece model. As I know, it doesn't support api.

the reason I want to know is I use sentencepiece model trained from gluonnlp wrapper 

```from gluonnlp.data import SentencepieceTokenizer```

But when it doesn't work in some case (e.g. low spec cpu).

So I want to load it in my laptop and save pure sentencepiece object.

is there any way to do that?

**Comment by taku910** [comment]
Model file is stored as serialized protobuf.
C++/Python wrapper provides API that directly load model from blob object (byte sequence), e.g.

```sp.load_from_serialized_proto(tf.Gfile('foo.model', 'rb').read())```
