### ISSUE TITLE
do_lower_case in the sentencepiece model files

### ISSUE THREAD

**Issue by kpe** [google/sentencepiece#425]
I'm wondering if it is a good idea to include a `do_lower_case` flag in the model files (as kind of minimal pre-processing instruction of how to prepare the input)?

As an alternative, one could take care that the `tokenize()` method automatically does `lower()` case for models trained on low case (instead of returning `<unk>` for all upper case characters).

Currently the flag of whether lower case pre-processing is needed is not contained in the model, thus those sentencepiece model are not self contained (one of the motivations of this wonderful project, right?).

**Comment by taku910** [comment]
Please use ```spm_train --normalization_rule_name=nmt_nfkc_cf ...``` to lowercase the input.

https://github.com/google/sentencepiece/blob/master/doc/normalization.md

Strictly speaking, lower_case should not be implemented as a simple boolean flag. Taking all Unicode characters into account, we have to have the actual character to character mapping. Unicode standard uses more general concept "case folding". The mapping is updated depending on the Unicode version. (You can find the character mapping in Unicode site). SentencePiece does include this mapping into the model file to make the model purely self-contained.

**Comment by kpe** [comment]
Thank you, @taku910 for the explanation!

**Comment by owos** [comment]
Hi @taku910  I have a sentencepiece model was only trained on lowercase texts. I recently edited the tokens in the tokenizer  to include more special tokens which works fine. The only issue is that all uppercase characters are converted to lowercase automatically even though I have added  Uppercase tokens to the tokenizer.
Is there a way of preventing this from happening?
@kashif
