### ISSUE TITLE
How to extend tokens dictionary?

### ISSUE THREAD

**Issue by kpe** [google/sentencepiece#426]
It would be nice if an existing sentencepiece model could be extended with additional extra special/`[MARKUP]` tokens.

While adding real language tokens might not be needed (or possible), adding additional atomic markup tokens to an existing model, should be possible right?

As an usage scenario - imagine you have a plain text pre-trained model, and you want to handle some HTML-like document, i.e. you need to add special markup/atomic tokens like - `[<P>]`, `[<TABLE>]`, etc.

This is currently not possible, right?

**Comment by taku910** [comment]
SentencePiece supports user-defined symbols. I think you can use this feature.

https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md

**Comment by kpe** [comment]
Thank you, @taku910 for your reply!  What I would like to do is to take a sentencepiece model and extend it with new user-defined symbols (i.e. without changing the piece-to-id mapping for the existing pieces or the tokenization behavior.)

A use case would be to fine-tune some of the official pre-trained ALBERT models on the Google's Natural Question task (which includes some HTML tags), i.e. I would like to convert an existing sentencepiece model to a sentencepiece model that can also handle those additional user-defined symbols (let's say `[<P>]` and `[</P>]`) but without training a new model, which would potentially result in a different sentencepiece model (as the original plain text data might not be available).

**Comment by SchenbergZY** [comment]
> Thank you, @taku910 for your reply! What I would like to do is to take a sentencepiece model and extend it with new user-defined symbols (i.e. without changing the piece-to-id mapping for the existing pieces or the tokenization behavior.)
> 
> A use case would be to fine-tune some of the official pre-trained ALBERT models on the Google's Natural Question task (which includes some HTML tags), i.e. I would like to convert an existing sentencepiece model to a sentencepiece model that can also handle those additional user-defined symbols (let's say `[<P>]` and `[</P>]`) but without training a new model, which would potentially result in a different sentencepiece model (as the original plain text data might not be available).

I also have the same problem, anything new?

**Comment by SchenbergZY** [comment]
My question is: is there a possible method to add some customer tokens at the end of an existing model with all score 0?

**Comment by gyc913** [comment]
I have the same question with SchenbergZY  and kpe.

**Comment by taku910** [comment]
You can rewrite the model file to add new user defined symbols. It is also possible to rewrite the id<->piece mapping.

https://github.com/google/sentencepiece/issues/398

**Comment by s4sarath** [comment]
In the case of ALBERT, they have not provided model.proto . They have only provided .model and .vocab files only. I tried to manually add tokens to .model file, but then it cause some issue https://github.com/google/sentencepiece/issues/296 . 

Basic need is to add some more SPECIAL_TOKENS as per new task.

**Comment by s4sarath** [comment]
@SchenbergZY - Have you find a hack regarding this. If anything please do update, if you don't mind. Thanks. :-)

**Comment by taku910** [comment]
The proto is a DSL and found at
https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto

> protoc --python_out=. sentencepiece_model.proto

**Comment by s4sarath** [comment]
My bad. I took sometime to figure it out. :-) .

**Comment by imen185** [comment]
Hello,
Is it possible to define a pattern with user-defined symbols that I don't want to tokenize? For example, I don't want to tokenize any words starting with a '$' symbol. I also want to understand how decoding works because currently, all the words I define with user-defined symbols are assigned the ID 0.
Thank you!

**Comment by hardtoname1002** [comment]
> 
Hello,
I'm confused about the sentence: "Control symbols must be inserted outside of the SentencePiece segmentation." Could you please explain this in detail, Thanks!

**Comment by coezbek** [comment]
I was able to update a sentencepiece tokenizer with the help of this Youtube Video: https://www.youtube.com/watch?v=Uzr553x1gdM

Run with uv. Or make sure you have the right protobuf version installed.

The gist of it:

```
# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "protobuf==3.20.3",
#     "sentencepiece",
#     "transformers",
# ]
# ///

import os
from transformers.convert_slow_tokenizer import import_protobuf
import sentencepiece as spm

# --- Start of user configuration ---

# 1. Path to your original SentencePiece model
original_model_path = "path/to/your/original.model"  # <--- CHANGE THIS

# 2. The single token you want to add (e.g., a special or control token)
new_token_to_add = "<NEW_TOKEN>"  # <--- CHANGE THIS

# 3. Path to save the new, extended model
new_model_path = "path/to/your/new.model"  # <--- CHANGE THIS

# --- End of user configuration ---

# Load the protobuf library
model_pb2 = import_protobuf()

# Create a new model proto object
m = model_pb2.ModelProto()

# Read and parse the original model file
try:
    with open(original_model_path, "rb") as f:
        m.ParseFromString(f.read())
except FileNotFoundError:
    print(f"Error: Original model not found at '{original_model_path}'")
    print("Please update the 'original_model_path' variable in the script.")
    exit()


print("--- Original Model ---")
print(f"Vocabulary size: {len(m.pieces)}")

# Check if the new token already exists
existing_pieces = {p.piece for p in m.pieces}
if new_token_to_add in existing_pieces:
    print(f"\nToken '{new_token_to_add}' already exists in the model. Aborting.")
else:
    # Create a new SentencePiece piece
    new_piece = model_pb2.ModelProto.SentencePiece()
    new_piece.piece = new_token_to_add
    new_piece.score = 0.0  # Scores are typically 0.0 for special/control tokens
    new_piece.type = 4     # 4 corresponds to the CONTROL type for special tokens

    # Add the new piece to the model's vocabulary
    m.pieces.append(new_piece)

    print("\n--- After Modification ---")
    print(f"Successfully added token: '{new_token_to_add}'")
    print(f"New vocabulary size: {len(m.pieces)}")

    # Write the modified model to a new file
    with open(new_model_path, "wb") as f:
        f.write(m.SerializeToString())
    print(f"New model saved to: {new_model_path}")

    # --- Verification Step ---
    print("\n--- Testing New Model ---")
    sp = spm.SentencePieceProcessor()
    sp.load(new_model_path)

    new_token_id = sp.piece_to_id(new_token_to_add)
    print(f"ID for the new token '{new_token_to_add}': {new_token_id}")

    test_sentence = f"This is a test with the {new_token_to_add}."
    encoded_ids = sp.encode_as_ids(test_sentence)
    print(f"Test sentence encoded as IDs: {encoded_ids}")
    print("Verification complete.")
```
