### ISSUE TITLE
[Question] Is NFKC normalization applied when a tsv rule is used?

### ISSUE THREAD

**Issue by ZJaume** [google/sentencepiece#427]
I noticed that, when using `spm_normalize` with a custom normalization tsv file, the NFKC normalization is not applied. If I use the custom rule on the training parameters, are both normalizations applied?

**Comment by taku910** [comment]
No, both are not applied. If you want to add both, just create new tsv by concatenating your tsv and nmt_nfkc.tsv
https://github.com/google/sentencepiece/blob/master/data/nmt_nfkc.tsv
