### ISSUE TITLE
Python 3.8 wheels for Windows

### ISSUE THREAD

**Issue by ahtik** [google/sentencepiece#429]
https://github.com/google/sentencepiece/releases/tag/v0.1.84 has all the Windows wheels for Python 3.5, 3.6, 3.7, but is missing Python 3.8.

Linux wheels for Python 3.8 do exist, so it's resuling in a bit of inconsistent installation experience between the platforms.

Please, would it be possible to include Python 3.8 Windows to the build matrix with the next release or even better, release the 3.8 Windows wheels for 0.1.84?

Huggingface Transformers depends on sentencepiece and looks like sentencepiece wheel is now the final component before it gets the full Python 3.8 support also under Windows. https://github.com/huggingface/transformers/issues/1802

**Comment by taku910** [comment]
v0.1.85 added support of Python3.8 on windows.
