### ISSUE TITLE
Internal: trainer_interface.cc(540) output->WriteLine(os.str())

### ISSUE THREAD

**Issue by Saltychtao** [google/sentencepiece#431]
Hello,
 I am using the bpe algorithm provided by the repository to segment the wikipedia text (about 5GB). The command I used is as follows:
`./spm_train --input=wikiclean.txt --model_prefix=wikiclean --vocab_size=32000 --model_type=bpe
`

However, after a long time run, the program threw an error when saving vocab:
```
bpe_model_trainer.cc(257) LOG(INFO) Added: freq=2725 size=31920 all=2696220 active=135254 piece=▁showcasing

bpe_model_trainer.cc(257) LOG(INFO) Added: freq=2721 size=31940 all=2696413 active=135447 piece=elan

trainer_interface.cc(507) LOG(INFO) Saving model: wikiclean.model

trainer_interface.cc(531) LOG(INFO) Saving vocabs: wikiclean.vocab

spm_train_main.cc(178) [_status.ok()] Internal: sentencepiece-master/src/trainer_interface.cc(540) [
output->WriteLine(os.str())]

Program terminated with an unrecoverable error.
```
I tried both the C++ version and python version and both threw the same error. Would you tell me what is the problem?

**Comment by taku910** [comment]
Do you have the write file permission or quota in the current directory? What happens when you run
```% echo foo > wikiclean.txt```

**Comment by Saltychtao** [comment]
Sorry for the late response, it seems that it is because I don't have write permission to the current directory. The problem has been solved after I got the write permission. Thanks a lot!
