### ISSUE TITLE
PyPI is missing 0.1.85 wheels for Python 3.6 and later

### ISSUE THREAD

**Issue by willfrey** [google/sentencepiece#433]
Could you please upload wheels for Python 3.6 and above? It appears that they're missing from the [files listed on PyPI](https://pypi.org/project/sentencepiece/#files) for the 0.1.85 release.

Thank you.

**Comment by taku910** [comment]
Sorry for the inconvenience. Uploaded.

**Comment by willfrey** [comment]
Thank you!
