### ISSUE TITLE
build subword dictionary MANUALLY

### ISSUE THREAD

**Issue by hahmyg** [google/sentencepiece#434]
Even though SentencePiece is based on a unsupervised model,
there are a way to build pre-defined subword set manually?

For example, add a suffix "-ing" manually.

**Comment by taku910** [comment]
You might be able to use user defined symbols.
https://github.com/google/sentencepiece/blob/master/doc/normalization.md

**Comment by taku910** [comment]
The link was incorrect. This is the correct link:
https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md
