### ISSUE TITLE
Would you please support BPE dropout?

### ISSUE THREAD

**Issue by zodiacR** [google/sentencepiece#435]
Hi Team,
Recently there is an interesting paper coming out from yandex: BPE dropout (https://arxiv.org/abs/1910.13267). This simple and effective method adopts a dropout technique over BPE, and demonstrates a competitive performance against subword regularization. I'm wondering whether this new technique can be incorporated into this repo.

Best
Zodiac

**Comment by taku910** [comment]
Yes, we've already implemented bpe dropout in the internal repository.  We will be merge them soon.

**Comment by zodiacR** [comment]
resolved

**Comment by stephanpeitz** [comment]
Hi, 

have the changes been merged yet?

Cheers,
Stephan

**Comment by rudvlf0413** [comment]
@zodiacR Hello, I also want to know whether this BPE dropout is merged or not.

**Comment by zodiacR** [comment]
I think not yet. I used the implementation from bpe github repo.

**Comment by zodiacR** [comment]
> @zodiacR Hello, I also want to know whether this BPE dropout is merged or not.

Not yet. I used the implementation from BPE github repo.

**Comment by taku910** [comment]
The latest release support BPE-dropout.
