### ISSUE TITLE
installation error !

### ISSUE THREAD

**Issue by chinayuyabin** [google/sentencepiece#436]
pip install sentencepiece
ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\brave\\AppData\\Local\\Temp\\pip-install-gu69yst7\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\brave\\AppData\\Local\\Temp\\pip-install-gu69yst7\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\brave\AppData\Local\Temp\pip-install-gu69yst7\sentencepiece\pip-egg-info'
         cwd: C:\Users\brave\AppData\Local\Temp\pip-install-gu69yst7\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\brave\AppData\Local\Temp\pip-install-gu69yst7\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "d:\python\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

python 3.5

**Comment by taku910** [comment]
Python3.5 on WIndows is not supported since SentencePiece v0.1.85. Please use older version or Python >= 3.6

**Comment by chinayuyabin** [comment]
Thanks a lot! Problem has been solved.------------------ 原始邮件 ------------------
发件人: "Taku Kudo"<notifications@github.com>
发送时间: 2019年12月26日(星期四) 中午1:18
收件人: "google/sentencepiece"<sentencepiece@noreply.github.com>;
抄送: "learnby"<952167295@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [google/sentencepiece] installation error ! (#436)



Python3.5 on WIndows is not supported since SentencePiece v0.1.85. Please use older version or Python >= 3.6
 
&mdash;
