### ISSUE TITLE
no valid symbol found

### ISSUE THREAD

**Issue by 5118Python** [google/sentencepiece#437]
![image](https://user-images.githubusercontent.com/14151451/71532211-4bc9b980-292d-11ea-8dda-d84bb11f2747.png)

**Comment by taku910** [comment]
This error is raised because BPE algorithm cannot find any new symbols. 
"all=65" means that only 65 pairs of new symbols are found in the queue. Probably the training data only contains the limited character combinations.

Possible workaround is to reduce ```--vocab_size```.
