### ISSUE TITLE
Extra piece preceding user_defined_symbol encoding

### ISSUE THREAD

**Issue by sarvghotra** [google/sentencepiece#438]
I trained a sentencepiece model with some `--user_defined_symbols` like **\<documenttitle\> \<main\> \<paragraph\>** etc. When I encode a sentence containing these symbols, there is always a `_` piece that appears as a **separate piece** preceding all user_defined_symbols in the encoding

**For e.g.**, encoding of **"\<documenttitle\> \<main\> \<paragraph\> how many points to win"** is 

**EncodeAsPiece:** [b'\xe2\x96\x81',  b'<documenttitle>',  b'\xe2\x96\x81',  b'<main>',  b'\xe2\x96\x81',  b'<paragraph>',  b'\xe2\x96\x81how',  b'\xe2\x96\x81many',  b'\xe2\x96\x81points',  b'\xe2\x96\x81to',  b'\xe2\x96\x81win']

**EncodeAsIds:** [19902, 8, 19902, 9, 19902, 10, 235, 460, 2854, 63, 1322]

My question is that is it a desired behavior to have `_` as a separate piece?

Thanks in advance.

**Comment by taku910** [comment]
This is expected, as sentencepiece doesn't distinguish normal Latin symbol and white spaces.

You can feed the input w/o whitespace around these special characters.

```<documenttitle><main><paragraph>how many points to win```


However, this also adds "_" at the beginning of the sentence.

if you want to fully control these special symbols, better to use "--control_symbols" instead.

The following Python code just insert these ids at the beginning.

```
id1 = sp.PieceToId("<documenttitle>")
id2 = sp.PieceToId("<main>")
id3 = sp.PieceToId("<paragraph>")

ids = [id1, id2, id3] + sp.EncodeAsPiece("how many points to win")
```
control symbols just reserve the ids.

**Comment by sarvghotra** [comment]
Thanks for the clarification.

A workaround that we found is to modify symbols as `--user_defined_symbols "\u2581<documenttitle>,\u2581<main>,\u2581<paragraph>"`

then a sentence like `<documenttitle> <main> <paragraph> how many points to win` is parsed just fine.
