### ISSUE TITLE
Is there a way to train on an in-memory corpus in Python?

### ISSUE THREAD

**Issue by pwsiegel** [google/sentencepiece#439]
This is a great library - thanks for all the hard work!

For both the CLI and the Python wrapper, the only documented way to train a new tokenizer is to specify a path to one or more text files containing the training corpus.  I am using the tokenizer as a step in the middle of a longer text processing pipeline (in Python), and so the corpus is in memory rather than in a file somewhere.  My workaround is to temporarily save the data to a file and then pass that filename to sentencepiece, but as I understand it the first thing sentencepiece does is load the file back into memory, so the workaround is a little silly.  Is there a better way?  I don't mind writing a little Cython or something if needed.

**Comment by taku910** [comment]
No at this moment, but we've received the same request. We think that loading from non-posix file system should be useful.

Let met close this issue, since it is duplicated:
https://github.com/google/sentencepiece/issues/292

**Comment by taku910** [comment]
FYI: 
https://github.com/google/sentencepiece/tree/master/python#training-without-local-filesystem

**Comment by pwsiegel** [comment]
Outstanding, thank you!
