### ISSUE TITLE
Specify the delimiter to segment the sentence at starting of training of BPE?

### ISSUE THREAD

**Issue by venkateshvayyavuru** [google/sentencepiece#441]
Hi,
I want specify the delimiter for splitting the sentence at starting of BPE training rather than utf-8 character sequence. 
Ex:
   c1-c2-c3-c4 c5-c6-c7-c8 c9-c10-c11-c12.
In this case delimiter is "-". The pairs are like (c1,c2) (c2,c3) and so on. Is there any option to specify the delimiter while training.    Please help me.

**Comment by taku910** [comment]
There is no option for that and maybe tricky to add this because it will affect large position of the current code especially dictionary lookup of unigram (default) model.
