### ISSUE TITLE
Get vocab and merges file from model file

### ISSUE THREAD

**Issue by andompesta** [google/sentencepiece#444]
There is a way to obtain the vocab file and the merges file from a .model file?

I'm using the python binding and I have a .model file, but I would like to obtain the original file vocab and merges generated during training.

**Comment by taku910** [comment]
Do you mean that you want to get some vocab list from .model file? If so, you can see these issues.
Model file is serialized protobuf data
#121
#323

**Comment by MysteryVaibhav** [comment]
@andompesta Did you figure out how to get the merges?

**Comment by kitkhai** [comment]
Hi @taku910 

To my understanding, a SentencePiece BPE model uses both the vocab and merge rules to tokenize. 

I think the OP is referring to the merge rules and not the vocab file. I can't seem to find how to extract & modify specifically the merge rules of a SentencePiece BPE model from the .model file

So is there a way to extract & modify the merge rules from the .model file?

**Comment by karpathy** [comment]
@andompesta @MysteryVaibhav fwiw i think it's possible to recover the merges from the vocab using the approach from here https://github.com/openai/tiktoken/issues/60

**Comment by jzhang533** [comment]
For those who are looking for a direct solution, there is a conversion script in [tokenizers](https://github.com/huggingface/tokenizers) library: https://github.com/huggingface/tokenizers/blob/main/bindings/python/scripts/sentencepiece_extractor.py, which I think is the simplest way to extract vocab and merge files from a .model file. 

here is an example:

```bash
python tokenizers/bindings/python/scripts/sentencepiece_extractor.py --provider sentencepiece --model tokenizer.model --vocab-output-path converted/vocab.txt --merges-output-path converted/merges.txt
```

the script is not shipped with tokenizers package, you need to clone the repository to use it.
