### ISSUE TITLE
Get sentencepiece vocab file from tf model

### ISSUE THREAD

**Issue by c00k1ez** [google/sentencepiece#446]
Hi!
Several days ago I had an interesting problem: there are some models in tfhub (e.g. Universal Sentence Encoder) with integrated preprocessing from ft.text and vocab file from sentencepiece.
Is it possible to get this vocab file from a model?

Thank you.

**Comment by morganmcg1** [comment]
+1 here

**Comment by taku910** [comment]
Universal sentence encoder and tf.text are independent project, so it is not clear what 'model' means in this context, but you can obtain the vocab from the sentencepiece's model file with python module.

```
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor()
>>> sp.Load('sp.model')
>>> for i in range(0, sp.GetPieceSize()):
...     print(sp.IdToPiece(i))
````
