### ISSUE TITLE
model mixes spanish Accents

### ISSUE THREAD

**Issue by cri5Castro** [google/sentencepiece#447]
hi there I'm training a tokenizer for spanish but the model are mixing the accents with the  ▁ resulting in things like : ▁́  and  _ a ar _́o n for instance. 

Notice that my spanish sentences are conformed by  words with accents as a separed char for example: 
museo arqueol´ogico de nic´opolis

the problem is the tokenizer are mixing the accents with the ▁ instead of treat them as a normal char

**Comment by taku910** [comment]
Please run spm_train with ```--user_defined_symbols=´``` so the accent is always treated as one character. You can pass multiple symbols in CSV.
