### ISSUE TITLE
Segmentation Fault loading USE Xling Embeddings with TF==1.15.0

### ISSUE THREAD

**Issue by jasonw247** [google/sentencepiece#448]
I am running into a seg fault when loading :

universal-sentence-encoder-multilingual-large/1 or universal-sentence-encoder-xling-many/1

using Tensorflow 1.15.0

Environment:

pip freeze | grep -iE "tensor|sentence"
bert-tensorflow==1.0.1
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
tensorflow-hub==0.7.0
tf-sentencepiece==0.1.85
Error:

Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 21:14:29)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow_hub
>>> import tf_sentencepiece
>>> tensorflow_hub.Module('https://tfhub.dev/google/universal-sentence-encoder-xling-many/1')
Segmentation fault (core dumped)

I am able to load the module using tensorflow==1.14.0 and tf-sentencepiece==0.1.85, as specified at: https://github.com/tensorflow/hub/issues/345.

I have previously opened an issue with the Tensorflow Hub team at: https://github.com/tensorflow/hub/issues/490 where it was specified the underlying issue is an incompatibility between tf-sentencepiece and tf 1.15.

**Comment by taku910** [comment]
Could you try the latest version. I think this is already fixed.
