### ISSUE TITLE
can't access file on "My Drive", despite quotes change

### ISSUE THREAD

**Issue by j2l** [google/sentencepiece#450]
Hi,
`spm.SentencePieceTrainer.Train('--input=/content/drive/My Drive/base.txt --model_prefix=base --vocab_size=3200 --character_coverage=1.0  --model_type=unigram')`
I tried to change quotes to "
I also tried to inject it as a variable:
```
path = "/content/drive/My Drive/narniachar.txt"
'+path+'
```
I also tried to escape it with \\
But it splits at the space in "My Drive" and stops.

How to use senetenpiece within python with "My Drive"?
Thanks

**Comment by taku910** [comment]
At this moment, you cannot use the file path containing white spaces.

**Comment by Serbernari** [comment]
Is there some workaround to use sentencepice in Colab?

**Comment by Serbernari** [comment]
@j2l 
Found a workaround! You can do "cd" in google collab, but is not "!cd", how you could expect but "%cd". For example "%cd ./gdrive/My\ Drive/MyAwesomeFolder/"

**Comment by taku910** [comment]
https://github.com/google/sentencepiece/releases/tag/v0.1.9

New API support to feed (multiple files) as python kwargs.

```
spm.SentencePieceTrainer.train(input=['foo bar.txt', 'bar buzz.txt'], model_prefix='m')
```
