### ISSUE TITLE
what do these two logs mean? Thanks

### ISSUE THREAD

**Issue by gaoxuezhao** [google/sentencepiece#454]
bpe_model_trainer.cc(166) LOG(INFO) Updating active symbols. max_freq=3276 min_freq=42

bpe_model_trainer.cc(257) LOG(INFO) Added: freq=3276 size=16020 all=20688530 active=1034409 piece=土天天风之旅忍者角色分析今天

**Comment by taku910** [comment]
Updating active symbols. max_freq=3276 min_freq=42

In the all BPE's merge, candidates, emits the candidate with max/min frequency.

 Added: freq=3276 size=16020 all=20688530 active=1034409 piece=土天天风之旅忍者角色分析今天

piece=土天天风之旅忍者角色分析今 is added.
The frequency is 32760,  the current vocab size is 16020, # of all BPE"s merge candidates is 20688530, the active candidate is 1034409.

"active" means that top frequent candidates and we only take the best one only from them to make the training faster.
