### ISSUE TITLE
Question: BPE & Unicode Points

### ISSUE THREAD

**Issue by jchwenger** [google/sentencepiece#455]
Hi,
Thanks for this great library! I've started experimenting with it and find it really efficient and easy to use.

I have one technical/theoretical question, and perhaps someone here might be able to give me some pointers.

I have been looking at OpenAI's GPT-2, and their choices for BPE. Especially this bit:

> Despite its name, reference BPE implementations often operate on Unicode code points and not byte sequences. These implementations would require including the full space of Unicode symbols in order to model all Unicode strings.  [...] In contrast, a byte-level version of BPE only requires a base vocabulary of size 256. However,directly applying BPE to the byte sequence results in suboptimal merges due to BPE using a greedy frequency based heuristic for building the token vocabulary. [...] This results in a suboptimal allocation of limited vocabulary slots and model capacity. To avoid this, we prevent BPE from merging across character categories for any byte sequence. We add an exception for spaces which significantly improves the compression efficiency while adding only minimal fragmentation of words across multiple vocab tokens.

I then found this line in your Readme:
> By default, SentencePiece normalizes the input with Unicode NFKC.

I'm researching this at the moment, but is that a hint that sentencepiece works in this way, i.e. working at a byte-level with the appropriate caveats for cross-categories merges? 

Thanks a lot in advance!

**Comment by taku910** [comment]
Byte-level fallback feature is already implemented internally. Not sure when we can merge, but hope it will be available soon.

**Comment by jchwenger** [comment]
Grand, I hope so too!

**Comment by danielinux7** [comment]
@taku910 Is this Byte-level fallback feature available yet? If so how can I use byte-level instead of char-level BPE?
