### ISSUE TITLE
Library version selection breaks for TF 2.1

### ISSUE THREAD

**Issue by jjedele** [google/sentencepiece#456]
The regex to looking for the most recent library version if no exact match is found extracts the whole match instead of the version number. This leads to the .so extension being duplicated.

Produces:
UserWarning: No so file is found for [2.1.0] from [so.1.15.0, so.1.14.0, so.2.0.0, so.1.13.1]
Should be:
UserWarning: No so file is found for [2.1.0] from [1.15.0, 1.14.0, 2.0.0, 1.13.1]

I'll fix and open a PR right away.

**Comment by jjedele** [comment]
Hmm, somehow GitHub doesn't let me create a PR for this repo (error 500).

Here's the fix of somehow wants to pull or just fix it here: https://github.com/jjedele/sentencepiece/commit/4d050563cebeaee5e21f91597af5b12c61dacf07

**Comment by JLHasson** [comment]
For what it's worth I am also seeing this on `tf-sentencepiece==0.1.85`.

```
File "/Users/lancehasson/miniconda3/envs/<package>/lib/python3.6/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/lancehasson/miniconda3/envs/<package>/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.so.2.0.0, 6): image not found
```

Selected file should be `_sentencepiece_processor_ops.so.2.0.0` not `_sentencepiece_processor_ops.so.so.2.0.0`, which is the file that does indeed exist:

```
$ ls -lh /Users/lancehasson/miniconda3/envs/<package>/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0
-rwxr-xr-x  1 lancehasson  staff   814K Mar 20 13:39 /Users/lancehasson/miniconda3/envs/<package>/lib/python3.6/site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.2.0.0
```

@taku910 any chance we can get someone to take a look at #457?

**Comment by taku910** [comment]
Fixed. Please try the latest version.
