### ISSUE TITLE
How to deal with space in custom symbols?

### ISSUE THREAD

**Issue by houwenxin** [google/sentencepiece#459]
spm.SentencePieceTrainer.Train(" ".join(args)) reports error when there is a space in the middle of custom symbols (like --user_defined_symbols=\<IS MAN\>). The function cut the arguments by the space.

Is there any solution to this problem?

**Comment by houwenxin** [comment]
Other issue indicates that it can be replaced with <IS_MAN>, but I am wondering could this be useful when the symbols in the source text remain <IS MAN>?

**Comment by taku910** [comment]
Please take a look at #467, though it is for user_defined_symbols.
In addition, space is basically replaced into meta character '_' internally, so it is not recommended to use them.

**Comment by taku910** [comment]
https://github.com/google/sentencepiece/releases/tag/v0.1.9

New API supports to feed arbitrary symbols.

```
spm.SentencePieceTrainer.train(input="foo.txt", model_prefix='m', vocab_size=1000, user_defined_symbols=['<IS MAN>', 'FOO bar', ","])
```
