### ISSUE TITLE
Encounter error message while load the pacakge:

### ISSUE THREAD

**Issue by saravanansaminathan** [google/sentencepiece#460]
I encounter the same problem with error message:

dlopen(/Users/...../site-packages/tf_sentencepiece/_sentencepiece_processor_ops.so.so.2.0.0, 6): image not found

Version installed within virtualenv:
- TensorFlow: 2.1.0
- tf-sentencepiece 0.1.85

OS: MacOS 10.15.2

_Originally posted by @RogerChu8 in https://github.com/google/sentencepiece/issues/309#issuecomment-592318076_

**Comment by taku910** [comment]
Fixed. Please try the latest version.
