### ISSUE TITLE
Query in subword regularization, in readme.

### ISSUE THREAD

**Issue by rossbrown9879** [google/sentencepiece#461]
Following line is mentioned at the beginning of Subword regularization in README.md. 

>To enable subword regularization, you would like to integrate SentencePiece library (C++/Python) into the NMT system to sample one segmentation for each parameter update, which is different from the standard off-line data preparations

What do author mean by "to sample one segmentation for each parameter update, which is different from the standard off-line data preparations". What parameter update is he talking about? Also I did not get anything about standard off-line data preparations.

**Comment by taku910** [comment]
The 'parameter' means that the weights of neural-based NLP systems, like NMT.
For more detail please see https://www.aclweb.org/anthology/P18-1007.pdf
