### ISSUE TITLE
Train model on large MS-MARCO corpus. 

### ISSUE THREAD

**Issue by rossbrown9879** [google/sentencepiece#463]
I'd like to train a sentencepiece model on MSMARCO corpus. The format of the corpus is `docid <tab> URL <tab> Query <tab> Document`. Now the real sentences in my corpus file are Query and Document lines. Is it possible to iteratively train a sentence piece model on lines (queries/documents) one by one? I tried training my model directly using

`spm_train --input=msmarco-docs.tsv --model_prefix=ir_model --vocab_size=30000 --character_coverage=1.0`

My model is starting to train, but I'm getting following warnings at the beginning.
```
trainer_interface.cc(267) LOG(INFO) Loading corpus: msmarco-docs.tsv
trainer_interface.cc(287) LOG(WARNING) Found too long line (6120 > 4192).
trainer_interface.cc(289) LOG(WARNING) Too long lines are skipped in the training.
trainer_interface.cc(290) LOG(WARNING) The maximum length can be changed with --max_sentence_length=<size> flag.
```

Now as determined in warning, training in this way skips some of the long lines. I guess this method will skip most of my documents, since they are all represented as a single line in MSMARCO dataset. I don't want to let my documents getting skipped. Does anyone have a better solution here? MS-MARCO dataset is a huge dataset of query-document pairs, with size of 22 gigs. Does anyone have idea on how long it should take to train a model on this huge dataset on i5 8th gen intel laptop with 8GB memory? Thanks in advance :)

**Comment by taku910** [comment]
You can increase the length with `--max_sentence_length=100000`. 
In addition, i`--input_sentence_size=1000000` will randomly sample 1000000 sentences for training so you can train the model with smaller memory.

**Comment by rossbrown9879** [comment]
@taku910  Thank you so much for this idea about `input_sentence_size`. I see that the model logs line like `Loaded 1000000 lines`, and on my device, this logging went up to 130 million sentences, 
and then crashed probably due to memory limit (I have 16 GB ram). I expect nearly 200 million sentences in my corpus. 
So, If I do `--input_sentence_size=1000000`, then I understand that it will randomly sample 1 million sentences at time, but how can I determine the number of epochs of such sampling. Training only 1 million sentences out of 200 million will not give better results right? I think my model should randomly sample 1 million sentences for roughly 200 times, to give overall good expected performance. Is there any way to tell my model to repeat this sampling for some `n` number of times? And thank you so much again, your library is really amazing.
