### ISSUE TITLE
module 'sentencepiece' has no attribute 'SentencePieceTrainer'

### ISSUE THREAD

**Issue by rossbrown9879** [google/sentencepiece#464]
I'm getting following error, when I run sentence piece trainer in python.

```
AttributeError                            Traceback (most recent call last)
<ipython-input-2-8589c63acb87> in <module>
----> 1 spm.SentencePieceTrainer.Train('--input=tx2.txt --model_prefix=m --vocab_size=1000')

AttributeError: module 'sentencepiece' has no attribute 'SentencePieceTrainer'
```

I'm running following code:

```
import sentencepiece as spm

spm.SentencePieceTrainer.Train('--input=tx2.txt --model_prefix=m --vocab_size=1000')
```

**Comment by taku910** [comment]
Probably you are loading python module which were installed with the previous (incompatible) version.

Please try
```
>pip uninstall sentencepiece
>pip install sentencepiece
```

**Comment by RulinShao** [comment]
> Probably you are loading python module which were installed with the previous (incompatible) version.
> 
> Please try
> 
> ```
> >pip uninstall sentencepiece
> >pip install sentencepiece
> ```

I tried but still got this error when I'm trying the huggingface example:
`````
from transformers import AutoTokenizer, AutoModelWithLMHead

tokenizer = AutoTokenizer.from_pretrained("hfl/chinese-xlnet-base")

model = AutoModelWithLMHead.from_pretrained("hfl/chinese-xlnet-base")

inputs = tokenizer("Hello, my dog is cute", return_tensors="pt")
outputs = model(**inputs)

last_hidden_states = outputs[0]  # The last hidden-state is the first element of the output tuple
```

**Comment by johncwok** [comment]
Got the same issue:
```
    spm.SentencePieceTrainer.train('--input=sentencepiece_train_string.txt --model_prefix=model_size500 --vocab_size=500')

AttributeError: module 'sentencepiece' has no attribute 'SentencePieceTrainer'
```
I uninstalled and re-installed but it didn't help.

**Comment by Charity333333333** [comment]
The problem I'm having is:
AttributeError: partially initialized module 'sentencepiece' has no attribute 'SentencePieceProcessor' (most likely due to a circular import)
It's because there is a sentencepiece file in my folder, which causes a call error
So I re-run the program in another folder

**Comment by NewNLPer** [comment]
yeah，i also get this problem，**AttributeError: partially initialized module 'sentencepiece' has no attribute 'SentencePieceTrainer' (most likely due to a circular import)**，But I created a new file and solved this problem

**Comment by NikolaySitnikov** [comment]
What new file did you create @NewNLPer ? I am having the same issue
