### ISSUE TITLE
how to add comma ',' to user_defined_symbols

### ISSUE THREAD

**Issue by gaoxuezhao** [google/sentencepiece#467]
how to add comma ',' to user_defined_symbols

**Comment by taku910** [comment]
At this moment, we cannot pass "," as long as using spm_train CLI tool.

C++ API accepts TrainerProto that can encode arbitrary string as user_defined_symbols.

https://github.com/google/sentencepiece/blob/master/src/sentencepiece_trainer.h#L30

You can take a look at spm_trian_main.cc as it makes the TrainProto from command line flags.
https://github.com/google/sentencepiece/blob/master/src/spm_train_main.cc#L161

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/issues/459

We can now use any strings as user_defined_symbols via python module.
