### ISSUE TITLE
Missing Mac OSX binaries for Python 3.8

### ISSUE THREAD

**Issue by kynan** [google/sentencepiece#469]
See https://pypi.org/project/sentencepiece/#files

Could you please add those?

**Comment by socmonitor** [comment]
+1

**Comment by zzj0402** [comment]
This bug is so annoying that it's getting personal.

**Comment by khellan** [comment]
I built my own wheel. You may download it from this gist: https://gist.github.com/khellan/e2d940017da279d718558cd3997c0e9f#file-sentencepiece-0-1-85-cp38-cp38-macosx_10_15_x86_64-whl

**Comment by ZeusFSX** [comment]
@khellan  thank you))

**Comment by taku910** [comment]
Added OSX py3.8 support from 0.1.86 https://pypi.org/project/sentencepiece/#files
