### ISSUE TITLE
No so file is found for [1.10.1] from [1.7.0, 1.13.1, 1.10.0, 1.11.0, 1.12.0, 1.9.0, 1.8.0]   ', '.join(versions)))

### ISSUE THREAD

**Issue by hazardwayne** [google/sentencepiece#471]
Could you please support tensorflow=1.10.1?

**Comment by taku910** [comment]
No, it only supports tf >= 1.13.1

You may be able to build tf_sentencepiece with this sh script. Please add ```build_tf_wrapper "1.10.0"```

https://github.com/google/sentencepiece/blob/master/tensorflow/make_py_wheel.sh
