### ISSUE TITLE
No module named '_sentencepiece'

### ISSUE THREAD

**Issue by ayusharora99** [google/sentencepiece#472]
I am trying to import sentencepiece to my jupyter notebook but I am running into an error on this line:

`import tokenization` 

because of this line in sentencepiece.py:

`return importlib.import_module('_sentencepiece')`

This is the error:

No module named '_sentencepiece'

**Comment by taku910** [comment]
Sorry, could you elaborate the error? it is hard to reproduce this error.

**Comment by taku910** [comment]
Let me close this bug, because this code doesn't follow the official instruction of sentencepiece.
