### ISSUE TITLE
Using `set_vocabulary` to modify vocabulary

### ISSUE THREAD

**Issue by sshleifer** [google/sentencepiece#474]
I am trying to use `set_vocabulary` to both change special tokens and add some tokens to the end of my vocab file. 

In the example below, set_vocabulary does not seem to have any effect. (In the real example, `new_vocab` is a much longer list and the behavior is identical).
Is that expected behavior?

I am open to manipulating `m.pieces` as in #121 , but I'm not clear on how to instantiate a new piece to append.

### Example Code:
The processor does not seem to be affected by `set_vocabulary`:

```python

#wget https://s3.amazonaws.com/models.huggingface.co/bert/facebook/mbart-large-en-ro/sentence.bpe.model

import sentencepiece as spm
vocab_file = 'sentence.bpe.model'
test_string = '▁de'

sp = spm.SentencePieceProcessor()
sp.load(vocab_file)
new_vocab = ['<s>', '▁de', '-']
print('encoded:', sp.encode_as_ids(test_string)) # 7
original_vocab = [sp.IdToPiece(id) for id in range(0, sp.GetPieceSize())]
sp.set_vocabulary(new_vocab)
v2 = [sp.IdToPiece(id) for id in range(0, sp.GetPieceSize())]
print('encoded:', sp.encode_as_ids(test_string)) # 7
assert v2 == original_vocab  # doesnt raise
assert v2 == new_vocab #=> AssertionError
assert v2 != original_vocab#  => AssertionError
```

Thanks!

**Comment by taku910** [comment]
set_vocab does not replace the vocabulary set, but mark "UNUSED" or "USED" mark to each vocab and enforce the segmentation not to "UNUSED" piece. This design allows us to reset the vocaburarly.

```sp.is_unused(vocab_id)``` will returns whether the vocab is used nor unsued.

**Comment by gjke** [comment]
@sshleifer I am also at the same spot, where I don't know how to instantiate a new `SentencePiece` to append to `pieces`. Do you have any tip?

**Comment by dddddjcole** [comment]
> set_vocab does not replace the vocabulary set, but mark "UNUSED" or "USED" mark to each vocab and enforce the segmentation not to "UNUSED" piece. This design allows us to reset the vocaburarly.
> 
> `sp.is_unused(vocab_id)` will returns whether the vocab is used nor unsued.

how to modify my vocabulary set

**Comment by fangzhangmnm** [comment]
> set_vocab does not replace the vocabulary set, but mark "UNUSED" or "USED" mark to each vocab and enforce the segmentation not to "UNUSED" piece. This design allows us to reset the vocaburarly.
> 
> `sp.is_unused(vocab_id)` will returns whether the vocab is used nor unsued.

Hello, can you give example on how to replace the vocab set? thanks!
