### ISSUE TITLE
No package for macOS for python 3.8

### ISSUE THREAD

**Issue by Kruszylo** [google/sentencepiece#479]
**MacOS: 10.14.6
Python 3.8.1**
currently there is no package for `python 3.8` for Mac. Workaround is: 

- download source code `tar.gz` ([v0.1.85](https://github.com/google/sentencepiece/releases/tag/v0.1.85))
- unpackage and install:
```
cd /path/to/surce/code/
tar xopf sentencepiece-0.1.85.tar
cd sentencepiece-0.1.85/python/
pip install .
```

**Comment by taku910** [comment]
Dup #469
