### ISSUE TITLE
How to get the frequency of a subword ?

### ISSUE THREAD

**Issue by liuyaox** [google/sentencepiece#480]
We know that in BPE algorithm, the frequency of subwords is used to iteratively update the model. After training the model, how can I get the frequency of a subword ?

I only found a function `sp.get_score(id)`, which obviously is not what I want.

BTW, anyone who can tell me what `sp.get_score(id)` means ?

**Comment by taku910** [comment]
Frequency is not kept in the model file as the BPE segmentation doesn't need the frequency.

`get_score(id)` does return logprob of the `id` when using the unigram model (default). You can get the unigram probability of the word by `exp(get_score(id))`.

`get_score(id)` in BPE returns the merge priority of the word for the sake of compatibilty.

**Comment by Piezoid** [comment]
Do BPE scores correspond to the positions/ranks of tokens in their frequency distribution?

I'm trying to approximate the frequencies from BPE's score by modeling the Zipf law on a text sample. However, the ranks from the BPE tokenizer (given by `-score`) are only weakly correlated to the ranks from the tokenized sample (wiki-text).

The tokenizer wasn't trained on that same corpus, but I wouldn't expect such a big difference:
The lowest scores from the BPE model are `▁t er in ▁a en on ▁th es ▁s ▁d at or an ▁c is re it ▁the ar le`,
while the most frequent tokens from wiki-text: `▁the ▁, ▁. ▁of ▁and ▁in ▁to ▁a ▁= ▁" ▁@ ▁was ▁\' ▁The ▁as ▁that ▁on ▁for ▁with ▁by`

Is my understanding of how BPE's ordering operates flawed?
