### ISSUE TITLE
Microsoft Visual C++ 14.0 isn't detected in conda environments

### ISSUE THREAD

**Issue by JGCoelho** [google/sentencepiece#482]
Ok, so i am trying to install transformers, and sentencepiece is a required package. I got transformers installed no problem on my default python 3.8, and was trying to install it on my python 3.5 conda environment. The issue is that when i run "pip install transformers" on the conda environment i get the following error message:

```bash
Building wheels for collected packages: sentencepiece
  Building wheel for sentencepiece (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\jgc\anaconda3\envs\tensorflow\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\JGC\\AppData\\Local\\Temp\\pip-install-bgwb_604\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\JGC\\AppData\\Local\\Temp\\pip-install-bgwb_604\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\JGC\AppData\Local\Temp\pip-wheel-bprwrdpd'
       cwd: C:\Users\JGC\AppData\Local\Temp\pip-install-bgwb_604\sentencepiece\
  Complete output (9 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.5
  copying sentencepiece.py -> build\lib.win-amd64-3.5
  running build_ext
  building '_sentencepiece' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads
```

Environment: Python 3.5.6 conda env on Windows 10. I have gone to https://visualstudio.microsoft.com/downloads/ and installed the build tools for Visual Studio.

**Comment by taku910** [comment]
Windows whl packages for python 3.5 is not uploaded to pypi site because 3.5 doesn't accept the latest feature of distutils. Could you download the whl packages from the release pages and install it manually?

https://github.com/google/sentencepiece/releases
