### ISSUE TITLE
SentencePiece for sentence boundary detection?

### ISSUE THREAD

**Issue by mustaszewski** [google/sentencepiece#483]
Hello,

rather than posting an issue, I'd like to ask whether SentencePiece can be used for the task of sentence segmentation (i.e. splitting raw text input into sentences). For my task in mind, only the sentence boundary detection would be required. I am interested in SentencePiece for this task because it is language agnostic and trainable.
Thank you very much for you reply, best regards!

**Comment by taku910** [comment]
I don't think SentencePiece itself can be used for sentence segmentation, as it is just a tokenizer. It would be possible to train ML-based segmenter from the sentencepiece tokens, but in this case, you might need to have manually annotated training data.
