### ISSUE TITLE
How should I change the value of a SentencePieceProcessor?

### ISSUE THREAD

**Issue by gyunggyung** [google/sentencepiece#485]
Hi, I want to change the value. 

Load a dictionary.
```
import sentencepiece as spm

sp = spm.SentencePieceProcessor()
sp.Load(tok_path)
```

Change from dictionary to desired.
```
test = {}
for id in range(sp.get_piece_size()):
    test[sp.id_to_piece(id)] = id

test["\n"] = test["<unused0>"]
del test["<unused0>"]
test["<|endoftext|>"] = test["<unused1>"]
del test["<unused1>"]
```

But I don't know what to do next. I'd like to set it up, but I don't know how. Help me.

![image](https://user-images.githubusercontent.com/26733242/80990160-ea809c80-8e70-11ea-9b63-caa95bb4aff1.png)

**Comment by taku910** [comment]
Sorry, I could not understand the issues. Could you elaborate it?

**Comment by gyunggyung** [comment]
How can I change the value of a dictionary made of essencepiece?

**Comment by gyunggyung** [comment]
And save `.spiece` file

**Comment by taku910** [comment]
Sentencepiece's dictionary is basically immutable. We do not assume that they are modified after training.

You can manually update the model file as your own risk-basis.
https://github.com/google/sentencepiece/issues/121

**Comment by gyunggyung** [comment]
Thx

2020년 5월 16일 (토) 오후 12:25, Taku Kudo <notifications@github.com>님이 작성:
