### ISSUE TITLE
Batch Processing

### ISSUE THREAD

**Issue by completelyboofyblitzed** [google/sentencepiece#486]
Hello!
Is there a way to process batches instead of sentences one by one? Otherwise it is very time consuming.

**Comment by ymoslem** [comment]
I second this request. Currently, to make things a bit faster, I either use `parallel` in bash or [multiprocessing](https://stackoverflow.com/a/20549090/7614380) in Python to train both directions (source and target) in parallel. Thanks for your effort!

**Comment by taku910** [comment]
v.0.1.97 supports multi-threaded batch processing. The process is executed in native threads.

```
sp = spm.SentencePieceProcessor(model_file='m.model')

with open('large.txt', 'r') as f:
   lines = f.readlines()

ids = sp.encode(lines)   # batch request.
```
