### ISSUE TITLE
How to remove "_" from the vocab terms of the trained model?

### ISSUE THREAD

**Issue by rossbrown9879** [google/sentencepiece#488]
I do not want "\_" in the vocabulary during training. I'm training the model just by providing the tsv file of tokens as input. How to get rid of "\_"?

**Comment by taku910** [comment]
`spm_train --add_dummy_prefix=false` will help. Please note that the input sentence must not include whitespaces. Otherwise, "_" is added to the vocab anyway.

**Comment by rossbrown9879** [comment]
@taku910 , Thank you, this worked. The problem of "_" is also found in `sp.EncodeAsPieces`, where it generates consecutive "_" tokens while tokenising. 
For example, when donig : 
`sp.EncodeAsPieces("i love natural language processing")`, I get following output 
```
>>> ['i', '_', 'love', '_', 'natural', '_', 'language', '_', 'processing']
```
Is there a way to get rid of them from this function as well?

**Comment by taku910** [comment]
You might want to encode word-by-word as follows.
Note that the the encoded result do not keep whitespace information -- we cannot reproduce the original sentence from the output as there are no distinction between subword and normal word.

```
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor(model_file='m.model')
>>> text = 'i love natural language processing'
>>> pieces=sum([sp.encode(s, out_type=str) for s in text.split(' ')], [])
>>> pieces
['i', 'lo', 've', 'natural', 'language', 'pro', 'ce', 's', 's', 'ing']
```

**Comment by jmeier-absci** [comment]
@taku910 How can we apply `spm_train --add_dummy_prefix=false` in the Python Wrapper? SentencePieceTrainer does not support an option called `add_dummy_prefix`. Thanks!
