### ISSUE TITLE
Working on folders (Training)

### ISSUE THREAD

**Issue by mainakmanna** [google/sentencepiece#489]
From the documentation, it is clear that the way to train over multiple files is to pass comma separated file names to the `input` (In case of python API) parameter. Is there any way we can process just from the folders instead or folder of folders? 

```
+----------+ f1
|
+-----+f2
|
+--> A.txt
|
+--> B.txt
|
+-----+f3
|
+--> C.txt
```

For this kind of situation we have to pass `input=./f1/f2/A.txt,./f1/f2/B.txt,./f1/f3/C.txt`. More specifically 
```
import sentencepiece as spm
spm.SentencePieceTrainer.Train('--input=./f1/f2/A.txt,./f1/f2/B.txt,./f1/f3/C.txt --model_prefix=m --vocab_size=64000')
```
1. Is there any better way of handling this?
2. Is there any plan to include this as a feature later?

**Comment by taku910** [comment]
You might want to use glob module

```
import glob

files = ','.join(glob.glob('f1/*/*.txt'))

spm.SentencePieceTrainer.Train('--input={}...'.format(files, ...)
```

By the way, from v0.1.90, Train method accepts kwargs style argument, which accept list of files.

```
spm.SentencePieceTrainer.Train(input=glob.glob('f1/*/*.txt'), vocab_size=10000, model_prefix='m')
```

**Comment by lcp580** [comment]
thank you very much
