### ISSUE TITLE
I want to use sentencepiece command (spm_encode) in google colaboratory

### ISSUE THREAD

**Issue by pdc-kaminaga** [google/sentencepiece#490]
Hi,

I want to use sentencepiece command (spm_encode) in google colaboratory.
I ran make and got 'CMake Error: cmake_symlink_library: System Error: Operation not supported'.
!make -j $(nproc)
[  8%] Built target sentencepiece_train-static
[  9%] Linking CXX shared library libsentencepiece.so
[ 44%] Built target sentencepiece-static
CMake Error: cmake_symlink_library: System Error: Operation not supported
CMake Error: cmake_symlink_library: System Error: Operation not supported
src/CMakeFiles/sentencepiece.dir/build.make:638: recipe for target 'src/libsentencepiece.so.0.0.0' failed
make[2]: *** [src/libsentencepiece.so.0.0.0] Error 1
make[2]: *** Deleting file 'src/libsentencepiece.so.0.0.0'
CMakeFiles/Makefile2:106: recipe for target 'src/CMakeFiles/sentencepiece.dir/all' failed
make[1]: *** [src/CMakeFiles/sentencepiece.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

How do I install sentencepiece in google colaboratory ?

**Comment by taku910** [comment]
You might want to use python wrapper instead. That would be more useful especially on google colab.

https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
