### ISSUE TITLE
TypeError: SentencePieceTrainer_train() takes no keyword arguments

### ISSUE THREAD

**Issue by cifkao** [google/sentencepiece#495]
I installed the Python package with `pip`. When I try to call `SentencePieceTrainer.train()`, I get the following error: `TypeError: SentencePieceTrainer_train() takes no keyword arguments`

**Comment by taku910** [comment]
train methods requires arguments to specify training data and output model.

https://github.com/google/sentencepiece/tree/master/python#model-training

**Comment by cifkao** [comment]
Sorry, I realized I had installed an older version of sentencepiece, which expected an arg string, and not the keyword arguments. The most recent version works fine.

**Comment by taku910** [comment]
I think the new version still supports single-string arg.

**Comment by cifkao** [comment]
Yes, the problem was I tried to pass keyword arguments to the old version (that's what the error says).
