### ISSUE TITLE
Deterministic sentencepiece model

### ISSUE THREAD

**Issue by alvations** [google/sentencepiece#496]
Following-up on https://github.com/marian-nmt/marian-dev/issues/657 

**Is there a way to control such that the sentencepiece model trained with the same data and settings to output the same model?**

**Comment by taku910** [comment]
I think sentencepiece is reproducible. Same model file is reproduced when using the same model.
Please let me know if you find non-deterministic behavior.

**Comment by taku910** [comment]
Let me close this bug, as we have no follow up thread.
