### ISSUE TITLE
How to make several characters as a whole 'character' (not token or piece) ?

### ISSUE THREAD

**Issue by liuyaox** [google/sentencepiece#498]
Is there any way that I can make several characters as a whole 'character' (not token or piece in user-defined symbols).  

I mean, the several characters can always be dealt with as a whole, and they can be either a token or a part of other token, but they will never be split, just like a character. For example, 

The several characters is "it's"

Input text is "it's okay and..."

The result is "▁it ' s▁okay ▁and..."  (Note that there are whitespaces after "it" and before "s")

Expected result is that "it's" is not split into 3 parts and "it's" can be a token or a part of a token, for example, "▁it's▁okay ▁and..."(there is only one whitespace after "okay") or "▁it's ▁okay ▁and..."(there are 2 whitespaces after "it's" and after "okay")

Thanks !

**Comment by taku910** [comment]
It would be difficult unless the pieces with your constraint can generate closed set of words (can enumerate all possible pieces in advance).  We cannot introduce any constraint to concat any characters, as they would increase the number of vocab.  It violates the philosophy of subwording.

#https://github.com/google/sentencepiece/issues/493
