### ISSUE TITLE
Sentencepiece input file format

### ISSUE THREAD

**Issue by working12** [google/sentencepiece#499]
I am training sentencepiece model from a text file. The file consists of line lines separated by `\n`. And it contains multiple logical sentences. Now if the portion separated by `\n` is lengthy, then will it be a problem? How to check if my input file is good enough for training or whether the training was successful or not?

**Comment by taku910** [comment]
The input looks good to me. Sentencepiece basically assumes that one-line-one-sentence text file. However, it would be basically okay that one line has multiple sentences unless the length is less than around 4000 bytes. By default, sentencepiece trainer will discard long lines to train.
