### ISSUE TITLE
make install passes, but am unable to run spm

### ISSUE THREAD

**Issue by rpryzant** [google/sentencepiece#5]
I followed all the installation steps without a hitch. 

`make` passes, as does `make check` and `sudo make install`.

However, when I try to run `spm_train`, `spm_decode`, or `spm_encode`, I get the following error message:

```
spm_train: error while loading shared libraries: libsentencepiece.so.0: cannot open shared object file: No such file or directory
```

I am running Ubuntu 16.04.2.

**Comment by taku910** [comment]
Please try "sudo ldconfig -v"

**Comment by rain1024** [comment]
This error occurred to me too. 'ldconfig -v' fixed it.

@taku910 : you may add `ldconfig -v` at installation section in README.md

**Comment by rpryzant** [comment]
Thanks all! 

Don't have access to my Ubuntu box now but will report on this later today.

**Comment by rpryzant** [comment]
Thanks all! `sudo ldconfig -v` did the trick.

**Comment by taku910** [comment]
Updated README.md. Thanks.

**Comment by abhirut** [comment]
Is there anyway to do this without sudo?
