### ISSUE TITLE
Unknown Field Name Error

### ISSUE THREAD

**Issue by Uncertain-Quark** [google/sentencepiece#501]

**Comment by Uncertain-Quark** [comment]
I am trying to run the spm_train on a Hindi text transcript. However, I am encountering the below error. 

OSError: Not found: unknown field name "�ा�प" in TrainerSpec.

I am relatively new using sentence piece. Any help to resolve it would be appreciated. I would like to apologise if such query was already sorted.

**Comment by taku910** [comment]
Could you elaborate the error message? including command line, training data you used, the piece of Python code. Otherwise, hard to identify the root cause.

**Comment by taku910** [comment]
Let me close this bug as we don't have updates sor far. Please reopen it if ncessary.
