### ISSUE TITLE
Line length limit when using Python module

### ISSUE THREAD

**Issue by johntmyers** [google/sentencepiece#502]
When using the Python module, when a line is too long, this error is logged out and the process aborts:

`RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/trainer_interface.cc(336) [!sentences_.empty()]`

When I adjust the max length using `max_sentence_length` things work. Why do we receive the above error instead of the other warnings?

I've attached sample input data.

This is running on v 0.1.91

[wide.csv.zip](https://github.com/google/sentencepiece/files/4726336/wide.csv.zip)

**Comment by taku910** [comment]
Probably all sentences in the corpus exceeds the length limit, then the input sentences get empty. 
The error message is raised when the input corpus is empty.

**Comment by johntmyers** [comment]
Ok, that is the case then. The warnings were not printed out so I was not sure.
