### ISSUE TITLE
Support custom tokens, symbols

### ISSUE THREAD

**Issue by zhangguanheng66** [google/sentencepiece#503]
For the vocab in sentencepiece, is there a way to insert some custom tokens and symbols (for example `<pad>`, `<sep`>) in the vocab? And to make spm work for some pretrained models, we want to use the old vocab as well.

For our usage case, we use spm to convert strings into a list of ids as a single step.

**Comment by taku910** [comment]
Please see this document. there are user defined symbols and control symbols.
https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md
