### ISSUE TITLE
unk_surface always

### ISSUE THREAD

**Issue by codekali** [google/sentencepiece#510]
Hi, 

I'm tuning a T5-transformer model for my source code summarization. The ```T5Tokenizer``` provided by ```huggingface``` is good but sometimes it produces an irrelevant result. I'm trying to make my own tokenizer using sentencepiece. But an issue happens whenever I use my custom spiece model, when I decode the output generated by the transformer model, it always sticks a unk_surface ```⁇```at the beginning, the rest of the string is ok ok.

```
custom  = T5Tokenizer.from_pretrained('spiece.model')
input = custom.encode("move the cursor down and return its position", return_tensors="pt")
out = model.generate(input)
custom.generate(out[0])
```

This code produces:
```
' ⁇  the cursor down the cursor down the cursor down the cursor down the cursor down the cursor down the'
```

I've created the sentencepiece model using this code snippet:
```
import sentencepiece as spm

params = ("--input=vocab.txt --model_prefix=spiece --vocab_size=35000 --hard_vocab_limit=false")

spm.SentencePieceTrainer.Train(params)
```

**Comment by taku910** [comment]
Please try the following

```
import sentencepiece as spm
sp = spm.SentencePieceProcessor(model_file='spiece.mode')
sp.decode(sp.encode('this is a test'))
```
You will see the same text ('this is a text'), which is the expected behavior.
If not, probably this is not a issue of sentencepiece.

**Comment by codekali** [comment]
Thanks @taku910. I figured out the problem. It was not an issue of sentencepiece. The model was pre-trained on a vocabulary which had words not present in my vocabulary of the spiece model. So the spiece model couldn't decode it and passed an unknown token.
