### ISSUE TITLE
SentenceIterator and trainer_spec.input() must be exclusive.

### ISSUE THREAD

**Issue by Srj** [google/sentencepiece#511]
```
import sentencepiece as spm
params = ('--input=./bn.txt ','--model_prefix=spm','--vocab_size=30000')
spm.SentencePieceTrainer.Train(params)
```
the size of bn.txt is 10.8 G and i am trying to train it on colab. It throws following error.
`
RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(311) [(sentence_iterator_ != nullptr && trainer_spec_.input().empty()) || (sentence_iterator_ == nullptr && !trainer_spec_.input().empty())] SentenceIterator and trainer_spec.input() must be exclusive.`

**Comment by taku910** [comment]
Train accepts either one string or kwargs.

Please try

```
spm.SentencePieceTrainer.train(input='/bn.txt', model_prefix='spm', vocab_size=30000)
```

**Comment by Srj** [comment]
Solved.
