### ISSUE TITLE
undefined symbol: FLAGS_minloglevel

### ISSUE THREAD

**Issue by lefterav** [google/sentencepiece#513]
Running the latest version 0.1.92 gives me the following error. 

`spm_decode: symbol lookup error: spm_decode: undefined symbol: FLAGS_minloglevel`

versions 0.1.91 and 0.1.90 give this error:

`spm_decode: symbol lookup error: spm_decode: undefined symbol: _ZN13sentencepiece5flags21ParseCommandLineFlagsEPKcPiPPPcb`

the only version I could run was 0.1.86

**Comment by lefterav** [comment]
Could it be related to #492 ?

**Comment by taku910** [comment]
Right. I reopend #492. and makr this issue as duplicate.

**Comment by taku910** [comment]
Fixed the issue in v0.19.3. Thank you.
