### ISSUE TITLE
Leftover "▁" characters after spm_decode

### ISSUE THREAD

**Issue by lefterav** [google/sentencepiece#514]
After running spm_decode v0.1.86 on the BPE-encoded output of neural machine translation,  special characters "▁" appear connecting some words. I assume that spm_decode should have removed them. Could you please explain why this is occurring and how I can fix it?

example:

before:

`▁The ▁film ▁service ▁calls ▁the ▁film ▁a ▁“ s imp ly ▁kn it ▁com edy ▁of ▁the ▁p ole ▁that ▁shows ▁the ▁un in hib ited ▁ra ge ▁of ▁destruction ▁of ▁children ▁without ▁thought ▁and ▁without ▁a ▁sense ▁of ▁ped agog ical ▁undert ones .”`

after:

`The film service calls the film a “simply▁knit comedy of the pole that shows the uninhibited rage of destruction of children without thought and without a sense of▁pedagogical▁undertones.”`

**Comment by JiayiFu** [comment]
Hi @lefterav , I have a naive question: how can vim show the symbol "▁"? I tried to use vim to open the text file but the positons of "▁"are some messy codes like:�~V~A.

**Comment by taku910** [comment]
I guess that model (vocab) file mismach happen -- the token '▁kn' may not be included in the vocab.

Please try
```
import sentencepiece as spm.
sp = spm.SentencePieceProecssor(model_file='model.file')
print(sp.is_unk(sp.piece_to_id('▁kn'))
```

If this returns True, the model file the NMT uses is different from the current model.

**Comment by sh0416** [comment]
Is there any other way to do this in bash?

**Comment by xiefangqi** [comment]
Maybe we can check with this command:
echo "▁kn" | spm_decode --model=your.model --input_format=piece
option 1: If result is still "▁kn" indicates that kn does not exist in the vocab
option 2: If result is "kn" indicates that kn exist in the vocab.

**Comment by taku910** [comment]
Seems that this issue is already resolved. Let me close it.
