### ISSUE TITLE
Allow regex for user-defined symbols

### ISSUE THREAD

**Issue by villmow** [google/sentencepiece#518]
Hi, 

thanks for this nice library. Is it possible to provide regular expressions for tokens that should remain single tokens? For example: 
`"<\w>"`

This is supported by subword-nmt (called glossaries), but I didn't find something like this in sentencepiece.

Thanks for your help

**Comment by taku910** [comment]
In general, it is hard to include a constraint that may increase the number of vocab.  In sentencepiece, the number of vocab is strictkly pre-determined. When we introduce a regexp to concat all digits, e.g. (\d+),  we can expect that the unique number of vocab would be larger than the vocab size. Also, we are not sure how to handle the digts that only appear in the test data.

On the other hand, subword-nmt does not have the vocab size constraint, but has the number of merge oprations. Subword-nmt doesn't manage the vocab <-> id mapping. User needs to construct the mapping from the segmented text. So, the situation is different.

Practically, you might want to explicitly extract the set of user defined symbols with regexp as a preprocessing, and pass them to sentencepiece.

**Comment by villmow** [comment]
Thanks, seems reasonable to me.

I have another unrelated question:

I need to tokenize "sentences" containing spaces, tabs, newlines and other control characters. 

I read that when training from file there should be one sentence per line. Is this different when training with `sentence_iterator`? How should I handle the special characters? Escape them manually before training sentencepiece?
