### ISSUE TITLE
Training Creates Float Number Vocab

### ISSUE THREAD

**Issue by Yanmarka** [google/sentencepiece#519]
When training on the data/botchan.txt fle, my vocab file looks like this:

\<unk>	0
\<s>	0
\</s>	0
,	-3.24863
.	-3.38172
▁the	-3.40852
▁I	-3.69947
▁to	-3.91285
s	-3.92535
▁a	-4.04742
▁and	-4.11791
▁of	-4.12551
▁	-4.18102
ed	-4.26836
ing	-4.29098
▁in	-4.56303
▁was	-4.62928
▁"	-4.65978
t	-4.75102
▁it	-4.80293
e	-4.87948
▁be	-4.9757
\-	-5.01115
▁that	-5.01613

and so on.
Command run: spm_train --input=botchan.txt --model_prefix=test --vocab_size=2000 --character_coverage=1.0 --model_type=unigram
This happens with other input files as well.

**Comment by taku910** [comment]
This is expected. The vocab file is a tsv file and the second colum is the logprob of token.
