### ISSUE TITLE
Is there any way to perform non-destructive tokenization?

### ISSUE THREAD

**Issue by Ryou0634** [google/sentencepiece#520]
I'm using the python wrapper of sentencepiece and want to preserve all the special characters such as newline characters, consecutive white spaces. However, the tokenizer automatically perform normalization for them and I cannot find an option to disable it.

**Additional Context**
I want to use sentencepiece for the task of question answering (https://github.com/google-research-datasets/tydiqa). For each example in the dataset, the answer span is specified by the unicode offset from the beginning of the paragraph. The automatic normalization of the special characters makes it unable to recover the original position information of each token.

**Comment by mingruimingrui** [comment]
Why not just pre-extract the sentences then join them back together again?

I think that this request is out of scope of this package.

**Comment by taku910** [comment]
please use normalization_rule_name=identity  to disable all normalizations (mainly NFKC)

Detail:
https://github.com/google/sentencepiece/blob/master/doc/normalization.md

**Comment by taku910** [comment]
If you are using Python module, you need to feed the sentences via iterator. As long as using file as input, "\n" is used as the sentence boundary.

Here's a sample code: This will allow to train the model from sentences containing return and consecutive spaces.

```
import urllib.request
import io
import sentencepiece as spm

input = []
with urllib.request.urlopen(
    'https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt'
) as response:
  for line in response:
      line = line.rstrip().decode()
      input.append(line.replace('x', '\n'))  # add dummy '\n' in the corpus

model = io.BytesIO()
spm.SentencePieceTrainer.train(
      sentence_iterator=iter(input), normalization_rule_name='identity', model_writer=model, vocab_size=1000)

# Serialize the model as file.
# with open('out.model', 'wb') as f:
#   f.write(model.getvalue())

sp = spm.SentencePieceProcessor(model_proto=model.getvalue())
print('id of return=', sp.piece_to_id('\n'))
print(sp.encode('This is\ntest\nfoo\nbar', out_type=str))
print(sp.encode('This is\ntest\nfoo\bar', out_type=int))
````
