### ISSUE TITLE
Possible to port underlying model to Java?

### ISSUE THREAD

**Issue by humzaiqbal** [google/sentencepiece#523]
Hi, I want to port the underlying Tensorflow model for `SentencePiece` to Java is it possible to do so? More specifically I want to take the `EncodeAsIds` function so I can take a String of text and get the tokenized IDs. I've started combing through the code and it isn't immediately obvious how to do so. I know two alternatives to a direct import would be to set up some sort of Python endpoint and do the computation in Python and send it back to Java or use JNI with the C++ code however for various reasons those aren't really options for me. Ideally if I could do something using Google's Java bindings to Tensorflow that would be ideal. Thanks much.

**Comment by taku910** [comment]
We are sorry, but we do not plan to support pure java binding at this time.
