### ISSUE TITLE
Could we don't consider the whitespace during the training phase.

### ISSUE THREAD

**Issue by Yunlongs** [google/sentencepiece#524]
I want to segment a sentence without any symbol concatenated , but the whitespace bother me some.
likes that `"wheninthecourseofhumaneventsitbecomesnecessary"`,I want it to be segmented with 
`['when', 'in', 'the', 'course', 'of', 'human', 'events', 'it', 'becomes', 'necessary']`.

But beacuse when you are train the sentencepiece model，`"_becomes" and "becomes", "_course" and "course"`, are seem as different tokens .
And we often only have` "_course" and "_becomes"`,not `"course" and "becomes"` in the sentencepiece's vocabulary. 

Then the `"wheninthecourseofhumaneventsitbecomesnecessary"` will be error segmented,  just because `"course" and "becomes"` no whitespace in this sentence.

Is there any way to don't regrad the whitespace "_" as a character to merge during the training phase.

**Comment by Yunlongs** [comment]
Oh, i think i have figure out this problem.
We can split the training courpus each line a word, and enable `--add_dummy_prefix=false` options.

Then we will get the only one form about words in the vocabulary.

**Comment by Yunlongs** [comment]
> Oh, i think i have figure out this problem.
> We can split the training courpus each line a word, and enable `--add_dummy_prefix=false` options.
> 
> Then we will get the only one form about words in the vocabulary.

I think this is a not good solution. Because when you split your corpus each line a word, your RAM memory will not enough. 
For example, i use a 6G corpus to train a BPE model and only use 20GB RAM, but memory overflow when use this solution .
My mechine has 64GB RAM !!

I hope there will be other solutions. Thanks.

**Comment by taku910** [comment]
Memory usage issue is a FAQ.

This looks FAQ. https://github.com/google/sentencepiece/issues?q=memory+
