### ISSUE TITLE
Syd:aloc keeps crashing

### ISSUE THREAD

**Issue by etetteh** [google/sentencepiece#528]
I really want to use the unigram feature of sentence... in fact my literature on unigram tokenization using Sentencepiece is already up.
the issue now is, not only that I can't read in all my data, but even the smallest chunk (12m lines) crashes and everything terminates

also can I control the alphabet size? As in setting a threshold.

**Comment by taku910** [comment]
Please use --input_sentence_size to limit the number of training sentences.  I think the crashes is cased by out-of-memory.
