### ISSUE TITLE
train tokenization model with or without punctuations?

### ISSUE THREAD

**Issue by DRosemei** [google/sentencepiece#529]
Thanks for your great works! Recently I trained a tokenization model using sentencepiece, then I use kenlm to train a subword level language model. When I use this language model to decode strings, I found that it tends to predict no punctuations or splitted punctuations. For example, 
Prediction#Firstly , Chinese people eat rice noodles vegetables
Ground Truth#Firstly, Chinese people eat rice, noodles, vegetables
Edit Distance# 3
Should I train tokenization model with or without punctuations?

**Comment by taku910** [comment]
I think it is task dependent. We can only conclude which is better from empirical experiments.
