### ISSUE TITLE
Confusion with SP vocabularies

### ISSUE THREAD

**Issue by mjpost** [google/sentencepiece#532]
SP training produces a `.vocab` file. It stands to reason that this file would be compatible with the `spm_encode --vocabulary` flag, but in fact it is not. The vocab file generated by training contains logprobs, while the `spm_encode` flag requires counts. This confusion has caused me to inadvertently train many translation models with character segmentation—I have passed the model-generated `.vocab` file, and since all the counts in that file are negative, no words are generated.

It would be a big help towards usability if `spm_encode --vocabulary` threw an error on encountering a negative count in the vocab file, and perhaps even clarified this point of confusion for the user, and directed them to build the count-based file per your instructions.

**Comment by mingruimingrui** [comment]
Agreed, and `.vocab` should probably be changed to `.scores` or `.probs` to prevent confusion.

**Comment by taku910** [comment]
Thank you for the comment.  We also think that vocab file is confusing, but we would like to keep the current behavior to keep the compatibility. spm_train has a flag ``--vocabulary_output_piece_score=false`` to stop emitting the score in the vocab file.

**Comment by mjpost** [comment]
Thanks, that makes sense. 

But what about throwing an error and quitting if negative values are found in the vocabulary file? This seems like a simple solution that would maintain backward compatibility while preventing users from making this mistake.
