### ISSUE TITLE
CMake install target fails to find sentencepiece.pc when included as a subproject

### ISSUE THREAD

**Issue by aaronpburke** [google/sentencepiece#533]
When including sentencepiece via `add_subdirectory` (i.e., as a 3rd party library), install targets fail:

`CMake Error at src/3rd_party/sentencepiece/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/path/to/myproject/build/sentencepiece.pc":
  No such file or directory.
Call Stack (most recent call first):
  src/3rd_party/cmake_install.cmake:175 (include)
  src/cmake_install.cmake:51 (include)
  cmake_install.cmake:66 (include)`

This is because the CMakeLists file installs sentencepiece.pc from CMAKE_BINARY_DIR (which refers to my top-level project), not CMAKE_CURRENT_BINARY_DIR (which refers to the sentencepiece project). I've resolved this in PR #530.

**Comment by taku910** [comment]
Let me close this bug, as the PR is already merged. Thank you.
