### ISSUE TITLE
[Feature request] Is there a way to input a file for the custom and control symbols?

### ISSUE THREAD

**Issue by alvations** [google/sentencepiece#536]
When using https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md, sometimes we want to use 100s to 1000s of controlled or custom symbols. Is there a way to do something like

```
$ cat control-symbols.txt
<foo>
<bar>

$ cat user-symbols.txt
<user1>
<user2> 

$ spm_train \
--control_symbols_file=control-symbols.txt \
--user_defined_symbols_file=user-symbols.txt \
--input=<input file> --model_prefix=<model file> --vocab_size=8000
```

Currently it's possible to do this but the above suggestion with `control_symbols_file` and `user_defined_symbols_file` would be very much preferred: 

```
$ spm_train \
--control_symbols=$(sed -e ':a' -e 'N;$!ba' -e 's/\n/,/g' control-symbols.txt) \
--user_defined_symbols=$(sed -e ':a' -e 'N;$!ba' -e 's/\n/,/g' user-symbols.txt) \
--input=<input file> --model_prefix=<model file> --vocab_size=8000
```

**Comment by taku910** [comment]
v0.19.3 added this feature. Thank you.

**Comment by danielinux7** [comment]
@taku910 when I tried to use user_defined_symbols_file in the python version, it threw unknown field error.
Another question, should I add a symbol to a newline?

**Comment by taku910** [comment]
In python, better to feed user_defined_symbols with a native python list

```
spm.SentencePieceTrainer.train(input='input.txt', user_defined_symbols=['foo','bar','buz'], vocab_size=2000)
```

I think it is redundant to have file-based API in python, as we can easily make the list.
