### ISSUE TITLE
Cannot parse --input_sentence_size when the given value exceeds int32 maximum value

### ISSUE THREAD

**Issue by szhengac** [google/sentencepiece#538]
I would like to train a sentencepiece model on a very large corpus with 20 billions of sentences. Based on the memory constraint, I would like to sample 5 billions of sentences by setting --input_sentence_size=5000000000. But it exceeds the int32 maximum value and the code gives me an error that it cannot be parsed into int. It would be good that sentencepiece supports int64 in the future.

**Comment by limia-ms** [comment]
Hi, thanks for raising up this question, since I have a similar problem here. On my side, the data is even more than 20B sentences. Is there a way to support sentencepiece in distributed system like PySpark? And when would this int32 maximum value limit be lifted?

**Comment by taku910** [comment]
Changed the type from int32 to uint64. However,  sentencepiece trainer loads all sentences into the memory, so you might need to have enough memory to use this flag anyway.
