### ISSUE TITLE
reproducibility of subword regularization

### ISSUE THREAD

**Issue by Zenglinxiao** [google/sentencepiece#540]
Hello there,
Just out of my curiosity, is there a way (in Python) to maintain the reproducibility when applying subword regularization?
Something like manually set the seed after loading the model.

**Comment by taku910** [comment]
Added set_random_generator_seed function

```
import sentencepiece as spm
spm.set_random_generator_seed(1234)
```
Note that the seed value is a global variable (thread local variable), so you can set only once before using spm.

**Comment by YuHengKit** [comment]
I tried the code above and experienced error in Python 3.7
"AttributeError: module 'sentencepiece' has no attribute 'set_random_generator_seed'"
