### ISSUE TITLE
Option to set log level. (identity normalization is really verbose)

### ISSUE THREAD

**Issue by villmow** [google/sentencepiece#543]
Is there an option to set the log level to ignore e.g. `LOG(INFO)`. 

I use identity normalization during training:
```python
spm.SentencePieceTrainer.train(
        sentence_iterator=iter_,
        model_prefix=args.spm_model_prefix,
        vocab_size=args.spm_vocab_size,
        max_sentence_length=3000,
        input_sentence_size=1000000000,
        shuffle_input_sentence=True,
        normalization_rule_name="identity",  # don't do normalization
        num_threads=max(8, args.workers),
)
```
This causes sentencepiece to produce the following log message very frequently during encoding:
```
normalizer.cc(50) LOG(INFO) precompiled_charsmap is empty. use identity normalization.
```
See also https://github.com/google/sentencepiece/blob/3b70b1a07344768df3b0236d8c94af682ea9e847/src/normalizer.cc#L50

**Comment by taku910** [comment]
Please use ``--minloglevel=2``

**Comment by villmow** [comment]
Hi, a follow up question. How can I set the log level with a trained model, when using `SentencePieceProcessor`

**Comment by Kyeongpil** [comment]
@taku910
