### ISSUE TITLE
How can I install the sentencepiece using pip with ppc64le-architecture CPU?

### ISSUE THREAD

**Issue by merchen911** [google/sentencepiece#544]
plz tell me :)

When I installed using pip, get below an error

Collecting sentencepiece
  Using cached sentencepiece-0.1.91.tar.gz (500 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-r96h7q7c/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-r96h7q7c/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-su4t3ebl
         cwd: /tmp/pip-install-r96h7q7c/sentencepiece/
    Complete output (5 lines):
    Package sentencepiece was not found in the pkg-config search path.
    Perhaps you should add the directory containing `sentencepiece.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'sentencepiece' found
    Failed to find sentencepiece pkgconfig
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

It always be found about the pip installation for vary version of the sentencepiece

**Comment by taku910** [comment]
Releases v0.1.93 that supports ppc64le, It will soon available via pypi.

https://github.com/google/sentencepiece/releases/tag/v0.1.93
