### ISSUE TITLE
How to set running params(mining_sentence_size/training_sentence_size/seed_sentencepiece_size) while datasets have more than 100M sentences?

### ISSUE THREAD

**Issue by lqniunjunlper** [google/sentencepiece#546]
By default, we have the following:
`   --input_sentence_size (maximum size of sentences the trainer loads)  type: int32  default: 10000000
   --mining_sentence_size (maximum size of sentences to make seed sentence piece)  type: int32  default: 2000000
   --seed_sentencepiece_size (the size of seed sentencepieces)  type: int32  default: 1000000
   --training_sentence_size (maximum size of sentences to train sentence pieces)  type: int32  default: 10000000`

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/issues/35
mining_sentence_size and training_sentence_size are deprecated

You might be able to find several tips to train the model from large training data.
https://github.com/google/sentencepiece/issues?q=input_sentence_size++large.
