### ISSUE TITLE
Not working on arm platforms?!

### ISSUE THREAD

**Issue by jshamg** [google/sentencepiece#553]
[#403](https://github.com/google/sentencepiece/issues/403) has never been addressed and closed without a fix. Haven't been reopened, but some people kept commenting on that issue. Please consider fixing it. Sentencepiece is breaking a lot of stuff on arm devices including [transformers](https://github.com/huggingface/transformers) on Raspberry Pi's.

**Comment by taku910** [comment]
Releases v0.1.93 that supports arm64.  It will soon available via pypi.

https://github.com/google/sentencepiece/releases/tag/v0.1.93
