### ISSUE TITLE
pip install sentencepiece error

### ISSUE THREAD

**Issue by da03** [google/sentencepiece#554]
The latest release `0.1.93` seems to have some problems, which I encounter when I install torchtext 0.7.0. Below is a snippet of the error msg. This issue is gone when I use the previous release `pip install sentencepiece==0.1.92`

ERROR: Command errored out with exit status 1:

     command: /home/travis/.pyenv/versions/3.8.3/envs/otter-latest/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-goywu74h/sentencepiece/setup.py'"'"'; __file__='"'"'/tmp/pip-install-goywu74h/sentencepiece/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info

         cwd: /tmp/pip-install-goywu74h/sentencepiece/

    Complete output (5 lines):

    Package sentencepiece was not found in the pkg-config search path.

    Perhaps you should add the directory containing `sentencepiece.pc'

    to the PKG_CONFIG_PATH environment variable

    No package 'sentencepiece' found

    Failed to find sentencepiece pkgconfig

    ----------------------------------------

ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by SeraphicRav** [comment]
Similar error when installing in the Docker image nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04

> Collecting sentencepiece!=0.1.92 (from transformers~=3.3->-r requirements.txt (line 13))
>   Downloading https://files.pythonhosted.org/packages/10/0b/c138719d683561fee1ac619b5445d74c981d5402e37d4a62b2a158222d7e/sentencepiece-0.1.93.tar.gz (498kB)
>     Complete output from command python setup.py egg_info:
>     /bin/sh: 1: pkg-config: not found
>     Failed to find sentencepiece pkgconfig
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2xi0aqvz/sentencepiece/

**Comment by taku910** [comment]
Thank you. I temporally disabled the package.

**Comment by taku910** [comment]
Released 0.19.4.  We start using manylinux2014 that requires ``pip >= 19.3``.
