### ISSUE TITLE
How to decide the size of subword vocabulary? 

### ISSUE THREAD

**Issue by thilakshiK** [google/sentencepiece#557]
I want to implement sentencepiece BPE as my segmentation algorithm for my NMT task. My corpus size is less than 100k. Also, the source and target languages are very distant languages.

- Should I use a joint vocabulary or two separate vocabularies for source and target?

- What should be the size of the subword vocabulary? 

Thank You

**Comment by taku910** [comment]
The optimal size totally depends on the training data. However, 8k-32k is widely used in many tasks.  In addition, joint-vocab is becoming popular these days.
