### ISSUE TITLE
unknown character sequence not segmented

### ISSUE THREAD

**Issue by Zenglinxiao** [google/sentencepiece#558]
Hello,
I'm reaching you as there seems to be something wrong with SentencePiece model.
Normally we would like to have all unknown characters are separated when using subword models, As in `subword_nmt`:
```
'东京翴礚┮続眖' -> ['东￭', '京￭', '翴￭', '礚￭', '┮￭', '続￭', '眖']
```
Note that the above example is produced using a `subword_nmt` en_fr shared BPE model which do not contain all those characters.
But with the SentencePiece, neither Unigram nor BPE separate those unknown characters.
```python
>>> spm.EncodeAsPieces("This is a test example where 东京翴礚┮続眖.")
['▁This', '▁is', '▁a', '▁test', '▁example', '▁where', '▁', '东京翴礚┮続眖', '.']
```
This means, even we don't judge the Unigram part, The SentencePiece's BPE does not perform the same as the original BPE algorithm.

I thought it was the nature of SentencePiece, then I find the following tests at [unigram_model_test.cc#L587-L594](https://github.com/google/sentencepiece/blob/0b5bd12205364c064a93c77d425ac7e6f8e41df3/src/unigram_model_test.cc#L587-L594), [bpe_model_test.cc#L108-L115](https://github.com/google/sentencepiece/blob/f7bc3dbfb6b9afb4b7323e01b200b83291ee9b34/src/bpe_model_test.cc#L108-L115). Both of which seems to check if the model has separated the unknown characters sequence into individual characters.
Then, my question is, is my understanding wrong or this is expected?

**Comment by Zenglinxiao** [comment]
The above mentioned issue also raises problems in the vocabulary.

As the vocabulary for machine translation is normally built by iterating all tokenized data to find all "words"(vocab). We may have built the SentencePiece model on a sample of the total corpora (since modern NLP system are trained with huge amount of data which may be too slow to train a spm on full size), we use this model to tokenize the training corpora but ended up with much greater vocabulary size compare to SentencePiece generated vocab.

Considering the above mentioned issue, if we do not separated the unknown character sequence, all those sequence will be considered as a new vocab to our neural model. We can indeed truncate the vocab by the frequency in order to make it the same size as spm.vocab, but this will also remove some vocab already exist in spm.vocab.

**Comment by taku910** [comment]
Sentencepiece does manage vocab <=> id mapping internally. In order to reduce the number of UNKs to be emitted, we simply merge them into single unknown. They do not have any corresponding surface form anyway.

You can split them with python module easily.

````
sp = spm.SentencePieceProcessor(model_file='spm.model')
tokens = []
for token in sp.encode('this is a test', out_type=str):
   if sp.is_unknown(token):
     tokens = tokens + list(token)
   else:
     tokens.append(token)
````

If you want to completely remove UNKs, you can try ```--byte_fallback``` . UNK unicode chars are split into byte sequence.
