### ISSUE TITLE
Error when pad, eos, bos, unk id is set to 1

### ISSUE THREAD

**Issue by usgnob3991** [google/sentencepiece#559]
I am making a bpe vocab in a colab environment.
--pad_id=0, --eos_id=1, --unk_id=2
I want to set it up like this.
Like eos_id, if I input the value 1, an error occurs.

runtimeerror: internal: /sentencepiece/src/trainer_interface.cc(571) [insert_id(trainer_spec_.eos_id(), trainer_spec_.eos_piece())]

Changing 1 to 3 does not cause an error.
I do not know why. Thank you.

**Comment by taku910** [comment]
This is because the default bos_id = 1.  We cannot override the id.
If you do not use bos_id, try ``--pad_id=0, --bos_id=-1 --eos_id=1, --unk_id=2``
