### ISSUE TITLE
Feature Request - sanitize id inputs

### ISSUE THREAD

**Issue by pandrey-fr** [google/sentencepiece#566]
Hello,

First, thanks a lot for sentencepiece, it is an awesome tokenizing tool. I started using it only recently, and am really pleased with both this interface and that being developed in TensorFlow Text.

That being said, one recurrent issue I am encountering is that of segmentation faults (that effectively break my running Python program) in case an out-of-vocabulary piece id is input to any method of an existing model (e.g. `is_unused`  or `id_to_string`). While it makes sense that inputting OOV would trigger errors, I believe that it would be practical to catch it rather than letting segfault happen - e.g. by checking whether the id is in {0, ..., vocab_size() - 1}.

It can easily be done at the level of the TensorFlow Text interface (where a default behaviour could be to replace OOV ids with that of the unk piece), but I was wondering whether a lower-level mechanism could be envisioned - and if not, I would be happy to learn why (since there might be aspects of that question that are unforeseen to me and would advocate to let segfaults happen).

Thank you in advance, and thank you again for sentencepiece.

**Comment by taku910** [comment]
Thank you for the feedback. 

It is reasonable to add these validation based on the programming language convention.

C++ (STL) doesn't run these validations. The client of the API has the responsibility.
In Python, it is common to raise an exception.

I would like to add these validations on the official Python module.  If some third-party Python module calls C++ API directly, we can ask the developer to change the behavior.

**Comment by pandrey-fr** [comment]
Thank you for your answer! I will then open an issue or a PR on the TensorflowText package.
