### ISSUE TITLE
Unluckly lost spm_trained model, how to generate a model based on bped data?

### ISSUE THREAD

**Issue by kkissmart** [google/sentencepiece#568]
I lost my spm model but have the bped data along with a dictionary of the bped data.

I can generate the raw text and re-generate a spm-model.

Besides this, any other choice do I have?

Thanks a lot.

**Comment by taku910** [comment]
This is not a perfect solution, but you can try
1. Aggregate all tokens and sort them by the length (shorter is fast)
2.  Train spm model with any dummy corpus.
3.  Swaps the 'pieces' field of the model with the tokens aggregated on 1.
    (note that first 3 tokens are <unk>, <s>, </s> so, you can swap the pieces[3:]
   See this colab to manipulate the model file.
   https://github.com/google/sentencepiece/blob/master/python/add_new_vocab.ipynb
