### ISSUE TITLE
Understanding ▁ in sentencepiece

### ISSUE THREAD

**Issue by danielinux7** [google/sentencepiece#575]
Hello,
To my understanding, instead of space the symbol ▁ has been used, which can used in the model to teach it word boundaries if it were tokenized separately.
Augmenting it to tokens drops a lot of what it means, and pollutes the symantecs of those tokens as well.
i.e "▁this ▁is ▁our s ." Should be "▁ this ▁ is ▁ our s ."
I tried it, it doubles the numbers of tokens to be processed and the results were worse. I am not looking for speed, but accuracy didn't get any better, maybe I did something wrong.
Could you elaborate on this point?

**Comment by taku910** [comment]
▁  is not treated as *word* boundary but a normal character. Sentencepiece does not consider semantic/syntactic relation but purely train segmentation almost ignoring the traditional concept of *word*. Please take a look at the pair.

https://www.aclweb.org/anthology/D18-2012.pdf
