### ISSUE TITLE
How can use extenrnal absl library

### ISSUE THREAD

**Issue by linuxpham** [google/sentencepiece#576]
Hi admin,

How can I use an external `absl` library when compiling your source code?
Because you always force use internal `absl' in third_party folder  (_USE_INTERNAL_STRING_VIEW)

`
error: undefined reference to 'sentencepiece::SentencePieceProcessor::Load(std::basic_string_view<char, std::char_traits<char> >)'
collect2: error: ld returned 1 exit status
`

<img width="1232" alt="Screen Shot 2020-11-01 at 03 19 00" src="https://user-images.githubusercontent.com/154762/97789190-fddaad80-1bf0-11eb-9925-c40d19128414.png">

Thanks !

**Comment by taku910** [comment]
At this moment, we don't support to external abls, but it is nice to support it.

**Comment by linuxpham** [comment]
Do you have a plan to support it?

**Comment by taku910** [comment]
It depends on how many people use it. Could you elaborate the background?

**Comment by taku910** [comment]
The step is a little complicated, but now we support to build sentencepiece with external abseil.
We have to put the abseil package under third_party sub directory.

```
> git clone https://github.com/google/sentencepiece.git  
> cd sentencepiece/third_party/
> git clone https://github.com/abseil/abseil-cpp.git 
> rm -fr absl
> ln -s abseil-cpp/absl absl
> cd ..
> mkdir build
> cd build
> cmake .. -DSPM_USE_EXTERNAL_ABSL=ON -DSPM_ENABLE_SHARED=OFF
> make
```

**Comment by wuchun** [comment]
Is there any specific reason we set -DSPM_ENABLE_SHARED=OFF in the step above?
