### ISSUE TITLE
Feature request: add min_sentencepiece_length

### ISSUE THREAD

**Issue by danielinux7** [google/sentencepiece#578]
Hello,
It would be helpful if an option is added for minimum sentencepiece length, it can be used in these cases:
> --max_sentencepiece_length=6
--min_sentencepiece_length=10

Allow pieces that are piece =<6 or piece =>10

> --max_sentencepiece_length=10
--min_sentencepiece_length=6

Allow pieces that are 6 =< piece =<10

> --min_sentencepiece_length=6

Allow pieces that are piece =>6

**Comment by taku910** [comment]
It is generally difficult to introduce such constraint as the unique number of pieces increases.  The basic motivation of subwording is to avoid UNK symbols as much as possible, so the model needs to include all characters as a last resort. If we introduce such constraint, any short input (<=4) is handled as UNK.

It would be nice to describe the background and motivation to introduce such constraint.

**Comment by danielinux7** [comment]
--required_chars or --user_defined_symbols could be used to cover the alphabet.
The motivation is to have pieces that are a hybrid of syllables and morphemes, and minimize meaningless pieces, I'm mostly be interested in the second case where you would allow pieces less than 6 pieces and more than 10 pieces as an example, finding the right combination could help me achieve that.
