### ISSUE TITLE
Python doesn't yet support `hard_vocab_limit`

### ISSUE THREAD

**Issue by neubig** [google/sentencepiece#58]
First, thanks for developing and releasing this package. It's really excellent and I recommend it to everyone :)

Just a very small request: the Python bindings from pip don't support the new `hard_vocab_limit` functionality, so when you have time I'd appreciate if you could make a new release to PyPI to that effect.

**Comment by taku910** [comment]
Thank you. Just updated the PyPI module.

**Comment by neubig** [comment]
Thanks a lot!
