### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'

### ISSUE THREAD

**Issue by marcusy1003** [google/sentencepiece#580]
I am using PyCharm to install [Senta](https://pypi.org/project/Senta/) on Python with `pip install Senta`

Python environment: Python 3.8 installed with Anaconda

I got the following results:

`(base) C:\Users\ypydo\PycharmProjects\pythonProject>pip install Senta
Collecting Senta
  Using cached Senta-2.0.0-py3-none-any.whl (178 kB)
Collecting scikit-learn==0.20.4
  Using cached scikit-learn-0.20.4.tar.gz (11.7 MB)
Collecting six==1.11.0
  Using cached six-1.11.0-py2.py3-none-any.whl (10 kB)
Collecting nltk==3.4.5
  Using cached nltk-3.4.5.zip (1.5 MB)
Collecting numpy==1.14.5
  Using cached numpy-1.14.5.zip (4.9 MB)
Collecting sentencepiece==0.1.83
  Using cached sentencepiece-0.1.83.tar.gz (497 kB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\ypydo\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ypy
do\\AppData\\Local\\Temp\\pip-install-_4pkhax1\\sentencepiece\\setup.py'"'"'; __file__='"'"'C:\\Users\\ypydo\\AppData\\Loca
l\\Temp\\pip-install-_4pkhax1\\sentencepiece\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read
().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\U
sers\ypydo\AppData\Local\Temp\pip-pip-egg-info-ger0iv0k'
         cwd: C:\Users\ypydo\AppData\Local\Temp\pip-install-_4pkhax1\sentencepiece\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ypydo\AppData\Local\Temp\pip-install-_4pkhax1\sentencepiece\setup.py", line 29, in <module>
        with codecs.open(os.path.join('..', 'VERSION'), 'r', 'utf-8') as f:
      File "C:\Users\ypydo\anaconda3\lib\codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '..\\VERSION'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

I tried to solve the issue by installing a [wheel file](https://github.com/google/sentencepiece/releases) of cp38 x86-64 version as previously found solution in another [issue](https://github.com/google/sentencepiece/issues/386)
the installation should be successful since it shows 
`Requirement already satisfied: sentencepiece==0.1.94 from file:///C:/Users/ypydo/PycharmProjects/pythonProject/sentencepiec
e-0.1.94-cp38-cp38-win_amd64.whl in c:\users\ypydo\anaconda3\lib\site-packages (0.1.94)
`
but the problem with installing Senta persisted

**Comment by taku910** [comment]
v0.1.94's pypi module is build with manylinux2014, which requires ``pip >= 19.3``

When the pip version is older, the module is build from source package, but the visual studio must be installed in your local machine to build sentencepiece.
