### ISSUE TITLE
README Clarification

### ISSUE THREAD

**Issue by ari-holtzman** [google/sentencepiece#582]
Hi,

It looks like compiling from source is the only way to get the executables that are referenced on the README, but this isn't mentioned anywhere that I could find. Perhaps y'all could add a warning that vcpkg won't get you an executable e.g. `spm_train` for those who weren't aware of that (like me)?

Thanks for all your hard work! This is an awesome project.

**Comment by taku910** [comment]
Thank you for the feedback. I've update the instructions (moved the vcpkg part at the end).
