### ISSUE TITLE
Rename VERSION file

### ISSUE THREAD

**Issue by ryandesign** [google/sentencepiece#583]
Hi, I'm a developer with MacPorts, where we have a port for sentencepiece and noticed [this compilation failure](https://trac.macports.org/ticket/61304):

```
version:1:1: error: expected unqualified-id
0.1.84
^
```

This happens in the following situation: the compiler is new enough to support the C++17 `<version>` header, and the filesystem is case insensitive (which it normally is on macOS).

Could you perhaps rename the VERSION file to avoid this problem? If you have any references to the file elsewhere in your sources those would need to be updated too.

**Comment by taku910** [comment]
Changed the name in the master branch.  If we don't see any problems, this fix is included in the next release. Thank you.
