### ISSUE TITLE
terminate called after throwing an instance of 'google::protobuf::FatalException'

### ISSUE THREAD

**Issue by rabeehk** [google/sentencepiece#587]
Hi
I am using huggingface repo seq2seq model, I am getting this error with iwstl datasets, could you have a look please thanks 

[libprotobuf FATAL /sentencepiece/src/../third_party/protobuf-lite/google/protobuf/repeated_field.h:1505] CHECK failed: (index) >= (0): 
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: (index) >= (0): 
run_t5_base_eval.sh: line 20:  6650 Aborted

**Comment by taku910** [comment]
Seems the huggingface library is accessing an array out of range.  Please double check the usage of huggingface library.
