### ISSUE TITLE
Installing 0.1.94 generates errors

### ISSUE THREAD

**Issue by AbdallahNasir** [google/sentencepiece#594]
Greetings,

I am trying to install the latest version of sentencepiece using `pip`.  Python version 3.6.9, Ubuntu 18 LTS. 

The following error log appears when trying to install it. Please note that everything seems okay when doing `pip install sentencepiece==0.1.92`.

Log attached because it is very long.
[spm.error.log](https://github.com/google/sentencepiece/files/5659827/spm.error.log)

Please advise,

**Comment by taku910** [comment]
Seems that it is trying to build wheel package from source, which is not expected. (usually binary wheel is installed).
sentencepiece uses manylinux2014, which requires pip >= 19.3.  Could you try it again after upgrading pip?

**Comment by AbdallahNasir** [comment]
It worked fine as you suggested, 
Thank you so much 
Best wishes,
