### ISSUE TITLE
protobuf upgrade to 3.14.0

### ISSUE THREAD

**Issue by jwijffels** [google/sentencepiece#595]
Protobuf v3.14.0 was released 25 days ago: https://github.com/protocolbuffers/protobuf/releases/tag/v3.14.0
Will you be planning to update the sentencepiece package with it?
If yes, that would solve the issue reported at https://github.com/google/sentencepiece/issues/432#issuecomment-640792815 as fixes were applied in protobuf release v3.14.0 in order to fix UBSAN compilation issues (trace here https://github.com/protocolbuffers/protobuf/issues/2073).
That would allow me to upgrade the sentencepiece R package on CRAN as this UBSAN compilation issue was a blocking factor there.

thank you!

**Comment by taku910** [comment]
Done in v0.19.5

**Comment by jwijffels** [comment]
Thank you! I'll look into it.
