### ISSUE TITLE
Segmentation fault (core dumped) on Centos

### ISSUE THREAD

**Issue by omrivm** [google/sentencepiece#597]
When i install sentencepiece (0.1.91) on Centos i get "Segmentation fault (core dumped)".
Dose sentencepiece supports Centos 7? or i'm doing something wrong?

**Comment by taku910** [comment]
Could you elaborate the report so we can reproduce? Ho
How did you install or run sentencepiece?, python version, and other pip libraries executed with sentencepiece.

**Comment by xiefangqi** [comment]
@omrivm Hello, Can this issue reproduce again? Can the installation methods and test cases be provided?

**Comment by omrivm** [comment]
@xiefangqi i don't have access to this machine anymore to reproduce the issue.

**Comment by taku910** [comment]
Please let me close this issue since there seems to be no further discussion
