### ISSUE TITLE
Process gets killed when it hits RAM limit

### ISSUE THREAD

**Issue by jacobastern** [google/sentencepiece#598]
I'm training the tokenizer on a large database of protein sequences (350 million sequences, ~400 characters apiece). When I get about a third of the way through my dataset (and coincidentally, when my RAM gets full), the process gets killed with no message other than `Killed`.

```
trainer_interface.cc(137) LOG(INFO) Loaded 103000000 lines
trainer_interface.cc(137) LOG(INFO) Loaded 104000000 lines
trainer_interface.cc(137) LOG(INFO) Loaded 105000000 lines
trainer_interface.cc(137) LOG(INFO) Loaded 106000000 lines
trainer_interface.cc(137) LOG(INFO) Loaded 107000000 lines
trainer_interface.cc(137) LOG(INFO) Loaded 108000000 lines
Killed
```
Any ideas how I can resolve this? I would like to train on the whole corpus if possible.

**Comment by taku910** [comment]
This looks FAQ.  https://github.com/google/sentencepiece/issues?q=memory+

**Comment by llhy60** [comment]
I had the same question as drescribed above. Do anyone have any idea how to slove this problem?
