### ISSUE TITLE
[Help] How to get the .spm file?

### ISSUE THREAD

**Issue by palooney** [google/sentencepiece#600]
Hello,

I was following the python module instructions for model training with 

`spm.SentencePieceTrainer.train(input="../clicr/train_text.txt", model_prefix='../models/reformer', vocab_size=15475)`

However, the above code returns `reformer.model` and `reformer.vocab`. How should I somehow merge these two files into a `.spm` for the huggingface reformer model? Thanks in advance

**Comment by taku910** [comment]
I could not fully understand the context, but feformer.model is the spm model file.
I'm afraid that this is not a  sentencepiece specific issue.  Please  the developer of huggingface reformer

**Comment by FlyingYanglu** [comment]
> Hello,
> 
> I was following the python module instructions for model training with
> 
> `spm.SentencePieceTrainer.train(input="../clicr/train_text.txt", model_prefix='../models/reformer', vocab_size=15475)`
> 
> However, the above code returns `reformer.model` and `reformer.vocab`. How should I somehow merge these two files into a `.spm` for the huggingface reformer model? Thanks in advance

I know it's been a long time, but may I ask that have u find any solution to this? I'm trying to convert spm's model to huggingface spm as well.

**Comment by changyeli** [comment]
@FlyingYanglu Sadly no. I got stuck here and didn't get any solution, so I went to a different model.
