### ISSUE TITLE
Support installation without administrative privliges

### ISSUE THREAD

**Issue by AmitMY** [google/sentencepiece#601]
Please add support for `conda` installation or any other way that doesn't require admin privileges.
I tried to install from source on a machine on which I don't have administrative privileges, and see you are trying to modify `/usr/local/lib64/pkgconfig`

Supporting this will make it easier for everyone to train tokenizers with `spm_train`

**Comment by taku910** [comment]
conda is not officially supported. Please ask conda/'sentencepiece owner.

As for the C++ (spm_train) installation, you can install them to arbitrary directory with CMAKE_INSTALL_PREFIX.
```
> mkdir build
> cd build
> cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/foo
> make install
````
