### ISSUE TITLE
what is the appropriate version for Win10 and Py2.7.18?

### ISSUE THREAD

**Issue by wangjiawei04** [google/sentencepiece#602]
Env:
OS: Win 10
Python: 2.7.18
I cannot install sentencepiece 0.1.94 0.1.83. 
Does someone know what is the version for Win? Or must I compile it?
Thank you.

**Comment by taku910** [comment]
Binary pip package for windows is supported from python >= 3.5 

This is the list of whl packages available:
https://github.com/google/sentencepiece/releases/tag/v0.1.94

You might be able to build whl package on python 2.7.x, but it is not officially supported.
https://github.com/google/sentencepiece/blob/master/test.bat
