### ISSUE TITLE
A gentle introduction to sentencepiece 

### ISSUE THREAD

**Issue by boba-and-beer** [google/sentencepiece#603]
Hi maintainers, 

I have written an [Unofficial gentle introduction to SentencePiece](https://medium.com/@jacky2wong/understanding-sentencepiece-under-standing-sentence-piece-ac8da59f6b08) to help users understand what SentencePiece is all about and its use in NLP. As someone who struggled to find these materials online prior to creating them, I was wondering if you would like to include it in the docs/README somewhere as SentencePiece is quite a technical piece of software that may help any new contributors better understand what SentencePiece is about. Happy to submit a PR if this is something that can be of help to you.

**Comment by taku910** [comment]
Thank you for your contribution. It would be appreciated it if you send us a PR.
