### ISSUE TITLE
vocabulary size error

### ISSUE THREAD

**Issue by riyaj8888** [google/sentencepiece#605]
i  am getting following error when i set vocab_size parameter as > 16000 .

"RuntimeError: Internal: C:\projects\sentencepiece\src\trainer_interface.cc(580) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (30000). Please set it to a value <= 16171.

Any one know how to solve this issue ,so i can increase my vocab_size

**Comment by taku910** [comment]
This error happens when the maximum vocab size commuted from the input data is 16171. 
You might need to pass more data to increase the vocab sizse.
