### ISSUE TITLE
Add Mac M1 Compatibility

### ISSUE THREAD

**Issue by pierreia** [google/sentencepiece#608]
Hi, 

Like the most part of Python librairies, SentencePiece won't install on Mac M1 architecture... "A revolution in data science" they said... what a joke, every data science library is a real pain to install! 
Do you plan to make a compatible version of SentencePiece?

Thank you!

**Comment by taku910** [comment]
What kind of error did you see when installing sentencepiece on Mac M1?  At least you might want to elaborate the steps you tried, otherwise, it is hard to provide the workaround at this moment.

**Comment by pierreia** [comment]
I use PyCharm, with a virtual environment where [Tensorflow Mac OS](https://github.com/apple/tensorflow_macos) and Torch are installed. Since the architecture of M1 is "arm64", there is a problem while building SentencePiece wheel. Here is my the end of my error logs: 
`    env: pkg-config: No such file or directory
    Failed to find sentencepiece pkg-config
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/user/tensorflow_macos/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-install-1svp5b95/sentencepiece_507a7b7ee8884aad99ee6348ea812b50/setup.py'"'"'; __file__='"'"'/private/tmp/pip-install-1svp5b95/sentencepiece_507a7b7ee8884aad99ee6348ea812b50/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-o2bcirdh/install-record.txt --single-version-externally-managed --compile --install-headers /Users/user/tensorflow_macos/include/site/python3.8/sentencepiece Check the logs for full command output.`

I got the same problem with Pytorch, which I was able to install since this answer: https://github.com/pytorch/pytorch/issues/48145

**Comment by taku910** [comment]
Seems that you are trying to build/install old package. What happens if you download the latest source package from [here](https://pypi.org/project/sentencepiece/#files)?  Then try the following command to build the wheel locally.

```
% pip -v install sentencepiece-0.1.94.tar.gz
```

**Comment by pierreia** [comment]
Thank you for your very fast answer. I manually build the .whl package, and I have been able to install sentence piece. However, I got an error while trying to import sentencepiece:

`
>>> import sentencepiece
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pierro/tensorflow_macos/lib/python3.8/site-packages/sentencepiece/__init__.py", line 13, in <module>
    from . import _sentencepiece
ImportError: dlopen(/Users/pierro/tensorflow_macos/lib/python3.8/site-packages/sentencepiece/_sentencepiece.cpython-38-darwin.so, 2): Symbol not found: __ZN13sentencepiece4util6StatusD1Ev
  Referenced from: /Users/pierro/tensorflow_macos/lib/python3.8/site-packages/sentencepiece/_sentencepiece.cpython-38-darwin.so
  Expected in: flat namespace
 in /Users/pierro/tensorflow_macos/lib/python3.8/site-packages/sentencepiece/_sentencepiece.cpython-38-darwin.so
`

**Comment by pierreia** [comment]
issue solved: I resintalled sentence piece through this:
`pip uninstall sentencepiece`

`pip install --no-cache-dir sentencepiece`

I don't know how, but it seems that a broken version of sentencepiece was cached. It now smoothly works on my Mac m1!

**Comment by millnerryan** [comment]
I'm still facing issues, even with @pierreia 's suggestion.

`Building wheel for sentencepiece (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/rmillner/miniforge3/envs/sentiment/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/zq/x2xccyn16ddbl6dzkr4lkzjm0000gn/T/pip-install-lb831ekl/sentencepiece_d30662501d75442aab80fcfc3f65ceeb/setup.py'"'"'; __file__='"'"'/private/var/folders/zq/x2xccyn16ddbl6dzkr4lkzjm0000gn/T/pip-install-lb831ekl/sentencepiece_d30662501d75442aab80fcfc3f65ceeb/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/zq/x2xccyn16ddbl6dzkr4lkzjm0000gn/T/pip-wheel-2y4k66lp
       cwd: /private/var/folders/zq/x2xccyn16ddbl6dzkr4lkzjm0000gn/T/pip-install-lb831ekl/sentencepiece_d30662501d75442aab80fcfc3f65ceeb/
  Complete output (43 lines):
  /Users/rmillner/miniforge3/envs/sentiment/lib/python3.9/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the underscore name 'description_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-11.0-arm64-3.9
  creating build/lib.macosx-11.0-arm64-3.9/sentencepiece
  copying src/sentencepiece/__init__.py -> build/lib.macosx-11.0-arm64-3.9/sentencepiece
  copying src/sentencepiece/sentencepiece_model_pb2.py -> build/lib.macosx-11.0-arm64-3.9/sentencepiece
  copying src/sentencepiece/sentencepiece_pb2.py -> build/lib.macosx-11.0-arm64-3.9/sentencepiece
  running build_ext
  Package sentencepiece was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sentencepiece.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sentencepiece' found
  Cloning into 'sentencepiece'...
  Note: switching to 'd8711f55d9b2cb9c77a00adcc18108482b29b675'.
  
  You are in 'detached HEAD' state. You can look around, make experimental
  changes and commit them, and you can discard any commits you make in this
  state without impacting any branches by switching back to a branch.
  
  If you want to create a new branch to retain commits you create, you may
  do so (now or later) by using -c with the switch command. Example:
  
    git switch -c <new-branch-name>
  
  Or undo this operation with:
  
    git switch -
  
  Turn off this advice by setting config variable advice.detachedHead to false
  
  ./build_bundled.sh: line 15: cmake: command not found
  ./build_bundled.sh: line 16: nproc: command not found
  make: *** No targets specified and no makefile found.  Stop.
  make: *** No rule to make target `install'.  Stop.
  Package sentencepiece was not found in the pkg-config search path.
  Perhaps you should add the directory containing `sentencepiece.pc'
  to the PKG_CONFIG_PATH environment variable
  No package 'sentencepiece' found
  Failed to find sentencepiece pkg-config
  ----------------------------------------
  ERROR: Failed building wheel for sentencepiece
  Running setup.py clean for sentencepiece
Failed to build sentencepiece`

**Comment by mdvandergon** [comment]
@millnerryan I ran into this issue today and got the same error you posted. I have a M1 Macbook, too.  I was able to fix it, first by installing cmake:
```
brew install cmake
```
And then by installing from the [sentencepiece-*.tar.gz source package](https://pypi.org/project/sentencepiece/#files) as recommended by @taku910. As of today, after downloading the file the command was:

```
pip -v install  sentencepiece-0.1.96.tar.gz
```

After these two steps I was able to `import sentencepiece`. I hope that also works for you. Take care.

**Comment by simhallq** [comment]
MacBook Pro M1 -21
`arch -arm64 brew install cmake` 
and then
`pip install --no-cache-dir sentencepiece`
did the trick for me

**Comment by atoultaro** [comment]
@simhallq Thanks! Your answer solved the problem for me.

**Comment by stevhliu** [comment]
Hi! I am also encountering some issues with installing `sentencepiece` on my M1 in a virtual conda environment. I've tried both solutions from @mdvandergon and @simhallq and unfortunately neither did the trick. The error I get at the end is:

![Screen Shot 2022-01-07 at 5 12 41 PM](https://user-images.githubusercontent.com/59462357/148625705-4ff0b8f6-2620-4953-95f9-0ecaacf0c2f3.png)

**Comment by ninjalu** [comment]
Hello. I have the same problem as @stevhliu above. Can't install with any of the solutions listed here. Really quite frustrating :I

**Comment by ninjalu** [comment]
@stevhliu 

Finally resolved
`brew install pkgconfig`
worked for me, after a long session of trials and errors. Hopefully this will help others with the same problem

**Comment by loyio** [comment]
> MacBook Pro M1 -21 using conda
> 
> ```
> $ arch -arm64 brew install cmake
> ```
> 
> ```
> $ pip install --no-cache-dir sentencepiece
> ```
> 
> did the trick for me

Thanks, It's work

**Comment by mrtipale** [comment]
I think, both 
`$ arch -arm64 brew install cmake` and  `brew install cmake` does same thing and worked for me to fix the issue. Thanks for details!

**Comment by lorenzoyeung** [comment]
> > MacBook Pro M1 -21 using conda
> > ```
> > $ arch -arm64 brew install cmake
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > $ pip install --no-cache-dir sentencepiece
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > did the trick for me
> 
> Thanks, It's work

this works for me, M1 Mac

**Comment by srulik-ben-david-hs** [comment]
what works for me a lot of the time is install some previous version of problematic packages, and thats it.
so for sentencepiece:
pip3 install sentencepiece==0.1.95
(instead of 0.1.96)

**Comment by ashesfall** [comment]
Installing cmake beforehand worked for me. Looking at the README, this is already part of the instructions (that I didn't read)

**Comment by linhaosheng** [comment]
brew install sentencepiece
brew install pkg-config
pip install sentencepiece

it work for me

**Comment by shaun-scale** [comment]
I was going crazy, thank you @linhaosheng ! 

```
brew install sentencepiece
``` 
seems to have done it...

**Comment by chandrakalagowda** [comment]
> what works for me a lot of the time is install some previous version of problematic packages, and thats it. so for sentencepiece: pip3 install sentencepiece==0.1.95 (instead of 0.1.96)

This worked for me. Using Mac 10.13.6

**Comment by kerbachi** [comment]
Installing cmake fixed the error on M2

```
brew install cmake
```

**Comment by rolyatmax** [comment]
In case it's helpful for someone else, I ended up having to install `protobuf-c` in addition to the above packages.

```
brew install protobuf-c
```

**Comment by swordfate** [comment]
> In case it's helpful for someone else, I ended up having to install `protobuf-c` in addition to the above packages.
> 
> ```
> brew install protobuf-c
> ```

Thank you. I finally succeeded in installing it on the M3 chip.

**Comment by Starrysparklez** [comment]
> In case it's helpful for someone else, I ended up having to install `protobuf-c` in addition to the above packages.
> 
> ```
> brew install protobuf-c
> ```

I had a problem installing sentencepiece on a macbook with Intel CPU (macOS Sequoia):
```
CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

Installing protobuf-c helped, thank you!
