### ISSUE TITLE
libtcmalloc_minimal.so is missing

### ISSUE THREAD

**Issue by zhangguanheng66** [google/sentencepiece#611]
I tried to compile sentencepiece locally and got the follow error. Any help are appreciated:

```
[ 16%] Built target sentencepiece_train-static
[ 83%] Built target sentencepiece-static
make[2]: *** No rule to make target '/usr/lib/x86_64-linux-gnu/libtcmalloc_minimal.so', needed by 'src/spm_normalize'.  Stop.
make[1]: *** [CMakeFiles/Makefile2:104: src/CMakeFiles/spm_normalize.dir/all] Error 2
```

**Comment by taku910** [comment]
Could you elaborate the report so we can reproduce?
How did you install or run sentencepiece?

**Comment by zhangguanheng66** [comment]
We upgraded our system to Ubuntu 20.04 and they didn't install `libgoogle-perftools-dev`. Will report back after we install it and see if it's fixed.

**Comment by zhangguanheng66** [comment]
Just wondering if I can disable the dependence on `google-perftools` on Ubuntu.

**Comment by taku910** [comment]
Please try ```cmake .. -DSPM_ENABLE_TCMALLOC=OFF```

**Comment by zhangguanheng66** [comment]
Thanks. It works.
