### ISSUE TITLE
Missing Unigram 0x0000 delimiter

### ISSUE THREAD

**Issue by david-waterworth** [google/sentencepiece#615]
More of a question than a bug, the function `Trainer::MakeSeedSentencePieces()` states

// Merges all sentences into one array with 0x0000 delimiter.

However this isn't performed as far as I can see - the end result seems to be that the input the the ESA algorithm is the concatenation of all sentences (which have been preprocessed to replace ' ' with '▁'

I'm wondering if this is an omission, or was it deemed unnecessary / counter-productive?

The reason I say this is technically I don't believe it's correct concatenate strings using the same end of string token when using Suffix Arrays to enumerate substrings - you're supposed to use a different suffix per string. Otherwise, the ancillary arrays such as the LCP tend to get messed up. For example, if you take "cat" and "bat" and concatenate them as "cat$bat$" you get the sorted suffix array

$
$bat$
at$
at$bat$
bat$
cat$bat$
t$
t$bat$

The longest common prefix of lines 2 and 3 is "at$" - if different terminators were used it would be "at" - what I've observed is this tends to ignore suffixes like "ing" unless they also occur inside words.

**Comment by david-waterworth** [comment]
I found another paper which showed that you can use string concatenation with a suffix array provided the calculation of the LCP (longest common prefix) correctly accounts for the string terminator (i.e. the LCP for "at$" and "at$bat$") should be 2 not 3. But the library used by `sentencepiece` doesn't do this.

It seems to me that by not taking this into account, you're likely to under-represent the frequency of suffixes. For example, if lots of words end in "ed" (followed by  '▁') they're get filtered out when generating the seed vocab for the unigram algorithm. 

It's quite easy to modify the LCP calculation in the esaxx library so that it doesn't count the prefix length beyond the end of a string (denoted either by an inter-word or sentence token). For a technical corpus I've trained a model on it makes a large difference, I suspect for standard languages it's not as important.

**Comment by taku910** [comment]
Fied in v0.1.96. Thank you.
