### ISSUE TITLE
set seed for  reproducible results

### ISSUE THREAD

**Issue by wlhonce** [google/sentencepiece#616]
How can I set random seed for reproducible results when using BPE-dropout

**Comment by taku910** [comment]
see https://github.com/google/sentencepiece/issues/609 and https://github.com/google/sentencepiece/issues/540

**Comment by wlhonce** [comment]
> see #609 and #540

Thanks, but I meet an AttributeError:

Traceback (most recent call last):
File "/home/lhwu/program/drop_bpe/replace_tok.py", line 2, in <module>
    spm.set_random_generator_seed(1234)
AttributeError: module 'sentencepiece' has no attribute 'set_random_generator_seed'

**Comment by taku910** [comment]
Please use the latest pip module. The latest version is v0.1.95
