### ISSUE TITLE
Is there any way to get model type from a loaded SentencePieceProcessor object?

### ISSUE THREAD

**Issue by Saltychtao** [google/sentencepiece#619]
Is there any way to get model type from a loaded SentencePieceProcessor object?

**Comment by taku910** [comment]
Yes, 'serialized_model_proto methods returns the model object in serialized protobuf format.

model_type returns the enum value of model type.
https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L47

````
>>> import sentencepiece as spm
>>> import sentencepiece.sentencepiece_model_pb2 as model
>>> sp = spm.SentencePieceProcessor(model_file='test_model.model')
>>> m = model.ModelProto()
>>> m.ParseFromString(sp.serialized_model_proto())
253165
>>> m.trainer_spec.model_type
1
````
