### ISSUE TITLE
Error with installing previous sentencepiece versions 

### ISSUE THREAD

**Issue by samahakk** [google/sentencepiece#620]
Hi I recently came across this type of bug when I was trying to install FLAIR. I am currently using python 39.

can someone resolve that issue ?

By trying to install a previous version via "pip install sentencepiece==0.1.91" I get this:

ERROR: Could not find a version that satisfies the requirement sentencepiece==0.1.91
ERROR: No matching distribution found for sentencepiece==0.1.91

**Comment by taku910** [comment]
python39 supported has just started from v0.1.94. Please use the latest version (>= 0.1.94) for python39
