### ISSUE TITLE
Allow querying for segmentation probability

### ISSUE THREAD

**Issue by llinda** [google/sentencepiece#622]
Thoughts on extending Encode (or similar) to support returning of the segmentation probability of each n-best? As I understand it, we are returning adding Nodes to the list of returned results (https://github.com/google/sentencepiece/blob/master/src/unigram_model.cc#L286), but the Agenda from which we get the Nodes have the scores available. Is my understanding correct?

**Comment by taku910** [comment]
Yes, it is correct. sentencepiece internally computes per-sentence segmentation probability, but they are not exposed to users and we do not have any public API them. Let me think what kind of API we can provide. 

By the way, how are you going to use these probability?

**Comment by taku910** [comment]
Please see https://github.com/google/sentencepiece/issues/634

You can obtain the sentence logprob with get_prob method.
