### ISSUE TITLE
How to encourage more subword splits?

### ISSUE THREAD

**Issue by NoviScl** [google/sentencepiece#626]
I want to encourage more splitting of whole-words into sub-word tokens, may I check how can I do that? Would decreasing the vocab size be a good option here?

Also, may I check if there's any good guidance on deciding the suitable vocab size for different languages?

Thanks.

**Comment by taku910** [comment]
yes, easiest way is to decrease the vocab size. Unfortunately, we do not have any silver bullet that tells the best vocab size in advance. At this moment, we can consider the vocab size as a hyperparameter of the model and find the best one with dev data.
