### ISSUE TITLE
Getting wrong splitting with - symbol

### ISSUE THREAD

**Issue by danielinux7** [google/sentencepiece#627]
Hello,
When setting the treat_whitespace_as_suffix='true' and user_defined_symbols_file=defined_symbols.txt options.
I get wrong splitting with - symbol:
(i.e) где-нибудь > где - ▁ нибудь▁ (incorrect)
It should be: где - нибудь▁
When using other symbols instead, I don't get this issue:
(i.e) где&нибудь > где & нибудь▁(correct)

**Comment by taku910** [comment]
Could you share the model file and defined_symbols.txt file? Otherwise, it is hard to reproduce the problems in our environment.

**Comment by danielinux7** [comment]
Hello,
It has been a long time, I have created many models since then, I won't find the files now.
I'll close the issue, If I come across similar issue in the future, I'll either reopen this one or create a new issue.
