### ISSUE TITLE
Using sentencepiece to tokenize Farsi language

### ISSUE THREAD

**Issue by Ali-Hatami** [google/sentencepiece#631]
I need to use sentencepiece to tokenize the Farsi language and use it for OpenNMT. I have some questions:
- Does sentencepiece support all languages like Farsi?
- When I try to detokenize the sentence, it returns the wrong character (just question ? mark). how can I solve this problem?
- To train the model of sentencepiece, Do we need raw text without any preprocessing task?

Thanks in advance for your help.
Ali

**Comment by taku910** [comment]
As long as the the text in Frasi can be encoded in Unicode (utf8), sentencepiece can *work*, but completely not sure sentencepiece can overcome other language-dependent approach.

When seeing question mark, you might want to to rum spm_train with the following flags:
* ```--character_coverage=1.0```:   use all character as vocab
* ```--byte_fallback=true```:  decompose unknown pieces into UTF-8 byte pieces.

Sentencepiece can train the model from raw text, but it is not mandatory. You can feed preprocessed text as well.
However, in this case, the decoded text is also pre-proecssed text, so you might need to run other postprocess.
