### ISSUE TITLE
How to get log probability scores of sentence during tokenization

### ISSUE THREAD

**Issue by irrawaddy28** [google/sentencepiece#634]
I have multiple sentencepiece models (using byte pair encoding) trained for different vocabulary sizes ranging from 2000-8000. For a given sentence, each model could potentially generate different token sequences using spm_encode. Is there a way retrieve the token sequence score for each tokenization done by spm_encode? (since this would be a quick way to know which model is the best fit model on a validation set). 

Examples below:
1. Model trained for 2000 vocab size tokenized the sentence with log probability score = -2.3
```
echo "I saw a girl with a telescope." | spm_encode --model=m.model.vocab2k
▁I ▁saw ▁a ▁girl ▁with ▁a ▁ te le s c o pe      -2.3
```

2. Model trained for 4000 vocab size tokenized the sentence with log probability score = -3.1
```
echo "I saw a girl with a telescope." | spm_encode --model=m.model.vocab4k
▁I ▁saw ▁a ▁girl ▁with ▁a ▁ te le s c o pe      -3.1
```
Is there an option in spm_encode that I can use to retrieve such scores?

**Comment by taku910** [comment]
You can obtain the logprob with python module.
get_score() returns the logprob of the token. The sentence logprob is obtained by summing per-token scores.
You might need to handle the unknown case. This code simply adds the smallest logprob for unkown.

````
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor(model_file='test_model.model')
>>> unk_logprob = min([sp.get_score(x) for x in range(sp.get_piece_size())])
>>> logprob = 0.0
>>> for id in sp.encode('this is a test.', out_type=int):
...     logprob += unk_logprob if sp.is_unknown(id) else sp.get_score(id)
...
>>> logprob
-34.625152826309204
````

Please note that BPE model cannot returns logprob.
