### ISSUE TITLE
Clarification about thread-safety, random sampling, random generator, random seed

### ISSUE THREAD

**Issue by albertz** [google/sentencepiece#635]
There is a global function `SetRandomGeneratorSeed`. Does this mean that there is a global random number generator? Is this thread-safe? So when I have multiple `SentencePieceProcessor`, and use `SampleEncodeAsIds`, does that work fine?

Maybe the documentation should be extended about thread-safety.

I would also maybe suggest to have a separate random generator per `SentencePieceProcessor`.

I'm using the Python module currently, but these questions should be independent about that, I assume?

**Comment by albertz** [comment]
Actually, this seems broken, or it uses an independent random generator?

```
import sentencepiece as spm
sp = spm.SentencePieceProcessor()
sp.load('m.model')

...

In [35]: spm.set_random_generator_seed(42)

In [36]: [sp.encode("hello", out_type=str, enable_sampling=True) for _ in range(10)]
Out[36]: 
[['▁he', 'l', 'l', 'o'],
 ['▁he', 'l', 'l', 'o'],
 ['▁he', 'll', 'o'],
 ['▁', 'h', 'e', 'l', 'l', 'o'],
 ['▁', 'he', 'l', 'l', 'o'],
 ['▁he', 'll', 'o'],
 ['▁he', 'l', 'l', 'o'],
 ['▁', 'he', 'll', 'o'],
 ['▁he', 'll', 'o'],
 ['▁he', 'll', 'o']]

In [37]: spm.set_random_generator_seed(42)

In [38]: [sp.encode("hello", out_type=str, enable_sampling=True) for _ in range(10)]
Out[38]: 
[['▁he', 'll', 'o'],
 ['▁he', 'll', 'o'],
 ['▁he', 'l', 'l', 'o'],
 ['▁', 'he', 'll', 'o'],
 ['▁', 'he', 'l', 'l', 'o'],
 ['▁', 'he', 'll', 'o'],
 ['▁', 'h', 'e', 'll', 'o'],
 ['▁he', 'll', 'o'],
 ['▁he', 'll', 'o'],
 ['▁', 'he', 'll', 'o']]
```

I would have expected to get exactly the same sequences in both cases?

**Comment by albertz** [comment]
I just looked at [this code](https://github.com/google/sentencepiece/blob/308d9bf37f2c49d9b4df5ae004483de937c65f26/src/util.cc), and now I see that calling `SetRandomGeneratorSeed` (`set_random_generator_seed`) has no effect once the random generator was created (on first usage), right?

Also, it seems to be thread-local? So this answers my questions about thread-safety. But this is even more unexpected and could potentially lead to strange results. E.g. when you use a thread pool to operate on some data, maybe some new threads would create a new random generator using the new seed, some other threads might reuse an existing random generator where `SetRandomGeneratorSeed` did not have any effect.

Maybe you can consider this a feature request to change this behavior. I'm not really sure how exactly it would be optimal, though.

* If this global random seed is kept like it is, at least `SetRandomGeneratorSeed` should reset all existing random number generators. (It might be tricky to make this thread-safe, though, when other threads use the random number generators while this gets called... But maybe we can just assume this will not be used like this.)
* Maybe every `SentencePieceProcessor` should have its own random number generator, and then also its own seed function. I'm not sure though whether this should also be thread local (probably the easiest and most efficient solution to make is thread safe).

**Comment by taku910** [comment]
First of all, I would like to say that we are not that willing to support this feature itself, and there is no guarantee that it will be supported in the future. In particular, if we move to absl::Bitgen (which is recommended in Google), we will not be able to provide the functionality itself. 

See below for more details.
https://abseil.io/docs/cpp/guides/random

The idea of SentencePieceProcessor to have its own random generator seem like a good idea, but inappropriate use of this function will not produce the original subword regularization functionality. If you mistakenly fix the seed every time or calling SetRandomGeneratorSeed every time, you will virtually get a fixed result, which will no longer be random. In addition, such design needs to have a mutex for random generator.

"Seeding" of random generators is a nontrivial task which often requires knowledge and non-trivial implementations technique, e.g., mutex and threadlocal.  We would like to focus on the standard use-case.
