### ISSUE TITLE
Pretokenization in sentencepiece

### ISSUE THREAD

**Issue by chandana1332** [google/sentencepiece#636]
Hello,

I have trained unigram SP models with punctuation. I noticed that my vocab doesn't contains any splits with special characters in them like:

Sentence: "I love the n. b. a."
tokenized: "_I _love _the _n . _b . _a ."

I was hoping that "_n." would be a token in my vocab. This is never the case. I see that sentencepiece pretokenizes the input to separate punctuation from tokens in order to control explosion of vocab but I would like to retain acronyms as is. 

Please elaborate on the exact pretokenization that is applied in sentencepiece and how to configure that.

**Comment by taku910** [comment]
The trained pieces must consist of the characters with the same Unicode script type. Since the period and 'n' are different script, they will not be one token.  We can disable this constraint with ```--split_by_unicode_script=false``` during the training.

```--split_by_unicode_script``` (use Unicode script to split sentence pieces)  type: bool default: true
