### ISSUE TITLE
Chinese comma '，' is converted to Latin comma ','

### ISSUE THREAD

**Issue by theoqian** [google/sentencepiece#643]
We used the sentencepiece model of xlm-roberta (https://s3.amazonaws.com/models.huggingface.co/bert/xlm-roberta-base-sentencepiece.bpe.model) to tokenize Chinese sentences and found the Chinese commas '，' were converted to Latin commas ',' after EncodeAsPieces. The sentencepiece version is 0.1.95.

``` python
import sentencepiece as spm

sp_model = spm.SentencePieceProcessor()
sp_model.Load('sentencepiece/sentencepiece.bpe.model')
print(sp_model.EncodeAsPieces("测试，和,"))
print(sp_model.EncodeAsIds("测试，和,"))
```

The results are:
['▁', '测试', ',', '和', ',']
[5, 49124, 3, 263, 3]

In input text, the former comma is Chinese while the later is Latin. But the returned tokens and ids are same.

**Comment by taku910** [comment]
This is expected. Sentencepeice normalizes the text with Unicode NFKC, which converts Chinese comma to Latin comma.

You can disable or customize the normalization rules in training phase, meaning that you might need to re-train roberta model with the new normalization rule.
https://github.com/google/sentencepiece/blob/master/doc/normalization.md
