### ISSUE TITLE
Making suffix array takes 1 day

### ISSUE THREAD

**Issue by chopinml** [google/sentencepiece#644]
Hello,

I have used this library for 9 million of sentences for a german - english translation task. Here is the script source:

https://github.com/OpenNMT/OpenNMT-py/blob/master/examples/scripts/prepare_wmt_data.sh

It basically downloads 3 bilingual corpus, concat them and runs this command afterwards:

spm_train --input=data/train.txt --model_prefix=data/wmtende --vocab_size=32000 --character_coverage=1

It is using 29 GB of RAM (6GB is system, 23 GB is swap on my laptop) and running for 24 hours and don't know when it is gonna end. 

train.txt file is 1.3 GB, 9.1M lines of sentences, first half is English, second half is German. 

Is this kind of RAM usage and CPU time normal for the above command for 9 million sentences ??

This is my log:

Training sentencepiece model
sentencepiece_trainer.cc(49) LOG(INFO) Starts training with :
TrainerSpec {
  input: data/train.txt
  input_format:
  model_prefix: data/wmtende
  model_type: UNIGRAM
  vocab_size: 32000
  self_test_sample_size: 0
  character_coverage: 1
  input_sentence_size: 0
  shuffle_input_sentence: 1
  seed_sentencepiece_size: 1000000
  shrinking_factor: 0.75
  max_sentence_length: 4192
  num_threads: 16
  num_sub_iterations: 2
  max_sentencepiece_length: 16
  split_by_unicode_script: 1
  split_by_number: 1
  split_by_whitespace: 1
  treat_whitespace_as_suffix: 0
  hard_vocab_limit: 1
  use_all_vocab: 0
  unk_id: 0
  bos_id: 1
  eos_id: 2
  pad_id: -1
  unk_piece: <unk>
  bos_piece: <s>
  eos_piece: </s>
  pad_piece: <pad>
  unk_surface:  ⁇
}
NormalizerSpec {
  name: nmt_nfkc
  add_dummy_prefix: 1
  remove_extra_whitespaces: 1
  escape_whitespaces: 1
  normalization_rule_tsv:
}

trainer_interface.cc(267) LOG(INFO) Loading corpus: data/train.txt
trainer_interface.cc(287) LOG(WARNING) Found too long line (25081 > 4192).
trainer_interface.cc(289) LOG(WARNING) Too long lines are skipped in the training.
trainer_interface.cc(290) LOG(WARNING) The maximum length can be changed with --max_sentence_length=<size> flag.
trainer_interface.cc(139) LOG(INFO) Loaded 1000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 2000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 3000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 4000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 5000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 6000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 7000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 8000000 lines
trainer_interface.cc(139) LOG(INFO) Loaded 9000000 lines
trainer_interface.cc(114) LOG(WARNING) Too many sentences are loaded! (9110889), which may slow down training.
trainer_interface.cc(116) LOG(WARNING) Consider using --input_sentence_size=<size> and --shuffle_input_sentence=true.
trainer_interface.cc(119) LOG(WARNING) They allow to randomly sample <size> sentences from the entire corpus.
trainer_interface.cc(315) LOG(INFO) Loaded all 9110889 sentences
trainer_interface.cc(321) LOG(INFO) Skipped 98 too long sentences.
trainer_interface.cc(330) LOG(INFO) Adding meta_piece: <unk>
trainer_interface.cc(330) LOG(INFO) Adding meta_piece: <s>
trainer_interface.cc(330) LOG(INFO) Adding meta_piece: </s>
trainer_interface.cc(335) LOG(INFO) Normalizing sentences...
trainer_interface.cc(384) LOG(INFO) all chars count=1331305324
trainer_interface.cc(392) LOG(INFO) Done: 100% characters are covered.
trainer_interface.cc(402) LOG(INFO) Alphabet size=3502
trainer_interface.cc(403) LOG(INFO) Final character coverage=1
trainer_interface.cc(435) LOG(INFO) Done! preprocessed 9110889 sentences.
unigram_model_trainer.cc(129) LOG(INFO) Making suffix array...

**Comment by AdolfVonKleist** [comment]
this may help you: https://github.com/google/sentencepiece/issues/641#issuecomment-804246527

**Comment by chopinml** [comment]
Hello again,

My training was completed in the 2nd day (at least 48 hours) but when i compiled the source code in google collab and do the same process, it just takes 20-30 minutes. But RAM usage is still an issue, does 1.86 version use much less RAM too? 

I can try both versions as inputs and may be compare them.

**Comment by taku910** [comment]
Could you try the latest version (0.1.96). This release has a fix for this issue.
