### ISSUE TITLE
Small bug in example nbest_size vs. nbest

### ISSUE THREAD

**Issue by PhilipMay** [google/sentencepiece#645]
In this example: https://github.com/google/sentencepiece#subword-regularization-and-bpe-dropout

You say `s.encode('New York', out_type=str, enable_sampling=True, alpha=0.1, nbest=-1)`
but it should be `s.encode('New York', out_type=str, enable_sampling=True, alpha=0.1, nbest_size=-1)`

**Comment by taku910** [comment]
Thank you. fixed
