### ISSUE TITLE
Vocab file has invalid line with large datasets

### ISSUE THREAD

**Issue by PJ-Finlay** [google/sentencepiece#647]
Sentencepiece is generating vocab files with invalid lines. Normally lines are \<character\>\<tab\>\<number\>, this line (near the end of the file) is just \<tab\>\<number\>. This only seems to happen on large datasets (82008718 lines in this case).

- Installed from source
- [OpenNMT Forum](https://forum.opennmt.net/t/opennmt-py-error-when-training-with-large-amount-of-data/4310/5)
- [Code](https://github.com/argosopentech/onmt-models/blob/7c758ab1d20a4dfdf7349626437b964b5716e194/train.sh#L8-L11)

Edit:
Actually the issue might be tokenizing as a carriage return and newline character. Not sure if this would be a SentencePiece or OpenNMT issue.

- https://forum.opennmt.net/t/opennmt-py-error-when-training-with-large-amount-of-data/4310/6

**Comment by taku910** [comment]
*.vocab emitted just for convenience.  The format strictly assumes that one toke doesn't contain newline character. We might be able to escape them, but the tool that uses *.vocab file might need to apply the same escaping.

We would like strongly recommend using the *.model file instead, that contains the list of token in protobuf. From python, we can obtain it as follows

````
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor(model_file='test_model.model')
>>> vocab = [sp.id_to_piece(x) for x in range(sp.get_piece_size())]
````

**Comment by PJ-Finlay** [comment]
I added a work around to OpenNMT: https://github.com/OpenNMT/OpenNMT-py/pull/2041
