### ISSUE TITLE
Serious bug? spm_encode ignores --vocabulary

### ISSUE THREAD

**Issue by mjpost** [google/sentencepiece#648]
From the README, I expect that tokens and characters that are not in the model vocabulary should be transformed to `<unk>` when using `spm_encode --vocabulary`:

> spm_encode accepts a --vocabulary and a --vocabulary_threshold option so that spm_encode will only produce symbols which also appear in the vocabulary (with at least some frequency). The background of this feature is described in subword-nmt page.

But it appears that `spm_encode` (0.1.95) ignores the `--vocabulary` option. I have trained a German 10k model, and no matter what text I pass into `spm_encode`, it just outputs it.

First, I generate the vocabulary:
```bash
# Generate the vocabulary
spm_encode --model=spm.model --generate_vocabulary < ../raw/train.de > vocab.de
```

Now, when I run the following, it will output basically any character:

```bash
$ echo 회 | spm_encode --model spm.model --vocabulary vocab.de --vocabulary_threshold 2
▁ 회
```

Here is proof this character is not accidentally in the model:

```bash
$ grep 회 vocab.de
$
```

The vocab looks fine:
```bash
head vocab.de
.       1702696
,       1356060
▁       1202369
s       1059431
en      996857
▁der    908500
▁und    770426
e       723539
▁die    644438
▁in     556034
```

I can also pump Russian through it!

```bash
$ sacrebleu -t wmt20 -l ru-en --echo src | head -n 1 | spm_encode --model spm.model --vocabulary vocab.de
▁ В ▁ ЦАР ▁ три ▁ человека ▁ погибли ▁ при ▁ крушении ▁ вертолета ▁ ООН
$
```

**Comment by mjpost** [comment]
Followup after discussion on Twitter: it appears this issue only exists when words are output. If the user adds `--output_format id`, then UNKs are used. While this makes a lot of sense at inference time, it creates problems if the user is relying on `spm_encode` to filter the data at training time.

I think the behavior here is quite confusing and hard to track down, and that the text mode output should use `<unk>` when unknown characters (that can't be decomposed) are encountered. An additional flag could be provided to allow users to preserve such characters instead of mapping to `<unk>`. It would break backward compatibility, but has the advantage of transparency. The current situation is hard to understand and track down for users that want `<unk>`, whereas for users that wish to have the OOV tokens preserved, the problem will be immediately apparent, and they'll search for a flag to preserve them.

**Comment by taku910** [comment]
v0.1.97 adds the option to emit ``<unk>`` instead of the original string.

Here is the example where feeding Japanese characters in English model.

```
>>> sp.encode('いろは', out_type=str, emit_unk_piece=True)
['▁', '<unk>']
>>> sp.encode('いろは', out_type=str, emit_unk_piece=False)
['▁', 'いろは']
>>> sp.encode('abc', out_type=str, emit_unk_piece=True)
['▁a', 'b', 'c']
```

In spm_encode CLI tool, we can change the behavior with ``--extra_options=unk``
```
% echo いろは | ../../build/src/spm_encode --model=test_model.model --extra_options=unk
▁ <unk>
% echo いろは | ../../build/src/spm_encode --model=test_model.model                    
▁ いろは
```

The reason why we do not emit ``<unk>``  by default is that ``<unk>`` will completely loose the information of what sort of input is passed to tokenizer.   It is trivial to rewrite ``<unk>`` from the vocab, while keeping the original information.
