### ISSUE TITLE
Prevent sentencepiece from normalizing whitespaces

### ISSUE THREAD

**Issue by miguelvictor** [google/sentencepiece#650]
Is there any way to prevent sentencepiece from normalizing whitespaces? For example, multiple consecutive spaces are normalized into one space but i would like to retain the original number of spaces. My use case is for tokenizing source codes where whitespaces are important.

I have tried training a BPE model with `byte_fallback=True` and `normalization_rule_name="identity"`, this does not normalize linebreaks anymore but multiple consecutive spaces are still converted into only one space.

**Comment by taku910** [comment]
Please use --remove_extra_whitespaces=false


```--remove_extra_whitespaces (Removes leading, trailing, and duplicate internal whitespace)  type: bool default: true```

**Comment by MaximumEntropy** [comment]
Sorry to bring this topic back up again, but the solution above works for spaces that are in the middle of a string, but setting this flag still seems to strip leading and trailing whitespace.
