### ISSUE TITLE
How to load vocab trained with huggingface Tokenizer's ByteLevelBPETokenizer?

### ISSUE THREAD

**Issue by hwijeen** [google/sentencepiece#653]
Hi, thank you for the great library.

Is it possible for sentencepiece to load a vocabulary that is trained with huggingface Tokenizer's `ByteLevelBPETokenizer`?
I have noticed that files created by `save_model` or `save` of `ByteLevelBPETokenizer` is not directly loadable, and I wonder if there is a workaround.

**Comment by taku910** [comment]
No, there is no simple workaround to load the model. thank you.
