### ISSUE TITLE
.whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by akmalkady** [google/sentencepiece#654]
Hi

I am trying to install sentencepiece on a raspberry pi (Linux raspberrypi 4.19.127v64 #1 SMP PREEMPT aarch64 GNU/Linux) with python version (Python 3.7.3 [GCC 8.3.0] on Linux) but I am getting the following error:
`ERROR: sentencepiece-0.1.95-cp37-cp37m-manylinux2014_aarch64.whl is not a supported wheel on this platform.
`

I used the following commands to install it:
```
wget https://github.com/google/sentencepiece/releases/download/v0.1.95/sentencepiece-0.1.95-cp37-cp37m-manylinux2014_aarch64.whl
pip install sentencepiece-0.1.95-cp37-cp37m-manylinux2014_aarch64.whl

```

Is it possible to install it? please help.
thanks

**Comment by taku910** [comment]
Usally, you can install the pip package via "pip install sentencepiece". When binary package is not available, pip tries to download the source package and built binary package on your machine.

you can explicitly build the binary package as follows.

```
wget https://files.pythonhosted.org/packages/95/bc/b39f9627c41027caf669cf4d1e47a7415cfa018a7dcb899aebd122af7c91/sentencepiece-0.1.95.tar.gz
pip install -v sentencepiece-0.1.95.tar.gz 
```
