### ISSUE TITLE
glob support in command-line sentencepience

### ISSUE THREAD

**Issue by akalieren** [google/sentencepiece#656]
Hello,

I am working on large corpus and they are splitted into small chards. There are roughly 60 files and I wanted to train bpe tokenizer using command-line tool. 

What I did is
```
spm_train --input=data/* --model_prefix=<mymodelname> --vocab_size=64000 --character_coverage=1.0 --model_type=bpe
```

But it did not work actually, I have solved this problem by joining files into "," with the help of python but are there better way to do that? 

Thanks in advance

**Comment by taku910** [comment]
You might want to try shell's glob feature as follows.

```
spm_train --input=$(echo data/* | sed 's/ /,/g') --model_prefix=m
```
