### ISSUE TITLE
SentencePieceProcessor.EncodeAsIds blocking when used across threads? 

### ISSUE THREAD

**Issue by vrnmthr** [google/sentencepiece#657]
I am trying to integrate SentencePiece with some C# code using interop. I have many instances of `SentencePieceProcessor` that are running concurrently in different managed threads from the C# level and am calling `EncodeAsIds` concurrently on these different instances. 

My logs are showing that sometimes the call to `EncodeAsIds` takes a huge amount of time (>1000ms). This does not happen on the same string that I run `EncodeAsIds` on under no load conditions, and so I suspect that something is blocking... Is this a known issue?

**Comment by taku910** [comment]
No. EncodeAsIds are not blocking and we can call it from multiple threads simultaneously. Please check the length of the input. The speed of EncodeAsIds is O(N) where N is the length of input.
