### ISSUE TITLE
[Question] byte_fallback effect on proper names

### ISSUE THREAD

**Issue by ymoslem** [google/sentencepiece#662]
Hello!

Currently, our NMT system copies UNKs from the source to the target during translation. This is useful for proper names like "Blackberry". However, it will do the same for UNKs that are regular words as well. For this, we are considering using the SentencePiece's model training option `byte_fallback` to reduce UNKs in the first place.

My questions is: can using `byte_fallback` negatively affect proper names. My understanding is that now there is a chance that "Blackberry" would be segmented and interpreted as maybe "black" and "berry", or the like. If this is the case, using `byte_fallback` will be considered a trade-off.

Could you please confirm or correct this. Many thanks!

**Comment by taku910** [comment]
bytefallback treats super-rare characters (e.g., emoji) as sequence of utf8-byte and actually encourages the model to simply copy the these characters from source to target. These rare characters are often appear in the source/target sentences in the same form.

**Comment by ymoslem** [comment]
Many thanks for the prompt reply. So in this case, it will not help reduce other types of UNKs, I guess. This makes it clear.
