### ISSUE TITLE
Contribute with a jvm wrapper

### ISSUE THREAD

**Issue by EmiCareOfCell44** [google/sentencepiece#663]
I have created a wrapper for the jvm for, at the moment, using it in Spark clusters. I followed the same strategy that was used in the python API, using SWIG for Java. I also added a Spark Estimator implementation. Let me know if you are interested in this feature and I can open a new PR.

**Comment by taku910** [comment]
Thank you for the contribution.  I think it's better to have a separate repo to reduce maintenance costs.
