### ISSUE TITLE
How to make sentencepiece project depend on external protobuf in other folders or projects?

### ISSUE THREAD

**Issue by Zuwei-Zhao** [google/sentencepiece#665]
Hi, is the **protobuf-lite** in sentencepiece compatible with other version protobuf?

Besides the parameter to set `SPM_USE_BUILTIN_PROTOBUF OFF`, how could I make sentencepiece project depend on external protobuf like the protobuf in **other folders or projects**?

Thanks.

**Comment by taku910** [comment]
When SPM_USE_BUILTIN_PROTOBUF is OFF,  we use the FindProtobuf feature Cmake provides.
It would be difficult to handle the case anything beyond the functionality supported by Cmake.

https://cmake.org/cmake/help/latest/module/FindProtobuf.html

**Comment by Zuwei-Zhao** [comment]
> When SPM_USE_BUILTIN_PROTOBUF is OFF, we use the FindProtobuf feature Cmake provides.
> It would be difficult to handle the case anything beyond the functionality supported by Cmake.
> 
> https://cmake.org/cmake/help/latest/module/FindProtobuf.html

Thanks for the information. I will try it.
