### ISSUE TITLE
How to get the sentencepiece vocabulary from .model file and store it to .vocab?

### ISSUE THREAD

**Issue by SambhawDrag** [google/sentencepiece#668]
Hi, I was working on implementing the XLNet language model in Julia. It uses the **sentence-piece** as the tokenizer.
I need the vocabulary for the tokenizer, which is stored inside **spiece.model** file. 

I did refer to this [Issue #121](https://github.com/google/sentencepiece/issues/121), but it only tells about modification of the model. 

Could you tell me, how I should obtain the vocabulary in a **.vocab** format?

**Comment by taku910** [comment]
Easiest way is to use the python module.

`````
>>> import sentencepiece as spm
>>> sp = spm.SentencePieceProcessor(model_file='test_model.model')
>>> vocabs = [sp.id_to_piece(id) for id in range(sp.get_piece_size())]
>>> vocabs
['<unk>', '<s>', '</s>', '\r', '▁', ',', '.', ... omit
````

**Comment by zhangqiaobit** [comment]
I have the same problem！

> Easiest way is to use the python module.
> 
> ```
> >>> import sentencepiece as spm
> >>> sp = spm.SentencePieceProcessor(model_file='test_model.model')
> >>> vocabs = [sp.id_to_piece(id) for id in range(sp.get_piece_size())]
> >>> vocabs
> ['<unk>', '<s>', '</s>', '\r', '▁', ',', '.', ... omit
> ````
> ```

I have the same problem！but the "vocabs" is a list not .vocab file

**Comment by aixuedegege** [comment]
把https://huggingface.co/xlm-roberta-base/tree/main里面的[tokenizer.json](https://huggingface.co/xlm-roberta-base/blob/main/tokenizer.json)放到模型目录下。AutoProcessor load完之后记得用sentencepiece load一下[sentencepiece.bpe.model](https://huggingface.co/microsoft/layoutlmv3-base-chinese/blob/main/sentencepiece.bpe.model) 看看对不对

**Comment by WjH444** [comment]
what's the meaning of the <s> and </s>?

**Comment by WjH444** [comment]
what's the meaning of the '<s>', '</s>'

**Comment by WjH444** [comment]
what's the meaning of the
`'<s>', '</s>'`

**Comment by erkhem42** [comment]
I think they are control symbols. Take a look here https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md

**Comment by erkhem42** [comment]
> what's the meaning of the `'<s>', '</s>'` ??????

I think they are control symbols. Take a look here https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md
