### ISSUE TITLE
how can I know which the protobuf version used in the past sentencepiece verison ?

### ISSUE THREAD

**Issue by zgj-gutou** [google/sentencepiece#673]
hello, I want to use the sentencepiece and the latest sentencepiece use the v3.14.0 protobuf , but the v3.14.0 protobuf is too high in my project , so I want to know which the protobuf version used in the past sentencepiece verison ?  For example , how can I know which the protobuf version used in the v0.1.90 sentencepiece or other past sentencepiece ?   Thank you for your answer.

**Comment by zgj-gutou** [comment]
Can you list the protobuf versions in the past sentencepiece versions?  Thank you very much.

**Comment by xiefangqi** [comment]
@zgj-gutou You need to consult the release note:

v0.1.95
Updates
upgraded protobuf 3.14.0

v0.1.92
upgrade builtin protobuf to 3.12.3

**Comment by taku910** [comment]
You can find the version from port_def.inc.
```
% grep "define PROTOBUF_VERSION " third_party/protobuf-lite/google/protobuf/port_def.inc 
#define PROTOBUF_VERSION 3014000
```
