### ISSUE TITLE
Is there any way to handle / preserve SPECIAL tokens .

### ISSUE THREAD

**Issue by s4sarath** [google/sentencepiece#674]
Hello Everyone,

I was trying to do some MASKING-based experiments.
But, what happens is that special tokens like [MASK] are getting split into further pieces.

Is the following possible.
```
text = 'this is [MASK] token with [SEP]'
sp.encode_as_pieces(text)

Output:

['▁this', '▁is', '[MASK]', '▁to', 'ken', '▁with', '[SEP]']
```
Thanks.

**Comment by SamueLacombe** [comment]
add this option:

--user_defined_symbols=[MASK],[SEP]

when calling spm.SentencePieceTrainer.train

user_defined_symbols can't be split.

**Comment by taku910** [comment]
Please use `user_defined_symbols'
