### ISSUE TITLE
User defined tokens during spm_encode

### ISSUE THREAD

**Issue by abhirut** [google/sentencepiece#675]
Is it possible to define tokens that are not tokenized while applying an existing model?

**Comment by LeeSureman** [comment]
+1

**Comment by abhirut** [comment]
I figured out how to do this, btw. The sentence piece model has protos for tokens, and you can add a proto for the extra token you want to add.

Adding it to the vocabulary is more tricky. Vocabulary cannot be extended once you've trained a model - since the embedding matrix is now fixed. Also, at least at an initial glance I did not see any extra unused tokens in the vocabulary. Since my model was only a Spanish-English model, I replaced a token in a different language with my extra token.

**Comment by taku910** [comment]
The model file is a serialized proto and you might be able to tweak the sentencepiece's behavior by manually editing the proto. However,  we do not expect that the model is modified after training. Please understand that it should be done completely at-your-own-risk basis.

If you have a pre-defined tokens that should not be tokenized, you can simply escape them as follows:

```
sp.encode('hello world') + ['foo'] + sp.encode('bar buzz')
```
