### ISSUE TITLE
How about vocab_size 100000 ?

### ISSUE THREAD

**Issue by kimsijin33** [google/sentencepiece#678]
How about vocab_size 10 thousands ?
Is it OK?
Is it better than lower size?
it seem to be rich vocabulary  right?

below code
spm.SentencePieceTrainer.Train('--input=imdb.txt --model_prefix=imdb --vocab_size=100000

Is it just make sentence piece and don't care rich vocabulary? 
so it's okay 10,000 or 20,000 
right?

**Comment by taku910** [comment]
The choice of vocab size highly depends on the applications and tasks. you might need to find the best data with held-out data/cross-validation etc.
