### ISSUE TITLE
Possible memory leakage

### ISSUE THREAD

**Issue by JackyYin** [google/sentencepiece#679]
I found some memory leakage problems when I use valgrind to debug:

> 128 bytes in 1 blocks are indirectly lost in loss record 4 of 9
> 192 (64 direct, 128 indirect) bytes in 1 blocks are definitely lost in loss record 6 of 9

and the stacks of memory allocation is:
```
sentencepiece::SentencePieceProcessor::LoadFromSerializedProto(absl::string_view serialized) ->
sentencepiece::ModelProto::ModelProto(google::protobuf::Arena*) ->
google::protobuf::internal::InitSCCImpl(google::protobuf::internal::SCCInfoBase*) ->
google::protobuf::internal::InitProtobufDefaultsSlow() ->
google::protobuf::internal::OnShutdownRun(void (*)(void const*), void const*) ->
operator new(unsigned long)
```

I think it's because of the struct ShutdownData is not correctly freed in third_party/protobuf-lite/message_lite.cc:540
```
struct ShutdownData {
  ~ShutdownData() {
    std::reverse(functions.begin(), functions.end());
    for (auto pair : functions) pair.first(pair.second);
  }

  static ShutdownData* get() {
    static auto* data = new ShutdownData;
    return data;
  }

  std::vector<std::pair<void (*)(const void*), const void*>> functions;
  Mutex mutex;
};
```

Calling function google::protobuf::ShutdownProtobufLibrary() before process exit may fix the problem,
but I don't think it's a good practice to directly call function of 3rdParty library of 3rdParty library of my project.

**Comment by taku910** [comment]
Thank you for the suggestion.

Fixed this issue by calling google::protobuf::ShutdownProtobufLibrary()
