### ISSUE TITLE
OOM with 290G RAM and only 70 million sentences.

### ISSUE THREAD

**Issue by SefaZeng** [google/sentencepiece#680]
I try to train the sentenpiece model with a multilingual data which includes 1 billion data. And I try to use part of them to get the sentencepiece model. This is the python code I used:
```
#coding:utf-8
import sys 
import sentencepiece as spm 
        
work_dir = "/mydir"
spm.SentencePieceTrainer.train(
    input=work_dir+'/all', 
    model_prefix=work_dir+'/vocab_sp3', 
    vocab_size=48000, 
    input_sentence_size=70000000,                                                                               
    shuffle_input_sentence=False, 
    num_threads=35, 
    train_extremely_large_corpus=True)
```
Is there something wrong with this code ?  In my opinion, such a large memory is enough for getting subwords vocab, e.g. BPE, with tens of millions of data. I skimmed through the past issues and did not find any good solutions for this.

**Comment by MatthewBieda** [comment]
You need to set shuffle_input_sentence to True, also your vocab size is probably too high, try 4k-32k for best results especially. Also I think train_extremely_large_corpus actually inreases RAM usage try without.

**Comment by SefaZeng** [comment]
> You need to set shuffle_input_sentence to True, also your vocab size is probably too high, try 4k-32k for best results. Also I think train_extremely_large_corpus actually inreases RAM usage try without.

Thanks for your reply. I have shuffled the corpus before as I am not quite sure if the shuffle process could be the cause of the OOM. 
For the vocab size, I try to lower it to 6k. In this way, sentencepiece can handle the 80 million sentences but also return an OOM error when I increase the data size to 90 million.
I will try to set the train_extremely_large_corpus to False, hope it will work.

**Comment by taku910** [comment]
Reduce the data to load e.g. ``` --input_sentence_size=700000```.   Then the trainer randomly samples the ```input_sentece_size`` sentences from all data before making the model.
