### ISSUE TITLE
How to handle multiple whitespaces or newlines

### ISSUE THREAD

**Issue by AmrMKayid** [google/sentencepiece#684]
Whilespaces are supposed to be handled as a normal symbol as mentioned in the [README](https://github.com/google/sentencepiece#whitespace-is-treated-as-a-basic-symbol). However when encoding text with multiple whitespaces, sentencepiece ignore this totally and treat it as a one whitespace only as shown in the image below.
<img width="400" alt="Screen Shot 2021-08-19 at 5 48 18 PM" src="https://user-images.githubusercontent.com/18689888/130100379-cb9eacaf-deb2-49a7-b1bb-5cb5f63105d2.png">

This also happen for newlines as well!

Are there any arguments that should be passed to sentencepiece to handle multiple symbols? or how to approach this issue?

**Comment by taku910** [comment]
Run spm_train with ```--remove_extra_whitespaces=false```.   In addition, newlines are all normalized whitespaces internally by default.  You can stop all normalizations with ```--normalization_rule_name=identity```

**Comment by KeremTurgutlu** [comment]
@taku910 if set `remove_extra_whitespaces=false` I can see that spmodel is able to tokenize each whitespace but would it be able to learn multiple repeated whitespace characters as a token? For example, BPE can have GGGG which stands for 4 whitespaces. In unigram model is this possible?
