### ISSUE TITLE
How to load and access spm model from AWS S3

### ISSUE THREAD

**Issue by jinrongchi** [google/sentencepiece#685]
Hello, I am new to aws and sentencepiece. This maybe a very stupid question.

Basically I had my models stored locally and accessed it with
`self.tokenizer = spm.SentencePieceProcessor(model_file=self.sp_model_path)`

But now I need to deploy my program to AWS Lambda, and to minimize the folder size, I uploaded my models to S3 AWS. I am confused here about how to load my model from S3 and access it with sentencepiece.

Thanks guys

**Comment by taku910** [comment]
Please see https://github.com/google/sentencepiece/tree/master/python#training-without-local-filesystem

Thank you.
