### ISSUE TITLE
Extend split_by_digits to non-latin numerals.

### ISSUE THREAD

**Issue by ibraheem-moosa** [google/sentencepiece#686]
I think the current implementation of `split_by_digits` only works for ASCII numerals. Many indian languages as well as arabic use their own numeric characters. I think it would be a good idea to extend the `split_by_digits` option to non-ASCII numerals too. Maybe there is also similar issue with `split_by_numbers` but I have not seen it. If there is then it would be good idea to accept non-ASCII numerals for that too.

**Comment by taku910** [comment]
If you have the list of these chars, you can specify them like ```--user_defined_symbols=A,B,C...```. Then A,B,C are always split into one chars.
