### ISSUE TITLE
Can I iteratively train a bpe model with one piece of data at a time?How can I train a BPE model for 700G text?

### ISSUE THREAD

**Issue by Null-op** [google/sentencepiece#687]
How can I train a BPE model for 700G text, what can I do is randomly sample the sentences?

**Comment by xiefangqi** [comment]
There may be an out-of-memory problem, you can refer https://github.com/google/sentencepiece/issues/680. If you want to do shuffle, parameter 'shuffle_input_sentence' should be set to True

**Comment by taku910** [comment]
Yes, please use `--input_sentence_size` to restrict (sample) the input, or use the computer with larger heap memory.
