### ISSUE TITLE
How to do not use whitespace in new pieces?

### ISSUE THREAD

**Issue by Meranolean** [google/sentencepiece#688]
I want to make unigram dict without pieces which include '\_' except single '\_' which represent whitespace itself. I didn't find option like this in arguments, what should I do?

By default in dict are pieces like
'_a'
'_hav'
Etc.

**Comment by taku910** [comment]
Please specify '▁' as user_defined_symbols

```
% spm_train --input=input --user_defined_symbols=▁  ...
```
