### ISSUE TITLE
sentencepiece with pre-tokenised text. 

### ISSUE THREAD

**Issue by hobodrifterdavid** [google/sentencepiece#689]
Hello. We are making a site for language learners (languagereactor.com).

We are training some machine translation models, sentencepiece is used for tokenisation/detokenisation.

We also run the source text through UDPipe (http://lindat.mff.cuni.cz/services/udpipe/), which tokenises the text into words (in the linguistic sense) and allows users to lookup/save words as they would expect.

We want to get alignment data from the translation models, and it would work nicest if the tokens from the machine translation output could be mapped (many-to-one) to UDPipe tokens. Said another way, force sentencepiece to respect the UDPipe token boundaries, and output tokens that are sub-units of the UDPipe tokens.. This way, the user can hover on a UDPipe token in the source text, and we can highlight the corresponding token(s) in the translation.

![image](https://user-images.githubusercontent.com/16459990/131888016-b64eb69d-c0aa-43f6-8994-f6b2cd1a0fd7.png)

Can we achieve this by training a sentencepiece model by feeding in text pre-tokenised by UDPipe? When translating text, would the input text always need to be pre-tokenised by UDPpipe to deterministically obtain the same sentencepiece tokens?

I am trying to read the sentencepiece paper but I am struggling. Thank you for any hints. :)

**Comment by taku910** [comment]
Yes, you can feed pre-tokenized data to sentencepiece.  sentencepiece is not aware of how the input text is generated. When pre-tokenized text is fed, the detokenized text will be not always the same as the user-input raw text and you might need to run language-dependent detokenizer.
