### ISSUE TITLE
Typo in logging?

### ISSUE THREAD

**Issue by ldong87** [google/sentencepiece#691]
According to [this line](https://github.com/google/sentencepiece/blob/master/src/trainer_interface.cc#L536), the variable sentences_ stores the token map. Then I think this [logging line](https://github.com/google/sentencepiece/blob/fab966ad218c6d3449f7ebf088c8b891afbabec2/src/unigram_model_trainer.cc#L489) should be "Using # **tokens** for EM training" instead of "**sentences**", is it?

**Comment by taku910** [comment]
It is correct.  In CJK, words are not segmented with whitespaces. It is just a simple preproecssing to split the input with whitespaces. The split chunks are not always a word.
