### ISSUE TITLE
How to disable logging - "precompiled_charsmap is empty. use identity normalization"

### ISSUE THREAD

**Issue by Kyeongpil** [google/sentencepiece#694]
When I using SentencePieceProcessor, I got a lot of logs as follow:
normalizer.cc(51) LOG(INFO) precompiled_charsmap is empty. use identity normalization.

It annoys me when I applying multiprocessing, because SentencePieceProcessor produces many logs.

How can I disable logging when using SentencePieceProcessor?

**Comment by taku910** [comment]
Please see https://github.com/google/sentencepiece/issues/543

**Comment by Kyeongpil** [comment]
@taku910  What I need is to ignore logging generated by SentencePiecePorcessor, not the training session.
The issue that you recommended doesn't have information on how to ignore logging of SentencePieceProcessor.

**Comment by taku910** [comment]
v0.1.97 stops emitting this error message.
