### ISSUE TITLE
Is it possible to recover spm model from spm vocab?

### ISSUE THREAD

**Issue by BrightXiaoHan** [google/sentencepiece#696]
I deleted spm model by mistake. Can I recover spm model from only vocab?

**Comment by lijiekiff** [comment]
Hello. Is it possible to generate spm vocab from spm model?  Thanks

**Comment by lijiekiff** [comment]
> Hello. Is it possible to generate spm vocab from spm model? Thanks

I wanna unigram vocab file.

**Comment by BrightXiaoHan** [comment]
Hi, use this command
```
spm_export_vocab --model spm.model --output spm.vocab
```

**Comment by BrightXiaoHan** [comment]
As for recover spm.model from spm.vocab, it is impossible. But if you train your model with same data, command and random seed, the model and the vocab will be same.
