### ISSUE TITLE
Version of protoc required and alternative to libprotobuf9v5 for Red Hat

### ISSUE THREAD

**Issue by WataruHibiki** [google/sentencepiece#7]
Hi,

I am trying to install sentencepiece following the instructions given in README, on a Red Hat distribution, and the make command gives me an error indicating that my protoc version is not adapted for sentencepiece_model.pb.h. May I ask which version was used to generate the file?

Also, it seems that no package libprotobuf9v5/libprotobuf-c++ is available for RHEL (I found for Ubuntu and Debian). Would there be an alternative to it? Thanks a lot.

Here is the detailed result:

> $ make
make  all-recursive
make[1]: Entering directory \`/data/sentencepiece'
Making all in src
make[2]: Entering directory \`/data/sentencepiece/src'
make  all-am
make[3]: Entering directory \`/data/sentencepiece/src'
g++ -DHAVE_CONFIG_H -I. -I.     -std=c++11 -Wall -O3      -MT builder.o -MD -MP -MF .deps/builder.Tpo -c -o builder.o builder.cc
In file included from builder.h:22:0,
                          from builder.cc:15:
sentencepiece_model.pb.h:12:2: error: #error This file was generated by a newer version of protoc which is
 #error This file was generated by a newer version of protoc which is
  ^
sentencepiece_model.pb.h:13:2: error: #error incompatible with your Protocol Buffer headers. Please update
 #error incompatible with your Protocol Buffer headers.  Please update
  ^
sentencepiece_model.pb.h:14:2: error: #error your headers.
 #error your headers.
  ^
sentencepiece_model.pb.h:22:35: fatal error: google/protobuf/arena.h: No such file or directory
 #include <google/protobuf/arena.h>
                                   ^
compilation terminated.
make[3]: *** [builder.o] Error 1
make[3]: Leaving directory \`/data/sentencepiece/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory \`/data/sentencepiece/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory \`/data/sentencepiece'

Then I downloaded the latest release of Protocol Buffer (v3.2.0) in C++, from https://github.com/google/protobuf/releases and compiled it.

When I try the 'make' command again, I got another error saying that this version is too new :

> $ make
make  all-recursive
make[1]: Entering directory \`/data/sentencepiece'
Making all in src
make[2]: Entering directory \`/data/sentencepiece/src'
make  all-am
make[3]: Entering directory \`/data/sentencepiece/src'
g++ -DHAVE_CONFIG_H -I. -I..     -std=c++11 -Wall -O3   -MT builder.o -MD -MP -MF .deps/builder.Tpo -c -o builder.o builder.cc
In file included from builder.h:22:0,
                 from builder.cc:15:
sentencepiece_model.pb.h:17:2: error: #error **This file was generated by an older version of protoc which is**
#error This file was generated by an older version of protoc which is
  ^
sentencepiece_model.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
#error incompatible with your Protocol Buffer headers.  Please
  ^
sentencepiece_model.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
#error regenerate this file with a newer version of protoc.
  ^
In file included from builder.h:22:0,
                 from builder.cc:15:
sentencepiece_model.pb.h: In member function ‘const string& sentencepiece::TrainerSpec::model_prefix() const’:
sentencepiece_model.pb.h:938:95: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return model_prefix_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                               ^
sentencepiece_model.pb.h:938:95: note: candidate is:
In file included from sentencepiece_model.pb.h:23:0,
                 from builder.h:22,
                 from builder.cc:15:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
In file included from builder.h:22:0,
                 from builder.cc:15:
sentencepiece_model.pb.h: In member function ‘const string& sentencepiece::NormalizerSpec::name() const’:
sentencepiece_model.pb.h:1477:87: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return name_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                       ^
sentencepiece_model.pb.h:1477:87: note: candidate is:
In file included from sentencepiece_model.pb.h:23:0,
                 from builder.h:22,
                 from builder.cc:15:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
In file included from builder.h:22:0,
                 from builder.cc:15:
sentencepiece_model.pb.h: In member function ‘const string& sentencepiece::NormalizerSpec::precompiled_charsmap() const’:
sentencepiece_model.pb.h:1531:103: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return precompiled_charsmap_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                                       ^
sentencepiece_model.pb.h:1531:103: note: candidate is:
In file included from sentencepiece_model.pb.h:23:0,
                 from builder.h:22,
                 from builder.cc:15:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
In file included from builder.h:22:0,
                 from builder.cc:15:
sentencepiece_model.pb.h: In member function ‘const string& sentencepiece::ModelProto_SentencePiece::piece() const’:
sentencepiece_model.pb.h:1664:88: error: no matching function for call to ‘google::protobuf::internal::ArenaStringPtr::GetNoArena(const string*) const’
   return piece_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
                                                                                        ^
sentencepiece_model.pb.h:1664:88: note: candidate is:
In file included from sentencepiece_model.pb.h:23:0,
                 from builder.h:22,
                 from builder.cc:15:
/usr/local/include/google/protobuf/arenastring.h:225:31: note: const string& google::protobuf::internal::ArenaStringPtr::GetNoArena() const
   inline const ::std::string& GetNoArena() const { return *ptr_; }
                               ^
/usr/local/include/google/protobuf/arenastring.h:225:31: note:   candidate expects 0 arguments, 1 provided
make[3]: *** [builder.o] Error 1
make[3]: Leaving directory \`/data/sentencepiece/src'
make[2]: *** [all] Error 2
make[2]: Leaving directory \`/data/sentencepiece/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory \`/data/sentencepiece'
make: *** [all] Error 2

Thanks for your help.

**Comment by elliottd** [comment]
@WataruHibiki if you are installing protobuf from source, you are looking for [libprotobuf v3.0 ](https://github.com/google/protobuf/releases/tag/v3.0.0)

**Comment by WataruHibiki** [comment]
@elliottd Thanks, it works now!

Also, not being able to find the package, I haven't installed libprotobuf9v5.
