### ISSUE TITLE
Unigram training always crashes when making suffix array

### ISSUE THREAD

**Issue by MatthewBieda** [google/sentencepiece#702]
Attempting to train 16 million parallel sentences separately by source (English) and target (Japanese) on an EC2 instance with 500GB RAM. 

Command is spm.SentencePieceTrainer.train('--input=English_lowercased_mosespretok.txt --vocab_size=32000 --num_threads=64 --train_extremely_large_corpus=true --model_prefix=English') .

Also tested with default 16 threads and large_corpus=false, training always gets to building the suffix array then crashes after it starts using multiple cores. 

However the vocab file and model file are saved regardless, is it ok to use them in production even though the process hangs?

**Comment by taku910** [comment]
Sencencepice training requires large heap memory as it loads all input sentences to build suffix array.
Please runs the command with the computer, or restrict (sample) the input data with --input_sentence_size

**Comment by thusinh1969** [comment]
i9 8 core, 256G RAM, huge 10T disk. Corpus 174m sentences, intended to create 50,000 vocab. Keep crashing silently. Why ? What can I do better ?

Steve

**Comment by thusinh1969** [comment]
Found! For each 10m sentences, you would need appx. 70G of RAM, that is it. I can train 36m sentence for 40,000 vocab with 256G RAM with unigram.

**Comment by MatthewBieda** [comment]
Glad you solved this.
