### ISSUE TITLE
How to Implement the decoder and encode of BPEmb with given list of words. 

### ISSUE THREAD

**Issue by istiaq28** [google/sentencepiece#706]
If I am not wrong, when training, sentencepiece merges the most frequent words. While doing that it creates a list of words and creates a spm model, word2vec who uses that list of words to either decode or encode words. 
I don't know how they work, But I would like to create a list of words first. Then use that to encode and decode any given words. 
Can anyone point me towards the right direction. Where and what to search for to achieve my task?

**Comment by xiefangqi** [comment]
Someone already using sentencepieces to do something about it, https://github.com/bheinzerling/bpemb/blob/9bcde40d870fc66d9b183c5f4f81dd3b4bff8c31/bpemb/bpemb.py

**Comment by taku910** [comment]
sentencepiece can train the model from word list with frequency.

```
% spm_train --input=input.tsv --input_format=tsv --
```
where input.tsv is written as 

```
<word>  <tab> <frequency>
```
