### ISSUE TITLE
Does sentencepiece support incremental encoding?

### ISSUE THREAD

**Issue by Litchilitchy** [google/sentencepiece#707]
Suppose my data contains some new words, so that I need to update my corpus.

Does it support the `.model` update? Or is there any preferred way to do it? (For example when data updates, the optimized encoding schema may also change so normal incremental encoding may not be the best choice)

**Comment by xiefangqi** [comment]
Currently, the Python interface does not provide the corresponding function. However, the C++ test code provides some examples:
`
ModelProto MakeBaseModelProto() {
  ModelProto model_proto;
  auto *sp1 = model_proto.add_pieces();
  auto *sp2 = model_proto.add_pieces();
  auto *sp3 = model_proto.add_pieces();

  sp1->set_type(ModelProto::SentencePiece::UNKNOWN);
  sp1->set_piece("<unk>");
  sp2->set_type(ModelProto::SentencePiece::CONTROL);
  sp2->set_piece("<s>");
  sp3->set_type(ModelProto::SentencePiece::CONTROL);
  sp3->set_piece("</s>");

  return model_proto;
}

void AddPiece(ModelProto *model_proto, const std::string &piece,
              float score = 0.0) {
  auto *sp = model_proto->add_pieces();
  sp->set_piece(piece);
  sp->set_score(score);
}

TEST(BPEModelTest, EncodeTest) {
  ModelProto model_proto = MakeBaseModelProto();

  AddPiece(&model_proto, "ab", 0.0);         // 3
  AddPiece(&model_proto, "cd", -0.1);        // 4
  AddPiece(&model_proto, "abc", -0.2);       // 5
  AddPiece(&model_proto, "a", -0.3);         // 6
  AddPiece(&model_proto, "b", -0.4);         // 7
  AddPiece(&model_proto, "c", -0.5);         // 8
  AddPiece(&model_proto, "ABC", -0.5);       // 9
  AddPiece(&model_proto, "abcdabcd", -0.5);  // 10
  AddPiece(&model_proto, "q", -0.5);         // 11
  AddPiece(&model_proto, "r", -0.5);         // 12
  AddPiece(&model_proto, "qr", -0.5);        // 13
  model_proto.mutable_pieces(9)->set_type(   // ABC
      ModelProto::SentencePiece::USER_DEFINED);
  model_proto.mutable_pieces(10)->set_type(  // abcdabcd
      ModelProto::SentencePiece::USER_DEFINED);
  model_proto.mutable_pieces(11)->set_type(  // q
      ModelProto::SentencePiece::USER_DEFINED);
  model_proto.mutable_pieces(12)->set_type(  // r
      ModelProto::SentencePiece::USER_DEFINED);

  const Model model(model_proto);

  EncodeResult result;

  result = model.Encode("");
  EXPECT_TRUE(result.empty());
}
`
You can refer to the AddPiece function above. Not sure if this is officially recommended behavior.

**Comment by Litchilitchy** [comment]
@xiefangqi Thanks, that's a great feature.

**Comment by taku910** [comment]
Model file is a serialized protobuf, so it is tehinically possible to manually modify/update the model file.
However, please do it at your own risk. Sentencepiece doesn't assume the case the model is modified outside of the model trainer.

Please see this issue to update the model.
https://github.com/google/sentencepiece/issues/121
