### ISSUE TITLE
Out of memory: Kill process PID (python) score 943 or sacrifice child

### ISSUE THREAD

**Issue by tkngoutham** [google/sentencepiece#708]
Process is getting 'killed' after OOM. Below is the the code.
file /path/to/file.txt  size: 68GB 
RAM size=59GB
16 cores ubuntu

import sentencepiece as spm

spm.SentencePieceTrainer.train('--input=/path/to/file.txt --model_type=bpe --vocab_size=60000 --model_prefix=SentencePieceBPE --pad_id=0 --unk_id=1 --bos_id=2 --eos_id=3 --pad_piece=[PAD] --unk_piece=[UNK] --bos_piece=[CLS] --eos_piece=[SEP]')

Kindly show if retraining on small chunks is possible

**Comment by xiefangqi** [comment]
https://github.com/google/sentencepiece/issues/680
The same oom problem which suggested to "Reduce the data to load e.g. --input_sentence_size=700000".

**Comment by taku910** [comment]
Sencencepice training requires large heap memory as it loads all input sentences to build suffix array.
Please runs the command with the computer, or restrict (sample) the input data with `--input_sentence_size`
