### ISSUE TITLE
undefined reference

### ISSUE THREAD

**Issue by lvbu12** [google/sentencepiece#711]
code:
#include <iostream>
#include <sentencepiece_processor.h>

using namespace std;

int main()
{
	sentencepiece::SentencePieceProcessor processor;
	const auto status = processor.Load("/root/sp.model");
	if(!status.ok())
	{
	   std::cerr << status.ToString() << std::endl;
	   // error
	}
	
	std::string text="床前明月光";
	
	std::vector<int> ids;

	processor.Encode(text, &ids);
	for (const int id : ids)
	{
 		std::cout << id << std::endl;
	}
	
	return 0;
}

error log:
tokenize.cpp:(.text+0x17)：undefined reference of ‘sentencepiece::SentencePieceProcessor::SentencePieceProcessor()’

**Comment by xiefangqi** [comment]
Do you link libsentencepiece.so and libsentencepiece_train.so when compiling?

**Comment by taku910** [comment]
You might need to add the linker flags obtained with pkg-config

```
% pkg-config sentencepiece --libs
-L/usr/local/lib -lsentencepiece -lsentencepiece_train
```
