### ISSUE TITLE
Training with sentence_iterator yields vocabulary size error

### ISSUE THREAD

**Issue by erip** [google/sentencepiece#717]
I have a script to train a unigram model using the `sentence_iterator` API:

```python
import io
import csv

import sentencepiece as spm

def get_text_column(file):
    with open(file, encoding='utf-8') as f:
        reader = csv.reader(f)
        for row in reader:
            yield row[1].strip()


if __name__ == "__main__":
    response = get_text_column('text_normalization_ag_news_test.csv')
    model = io.BytesIO()
    status = spm.SentencePieceTrainer.train(sentence_iterator=response, model_writer=model, vocab_size=23456)
```

This fails with 

> RuntimeError: Internal: /Users/travis/build/google/sentencepiece/src/trainer_interface.cc(590) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (23456). Please set it to a value <= 10426.

The same script using the `input` API seems fine:

```python
import sentencepiece as spm

if __name__ == "__main__":
    status = spm.SentencePieceTrainer.train(input='text_normalization_ag_news_test.csv', model_prefix='p', vocab_size=23456)
```

Is there something special I need to do to train roughly the same model using the same data? The CSV here is [here](https://raw.githubusercontent.com/pytorch/text/main/test/asset/text_normalization_ag_news_test.csv) in case it's relevant.

**Comment by erip** [comment]
The CSV here is [here](https://raw.githubusercontent.com/pytorch/text/main/test/asset/text_normalization_ag_news_test.csv) in case it's relevant.

**Comment by erip** [comment]
It seems like adding `hard_vocab_limit=False` to the `train` call will suppress the error, but I'm not sure if it's the equivalent thing to do...

**Comment by erip** [comment]
If I add `hard_vocab_limit` to false, I don't see the error but my serialized model's `GetPieceSize()` yields a number smaller than the set vocab size.

**Comment by taku910** [comment]
The training data seems too small so sentencepiece cannot allocate the enough vocab. hard_vocab_limit tries to allocate vocab in best-effort basis.

Each token needs to appear at least two times in the corpus, except for the single character token.
If the data is too small,  the total number of valid tokens could be small than the vocab size specified.

**Comment by erip** [comment]
So concretely the answer is that the models produced using the two methods are not equivalent?
