### ISSUE TITLE
Multiple input files for training

### ISSUE THREAD

**Issue by TaihouKai** [google/sentencepiece#722]
For `spm.SentencePieceTrainer.train()`, is it possible to feed multiple input files as training data into the model? My training data is super large, storing in the database, and I want to avoid memory issues as it may cause by loading them piece by piece.

**Comment by taku910** [comment]
You can feed mutiple files as a list or CSV.
```
SentencePieceTrainer.train(input=['foo.txt', 'bar.txt'], ...)   # new API
SentencePieceTrainer.train('--inpput=foo.txt,bar.txt --..')   # old API
```
