### ISSUE TITLE
spm.sentencePieceTrainer.train() Logs directed to specific file

### ISSUE THREAD

**Issue by AmmarKamran** [google/sentencepiece#724]
Hello, I hope you are well.

In your python API, I'm currently running:

`import sentencepiece as spm
spm.sentencePieceTrainer.train() 
`
with the relevant parameters. The logs are printed directly out onto the terminal. How can I channel the logs to a specific file? I couldn't seem to find the answer in your docs. I also check the list of parameters to this function here (https://github.com/google/sentencepiece#train-sentencepiece-model) but couldn't seem to find the answer.

Thanks in advance.

**Comment by AmmarKamran** [comment]
Hello, thanks for labelling this so far. Does the label "feature request" indicate that this functionality (of sending logs to a specific file) is not available yet?

**Comment by taku910** [comment]
Right. It is not available now, it is possible to suppress the logging message though.

**Comment by taku910** [comment]
v0.1.97 supports to specify logstream during training.

Here's the sample code.
https://github.com/google/sentencepiece/blob/master/python/test/sentencepiece_test.py#L210
