### ISSUE TITLE
Proportion when mixing languages

### ISSUE THREAD

**Issue by marton-avrios** [google/sentencepiece#725]
I want to train on a corpus which contains sentences from 2 or more different languages and I want the model to treat them equally important. Each language (or more precisely the data I have for them) has significantly different average sentence length. Should I include the same number of lines from each language or the same number of characters? Which one is more important?

**Comment by taku910** [comment]
The optimal params/mixtures depends on the data and the task, so it is difficult to give a clear answer. You might need to find the best params with a standard hyperparameter tuning methods, like cross-validations. Thank you.
