### ISSUE TITLE
Vocabulary Min and Max Size

### ISSUE THREAD

**Issue by panizbehboudian** [google/sentencepiece#727]
Hi,

Thanks for sharing the project publicly. Apparently with a certain corpus there's a valid range of vocab-size [a,b] and going beyond  the range will raise an error like (e.g. if you choose a number c > b) :
`RuntimeError: Internal: src/trainer_interface.cc(590) [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (c). Please set it to a value <= b.`
So I was wondering if there's a way to know/estimate the range without trial and error and how this range is determined?

Best,
Paniz

**Comment by taku910** [comment]
No. there isn't. Usually, this error occurs when training the model from extremely small corpus.  Easiest workaround is to increase the training data.
