### ISSUE TITLE
importing sentencepiece on kubernetes raise iostream error 

### ISSUE THREAD

**Issue by teang1995** [google/sentencepiece#729]
Hi, importing sentencepiece on kubernetes raise iostrem error.
Here is the result of command `cat /etc/os-release`.
```
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="
https://www.debian.org/
"
SUPPORT_URL="
https://www.debian.org/support
"
BUG_REPORT_URL="
https://bugs.debian.org/
"
```
and below is the error i saw.
```
terminate called after throwing an instance of 'std::__ios_failure'
  what():  basic_filebuf::underflow error reading the file: iostream error
```

python version is 3.7 and i installed requirements for sentencepiece using command  `RUN apt-get install -y cmake build-essential pkg-config libgoogle-perftools-dev` at Dockerfile.

**Comment by taku910** [comment]
It seems that this is an OS or machine specific issue. ios error occurs when the read/write file fails, which is outside of sentencepiece library. Could you show the actual command line or code so we can reproduce this error?

**Comment by taku910** [comment]
We are going to close this bug as there is no update.

**Comment by taku910** [comment]
Let me close this bug.
