### ISSUE TITLE
Training ignores vocab_size?

### ISSUE THREAD

**Issue by jbmaxwell** [google/sentencepiece#730]
I'm training on data (not natural-language) and finding that I can't set a larger `vocab_size`—e.g., I indicate 4000 in the parameter, but the training produces a vocab of 437 tokens (and encoded sentences are almost character-level much of the time).

Anything I should check?

**Comment by jbmaxwell** [comment]
...or I get an error: " [(trainer_spec_.vocab_size()) == (model_proto->pieces_size())] Vocabulary size too high (4000). Please set it to a value <= 497."

**Comment by taku910** [comment]
this error happens when the input corpus is too small and cannot reserve the specified vocabs. Please use `--hard_vocab_limit=true` or feed large training data.
