### ISSUE TITLE
How to train with custom vocab

### ISSUE THREAD

**Issue by Cross-Caps** [google/sentencepiece#733]
I have a few custom symbols in a vocab.json file.
How I can pass these to the tokenizer for training so that it can include these?

PS: I tried using user_defined_symbols['yi', 'aa']
but got error     `can only concatenate str (not "list") to str`

**Comment by taku910** [comment]
Please read the document for the special symbols.
https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md
