### ISSUE TITLE
Vocabulary issues loading pretrained bpemb

### ISSUE THREAD

**Issue by LucWeber** [google/sentencepiece#734]
Hey,

I am trying to load pre-trained embeddings ([bpemb](https://github.com/bheinzerling/bpemb)). Those are implemented using sentencepiece. 

Loading them using 

```
!pip install bpemb

from bpemb.bpemb import BPEmb

embeddings = BPEmb(lang='en')
```
in a python(3.7) console works fine. However, if I put things into a python-script and run that, it gives me a memory-error (Segmentation fault (core dumped)). The memory available / environment is exactly the same. 

Looking deeper into it, I find that sentencepiece assumes a huge vocabulary in the script case:
```
from sentencepiece import SentencePieceProcessor

file = /path/to/en.wiki.bpe.vs1000.model 
spm = SentencePieceProcessor() 
spm.Load(str(file)) 
spm.vocab_size() 
```
Which gives me a vocab size of 1569482480 (most likely producing the memory error as soon as I access it), even though the original vocab-size is 1000.

I tried out different versions of sentencepiece, but always get the same behaviour. I am very puzzled right now.

Let me know if there is anything else you need to know. Thanks!

**Comment by taku910** [comment]
Okay, then this issue will be caused by the utils-script. Could you please ask the developer of utils-script?
If you find the errors during the model loading,  could you share the model file so that I can reproduce the error in our environment?
