### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(890)

### ISSUE THREAD

**Issue by aahad5555** [google/sentencepiece#736]
Having this issue in preprocessing everything looks fine but the problem still exists!!!

**Comment by taku910** [comment]
Let me close this bug due to lack of specific information and inability to reproduce.

**Comment by aahad5555** [comment]
> Let me close this bug due to lack of specific information and inability to reproduce.

I provided the issue with full reference but it seems deleted now... why?? It appears the model is not available on hugging face either now.
