### ISSUE TITLE
Training fails on Darts - failed to modify unit: too large offset

### ISSUE THREAD

**Issue by Eytan-S** [google/sentencepiece#737]
Hi,
During training I get the following error:

> unigram_model_trainer.cc(194) LOG(INFO) Initialized 104857600 seed sentencepieces
terminate called after throwing an instance of 'Darts::Details::Exception
  what():  third_party/darts_clone/darts.h:1380: exception: failed to modify unit: too large offset

Not sure if this is related, but I'm using a pretty large corpus, are there limits on the number of sentences/chars/alphabet size?

Thanks!

**Comment by taku910** [comment]
I think the vocab size is too big. (larger than 1 << 29).

**Comment by Eytan-S** [comment]
Thanks Taku, but I don't think that's the case here.. 
My failing run had input_sentence_size=50000000 (50m), I ran again but limited the input_sentence_size to 30000000 and it worked this time. I don't know if that's the root cause of the issue but maybe that could help in finding it.

**Comment by taku910** [comment]
Since the training data is too big, the seed vocab will be too big and the size exceeds the limit of darts library.  
sentencepiece starts from large vocab and shrink its size incrementally during the training.

Anyway, the workaround is to reduce the training data. Thank you.

**Comment by taku910** [comment]
Since the training data is too big, the seed vocab will be too big and the size exceeds the limit of darts trie library.  
sentencepiece starts from large vocab and shrink its size incrementally during the training.

Anyway, the workaround is to reduce the training data. Thank you.

**Comment by Eytan-S** [comment]
Yeah, that's what I'm doing now. 
Thank you!
