### ISSUE TITLE
Exception occurs when reading the saved model again

### ISSUE THREAD

**Issue by zchu-hit-scir** [google/sentencepiece#738]
After modifying pieces and saving model, an exception occurs when reading the saved model again.
RuntimeError: Internal: there are not 256 byte pieces although `byte_fallback` is true.``
```
m = sp_pb2_model.ModelProto()
m.ParseFromString(tokenizer.sp_model.serialized_model_proto())
new_pieces = ....get new pieces...
del m.pieces[:]
m.pieces.extend(new_pieces)
with open(save_path, 'wb') as f:
    f.write(m.SerializeToString())

tokenizer = AutoTokenizer.from_pretrained(save_path)
RuntimeError: Internal: there are not 256 byte pieces although `byte_fallback` is true.``
```
`

**Comment by taku910** [comment]
Seems that original model is built with `byte_fallback` is true, while you've just deleted the reserved tokens for byte fallback.
Model modification is not officially supported.  Please do so at your own risk.  Let me close this issue.

**Comment by Pay20Y** [comment]
> Seems that original model is built with `byte_fallback` is true, while you've just deleted the reserved tokens for byte fallback. Model modification is not officially supported. Please do so at your own risk. Let me close this issue.

Sorry to bother, it seems that when a model is built with byte_fallback,  it does not support SetVocabulary anymore, even the input parameter of the SetVocabulary is all the pieces from the original model, that's right?
