### ISSUE TITLE
[Query/Help] Pieces Field in ModelProto

### ISSUE THREAD

**Issue by abheesht17** [google/sentencepiece#739]
@taku910 and the rest of the sentencepiece team:

I've been going through the [ModelProto spec](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L271). It has a proto, [SentencePiece](https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L272-L290). Does every "piece" represent a merge?

So, for example, when we talk about BPE, at every iteration, we have a merge. The encoding (given a string) is done on the basis of a list of merges (these merges are formed during the training process). So, is the `pieces` field a list of these "merges"?

For example, Hugging Face has a [ `merges.txt`](https://huggingface.co/gpt2/tree/main) for every text file, and they use this to tokenise the text. So, if `pieces` is equivalent to `merges`, I can convert the merges in `merges.txt` (to a suitable format), and populate `pieces` in `ModelProto`.

Thanks!

**Comment by abheesht17** [comment]
I went through the unit tests for the tokenizer: https://github.com/google/sentencepiece/blob/bc53923a9147dc8ffa54034c8ed774de78cc4d39/src/bpe_model_test.cc#L52. Does `pieces` represent tokens from the vocabulary? What then does `score` mean?

**Comment by taku910** [comment]
Yes, pieces are the vocab.

Each piece has a score field (The larger is better). In unigram model, score is log prob. In BPE, the score is merge-priority.
For the sake of convenience, the BPE score starts from 0.0.

The vocab that has larger score has merged first.    For example,  if we can merge "ab" and "bc"   in the text "abc",   "ab" is merged first.  Then the output will be "ab" "c". (if "abc" is not in the vocab)

By the way,  manual model modification/creation is totally unsupported. Please do it at your own risk.
