### ISSUE TITLE
“sentencepiece_processor.h”: No such file or directory

### ISSUE THREAD

**Issue by Helmsman-Lab** [google/sentencepiece#741]
cl: 命令行 warning D9025 :正在重写“/MD”(用“/MT”)
      sentencepiece_wrap.cxx
      src/sentencepiece/sentencepiece_wrap.cxx(2809): fatal error C1083: 无法打开包括文件: “sentencepiece_processor.h”: No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> sentencepiece

**Comment by Helmsman-Lab** [comment]
win10
Python 3.10.2

**Comment by taku910** [comment]
wheel package for windows on python3.10 is not available yet.
Please check the following batch script to build the wheel package.

https://github.com/google/sentencepiece/blob/master/test.bat

**Comment by TodayWei** [comment]
o，the same error， how to install on win10 and win11？？？
