### ISSUE TITLE
Char based tokenization, meta-pieces

### ISSUE THREAD

**Issue by vsokolov00** [google/sentencepiece#742]
My data have \<unk> tokens in the training and reference data, why does the sentencepiece handles it as 4 separate tokens '<', 'u', 'n', 'k' '>', at least they appear in the .vocab file.
For example:
```
<unk>   0
▁       -1.39806
u       -2.31998
<      -2.4668
n       -2.5174
k        xxxx
>       xxxx       
```

And why does the \<unk> always has 0 log probability regardless of the tokenization method? Isn't it log(P)?

I use sentencepiece with the integration with Speechbrain:
```
tokenizer: !name:speechbrain.tokenizers.SentencePiece.SentencePiece
   model_dir: output
   vocab_size: 28
   annotation_train: train.csv
   annotation_read: wrd
   model_type: char 
   character_coverage: 1.0
   annotation_list_to_check: [train.csv, valid.csv]
   annotation_format: csv
```

**Comment by taku910** [comment]
"<unk>" (and <s>, </s> and <pad>) is a control symbols that should not appear in the input.
https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md

If you want to insert the "<unk>",  please use the python module.
