### ISSUE TITLE
Tokens and values 

### ISSUE THREAD

**Issue by Dhurim** [google/sentencepiece#744]
I am using xlnet in an old english corpus and I am not being able to find how to make xlnet not consider "+" as a word.

E.g I have Adrianus cw+a+d to Ritheus .

It takes word cw+a+d into 5 tokens instead of one "cw", "+", "a", "+", "d"

Checked on sentencepiece but could not find anything. Can someone please help me.

**Comment by taku910** [comment]
It seems that you might not understand the behavior of subwording.  Even if we can handle "cw+a+d" as one token, it would be OOV.
