### ISSUE TITLE
input_sentence_size for std::bad_alloc

### ISSUE THREAD

**Issue by saiefulEZO** [google/sentencepiece#746]
Hello, So.. I have an extremely large data(around 136Mil lines) running on SentencePiece Unigram and encountered termination due to `std::bad_alloc.` . There's a lot of people recommended to use `--input_sentence_size ` for bad_alloc exception. Obviously I wanted to train the whole data, but I was wondering if I restrict the size, will it affect the accuracy of the tokenization? I am currently running it on a PC that have 125GB RAM and 263GB Swap (apparently its still not enough for 136Mil lines). If there's other work around for this, please do share..

Thank you.

**Comment by taku910** [comment]
Sampling works well in general unless the vocab size is extremely large. Subwording just uses the most frequent 32k-64k tokens.
The nature of high-frequency tokens does not change much after sampling
