### ISSUE TITLE
Any way to load from Huggingface `tokenizer.json` file?

### ISSUE THREAD

**Issue by jbmaxwell** [google/sentencepiece#748]
I've trained a SentencePieceBPETokenizer from Huggingface on my data and want to use it in a TF script that utilizes the SentencepieceTokenizer from `tensorflow-text`. Is there any way to load or convert Huggingface's `tokenizer.json` for use with this tokenizer? The main components—the `vocab` and `merges`—are the key elements, which seem to be pretty standard across libraries.

To clarify why I want to do this, if I train the Huggingface SentencePieceBPETokenizer on my data, with `vocab_size=4000`, I get a 4000-token vocab. If I train Google's model, I get an error when indicating 4000 and can't get more than around 1400 tokens without error.
 I want a larger vocab partly to keep sequence lengths down and partly to leverage the format of my data (following AI21's thoughts on larger vocabs). So, since I can't force the `vocab_size` from the Google model, I'm wondering if I can load the vocab (and merges?) from the Huggingface model into the Google version, to run in a TF-based training script I'm using.

**Comment by jbmaxwell** [comment]
For example, is there any way to instantiate a SentencepieceTokenizer, and manually "feed" it the vocab?... Are `user_defined_symbols` treated as regular vocabulary items at runtime?

**Comment by taku910** [comment]
Sorry, we cannot handle the issues of the libraries that use sentencepiece.

You can write the model file manually, but it is unsupported and please do at your own risk.

https://github.com/google/sentencepiece/issues/473

**Comment by jbmaxwell** [comment]
If not directly  a Sentencepiece issue then it certainly caused by one , since it appears that its training can't meet the specified `vocab_size` (whereas the huggingface trainer can). My question is more about a workaround for this problem in Sentencepiece. 

Specifically, I'm wondering about my last question—i.e., are `user_defined_symbols` treated as regular vocabulary tokens at runtime? Some tokenizers (can't recall which) add them as a separate process in a way that significantly impacts performance, proportional to the number of tokens added.

**Comment by jbmaxwell** [comment]
Okay, I saw you comment in another issue that the "dictionary is basically immutable"... that should be clarified in the README file—it could save people from wasting time trying to modify it.

**Comment by keunwoochoi** [comment]
is there anyone who figured out how to do this?

**Comment by jbmaxwell** [comment]
It would be great, but no point looking for help here, in my experience.
