### ISSUE TITLE
How to deal with corpus with mixed language?

### ISSUE THREAD

**Issue by winston0410** [google/sentencepiece#749]
I have a corpus that would mix up Cantonese and English. It is the only source of data of that specific domain, so I don't have another cleaner source for training.

```
我去咗Central London食飯。
```

In the example sentence above, I am **only interested in Cantonese not English**, and I don't want to include any English in that trained output. Is it possible to ignore all the English here? Can I replace them with an unknown token like this?

```
我去咗<unk>食飯。
```

**Comment by taku910** [comment]
No. Please implements a preprocessor that removes English part.
