### ISSUE TITLE
import sentencepiece Error - ImportError: Library not loaded: @rpath/libsentencepiece.0.dylib

### ISSUE THREAD

**Issue by njsalazar** [google/sentencepiece#752]
I'm on MacOS 12.1 and using Python 3.10.1

I had to do a workaround to install as pip was failing.  I used these commands from the ReadMe

`% git clone https://github.com/google/sentencepiece.git`

`% cd sentencepiece`

`% mkdir build`

`% cd build`

`% cmake ..`

`% make -j $(nproc)`

`% sudo make install`

It's installed now, if I do `pip freeze` I see `sentencepiece==0.1.95`.

However if I try to run `import sentencepiece`. I get the below errors:

`import sentencepiece
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/__init__.py", line 13, in <module>
    from . import _sentencepiece`

`ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/_sentencepiece.cpython-310-darwin.so, 0x0002): Library not loaded: @rpath/libsentencepiece.0.dylib`

 ` Referenced from: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sentencepiece/_sentencepiece.cpython-310-darwin.so`

  `Reason: tried: '/usr/lib/libsentencepiece.0.dylib' (no such file)`

**Comment by taku910** [comment]
Please read the document.
https://github.com/google/sentencepiece#build-and-install-sentencepiece-command-line-tools-from-c-source

```
On OSX/macOS, replace the last command with sudo update_dyld_shared_cache
```
