### ISSUE TITLE
Wheel file missing on PIP for Python 3.10 on macos

### ISSUE THREAD

**Issue by mdm-code** [google/sentencepiece#758]
Guys, I can't install sentencepiece on macos. I guess it boils down to the wheel file missing. Can you add it to pypi?

**Comment by taku910** [comment]
Could you please build from the wheel source?   

```> cd python; python setup.py bdist_wheel;  pip install dist/*.whl```

We've switched the CI build infrastructure from travis to github actions, and it is hard to build wheel binary packages of older releases.
The 3.10 support on mac os will be available from the next release 0.1.97.

The wheelpackage of release candidate is available from 
https://github.com/google/sentencepiece/actions/runs/2526530161

artifact.zip contains the all wheelpackages including python3.10 for macos.

**Comment by mdm-code** [comment]
@taku910 Thank you very much. I'll try to do so and I'll get back you.
