### ISSUE TITLE
ImmutableSentencePieceText::pieces() will get the empty size vector.

### ISSUE THREAD

**Issue by cart0909** [google/sentencepiece#764]
Hi all,
Thanks for developing this great library which is contributing every NLP work.

I got some troubles when I tried to get the all tokens from the API by calling the below function. 
https://github.com/google/sentencepiece/blob/901368e0752b57a408ac5c84bca0a219d62c648f/src/sentencepiece_processor.cc#L93
I always got the empty vector.

I am just curious about why don't use the `emplace_back` in vector?
```c++
std::vector<ImmutableSentencePieceText::ImmutableSentencePiece>
ImmutableSentencePieceText::pieces() const {
  std::vector<ImmutableSentencePieceText::ImmutableSentencePiece> pieces;
  if (spt_ == nullptr) return pieces;
  pieces.reserve(spt_->pieces_size());
  for (int i = 0; i < spt_->pieces_size(); ++i)
    pieces[i] = ImmutableSentencePiece(spt_->pieces(i)); // <-------- pieces.emplace_back(spt_->pieces(i));
  return pieces;
}
```
When I changed the code and rebuilt it, the behaviors are expected in my local.

Same as this function.
https://github.com/google/sentencepiece/blob/901368e0752b57a408ac5c84bca0a219d62c648f/src/sentencepiece_processor.cc#L147

**Comment by taku910** [comment]
Thank you for the report.  This issue is already fixed.

In general, we want to avoid push_back/emplace_back if we know the size of vector in advance.
We needed to use "reverse" instead of "resize" here.
