### ISSUE TITLE
Invalid trace stack for exception of type: std::length_error

### ISSUE THREAD

**Issue by pichuang1984** [google/sentencepiece#765]
I am trying to create a sentencePiece vocab with a dataset that has ~90M sentences and 8.5B character count.

I am getting the following error during the process:
```
W0719 10:03:39.146420 3947509 ExceptionTracer.cpp:187] Invalid trace stack for exception of type: std::length_error
terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
```

Here is the log that leads to this error:
```
trainer_interface.cc(385) LOG(INFO) all chars count=8497854102
trainer_interface.cc(393) LOG(INFO) Done: 99.99% characters are covered.
trainer_interface.cc(403) LOG(INFO) Alphabet size=1002
trainer_interface.cc(404) LOG(INFO) Final character coverage=0.9999
trainer_interface.cc(436) LOG(INFO) Done! preprocessed 88628457 sentences.
```

Wondering if anyone else has encountered this problem before and how to bypass it?

**Comment by taku910** [comment]
length_error is raised when more than 4G entries are added to std::vector.  You might want to sample the data with ``--input_sentence_size`` flag.
