### ISSUE TITLE
How to identify subwords in the tokenization results?

### ISSUE THREAD

**Issue by ryangawei** [google/sentencepiece#767]
Hi,

Is there a way to tell if certain tokens are subwords split from whole words? For example, I have the following SQL query,
```
select tourney_name from matches group by tourney_name having count(*)  >  10 order by desc
```
And the tokenization result is
```
"['▁select', '▁tourne', 'y', '_', 'name', '▁from', '▁matches', '▁group', '▁by', '▁tourne', 'y', '_', 'name', '▁having', '▁count', '(', '*', ')', '▁>', '▁10', '▁order', '▁by', '▁des', 'c', '</s>']"
```

Is it possible to know from the result that `'▁select'` is a whole word while `['y', '_', 'name',]` are subwords?

Thanks.

**Comment by taku910** [comment]
You can tell by checking if the next tokens begin with ```▁```.   

'▁select' :  next token is '▁tourne' and starts with ▁ => one word
'y': next token is '_' and doesn't' start with ▁  => part of word.

I'm afraid that this issue page is not the place to discuss general programming techniques.
Such questions are generally not accepted.
