### ISSUE TITLE
using C++ api

### ISSUE THREAD

**Issue by lyzKF** [google/sentencepiece#768]
i have installed the sentencepiece, and when i try to use c++ api, the error "undefined reference to `sentencepiece::SentencePieceProcessor::SentencePieceProcessor()'" always appears.

why?

**Comment by taku910** [comment]
you need to pass a linker option which is available with pkg-config command

```
% pkg-config sentencepiece --libs
-L/usr/local/lib/x86_64-linux-gnu -lsentencepiece -lsentencepiece_train
```

In this case, add ```-L/usr/local/lib/x86_64-linux-gnu -lsentencepiece -lsentencepiece_train``` to build/compiler options.
