### ISSUE TITLE
We need a new release (even a dev release.

### ISSUE THREAD

**Issue by johnml1135** [google/sentencepiece#769]
There are a lot of fixes that are difficult to use without this code being released.  Even a dev release (on pip) would be really helpful if it is not ready for production.  This has been causing a significant disruption to our workflow (it's not easy to install non released packages using poetry). 
  I see you are creating wheels on every commit to master.  One resolution could be to make a dev release on every master commit, such as "0.1.97.dev13", or on a periodic basis, such as the end of every week.

**Comment by taku910** [comment]
Thank you for the suggestion, but I don't have such bandwidth for that.

**Comment by johnml1135** [comment]
When is the next release scheduled for?  How much work goes into making a release?  Would assistance to setup a dev release schedule be welcomed?  We use sentencepiece here: https://github.com/sillsdev/silnlp and are often working with new languages.   Having a more steady release would be a big help and something we may be able to invest time into to make a reality.

**Comment by johnml1135** [comment]
Thank you for the new release!
