### ISSUE TITLE
Creating tokenizer from counts file?

### ISSUE THREAD

**Issue by sgondala** [google/sentencepiece#775]
Is there a way to create the tokenizer from the counts file? This would enable generating a tokenizer from extremely large corpuses feasible as we can use a Hadoop preprocessing step to create the word count statistics. This shouldn't change the correctness because, for languages like English, we don't consider subwords across word boundaries anyways.

**Comment by taku910** [comment]
Please see https://github.com/google/sentencepiece/issues/181 and https://github.com/google/sentencepiece/issues/359
