### ISSUE TITLE
SentencePieceProcessor.encode() breaks down special tokens that exist in vocabulary

### ISSUE THREAD

**Issue by armancohan** [google/sentencepiece#777]
Hi,
I am using the t5 sentencepice model:  `gs://t5-data/vocabs/cc_all.32000/sentencepiece.model`.
The `SentencePieceProcessor.encode()` function does _not_ seem to recognize the special tokens (e.g., `<pad>`,`</s>`), while these tokens do exist in the vocab.

```
gsutil cp gs://t5-data/vocabs/cc_all.32000/sentencepiece.model /tmp/
```

```python
import sentencepiece as spm
s = spm.SentencePieceProcessor(model_file='/tmp/sentencepiece.model')

# Check that EOS exists in the model vocab, get the token corresponding to EOS
s.IdToPiece(s.eos_id())
Out: '</s>'

# Encode EOS string to its id, it doesn't work, breaks it down to smaller pieces
s.encode('</s>')
Out: [3, 2, 87, 7, 3155]

s.IdToPiece([3, 2, 87, 7, 3155])
Out: ['▁', '<unk>', '/', 's', '>']
```

Am I using the wrong function to encode the text into ids?

**Comment by taku910** [comment]
This is a FAQ. https://github.com/google/sentencepiece/issues/667
