### ISSUE TITLE
fatal error: string_view: No such file or directory

### ISSUE THREAD

**Issue by TheHonestBob** [google/sentencepiece#778]
when I pip install sentencepiece or compile sentencepiece，there is error occur，
![微信截图_20220830154237](https://user-images.githubusercontent.com/58240629/187379421-bbab62dd-0cc3-49d2-b763-1c6d71088cef.png)

**Comment by taku910** [comment]
building sentencepiece from source requires C++ 17 feature that includes string_view support. You might be able to fix this issue by updating the build environment.
https://en.cppreference.com/w/cpp/string/basic_string_view
