### ISSUE TITLE
how do i too add the extra_ids already for the tokenizer such that i could keep the extra_ids=0

### ISSUE THREAD

**Issue by StephennFernandes** [google/sentencepiece#779]
I've been seeing in the mt5 tokenizer the extra 100 ids needed for the sentinel tokens come already included in the tokenizer. 
`'gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model'` 

how do i too train my own sentencepiece tokenizer where i could too include the 100extra already in my tokenizer, just like the original one above.

as i am training a variant of mt5 that covers multiple langugaes that the common mt5 does cover. i went on to training a unigram sentencpiece tokenizer with 250000 vocab_size but i tripped into confusion, on how to get the 100 extra_ids similar the the official mt5 tokenizer.

**Comment by taku910** [comment]
The model file is immutable, so we do not support modifying the model after training. However, the model file is just a serialized protobuf so it is technically possible to update the model (adding tokens) manually at-your-own-risk basis.

Please take a look at this thread.

https://github.com/google/sentencepiece/issues/121
