### ISSUE TITLE
ModelProto and trainer_spec.model_prefix() must be exclusive.

### ISSUE THREAD

**Issue by SE-Nickjackson** [google/sentencepiece#781]
arguments:
```--input=D:/Daip_Lab/lip_reading_recognition/dataset/tmp/tmp.txt
--model_prefix=D:/Daip_Lab/lip_reading_recognition/dataset/lrs3/spm100/spm_unigram100
--model_type=unigram
--vocab_size=100
--character_coverage=1.0
--hard_vocab_limit=false
--num_threads=16
--unk_id=3
--bos_id=0
--eos_id=2
--pad_id=1
```

It throws following error.
RuntimeError: Internal: C:\projects\sentencepiece\src\trainer_interface.cc(316) [(output_model_proto_ != nullptr && trainer_spec_.model_prefix().empty()) || (output_model_proto_ == nullptr && !trainer_spec_.model_prefix().empty())] ModelProto and trainer_spec.model_prefix() must be exclusive.

Can you help me?

**Comment by taku910** [comment]
This error happens when specifying both model_prefix and model_writer in the Python module. 

```
spm.SentencePieceTrainer.train(model_prefix='m', input='text', vocab_size=1000, model_writer=open('/dev/null', 'w'))
```

```
RuntimeError: Internal: src/trainer_interface.cc(334) [(output_model_proto_ != nullptr && trainer_spec_.model_prefix().empty()) || (output_model_proto_ == nullptr && !trainer_spec_.model_prefix().empty())] ModelProto and trainer_spec.model_prefix() must be exclusive.
>>> 
```

**Comment by taku910** [comment]
Will close this issue in two weeks if there is no update.

**Comment by taku910** [comment]
Let me close this bug as there is no update.
