### ISSUE TITLE
create sentencepiece from own vocab file

### ISSUE THREAD

**Issue by berkuva** [google/sentencepiece#783]
I am very new to using sentencepiece.

I am trying to convert DNA sequences into sentencepiece. My file contains a list of sequences.
For example, two sequences would look like this:
ACTGCACAGTCAGTA
AAACGTGTGTGACCC
...
Using sentencepiece from pretrained English such as test/test_model.model, each DNA letter is considered a word. The ideal case would be to break down each sequence into a sequence of k-mers. For example,
ACTGCACAGTCAGTA consisting of three "words": ACTGC ACAGT CAGTA, if k=5. Is this possible?

It's not clear to me what model_file's are so I am not sure how to convert DNA sequences to sentencepiece. I am using the python module. Right now I am getting `RuntimeError: Internal: src/sentencepiece_processor.cc(891) [model_proto->ParseFromArray(serialized.data(), serialized.size())] `

My goal is to use BigBird in Huggingface, which uses sentencepiece tokenization.

I appreciate your help. Thanks.

**Comment by taku910** [comment]
We can limit the length of tokens with  ``--max_sentencepiece_length=5``. However, this setting extracts the pieces of length 1..5.

Creating the vocab is not supported. Currently, the model and vocab can only be generated with the trainer and the training data.
However, it is technically possible to manually edit the model file. Please check the previous threads.
