### ISSUE TITLE
when I build from C++ source, meet fatal error: string_view.h: No such file or directory

### ISSUE THREAD

**Issue by MzY-1999** [google/sentencepiece#784]
I use gcc version 9.2.0 (GCC)

`make[2]: *** [src/CMakeFiles/sentencepiece-static.dir/model_factory.cc.o] Error 1
In file included from /home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/normalizer.h:26:0,
                 from /home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/model_interface.h:25,
                 from /home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/model_interface.cc:17:
/home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/sentencepiece_processor.h:21:25: fatal error: string_view.h: No such file or directory
compilation terminated.
src/CMakeFiles/sentencepiece-static.dir/build.make:537: recipe for target 'src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.o' failed
make[2]: *** [src/CMakeFiles/sentencepiece-static.dir/model_interface.cc.o] Error 1
In file included from /home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/normalizer.h:26:0,
                 from /home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/normalizer.cc:15:
/home/bit/data/ymz/vecalign-master/LASER-main/tools-external/sentencepiece-master/src/sentencepiece_processor.h:21:25: fatal error: string_view.h: No such file or directory
compilation terminated.
src/CMakeFiles/sentencepiece-static.dir/build.make:551: recipe for target 'src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.o' failed
make[2]: *** [src/CMakeFiles/sentencepiece-static.dir/normalizer.cc.o] Error 1
CMakeFiles/Makefile2:183: recipe for target 'src/CMakeFiles/sentencepiece-static.dir/all' failed
make[1]: *** [src/CMakeFiles/sentencepiece-static.dir/all] Error 2
Makefile:155: recipe for target 'all' failed
make: *** [all] Error 2`

I appreciate your help. Thanks.

**Comment by taku910** [comment]
string_view is the library available from C++17.  Seems that your build environment is old and doesn't support all the features of C++17.  Please upgrade your development environment.
