### ISSUE TITLE
Recommended corpus size

### ISSUE THREAD

**Issue by astariul** [google/sentencepiece#790]
My corpus has 60+ millions sentences.

When I train a SentencePiece tokenizer I get the following warning : 

> LOG(WARNING) Too many sentences are loaded! (60775390), which may slow down training.

I thought having as many training data as possible was a good thing. **But is there a specific training data size "soft limit" (i.e. adding more data over this limit wouldn't really change the output) ?**

**Comment by taku910** [comment]
We do not always need to train the model from larger data. I think sampling is sufficient.
Ssuwbword algorithm only uses the frequent 32-64k tokens.  The trend of frequent tokens does not change that much after sampling.
