### ISSUE TITLE
Continuous Tokenizer Training

### ISSUE THREAD

**Issue by dszhengyu** [google/sentencepiece#791]
Hi there, 

Can we continue the training for a SentencePiece tokenizer? 
We got a English tokenizer with 10K vocab_size, and want to train the tokenizer on Chinese corpus to learn additional 5K tokens, to have a final tokenizer with 10K of English tokens at the beginning (start from index 0) and 5K of Chinese tokens follows (start from index 10,000). 
Can we do that?

**Comment by taku910** [comment]
Sentencepiece doesn't support continuous training, but you can try to merge two models (En/Zh models) trained independently.

The models file a serialized protobuf. We can merge the "pieces" fields in the proto.
https://github.com/google/sentencepiece/issues/121
