### ISSUE TITLE
sentencepiece 0.1.97 re-released?

### ISSUE THREAD

**Issue by kenhys** [google/sentencepiece#794]
# Problem

I may be wrong, as far as I recalled, sentencepiece was released around June 6, 2022.

upstream monitoring system of debian, notified release of sentencepiece 0.1.97.
https://qa.debian.org/cgi-bin/watch?pkg=sentencepiece

Then that version of sentencepiece was packaged as 0.1.97-1.

After that, it seems that sentencepiece was released at Aug 7.
https://github.com/google/sentencepiece/releases/tag/v0.1.97

It causes mismatch of actual code base even though It says "0.1.97".
Could you release 0.1.98 in such a case?

Correct me, If I was wrong, @taku910

**Comment by taku910** [comment]
We had several v0.1.97 releases, but only the last one is the official latest release, and others were labeled as "pre-release". (This release will be labeled as non-production ready).

**Comment by kenhys** [comment]
> We had several v0.1.97 releases, but only the last one is the official latest release, and others were labeled as "pre-release". (This release will be labeled as non-production ready).

Thanks, I've mistaken pre-release, sorry to bother you.
