### ISSUE TITLE
self implemente add_tokens by requesting pb, encounter "Runtime error: X is already defined" when load sp model file

### ISSUE THREAD

**Issue by lsy641** [google/sentencepiece#797]
def add_tokens(self, tokens, vocab_file, model_file):
        m = proto_model.ModelProto()
        m.ParseFromString(open(model_file, "rb").read())
        for token in tokens:
            print(self.sp.piece_to_id(token))
            if self.sp.piece_to_id(token) == 0:
                new_token = proto_model.ModelProto().SentencePiece()
                new_token.piece = token
                new_token.score = 0
                m.pieces.append(new_token)
            if token not in self.encoder:
                self.encoder[token] = max(list(self.decoder.keys())) + 1
                self.decoder[self.encoder[token]] = token
        with open(model_file, 'wb') as f:
            f.write(m.SerializeToString())
        self.sp = spm.SentencePieceProcessor(model_file=model_file)
        with open(vocab_file, "w") as f:
            json.dump(self.encoder,f) 

Then I run:

    tokenizer.add_tokens(['<que>', '<desc>', '<kwd>', '<ans>'], os.path.join(args.tokenizer_path, 'vocab.json'), os.path.join(args.tokenizer_path, 'chinese_vocab.model'))

So far, it successfully updates model_file to local. But when I rerun:

    self.sp = spm.SentencePieceProcessor(model_file=model_file)

It reports:

  File "finetune_psyqa.py", line 279, in main
          File "finetune_psyqa.py", line 408, in <module>
        return self.LoadFromFile(model_file)
  File "/scratch/mihalcea_root/mihalcea0/lsiyang/miniconda3/envs/psyqa_cpm/lib/python3.8/site-packages/sentencepiece/__init__.py", line 310, in LoadFromFile
tokenizer = GPT2Tokenizer(os.path.join(args.tokenizer_path, 'vocab.json'), os.path.join(args.tokenizer_path, 'chinese_vocab.model'))
  File "/gpfs/accounts/mihalcea_root/mihalcea0/lsiyang/template-is-token/CPM-1-Finetune/data_utils/tokenization_gpt2.py", line 42, in __init__
    self.sp = spm.SentencePieceProcessor(model_file=model_file)
  File "/scratch/mihalcea_root/mihalcea0/lsiyang/miniconda3/envs/psyqa_cpm/lib/python3.8/site-packages/sentencepiece/__init__.py", line 447, in Init
    return _sentencepiece.SentencePieceProcessor_LoadFromFile(self, arg)
RuntimeError: Internal: <que> is already defined.

**Comment by taku910** [comment]
As the error message indicates, the newly added token (piece) is already in the vocab. In addition, adding an empty piece is not allowed.

Manual updating of the model is out of the scope of support, so please update the model at your-own-risk-basis.
