### ISSUE TITLE
libprotobuf-c++ does not exist

### ISSUE THREAD

**Issue by elliottd** [google/sentencepiece#8]
In README.md, you recommend to install `libprotobuf-c++` if `libprotobuf9v5` cannot be found but `libprotobuf-c++` [does not exist in the Ubuntu package repositories](http://packages.ubuntu.com/search?keywords=libprotobuf-c%2B%2B&searchon=names&suite=yakkety&section=all).

**Comment by taku910** [comment]
Could you take a look at the latest document, which lists per-version packages?
https://github.com/google/sentencepiece#required-packages-c
