### ISSUE TITLE
Is it allowed to rearrange index/id of each vocabulary?

### ISSUE THREAD

**Issue by lsy641** [google/sentencepiece#802]
Thank you for reading my question. I have a demand of rearranging vocabulary id and assigning scores freely to any token. Here is a background
 
Background:

Firstly, I want to manually add some tokens to a vocabulary that was trained with unigram model type. These tokens should allow other pieces to contain these tokens, so they are not user_defined_symbols. I want to manually assign them a score, so they can be sampled according to probability.

Secondly, I want to align the trained vocabulary with the other vocabulary. The other vocabulary makes indexes for those tokens I mentioned before. I hope the indexes for the common tokens in both vocabularies are of the same values. The indexes of other vocabularies are assigned with numbers after the last common index.

Could you please give me some advice about how to achieve this goal? Thank you

**Comment by taku910** [comment]
Creating and modifying the vocab/model are not supported. Currently, the model and vocab can only be generated with the trainer and the training data.
However, it is technically possible to manually edit the model file though it is just an at-your-own-risk-basis. Please check the previous threads. The model file is just a serialized protobuf, so it is easy to rewrite the model.

https://github.com/google/sentencepiece/issues/121
