### ISSUE TITLE
Training a BPE model w/ "identity" normalization rule doesn't add "\n" to the vocab

### ISSUE THREAD

**Issue by pks** [google/sentencepiece#804]
Training a BPE model w/ the identity normalization rule doesn't add the newline character to the vocab:

```
#!/bin/bash

../sentencepiece_upstream/build/src/spm_train \
  --input ../europarl-v7.de-en.en,../europarl-v7.de-en.de \
  --input_sentence_size 9999 \
  --model_prefix "bpe.joint" \
  --model_type "bpe" \
  --pad_id 3 \
  --pad_piece "<pad>" \
  --normalization_rule_name "identity" \
  --remove_extra_whitespaces 0
```

This causes unks when encoding strings w/ `\n`:
```
>>> import sentencepiece
>>> x=sentencepiece.SentencePieceProcessor("bpe.joint.model")
>>> x.encode_as_ids("asdf\nasdf\n", add_eos=True, add_bos=True)
[1, 174, 7930, 7936, 0, 41, 7930, 7936, 0, 2]
```
Without the identity normalization, newlines just get replaced with whitespace, for example:
```
../sentencepiece_upstream/build/src/spm_train \
  --input ../europarl-v7.de-en.en,../europarl-v7.de-en.de \
  --input_sentence_size 9999 \
  --model_prefix "bpe.joint" \
  --model_type "bpe" \
  --pad_id 3 \
  --pad_piece "<pad>" \
  --remove_extra_whitespaces 0
[...]
>>> x.encode_as_ids("asdf\nasdf\n", add_eos=True, add_bos=True)
[1, 174, 7931, 7937, 174, 7931, 7937, 7921, 2]
```

**Comment by taku910** [comment]
Specifying "\n" as a user symbol using the Python API,  "\n" can be recognized as a normal token.

```
>>> import sentencepiece as spm
>>> spm.SentencePieceTrainer.train(input='botchan.txt', vocab_size=1024, model_type='bpe', normalization_rule_name='identity', model_prefix='m', user_defined_symbols=['\n'])
>>> sp = spm.SentencePieceProcessor(model_file='m.model')
>>> sp.encode("hello\nworld")
[51, 36, 958, 3, 970, 28, 55]
>>> sp.decode([51, 36, 958, 3, 970, 28, 55])
'hello\nworld'
```

**Comment by pks** [comment]
Thanks @taku910! I kind of hoped that it would be automatically added when not removing whitespace and leaving the data as is with `identity` normalization. But your solution makes sense.

**Comment by samhavens** [comment]
Should we also use the arguments `allow_whitespace_only_pieces=True` and `remove_extra_whitespaces=False`?

**Comment by samhavens** [comment]
> user_defined_symbols=['\n']

It seems like if one is doing no normalization, we might also want to do `user_defined_symbols=['\n', '\t', '\r', '\b']`?

**Comment by samhavens** [comment]
@taku910 Using this, we see tokens in our vocabulary like `nThe`, which seem to come `\nThe` in the data. Is there a way around this, or do we need to preprocess the training data to replace `\n` with `<\n>` or some other special token not present in the corpus?
