### ISSUE TITLE
Output folder for spm_train

### ISSUE THREAD

**Issue by AlexUmnov** [google/sentencepiece#806]
I couldn't find any way to control the output path of spm_train. As far as I understand it just saves the result in the current directory with the defined prefix. 
But this functionality seems so obvious for me, so I'm surprised that it's missing. 
Am I missing something or there actually is no output path argument?

**Comment by tinsaye** [comment]
You can use `--model_prefix=path/to/models/my_model`.

This will then create:
```
path/to/models/my_model.model
path/to/models/my_model.vocab
```

**Comment by AlexUmnov** [comment]
@tinsaye thanks for your answer. But this is only for a relative path. And there are cases where I'd want it to be absolute. For example if my data is in a different folder from my model and I want to store spm model in the model folder.

**Comment by tinsaye** [comment]
I just tried an absolute path and it works :)

**Comment by AlexUmnov** [comment]
Oh alright then. It's an issue of documentation then. Thank you for clearing it out!
I guess we can close the issue unless the maintainers want to update the docs first
