### ISSUE TITLE
Exporting tokenizer to .spm

### ISSUE THREAD

**Issue by SupreethRao99** [google/sentencepiece#807]
Hello,

I've trained my tokenizer using the example scripts and the output, is .vocab file and a .model file. HuggingFace tokenizers consume a .spm file, how would I go about converting the .vocab and .model file to a .spm file. Thank You!

**Comment by taku910** [comment]
Sentencepiece does not support the .model to .spm file conversion in the first place, so please ask the HuggingFace team.
