### ISSUE TITLE
Can I know the loss of training with BPE and subword regularization?

### ISSUE THREAD

**Issue by lsy641** [google/sentencepiece#809]
In the paper of subword regularization, I didn't see the loss or PPL to report. I was wondering if there should be a higher loss brought by subword regularization as it often leads to multiple input tokens per sentence.

**Comment by taku910** [comment]
Yes. Subword regularization brings higher loss since it makes the training inference more difficult. However, it is a general characteristic of regularization in the sense that that makes a penalty to the loss.
