### ISSUE TITLE
Error while installing from source

### ISSUE THREAD

**Issue by singhakr** [google/sentencepiece#814]
I am trying to install sentencepiece (to local folder) from source on a SLURM cluster. While trying to build, I get this error:

> Target "sentencepiece_train" requires the language dialect "CXX17"

As I don't have root access, so I can't install from source, even to a local folder, it seems. However, sentencepiece Python wrapper seems to be installed. In that case, can't I simply write a Python script to call spm_train from this version and point to this script for the tokenizer script of the toolking (YANMTT), instead of calling spm_train separately on the command line? I haven't yet checked if the Python wrapper is working, but I will try it.

My logic was that if sentencepiece Python wrapper is installed through the wheel packaging (with pip), it may work this way. Even if it is possible, will it be slower with Python wrapper?

**Comment by singhakr** [comment]
I have tried the Python wrapper and it seems to be working, but there is some locale or encoding related error in the output.

**Comment by taku910** [comment]
It should be fine. Probably the machine does not have a proper font to render the under score tokens.

Please test the behavior with
```
import sentencepiece as spm

sp = spm.SentencePieceProcessor(model_file='model.m')
input = 'hello world'

sp.decode(sp.encode(input))
```

When `hello world` is emitted, the sentencepiece is working as expected.
Let me close the bug, as the original "installation problem" is already resolved.
