### ISSUE TITLE
Cannot encode special tokens in input

### ISSUE THREAD

**Issue by pks** [google/sentencepiece#816]
Hi!

When I train a basic model like so:
```
#!/bin/bash

../sentencepiece_upstream/build/src/spm_train \
  --input europarl-v7.de-en.en,europarl-v7.de-en.de \
  --input_sentence_size 100000 \
  --model_prefix "bpe" \
  --model_type "bpe" \
  --unk_id 0 \
  --unk_piece "<unk>" \
  --unk_surface "<unk>"
```

... it doesn't seem to be possible to have the surface form of `<unk>` correctly encoded:
```
> echo "This is a <unk>." | ../sentencepiece_upstream/build/src/spm_encode --model bpe.model
▁This ▁is ▁a ▁ < un k > .
```

I'd expect the model to output something like this: `▁This ▁is ▁a ▁ <unk> .`, correctly encoding the `<unk>` token as specified.

With `--user_defined_symbols` of course it works as expected:
```
> echo "This is a <testing>." | ../sentencepiece_upstream/build/src/spm_encode --model bpe.model
▁This ▁is ▁a ▁ <testing> .
```

As a workaround I found you can do this: https://github.com/lilt/sentencepiece/commit/e68969f65faf0d582f04c171be2ce42a5f319128
Which is however not ideal.

Is it the intended behavior to not be able to encode special tokens?

**Comment by taku910** [comment]
Yes. This is an intended behavior.  Unknown tokens cannot be re-defined as a user-defined symbol. 

If you want to inject unknown tokens, either
1)  insert a real unknown tokens not in the vocab.
2) Use python module and pre-process unknown tokens by themselves.
