### ISSUE TITLE
Error with ProtoBuf code Python

### ISSUE THREAD

**Issue by ahmedlone127** [google/sentencepiece#818]
I downloaded the latest version of protobuf https://github.com/protocolbuffers/protobuf/releases/tag/v21.12

and then I converted the ` sentencepiece_model.proto ` to  a .py implementation with the command ` protoc --python_out=. sentencepiece_model.proto `

Firstly the generated code was different form the code  in ` sentencepiece_model_pb2.py ` inside this repo. I also noticed that I can't import the code. I get the following error

``` 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Admin\Documents\GitHub\sentencepiece\src\protoc-22.0-rc-2-win64\bin\sentencepiece_model_pb2.py", line 5, in <module>
    from google.protobuf.internal import builder as _builder
ImportError: cannot import name 'builder' from 'google.protobuf.internal' (C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\google\protobuf\internal\__init__.py)


```

I also attatched my code 

[sentencepiece_model_pb2.txt](https://github.com/google/sentencepiece/files/10581750/sentencepiece_model_pb2.txt)

**Comment by taku910** [comment]
Probably you might need to install a protobuf python wrapper.  e.g. ```pip install protobuf```.

**Comment by ahmedlone127** [comment]
That's very intereesting! That worked ( even though it wasn't working when I tried this on colab with the protobuf file provided in the repository). I have a quesiton if you don't mind answering, I have read the previous threads and understand that we can manually edit the protobuf files but I was wondering if there was a way to manually decode the binary of  a protobuf file. the reason I am asking for this is because I am using hugging face which has json equvilants of sentencepeice model files in their FastTokenizers. I want to get the actual sentencepeice file from that json and the only way I can think of doing that is to manually convert the json to the spm file. 

What would you suggest the best way to go about something like this is? I am attatching a few files to show the schema of the json file I have .

json files: 
https://drive.google.com/file/d/1aJ6k9lop3veow2lN1syrEWfR0c-yXoSk/view?usp=sharing

**Comment by ahmedlone127** [comment]
@taku910  any insight will be appreciated !

**Comment by taku910** [comment]
protobuf is a general data serialization library so it is technically possible decode the binary proto with python-protobuf interface.

Here's the proto file of model file
https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L282

The document of python protobuf.
https://protobuf.dev/getting-started/pythontutorial/

Sorry, but this is the only information we can provide at this time, as we do not support direct editing of the model files.
