### ISSUE TITLE
Can the score of token be updated manually? Can two vocabulary been merged?

### ISSUE THREAD

**Issue by obangw** [google/sentencepiece#822]
I trained an English tokenizer and a Chinese one based on different corpus. Unigram language model is selected. And I want to merge two vocabulary with this script https://github.com/google/sentencepiece/blob/master/python/add_new_vocab.ipynb

As you know, some English tokens exist in a low frequency when I trained a Chinese tokenizer. But maybe these tokens behave different in English corpus. Based on the Chinese .model file, I wonder if I can change the score of English token in Chinese vocabulary when this case happened. Or would you please give me some advice to merge two vobulary. Thanks!

**Comment by taku910** [comment]
Assuming that you are using the default "unigram" model,  it would be possible to merge the unigram emission probabilities.

The score field in the proto is the unigram log probability.  So, you can simply liner-interpolate multiple probabiities.

````
new_prob = alpha * exp(score_en) + (1 - alpha) * exp(score_zh)
new_score = log(new_prob)
````

where alpha is the interporation parameter.

**Comment by mx8435** [comment]
@taku910 
Can we merge a BPE based model file with a unigram based model file using linear-interpolate method ? Thanks.
