### ISSUE TITLE
Usage of MSVC static runtime by default

### ISSUE THREAD

**Issue by ilya-lavrenov** [google/sentencepiece#825]
Hi,

Is there any reason why sentencepiece project uses `/MT` flags by default:
https://github.com/google/sentencepiece/blob/master/CMakeLists.txt#L71-L74

It's not a default behavior in MSVC (default is `/MD`) and it means that if we build static version of `sentencepiece` it cannot be used by most of the other projects, because they use `/MD`

**Comment by taku910** [comment]
If we build MD, the user needs to have the appropriate Microsoft runtime redistributable package to execute the sentencepiece executable.  That usually causes a lot of troubles and significant support work is required.  MT is much easier when building a standalone CRT library/executable.

When you want to integrate the sentencepiece into your binary, please decide the build options according to the build rules of the integrated system.

**Comment by ilya-lavrenov** [comment]
> user needs to have the appropriate Microsoft runtime redistributable 

This is not right, because MSVC runtime is fully compatible since Visual Studio 2015
See https://learn.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=msvc-170

> MT is much easier when building a standalone CRT library/executable.

If I build sentencepiece dynamic library with /MT, it unsafe to redistribute this library having a dedicated runtime, because C++ objects will migrate from one runtime to another which may lead to undesired behavior.

> When you want to integrate the sentencepiece into your binary, please decide the build options according to the build rules of the integrated system.

Have you thought why cmake has `/MD` by default? because all the other SW product totally rely on MSVC compatibility. 
And it's hard to understand why sentencepiece is the exception here, thus overriding cmake defaults.

Your project does not provide a option to override build flags, because it overrides cmake defaults in a dirty manner.

Please, consider usage of /MD

**Comment by taku910** [comment]
Okay, let us add the option to switch /MT and /MD.  Let us check whether there are no compatibility issues.

**Comment by ilya-lavrenov** [comment]
Thanks for the re-opening the issue, I've created the PR to address the problem https://github.com/google/sentencepiece/pull/837
