### ISSUE TITLE
can sentencepiece python wrapper training with generator rather than files?

### ISSUE THREAD

**Issue by Maxlinn** [google/sentencepiece#826]
hi to the community!

recently i'd like to train a bpe tokenizer using sentencepiece library, but my data is not organized as one-text-per-line style (e.g. text files are packed in `.tar`) and is really huge in size. so i'd like to write a python generator, which reads tars underneath and yields a string.

does sentencepiece support this usage? it would be much helpful since i don't have to repack a large amount of data.
i tried with `spm.SentencePieceTrain.train(input=generator())` but received `OSError: Not found: "": No such file or directory Error #2`.

thanks in advance!

**Comment by taku910** [comment]
Please read the following document
https://github.com/google/sentencepiece/tree/master/python#training-without-local-filesystem
