### ISSUE TITLE
Windows debug build fails to load anything, with “file not found” status code

### ISSUE THREAD

**Issue by Const-me** [google/sentencepiece#829]
`MultiByteToWideChar` function does not null-terminate the output string, [see the documentation](https://learn.microsoft.com/en-us/windows/win32/api/stringapiset/nf-stringapiset-multibytetowidechar#remarks).
Yet your code incorrectly assumes it does, [see there](https://github.com/google/sentencepiece/blob/master/src/util.cc#L255-L262).

This bug breaks debug builds made with Visual C++ with 100% probability — because debug heap in Visual C++ fills new heap memory with a [magic number](https://asawicki.info/news_1292_magic_numbers_in_visual_c) which is not zero, to detect bugs like that.

**Comment by taku910** [comment]
Thank you. Will fix it in the next release.

**Comment by taku910** [comment]
Fixed in v0.1.98
