### ISSUE TITLE
PyPI source distribution do not contain full sources

### ISSUE THREAD

**Issue by pkubik** [google/sentencepiece#835]
The sdist archive submitted on PyPI contain only the contents of `python` directory which is not sufficient to build the package.

The `setup.py` script assumes that `../build` directory contains directories with binaries and headers. This is true if we follow the instructions from the README manually and build the C++ library first, but it's not true if we run `pip install sentencepiece` and a wheel is not available for our platform, e.g. for Python 3.11.

**Comment by qufeihuo** [comment]
I have encountered the same problem, how can I solve it?

**Comment by jonmatthis** [comment]
I was having this issue in a python 3.11 environment -switched to 3.10 and it installed no problem

**Comment by taku910** [comment]
Will fix it in next release.

**Comment by taku910** [comment]
Fixed in v0.1.98
