### ISSUE TITLE
Question about decode sentence pieces?

### ISSUE THREAD

**Issue by dsj96** [google/sentencepiece#838]
I want to use a trained sentencepiece model from  InfoXLM ([Vocabulary](https://deltalm.blob.core.windows.net/deltalm/dict.txt) and [Sentencepiece-model](https://deltalm.blob.core.windows.net/deltalm/spm.model) according [deltalm](https://github.com/microsoft/unilm/tree/master/deltalm) ) model to encode the raw text.

```bash
#test.txt files
A Republican 'strategy' to counter the re-election of Obama. <s> yes </s> 我在中国过得很好。 <s> 你呢？ </s> 我不吃苹果。 <s> 你吃吗？</s> please answer me. <s>

#output.txt files
▁A ▁Republican ▁' strate gy ' ▁to ▁counter ▁the ▁re - ele ction ▁of ▁Obama . ▁< s > ▁yes ▁ </ s > ▁我 在中国 过 得 很好 。 ▁< s > ▁你 呢 ? ▁ </ s > ▁ 我不 吃 苹果 。 ▁< s > ▁你 吃 吗 ? </ s > ▁please ▁answer ▁me . ▁< s >

# output.txt
# when commond is spm_encode --model=trained_spm/spm.model --output_format=id < ./test.txt > output.txt
61 131160 241 151894 3431 24 46 105415 69 455 8 1017 10762 110 16041 4 4425 6 2739 72271 5 42945 6 2739 13128 47239 3073 1843 29786 29 4425 6 2739 73674 3744 31 5 42945 6 2739 5 55496 4010 64045 29 4425 6 2739 73674 4010 9130 31 42945 6 2739 22935 35165 162 4 4425 6 2739
```
The command are as follows:
```spm_encode --model=trained_spm/spm.model --output_format=piece < ./test.txt > output.txt```
`<s>` and `<\s>` is detokenized as `< s >` and `</ s >`.

the vocab.txt of the is when I run ```spm_export_vocab --model=trained_spm/spm.model --output=vocab.txt```:
```bash
# vocab.txt
<unk>	0
<s>	0
</s>	0
,	-3.46354
.	-3.62564
▁	-3.92997
s	-5.07262
▁de	-5.30664
....
```

I want to know how to make`<s>`and`<\s>` still detokenized as `<s>`and`<\s>` ?

**Comment by taku910** [comment]
This is FAQ.

https://github.com/google/sentencepiece/issues/215
