### ISSUE TITLE
[Question] Why include characters that are in the set of fallback bytes?

### ISSUE THREAD

**Issue by ZJaume** [google/sentencepiece#840]
Noticed that, when enabling `byte_fallback`, the vocabulary can still include characters that are included in this fallback. Wouldn't it be better to not include them and use the fallback? That way there would be more appearances of the fallback bytes in the training, and their embeddings would be trained more. Is this possible?

Example:
```
$ grep -P '^[%\]\[\)\(\?a-z]\t' spm.vocab
```
```
s       -4.58061
a       -4.61907
n       -5.29015
k       -5.65815
)       -5.7532
?       -6.19453
z       -6.43154
r       -6.44922
o       -6.70358
e       -7.11872
i       -7.45622
t       -7.5203
l       -7.64536
y       -7.84538
%       -7.98504
d       -7.99147
c       -7.99559
u       -8.09691
m       -8.0978
g       -8.38704
h       -8.42404
]       -8.55152
b       -8.55902
p       -8.59333
f       -8.63158
x       -8.65159
v       -9.1633
w       -9.32885
(       -9.38913
j       -9.39931
[       -9.62329
q       -10.6993
```

**Comment by taku910** [comment]
We can see the point. If we only want to handle UTF8 sequences, we can exclude these characters.  However, byte-fallback reserves 256 special symbols in order to encode arbitrary byte objects, which are not necessarily UTF8 characters.

**Comment by ZJaume** [comment]
If these characters are removed, the 256 special symbols can't manage both ascii characters and arbitrary UTF8 symbols? At least in the case of NMT, I've seen hallucinations in the output because of some strange utf8 symbol coming in. Even if byte fallback was enabled. Probably because the embeddings of byte fallback symbols it was encoded in, weren't trained at all or were poorly trained. I was hoping that if ascii characters were removed, these untrained byte fallback symbols would happen less often.

Thanks for your reply.

**Comment by taku910** [comment]
When the strange UTF8 symbols are coming in and these symbols aren't in the training data, we will expect such behavior anyway.  This is a problem of mismatch between training and test data and is not specific to byte fallback.

If you train the sentencepiece model with bytefallback, it would be better to set ``--character_coverage=0.9995`` so that
some rare tokens in the training data are treated as bytefallback. When we set 1.0,   no bytefallback tokens exist in the training data, and embeddings for bytefallbak tokens are not trained.

**Comment by ZJaume** [comment]
Yes, it is a problem of mismatch between training and "test" because it has happened under productions where clients translate sentences that contain symbols that there aren't in the training. But I was already using that character coverage :sweat_smile:. Will try lower coverage to try to increase chances of bytefallback tokens being trained.
