### ISSUE TITLE
How to customize `input_format` except txt, tsv

### ISSUE THREAD

**Issue by cyk1337** [google/sentencepiece#841]
`spm_train` only supports the `input_format ` of `text ` and `.tsv`. Suppose the training files contain newline characters ("\n") such as code data, how to train on them (`.jsonl` format for example) ?  @taku910

**Comment by taku910** [comment]
We can use `sentence_iterator` in Python module.

SentencePiece trainer accepts any python iterator object to feed training data.  Each element of iterator can any string "\n".  

https://github.com/google/sentencepiece/blob/master/python/README.md#training-without-local-filesystem
