### ISSUE TITLE
Potential bug in Unigram model

### ISSUE THREAD

**Issue by tsinggggg** [google/sentencepiece#843]
Hello, I ran into an example where I think the unigram model is not performing as it is expected to. Even though I can't attach the model file that causes the issue, here are some snippets that shows the problem

```
sp = SentencePieceProcessor()
sp.Load(path)
```

```
sp.encode_as_pieces('kan je draaipunt ?')
```
![image](https://user-images.githubusercontent.com/20978879/230521685-86051e1b-deb8-4ed1-99cb-21c1ca2f6ed7.png)
![image](https://user-images.githubusercontent.com/20978879/230525169-a3d522fa-40d4-4814-9ccc-56484a4c8128.png)

We can notice from below `ai p` actually gives a higher log probability than `a ip`

![image](https://user-images.githubusercontent.com/20978879/230524336-d1cd5ef8-a27b-4c38-b37f-6337ccd67d8e.png)

![image](https://user-images.githubusercontent.com/20978879/230524288-de14fc9c-8eff-452d-aba1-393bfe8b3c77.png)
Did I miss anything?

Thank you!

**Comment by taku910** [comment]
These scores are very close (almost identical). Floating-point calculations are not always accurate. 
https://en.wikipedia.org/wiki/Floating-point_arithmetic#Accuracy_problems.

We may be able to debug the decoding logic if we can have the model file.

**Comment by taku910** [comment]
We can make some debugging if the model file is shared. 

If there are no further discussions, we will automatically close this bug on May 1.
