### ISSUE TITLE
pip install failed on windows x64 with python 3.9

### ISSUE THREAD

**Issue by liqingjun123** [google/sentencepiece#846]
src/sentencepiece/sentencepiece_wrap.cxx(2822): fatal error C1083: Cannot open include file: 'sentencepiece_processor.h': No such file or directory

**Comment by markusantonuis** [comment]
Got the same error installing on 3.11 but successfully installed on 3.10.

**Comment by taku910** [comment]
Please check https://github.com/google/sentencepiece/issues/827
