### ISSUE TITLE
encode underline

### ISSUE THREAD

**Issue by yangsp5** [google/sentencepiece#853]
When I use sentenpiece and find that there is sometime `_` prefix underline. Why is there a  `_` prefix?

```
from sentencepiece import SentencePieceProcessor

tokenizer = SentencePieceProcessor('spm.model')

# example 1
tokenizer.encode("Today is a good day", out_type=str) # ['Today', '▁is', '▁', 'a', '▁good', '▁day']

# example 2
tokenizer.encode("今天是个好日子", out_type=str) # ['▁', '今', '天', '是', '个', '好', '日子']
```
It seems that `▁` represent whitespace in `example 1`. I can't understand why the first token in `example 2` is `'▁'` rather than `今`

**Comment by taku910** [comment]
I think the '_' also appears in example 1.   Anyway, '_' is always put at the BOS by default.

**Comment by taku910** [comment]
If there are no further discussions, we will automatically close this bug on May 1.
