### ISSUE TITLE
Potential bug: sequential unk tokens are combined in word mode

### ISSUE THREAD

**Issue by smesham** [google/sentencepiece#854]
When using word mode, the tokenizer combines consecutive unknown words into a single token.

Is this behaviour expected? If so, is there any way to disable it? I would like each unknown word to tokenize to a separate `<unk>` token.

# How to reproduce issue

Download example data:

```bash
wget https://raw.githubusercontent.com/google/sentencepiece/master/data/botchan.txt
```

Run tokenization:

```python
import sentencepiece as spm
spm.SentencePieceTrainer.train('--input=botchan.txt --model_prefix=m_word --model_type=word --vocab_size=2000')

sp_word = spm.SentencePieceProcessor()
sp_word.load('m_word.model')

my_string = 'this is a test1 test2'
print('input segmentation:\t', sp_word.encode_as_pieces(my_string))
print('tokens:\t\t\t', [sp_word.id_to_piece(id) for id in sp_word.encode(my_string)])
```
Output:
```
input segmentation:	 ['▁this', '▁is', '▁a', '▁test1▁test2']
tokens:			 ['▁this', '▁is', '▁a', '<unk>']
```

Desired output:
```
input segmentation:	 ['▁this', '▁is', '▁a', '▁test1', '▁test2']
tokens:			 ['▁this', '▁is', '▁a', '<unk>', '<unk>']
```

Is there any way for me to get my desired output?

**Comment by taku910** [comment]
Yes, this is expected.  multiple unk tokens are merged into single tokens.
The easiest workaround is to split the unk strings into sub-characters. 

````
tokens = sp.encode('こんにちは世界')
out = []
for t in tokens:
     if sp.is_unknown(sp.piece_to_id(t)):
            out.extend(list(t))
     else:
             out.append(t)
````

**Comment by smesham** [comment]
Is there any way to make the tokenizer itself output separate unk tokens? (without adding post-tokenization Python code)

I need to use the tokenizer within [SeqIO](https://github.com/google/seqio), so I can't apply Python code afterwards.
