### ISSUE TITLE
Code for tf-sentencepiece

### ISSUE THREAD

**Issue by lxomb** [google/sentencepiece#855]
Is code for tf-sentencepiece provided in this repo? The newest version (0.1.90) is incompatible with nvidia-tensorflow 1.15.5 (yet I'm forced to use this version). The error message is that tf_sentencepiece is compiled with protobuf 3.6.1 (yet installing that version via pip has no effect), and nvidia-tensorflow uses 3.8.0.

**Comment by taku910** [comment]
tf-sentencepiece is now deprecated.  No tf-sentencepiece code is updated nor provided. Please use tf-text.
