### ISSUE TITLE
segment fault

### ISSUE THREAD

**Issue by wlike** [google/sentencepiece#862]
版本 0.1.98

基于 98GB 的多语言语料进行训练，出现如下段错误：

![image](https://user-images.githubusercontent.com/6084282/237049386-e8fc876a-1284-4f1d-82bc-0b1bb45e4901.png)

参数设置如下：

--model_type=bpe \
--max_sentence_length=41920 \
--pad_id=3 \
--train_extremely_large_corpus=true \
--control_symbols="<sep>,<endofprompt>" \
--num_threads=128 \
--byte_fallback=true \

**Comment by taku910** [comment]
Probably the process is killed with OOM.

Could you check the workarounds already reported?
https://github.com/google/sentencepiece/issues?q=memory

**Comment by taku910** [comment]
If there is no update, this bug will be closed on Aug 9.
