### ISSUE TITLE
How about `▁` own escape?

### ISSUE THREAD

**Issue by fseasy** [google/sentencepiece#863]
It seems no description about `▁` own escape?

```python
>>> sp.encode("abc▁d d", out_type=str)
['▁a', 'b', 'c', '▁d', '▁d'] # Not Expected => the ▁d and ` d` is same after encoded, original `▁` lost
```

I know `▁` rarely occurs in normal text, but I think it is funny we can't reverse the encoded text about `sentencepiece` docs, because every doc which introduces the sentencepiece will contain the `▁`, it is not rare in this condition.
And I can't found anything talking about this... Did I miss something?

**Comment by taku910** [comment]
No, your point is correct. The character ▁ is rare, so we don't think it's a problem in real applications. Please let us know if you have any concerns.

**Comment by fseasy** [comment]
> No, your point is correct. The character ▁ is rare, so we don't think it's a problem in real applications. Please let us know if you have any concerns.

Haha, Thanks for your attention. My concerns is that any Text-Generating model based on the awesome SentencePiece can't produce the right BPE implementation details (because it can't generate `▁`).  
Or maybe we could add some notes for the limit in the document (because I've tried  to search about this but got nothing)

> In fact I'm reading your code and it's amazing. I don't expect to point some bug or want some perfect encoder, but just interested in this edge case.
