### ISSUE TITLE
why spm_encode keeps characters not in the vocab?

### ISSUE THREAD

**Issue by Smu-Tan** [google/sentencepiece#872]
Hi!

I encountered a question. I found out that spm_encode keeps the unknown characters (characters not in the spm_vocab). Could you please elaborate on it a bit?

For example, 

1. I train a multilingual vocab by `spm_train --input=train.all --model_prefix=spm_64k --vocab_size=64000 --character_coverage=0.9995 --train_extremely_large_corpus --num_threads 40 --max_sentence_length 200` on a 66M corpus.
2. Then I got the spm_model and spm_vocab. Then I continue to encode my corpus by `spm_encode --model spm_64k.model < en-ne.ne > train.en-ne.ne.spm`. 
3. Note: ◆ is not in the vocab, however, here's what i am confused about:

![image](https://github.com/google/sentencepiece/assets/79228128/a4856af8-ef0d-4b39-a287-37bc5d181008)

**Comment by taku910** [comment]
https://github.com/google/sentencepiece/issues/134
