### ISSUE TITLE
Respecify the normalization rule for trained sentenpieces models

### ISSUE THREAD

**Issue by geolvr** [google/sentencepiece#873]
Is there a way to respecify the normalization rule for trained models? I want to use the 'identity' rule, but the public pre-trained model which I used chooses the default 'nmt_nfkc' rule during its training process, and its training process is not reproducible for me. The application of the normalization makes some pure extraction tasks such as text cleaning and validation difficult to implement correctly. 

In the tutorial, all I see is how do I specify the normalization rule when training a new model.

**Comment by taku910** [comment]
The model file is a serialized protobuf. We can specify 'identity' rule just by clearing the `precompiled_charsmap` filed.

https://github.com/google/sentencepiece/blob/master/src/sentencepiece_model.proto#L248

Please check the following thread to see how to edit the proto files.
https://github.com/google/sentencepiece/issues/121

Finally,  manual modification of model files is not officially supported. Please do it on an at-your-own-risk basis.
