### ISSUE TITLE
There is always a "▁" before the first piece after tokenization, why?

### ISSUE THREAD

**Issue by hxs91** [google/sentencepiece#877]
For string "北京北京是个不错的城市。", it will be tokenized as ['▁北京', '北京', '是个', '不错的', '城市', '。']. I noticed that there is always a "▁" before the first token, and it result in different id for the same piece "北京".

I am quite confused about this mechanism, what is the advantage?

**Comment by taku910** [comment]
https://github.com/google/sentencepiece/issues/305

**Comment by hxs91** [comment]
@taku910 thanks! is there any detailed experimental result that can show the performance difference whether `add_dummy_prefix` is enabled or not?

**Comment by taku910** [comment]
We haven't had any experiments yet.
