### ISSUE TITLE
vocab size is smaller than required_chars

### ISSUE THREAD

**Issue by jiangix-paper** [google/sentencepiece#885]
Hello, I have an error: "RuntimeError: Internal: src/trainer_interface.cc(581) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 10000 vs 37051. Increase vocab_size or decrease character_coverage with --character_coverage option.". Should I increase the vocab size to 37051?

**Comment by taku910** [comment]
Yes, this error happens when the minimum vocab set (all single-Unicode chars-based voacb) has already exceeded the specified vocab size. We can set the size to be 37051, but it is essentially the same as character-based tokenization.
