### ISSUE TITLE
Can options from SentencePieceTrainer training be extracted from the tokenizer.model file?

### ISSUE THREAD

**Issue by DinhLuan14** [google/sentencepiece#886]
I have a question that I hope can be addressed:

If I have a tokenizer.model file, is there any way to know the options used during the SentencePieceTrainer training process?
For instance, with the tokenizer_test.model file, can I extract:

vocab_size = ?
split_digits = ?
split_by_unicode_script = ?
byte_fallback = ?
...

Is there any way to accomplish this? I appreciate any guidance.

**Comment by taku910** [comment]
The model file is just a serialized protobuf, so we can dump the contents in text format. Note that python module must be installed to use sentence_piece_model_pb2.

```
>>> import sentencepiece_model_pb2
>>> m = sentencepiece_model_pb2.ModelProto()
>>> with open('../../test/test_model.model', 'rb') as f:
...     m.ParseFromString(f.read())
... 
253165
>>> m.trainer_spec
input: "botchan.txt"
model_prefix: "m"
model_type: UNIGRAM
vocab_size: 1000
character_coverage: 0.9994999766349792
input_sentence_size: 10000000
mining_sentence_size: 2000000
training_sentence_size: 10000000
seed_sentencepiece_size: 1000000
shrinking_factor: 0.75
num_threads: 16
num_sub_iterations: 2
max_sentencepiece_length: 16
split_by_unicode_script: true
split_by_whitespace: true

>>> m.normalizer_spec.precompiled_charsmap = b''
>>> m.normalizer_spec
name: "nfkc"
precompiled_charsmap: ""
add_dummy_prefix: true
remove_extra_whitespaces: true
````

**Comment by DinhLuan14** [comment]
Could you please guide me on how to install "sentence_piece_model_pb2" with Python? Thank you.

**Comment by ZJaume** [comment]
I could not do that by simply installing the python package because it seems that protobuf is not installed as dependency. However, doing this, it worked:
```
pip install sentencepiece protobuf
```
```
>>> from sentencepiece import sentencepiece_model_pb2
>>> m = sentencepiece_model_pb2.ModelProto()
...
```
