### ISSUE TITLE
set add_dummy_prefix according to the identified language

### ISSUE THREAD

**Issue by Life-0-1** [google/sentencepiece#888]
`--add_dummy_prefix` is very brilliant for getting the same tokenized result for a word at the beginning of a sentence or not. 

But it is not suitable for Chinese text, as there is no whitespace at neither the beginning of a document nor a sentence. 

While training a tokenizer based on the mixture of Chinese and English texts, the dummy prefix is supposed to be added for English text but not added for Chinese text. 

Is there any way to achieve this based on the current version of sentencepiece?

**Comment by taku910** [comment]
By design, we do not introduce any logic that is language-dependent. Therefore, it would be preferable to control the behavior outside of the sentencepiece, but this is not possible at this moment. For instance, it would be great if we can change the ``--add_dummy_prefix``` behavior per training sentences.

At this moment, what we can do is 
1. Train Chinese and English models independently with and without ``--add_dummy_prefix`` flag
2.  Make one model by merging Chinese and English models (Please check https://github.com/google/sentencepiece/issues/121 to manually modify the models).

Note that even with this workaround, the one dummy prefix is added to Chinese text in the inference time, as the model itself doesn't have the language information.o

**Comment by Life-0-1** [comment]
Thanks very much
