### ISSUE TITLE
Generate `sentencepiece_model_pb2.py` with newer protobuf

### ISSUE THREAD

**Issue by ydshieh** [google/sentencepiece#889]
Currently, when trying to use [python/src/sentencepiece/sentencepiece_model_pb2.py](https://github.com/google/sentencepiece/blob/master/python/src/sentencepiece/sentencepiece_model_pb2.py), we get `TypeError: Descriptors cannot not be created directly.`
(full log below).

I tried the latest commit for the file `sentencepiece_model_pb2` on this repository.

A lot of users in [transformers](https://github.com/huggingface/transformers) is asking to be able to use `protobuf 4`. However, due to this file from `sentencepiece`, this is blocking for years.

Is it possible to have an official `sentencepiece_model_pb2.py` file generated with newer `protobuf` 🙏. 

### Full error log
```bash
>>> from src.transformers.utils import sentencepiece_model_pb2 as model_pb2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/transformers/src/transformers/utils/sentencepiece_model_pb2.py", line 34, in <module>
    _descriptor.EnumValueDescriptor(
  File "/usr/local/lib/python3.8/dist-packages/google/protobuf/descriptor.py", line 796, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```

**Comment by ydshieh** [comment]
cc @taku910

**Comment by taku910** [comment]
Updated in head.

Direct modification of model files is not directly supported. 
Though we provide some tips on the model files, they are all at-your-own-risk-basis. 
Therefore, the systems relying on pb2 should be responsible for this issue.
