### ISSUE TITLE
The vocabulary order in BPE

### ISSUE THREAD

**Issue by cyk1337** [google/sentencepiece#890]
Suppose we have trained a 100k-sized BPE model, and we would like to reduce it into 50k as if was trained as original BPE. How is the vocabulary order in the .model file? I observe that the very first few are special symbols, while the last bunches are single characters. So I guess we should reduce from in between. But what is the correct order to reduce them?

**Comment by taku910** [comment]
The BPE tokens are stored in the order of BPE merge operations, so we can remove the last 50k except for the single-char tokens.
