### ISSUE TITLE
Adding continuous `'<0x0A><0x0A>'` tokens to encode continuous `\n\n`

### ISSUE THREAD

**Issue by cyk1337** [google/sentencepiece#891]
Given a trained BPE tokenizer (w/ byte-fallback), `\n\n` will be encoded as `['<0x0A>', '<0x0A>']`.  I would like to encode continuous `\n` such that `\n\n` can be encoded as one token. Have tried added new tokens `<0x0A><0x0A>` to ".model" file but it does not take effect. Any solutions to this?

**Comment by taku910** [comment]
You might want to use `user_defined_symbols` and `normalization_rule_name=identity`

Note that the normalization_rule_name turns off the default normalization rule.

```
>> import sentencepiece as spm
>>> spm.SentencePieceTrainer.train(input='botchan.txt', model_prefix='m', vocab_size=4000, normalization_rule_name='identity', user_defined_symbols=['\n\n'])
>>> 
... snip
>>> sp = spm.SentencePieceProcessor('m.model')
>>> sp.encode('hello\n\nworld')
[27, 150, 172, 3, 953, 93, 1650]
>>> sp.decode([27, 150, 172, 3, 953, 93, 1650])
'hello\n\nworld'
>>> sp.piece_to_id('\n\n')
3
>>> 
```

**Comment by cyk1337** [comment]
Thank you for answering my question! How about post-adding the `\n\n` tokens on a trained `.spm` models?
