### ISSUE TITLE
Suppress Warnings via Python API?

### ISSUE THREAD

**Issue by dgrahn** [google/sentencepiece#893]
All,

I'm receiving a huge number of warnings that the Agenda size is too big. I'm OK ignore this warning, but I can't figure out how to do that from the python API.

I should clarify, that this is in the `nbest_encode` function of the `SentencePieceProcessor`, not during training.

Thanks in advance!

**Comment by dgrahn** [comment]
After searching the documentation and source code. It looks like this is not an option in the Python API. I'd be happy to add it if someone points me in the right direction.

**Comment by dgrahn** [comment]
@taku910 Apologies for the ping, but I wanted to make sure you saw that there was a commit almost ready for merge here.

I was able to expose the log levels as `set_min_log_level` and `get_min_log_level`. When I test it on the local machine using `python setup.py bdist_wheel`, it works fine.

Commit: https://github.com/dgrahn/sentencepiece/commit/89b80357b338f7254a6364138d812102d32c8c12

However, the actions fail because it says that `sentencepiece::logging` is not a part of `sentencepiece`.

Failed Action: https://github.com/dgrahn/sentencepiece/actions/runs/5557489770

If you tell me what updates to make, I'll prepare a pull request.

**Comment by taku910** [comment]
We are going to expose logging functions for python.

**Comment by taku910** [comment]
Fixed in v0.2.0
