### ISSUE TITLE
Right bigram index too large for uint16

### ISSUE THREAD

**Issue by Numeri** [google/sentencepiece#894]
I was training a BPE model on what I'd imagine is a rather large training set for a tokenizer (60 GiB), and encountered this error:

```
...
trainer_interface.cc(537) LOG(INFO) all chars count=29457610903
trainer_interface.cc(548) LOG(INFO) Done: 99.95% characters are covered.
trainer_interface.cc(558) LOG(INFO) Alphabet size=7854
trainer_interface.cc(559) LOG(INFO) Final character coverage=0.9995
trainer_interface.cc(591) LOG(INFO) Done! preprocessed 115278662 sentences.
trainer_interface.cc(597) LOG(INFO) Tokenizing input sentences with whitespace: 115278662
trainer_interface.cc(608) LOG(INFO) Done! 206163880

bpe_model_trainer.h(73) [(r) <= (std::numeric_limits<uint16_t>::max())] 
Program terminated with an unrecoverable error.
```

Looking at [the code in question](https://github.com/google/sentencepiece/blob/master/src/bpe_model_trainer.h#L67-L78), I assume this is a hard limit on the amount of data one can train the tokenizer on? What is the right bigram index measuring exactly?

**Comment by Numeri** [comment]
Specifically, I was using these arguments (through the Python API):
```python3
spm.SentencePieceTrainer.train(
    input=input_file_list,
    model_prefix='spm_model',
    model_type='bpe',
    vocab_size=100_000,
    num_threads=32,
    train_extremely_large_corpus=True,
    max_sentence_length=128*1024,
    split_by_unicode_script=True,
    split_by_number=True,
    split_by_whitespace=True,
    split_digits=True,
    allow_whitespace_only_pieces=True,
    byte_fallback=True,
    remove_extra_whitespaces=False,
    normalization_rule_name='identity',
    user_defined_symbols=user_defined_symbols,
    bos_id=-1,
    eos_id=-1,
)
```

**Comment by Numeri** [comment]
I got this to work by splitting all of my training data into much shorter lines (max 2048 characters) and reducing `max_sentence_length` to match. This seems like a good solution, but I'll leave this open for a little bit longer just in case there's something I'm misunderstanding.

**Comment by taku910** [comment]
Thank you for the report. It seems that the data you are feeding is too big.
I think shrinking the sentence length is enough, since BPE cannot capture the long contextual information.
