### ISSUE TITLE
Zero width non-joiner incorrectly mapped to space

### ISSUE THREAD

**Issue by angelaslin** [google/sentencepiece#896]
I am working with data in Telugu where the zero width non-joiner (ZWNJ), u+200c, is used to prevent characters from merging together. In `nmt_nfkc.tsv`, the ZWNJ is mapped to a space. This issue was mentioned in [this comment](https://github.com/google/sentencepiece/issues/731#issuecomment-1080994371) but was not addressed in the fix for that issue. Replacing the ZWNJ with a space makes the word ungrammatical. Can you remove this mapping from `nmt_nfkc.tsv`?

Here is how I tried to manually remove the ZWNJ -> space mapping:
- I am using the mT5 pretrained sentence piece model: gs://t5-data/vocabs/mc4.250000.100extra/sentencepiece.model
- I manually removed the normalization replacing the `precompiled_charsmap` with an empty string following the instructions in this #873.
- I added the ZWNJ to the vocabulary by replacing the last subword in the vocabulary with the ZWNJ. 
- I trained an mT5 model using the updated sentence piece model.
- The model works fine except it outputs numbers/characters from other scripts at the end of the prediction, for example, "నాకు మీ కాంటాక్ట్‌లలో మ్యాచ్ అయ్యే వారు కనిపించడం లేదు. మీ సోదరుడి పేరు మరోసారి చెప్పండి.**dobrovol**", "తప్పకుండా, 20 నిమిషాల ది. ఇప్పుడు ప్రారంభమవుతోంది.**거든요**", "నేను ఇంకా WhatsApp యాప్‌లో దీని కోసం సెర్చ్ చేయలేను, కానీ నేను కనుగొన్నది ఇదిగోండి.**3340**". This issue doesn't occur when I export the model with the pretrained sentence piece model and normalization. Have you seen this issue before?

Is there a way to remove the ZWNJ from the normalization rules without retraining the sentence piece model?

Thank you so much for your help!

**Comment by taku910** [comment]
Currently, we do not officially support modifying the model file after training, as the scope of support increases and the issues reported will be more complicated.  Could you please rewrite the model (proto file) manually at-your-own-risk-basis.

If you have any issues on the default normalization rules, please send us PR.  Thank you.
