### ISSUE TITLE
Restarting sentencepiece on a new dataset

### ISSUE THREAD

**Issue by zachmayer** [google/sentencepiece#9]
I have a corpus of .xz files from the common crawl.  I don't have enough disk space to unzip all the files and concatenate them into a single file.  Is there any way to re-start the sentencepiece model on a new corpus of text? 

I'd like to loop through each of my files, unzip them to a temp file, run feed it to the tokenization model, delete the temp file, and then move on to the next one.

**Comment by taku910** [comment]
How big the corpus is?  spm_train loads all sentences into the memory. If the data is bigger than the memory size, spm_train will not run anyway.  By default, spm_trains first loads 10M sentences of input data to avoid memory explosion (--input_sentence_size).   In general, we can obtain reasonable accuracy with 1-10M sentences.  If your corpus is already randomized, you might want to unzip the first several corpus.

Other tips is that spm_train accepts multiple files in CSV format:
spm_train --input=input1.txt,input2.txt,input3.txt --model_prefix=model

This can avoid an extra step to merge all files into a single file.

**Comment by zachmayer** [comment]
That make sense. I'll try a random sample of 100M sentences with the `--input_sentence_size` flag

**Comment by taku910** [comment]
I think we can close this issue, as we can specify the number of sentences for training with --input_sentence_size.

**Comment by rjurney** [comment]
What is a reasonable `input_sentence_size`? I've got 64GB of RAM and no idea what to put.
