### ISSUE TITLE
Model can't load if special characters are in the path

### ISSUE THREAD

**Issue by gianmarcohutter** [google/sentencepiece#902]
If there are Korean characters in the path of the tokenizer model when it's loaded like this: 
`sentencepiece::SentencePieceProcessor tokenProcessor;`
`tokenProcessor.load(pathtomodel);`

Any help appreciated on how to work around this

**Comment by taku910** [comment]
Could you describe the details of the errors?

1. What does a special character mean? Korean characters are in Unicode, so isn't special
2.  Which language are you using. C++/Python?
3.  Please provide a minimum code that reproduces the error. 
4.   Please provide the error messages.

**Comment by gianmarcohutter** [comment]
Sorry for the vague framing of the report! 

> * Which language are you using. C++/Python?
C++

> * Please provide a minimum code that reproduces the error.
The example given at https://github.com/google/sentencepiece/blob/master/doc/api.md if the path contains Korean characters:
`#include <sentencepiece_processor.h>

sentencepiece::SentencePieceProcessor processor;
const auto status = processor.Load("C:\\path\\to\\아라\\model.model");
if (!status.ok()) {
   std::cerr << status.ToString() << std::endl;
   // error
}`

> * Please provide the error messages.
The code works if no special characters are added, but as soon as there are Korean characters present: 
Not found: "C:/path/to/model/??/t.model": Invalid argument Error #22

I'm running this with Visual Studio on Windows so it might be that the error completely on my side in which case I apologize!

**Comment by taku910** [comment]
I think you would like to build the binary with UNICODE mode.

1. Build targets with _UNICODE and UNICODE flag
2. Write the code in UTF8 encoding.

https://github.com/google/sentencepiece/issues/902

**Comment by taku910** [comment]
Let me close this bug as no additional information is provided.
