### ISSUE TITLE
BPE Model does not recognize long words in manually extended vocabulary

### ISSUE THREAD

**Issue by TianwenWei** [google/sentencepiece#903]
I have a BPE model pretrained on English text. Its vocabulary consists of almost entirely Enlish subwords. Now I want to extend the vocabulary with some Chinese words. As a minimal example, let's say I extended the vocab with `"你好"`, `"澳大利亚"`. Then I load the model to segment the sentence "你好澳大利亚". However, it turns out that the model only recognize "你好"，but not "澳大利亚". 

It appears that the model can not recognize Chinese words longer than 2 characters, unless their constituent subwords have already been added to the vocabulary.

Could anyone explain why?

Here is the minimal code:
```python
m = model.ModelProto()
m.ParseFromString(open("original.model", "rb").read())
# original vocab size is 16380

# add new tokens to vocab
new_tokens = ["你好", "澳大利亚"]
for token in new_tokens:
    new_p = model.ModelProto().SentencePiece()
    new_p.piece = token
    new_p.score = 0
    m.pieces.append(new_p)

with open("extended.model", 'wb') as f:
    f.write(m.SerializeToString())

string = "你好澳大利亚"

sp = spm.SentencePieceProcessor("extended".model)
print(sp.encode_as_pieces(string))  # ['▁', '你好', '澳大利亚']
print(sp.encode(string))  # [16289, 16384, 0]  here 0 is the <unk> token
``` 
Note that in the example above, neither of "你" nor "好" is present in the original vocabulary. 

In contrast, if both "澳大" and "利亚" are added to the vocab, then the model can successfully segment and encode "澳大利亚" as a whole:
```python
m = model.ModelProto()
m.ParseFromString(open("original.model", "rb").read())
# original vocab size is 16380

# add new tokens to vocab
new_tokens = ["你好",  "澳大", "利亚", "澳大利亚"]
for token in new_tokens:
    new_p = model.ModelProto().SentencePiece()
    new_p.piece = token
    new_p.score = 0
    m.pieces.append(new_p)

with open("extended.model", 'wb') as f:
    f.write(m.SerializeToString())

string = "你好澳大利亚"

sp = spm.SentencePieceProcessor("extended".model)
print(sp.encode_as_pieces(string))  # ['▁', '你好', '澳大利亚']
print(sp.encode(string))  # [16289, 16384, 16387] 
```

**Comment by taku910** [comment]
First of all, manual modification of model files is at your own risk and is not officially supported.

BEP is purely bottom up segmentation, so adding tokens is not enough.  At least one sub-token must also be included in the vocab.   BPE makes the token "ABCD"  by merging "AB" and "CD",  or "A" and "BCD" or  "ABC" and "D", so these subtokens are also in the vocab list.

For "澳大利亚"  case, ["澳", "大利亚"] or  ["澳大", "利亚"]  or  ["澳大利", "亚"] must be included recursively.

That's not the case in ULM model.  We can add any token in ULM.
