### ISSUE TITLE
Access to bytes representation when decoding

### ISSUE THREAD

**Issue by fanzeyi** [google/sentencepiece#906]
In the current Python SentencePiece API, there is no way to access the underlying bytes result after decoding.

For example, with a tokenizer defined `<0x00>` ... `<0xFF>` from `3` to `259`:

```python
>>> print(sp.decode([3+0xF0]))
'�'

>>> print(sp.decode([3+0xF0, 3+0x9F]))
��

>>> print(sp.decode([3+0xF0, 3+0x9F, 3+0x9A]))
���

>>> print(sp.decode([3+0xF0, 3+0x9F, 3+0x9A, 3+0x80]))
🚀
```

is producing a result with `U+FFFD UNICODE REPLACEMENT CHARACTER` automatically. I haven't looked but I suspect this is a result of running something equivalent to `b"\xF0\x9F".decode("utf-8", "replace")` in Python API.

Currently there is no easy way to access the original bytes representation. The closest method is to decode the tokens as `immutable_proto` then inspect the output struct.

This is commonly seen when LLM producing multi-byte characters and we'd like to have a way to access the raw bytes after decoding.

It would be great if SentencePiece can support `sp.decode(..., out=bytes)` in Python. Currently this throws an exception `unknown output or input type`.

**Comment by taku910** [comment]
Fixed in v0.2.0
