### ISSUE TITLE
Warning during training:  "The piece..contains escaped characters that break the format of..vocab"

### ISSUE THREAD

**Issue by ykoyfman** [google/sentencepiece#907]
I see that based on this:
https://github.com/google/sentencepiece/blob/8cbdf13794284c30877936f91c6f31e2c1d5aef7/src/trainer_interface.cc#L705

certain pieces (tab, newline) aren't allowed as user defined symbols. Is there another way to ensure that these end up as individual tokens?

**Comment by ykoyfman** [comment]
I also get this warning when following the pattern here to add [\n] to user defined symbols: https://github.com/google/sentencepiece/issues/804#issuecomment-1410743501

**Comment by taku910** [comment]
They are just a warning. As long as using *.model file, we don't worry about it.
*.vocab files are legacy text-based TSV, so we cannot store these special symbols properly.

**Comment by ykoyfman** [comment]
Thank you for confirming.
