### ISSUE TITLE
Sentencepiece in C++ is tokenizing is different from python.

### ISSUE THREAD

**Issue by Zapotecatl** [google/sentencepiece#913]
Hi,

I am trying to develop a tokenizer for the Spanish language using sentencepiece. I am using Marian's source.spm (https://huggingface.co/Helsinki-NLP/opus-mt-es-en/tree/main) model.

My program in C++:

```
#include <iostream>
#include <sentencepiece_processor.h>
int main()
{
    sentencepiece::SentencePieceProcessor processor;
    const auto status = processor.Load("D:\\SentencePiece\\source.spm");

    if (!status.ok()) {
        std::cerr << status.ToString() << std::endl;
        // error
    }
        
    std::vector<std::string> pieces;
    processor.Encode("Hola mi amor, cómo estás?", &pieces);
  
    for (const std::string& token : pieces) {
        std::cout << token << std::endl;
    }
}
```
Output

```
ÔûüHola
Ôûümi
Ôûüamor
,
Ôûüc
´┐¢
mo
Ôûüest
´┐¢
s
?
```
My program in python:

```
from transformers import AutoTokenizer
src = "es"  # source language
trg = "en"  # target language
model_name = f"Helsinki-NLP/opus-mt-{src}-{trg}"

tokenizer = AutoTokenizer.from_pretrained(model_name)

sample_text = "Hola mi amor, cómo estás?"
tokens = tokenizer.tokenize(sample_text)
print(tokens)
```
Output
`['▁Hola', '▁mi', '▁amor', ',', '▁cómo', '▁estás', '?']`

So the way sentence piece in C++ is tokenizing is different. For words in Spanish that do not have accents it does it correctly, but for a word that has an accent it divides it into three tokens (pre-accent, accent and pos-accent).

I was wondering if maybe there is some flag or parameter that I can pass to sentencepiece so that it tokenizes the words with accents as a single token?

Any suggestion is welcome, thank you!

**Comment by taku910** [comment]
Seems that non-UTF8 string is passed  in C++ code.  In C++, the character encoding changes depending on the build environment. Please use utf8. e.g.,  u8"Hola mi amor, cómo estás?".

As long as I tested on Linux, it works as expected.
