### ISSUE TITLE
aggregate multiple user_defined_symbols to a new token?

### ISSUE THREAD

**Issue by tzhma** [google/sentencepiece#914]
Is it possible to aggregate multiple user_defined_symbols to a new token? For example, a text file with a sentence:

```
<sym1><sym2> <sym3> <sym3><sym2>
<sym1><sym3> <sym3> <sym1>
```

using `user_defined_symbol=[<sym1>, <sym2>, <sym3>]`
results vocab like:

```
<sym1>
<sym1><sym2>
<sym1><sym3>
<sym3> 
<sym3><sym2>
```

Essentially, is it possible to tokenize over a pre-defined set of characters? like described [here](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-chargroup-tokenizer.html)?

**Comment by taku910** [comment]
No, currently such features are not supported.  It makes the behavior and implementation more complicated, so there is no plan to support such features.
