### ISSUE TITLE
[Question] about loading fairseq to sentencepiece

### ISSUE THREAD

**Issue by phamkhactu** [google/sentencepiece#916]
Thanks for your great  working.

I have a fairseq contains:
```
bpe.codes
dict.txt
model.pt
```
Now, I want to load fairseq to sentencepiece for merging some tokens.

```
from sentencepiece import sentencepiece_model_pb2 as sp_pb2_model

sp_model_file = "path_to_fairseq_model"
sp_model = spm.SentencePieceProcessor()
sp_model.Load(sp_model_file)

```
I get error. I know that it comes from not correcting methods. I've searched on the internet, but not found anythings
I'm very happy for your help.

Thank you.

**Comment by taku910** [comment]
Please provide the details of the error message. Probably you might pass a file that is not stored in sentencepiece's model file.

**Comment by taku910** [comment]
Let me close this bug, as any additional information is provided.
