### ISSUE TITLE
Skipping numbers in tokenization

### ISSUE THREAD

**Issue by kpriyankavya** [google/sentencepiece#917]
@taku910 

Hi Team , how to stop mdoel tokenize numbers ? 

i tried `split_by_number =False ` and `split_by_digit = False `

but still number isbeing tokenized into multiple digits 

Example Input : My phone number is 1234567890
Model Output : ['My','Phone','number','is','12'.'3','45','67','890']
Expected Output :  : ['My','Phone','number','is','1234567890']
``

**Comment by taku910** [comment]
It is theoretically impossible to introduce constraints to merge tokens, including stopping number tokenization, because the vocab size is fixed in subword segmentation.

For example, when the vocab size is 1000,   we cannot encode the numbers from 0000-9999 when making them independent tokens.
