### ISSUE TITLE
Build shared library on Windows?

### ISSUE THREAD

**Issue by findmyway** [google/sentencepiece#918]
It seems the static library is built on windows platform only. Any reason why we did so?

https://github.com/google/sentencepiece/blob/8cbdf13794284c30877936f91c6f31e2c1d5aef7/CMakeLists.txt#L43C1-L45

---

Ref: https://github.com/JuliaPackaging/Yggdrasil/pull/7493#issuecomment-1749288873

**Comment by taku910** [comment]
The reason is simply that the build will fail.
Many changes are required to export class of C++ in DLL, so currently, we deprioritize the shared library support on Windows.  We appreciate the contribution to this area.

**Comment by giordano** [comment]
> The reason is simply that the build will fail.

Funny, because in the PR linked in the OP we're building the shared library just fine.
