### ISSUE TITLE
Expose Advanced API?

### ISSUE THREAD

**Issue by jerinphilip** [google/sentencepiece#922]
Thanks for the open-source library. I am using the advanced API for inference part of `SentencepieceProcessor`. 

https://github.com/google/sentencepiece/blob/8cbdf13794284c30877936f91c6f31e2c1d5aef7/src/sentencepiece_processor.h#L388-L408

`sentencepiece.pb.h` is not part of the install targets:

https://github.com/google/sentencepiece/blob/8cbdf13794284c30877936f91c6f31e2c1d5aef7/src/CMakeLists.txt#L313 

I'm able to compile from source (as submodule), but would prefer to use [libsentencepiece-dev](https://packages.debian.org/stable/libdevel/libsentencepiece-dev), [sentencepiece-git](https://aur.archlinux.org/packages/sentencepiece-git) not bundling sentencepiece.  

What's the recommendation here? Is it possible to do something to improve this?

**Comment by taku910** [comment]
[libsentencepiece-dev](https://packages.debian.org/stable/libdevel/libsentencepiece-dev), [sentencepiece-git](https://aur.archlinux.org/packages/sentencepiece-git) are maintained by independent third party distributors.
What we can recommend is that we can ask them to upgrade the packages.
