### ISSUE TITLE
No module named 'sentencepiece' even though sentence piece is installed

### ISSUE THREAD

**Issue by Andyple** [google/sentencepiece#925]
I have installed sentencepiece 0.1.99 in a conda environment using pip install sentencepiece, but when I try to import it in a jupyter notebook, I get this error:

```python
import sentencepiece

ModuleNotFoundError: No module named 'sentencepiece'
```

However, when I run ipython in the same environment and import sentencepiece, it works fine.

I have checked my Python version (python --version) and it is 3.10.13.

I have also tried to reinstall sentencepiece using conda install -c conda-forge sentencepiece and pip install --upgrade --force-reinstall sentencepiece, but none of them solved the problem.

I suspect there is some issue with the path or environment variables, but I don’t know how to fix it.

**Comment by taku910** [comment]
I'm afraid that this issue is not directly related to sentencepiece.  It appears to be a conda and jupyter notebook specific problem.
