### ISSUE TITLE
Seg fault

### ISSUE THREAD

**Issue by chiamp** [google/sentencepiece#928]
I submitted a PR to Flax that re-arranges import statements, and it causes a seg fault that seems to originate from `sentencepiece`. 
The PR can be found here: https://github.com/google/flax/pull/3442
Traceback can be found here: https://github.com/google/flax/actions/runs/6662547269/job/18107064221?pr=3442#step:9:384
Dependencies can be found here (this example is using `sentencepiece==0.1.96`): https://github.com/google/flax/blob/596cf6d8777bc8654a68f7f11917f1119ffa3b9f/examples/wmt/requirements.txt
This test is run on python 3.10.

**Comment by Micky774** [comment]
Just wanted to mention that at first glance it looks like it's coming from `sentencepiece/__init__.py::_TrainFromString`, which wraps `sentencepiece/sentencepiece_wrap.cxx::_wrap_SentencePieceTrainer__TrainFromString`

**Comment by taku910** [comment]
It is hard to reproduce and test this error only with this information. At least it wold better to try the latest release.

**Comment by taku910** [comment]
We are going to close this issue on March 1 if there are not further updates.
