### ISSUE TITLE
About the corpus used to train the vocab

### ISSUE THREAD

**Issue by tszslovewanpu** [google/sentencepiece#929]
Hello and excellent work!

I'm looking to expand the original vocabulary with new subwords using SentencePiece on a corpus with sentences like the following:
"青光闪动，一柄青钢剑倏地刺出，指向在年汉子左肩"

Should I employ a tool to segment the sentence into subwords like "青 光 闪 动 ，一 柄 青 钢 剑 倏 地 刺 出 ，指 向 在 年 汉 子 左 肩",
or should it be segmented more coarsely as "青光 闪动，一柄 青钢剑 倏地 刺出 ，指向 在年 汉子 左肩"?

Which format would be optimal for training the vocabulary on the mentioned corpora?

Thank you in advance for your guidance!

**Comment by taku910** [comment]
Since we do not support expanding vocabulary (or increasing the vocab) in the first place, 
we cannot answer this question.

**Comment by tszslovewanpu** [comment]
> Since we do not support expanding vocabulary (or increasing the vocab) in the first place, we cannot answer this question.

Sorry for not explaining my mission clearly, I am looking to train the vocabulary from a text using the BBPE (Byte Pair Encoding) method. What is the best way to preprocess the text before training it with SentencePiece? Should I use the former approach or is the latter method？Or i don't have to preprocess the text at all?

raw text(only punctuation to split the sentence): "青光闪动，一柄青钢剑倏地刺出，指向在年汉子左肩"

former way(split every characters independently): "青 光 闪 动 ，一 柄 青 钢 剑 倏 地 刺 出 ，指 向 在 年 汉 子 左 肩"

latter way(pre-knowledge of chinese phrase): "青光 闪动，一柄 青钢剑 倏地 刺出 ，指向 在年 汉子 左肩"
