### ISSUE TITLE
the value Conflict.

### ISSUE THREAD

**Issue by xzdong-2019** [google/sentencepiece#930]
hello, 
      i use the module load the multilingual-e5-small [sentencepiece.bpe.model]， when i encode the text ,  I found that each value of the input_ids is one less than the python versions. why?
 

my code:
sentencepiece::SentencePieceProcessor processor;
processor.Load("sentencepiece.bpe.model");
std::vector<int> ids;
string input_text="hello world";
processor.Encode(input_text, &ids);

**Comment by taku910** [comment]
Which token is actually added to input_ids in python. If they are bos/eos tokens,  it would be possible that add_bos/eos options are passed to encode methods in python module.

Could you show the minimum piece of code that reproduces the problems?

**Comment by xzdong-2019** [comment]
this is my python code:
tokenizer = AutoTokenizer.from_pretrained(bert_path)
batch_dict = tokenizer(input_text, max_length=512, padding=True, truncation=True, return_tensors='pt')
input_ids =  batch_dict["input_ids"]

**Comment by xzdong-2019** [comment]
hello， this is my python code show decode result :
['<s>', '▁我', '就是', '相', '测试', '一下', '</s>']
it add <s> & </s>， and i want to know how add the special word in c++.

**Comment by xzdong-2019** [comment]
My understanding is that the sentencebpe model only retains vocabulary, and the Python code also loads some configuration files such as tokenizer.json during loading. Therefore, inconsistencies may occur, which can be corrected through post-processing to align with Python.
