### ISSUE TITLE
[Question] How does encoding work?

### ISSUE THREAD

**Issue by 99991** [google/sentencepiece#931]
I am trying to understand how SentencePiece encoding works. My current understanding is:

* A model is loaded. The model can map "pieces" to "scores".
* A given text is prepended with the `"▁"` character.
* All `" "` characters are replaced with `"▁"`.
* The text is split into pieces such that the sum of the scores of the individual pieces is maximized.

I tried to split several sentences to see whether the split produced by SentencePiece has the largest score, but that does not seem to be the case. In addition, the absolute magnitude of the score values seems much larger than I'd expect for log probabilities. Is this score calculation incorrect? Or is there some error in my understanding?

Here are some split examples using the [tokenizer.model](https://huggingface.co/PY007/TinyLlama-1.1B-intermediate-step-715k-1.5T/blob/main/tokenizer.model) from TinyLlama, which I believe is almost the same as the tokenizer from the regularly sized llama.

```python
from sentencepiece import SentencePieceProcessor

# download tokenizer.model from
# https://huggingface.co/PY007/TinyLlama-1.1B-intermediate-step-715k-1.5T/resolve/main/tokenizer.model
s = SentencePieceProcessor("tokenizer.model")

for text in ["r spl", "Hello, World!", "kan je draaipunt ?"]:
    print(repr(text), "split into", s.encode_as_pieces(text))
print()

for pieces in [
    ['▁r', '▁s', 'p', 'l'],
    ['▁r', '▁spl'], # <--- does not have largest score among 3 splits
    ['▁r', '▁s', 'pl'],

    ['▁Hello', ',', '▁Wor', 'ld', '!'],
    ['▁Hello', ',', '▁World', '!'], # <--- does not have largest score
    ['▁Hello', ',', '▁W', 'or', 'ld', '!'],

    ['▁kan', '▁je', '▁dra', 'a', 'ip', 'u', 'n', 't', '▁?'],
    ['▁kan', '▁je', '▁dra', 'a', 'i', 'pu', 'nt', '▁?'],
    ['▁kan', '▁je', '▁dra', 'a', 'ip', 'unt', '▁?'], # <--- ok (does have largest score)
]:
    score = sum(s.get_score(s.piece_to_id(piece)) for piece in pieces)
    print(f"Score {score:10.2f} for {pieces}")
```

#### Output

```python
'r spl' split into ['▁r', '▁spl']
'Hello, World!' split into ['▁Hello', ',', '▁World', '!']
'kan je draaipunt ?' split into ['▁kan', '▁je', '▁dra', 'a', 'ip', 'unt', '▁?']

Score  -59363.00 for ['▁r', '▁s', 'p', 'l']
Score   -8382.00 for ['▁r', '▁spl'] # <--- does not have largest score among 3 splits
Score    -428.00 for ['▁r', '▁s', 'pl']

Score  -93723.00 for ['▁Hello', ',', '▁Wor', 'ld', '!']
Score  -76677.00 for ['▁Hello', ',', '▁World', '!'] # <--- does not have largest score
Score  -74473.00 for ['▁Hello', ',', '▁W', 'or', 'ld', '!']

Score -135186.00 for ['▁kan', '▁je', '▁dra', 'a', 'ip', 'u', 'n', 't', '▁?']
Score  -79360.00 for ['▁kan', '▁je', '▁dra', 'a', 'i', 'pu', 'nt', '▁?']
Score  -47728.00 for ['▁kan', '▁je', '▁dra', 'a', 'ip', 'unt', '▁?']  # <--- ok (does have largest score)
```

**Comment by taku910** [comment]
This model is not trained in ULM mode, but in BPE. So get_score() returns the merging priority, not the ULM score.
If ULM is used, the input text is split into pieces such that the sum of the scores of the individual pieces is maximized.

**Comment by 99991** [comment]
Thank you! This answers the question why the computed scores did not match.

I could also find out the answer to the general question "How does encoding [with BPE] work?"

1. Prepend the given text with the unicode underscore character `"▁"` ("\u2581"`)
2. Replace spaces with `"▁"`
3. Split a given text into smallest possible pieces (probably single characters)
4. Find the two neighboring pieces where the concatenation of the two neighboring pieces has the largest score.
    - The concatenation must also exist in the vocabulary.
    -  If two concatenations have the same score, the one which occurs earlier in the text is chosen.
    - This step can be done in $O(\log n)$ using a priority queue.
5. Merge those two neighboring pieces.
6. Continue with step 4 until no more mergeable pieces are found.

Here is an example for the string `"Hello, World!"` with unicode underscore `"▁" == "\u2581"`.

```python
Initial pieces:
['▁', 'H', 'e', 'l', 'l', 'o', ',', '▁', 'W', 'o', 'r', 'l', 'd', '!']

Merge 'o' and 'r' into 'or' with score -13.0. New pieces:
['▁', 'H', 'e', 'l', 'l', 'o', ',', '▁', 'W', 'or', 'l', 'd', '!']

Merge 'e' and 'l' into 'el' with score -36.0. New pieces:
['▁', 'H', 'el', 'l', 'o', ',', '▁', 'W', 'or', 'l', 'd', '!']

Merge '▁' and 'H' into '▁H' with score -120.0. New pieces:
['▁H', 'el', 'l', 'o', ',', '▁', 'W', 'or', 'l', 'd', '!']

Merge '▁' and 'W' into '▁W' with score -140.0. New pieces:
['▁H', 'el', 'l', 'o', ',', '▁W', 'or', 'l', 'd', '!']

Merge 'l' and 'o' into 'lo' with score -158.0. New pieces:
['▁H', 'el', 'lo', ',', '▁W', 'or', 'l', 'd', '!']

Merge 'l' and 'd' into 'ld' with score -171.0. New pieces:
['▁H', 'el', 'lo', ',', '▁W', 'or', 'ld', '!']

Merge 'or' and 'ld' into 'orld' with score -1354.0. New pieces:
['▁H', 'el', 'lo', ',', '▁W', 'orld', '!']

Merge '▁W' and 'orld' into '▁World' with score -2528.0. New pieces:
['▁H', 'el', 'lo', ',', '▁World', '!']

Merge 'el' and 'lo' into 'ello' with score -2897.0. New pieces:
['▁H', 'ello', ',', '▁World', '!']

Merge '▁H' and 'ello' into '▁Hello' with score -14784.0. New pieces:
['▁Hello', ',', '▁World', '!']
```
