### ISSUE TITLE
What is the appropriate vocabulary length setting?

### ISSUE THREAD

**Issue by 2088208** [google/sentencepiece#935]
`import sentencepiece as sp`
`sp.SentencePieceTrainer.train(
    input='./data/corpus.txt',
    model_prefix='tokenizer',
    vocab_size=3000,
    character_coverage=1.0,
    model_type="bpe"
)`
As above, what is the appropriate setting for `vocab_size`? Is it determined based on the training corpus or something?

**Comment by taku910** [comment]
https://github.com/google/sentencepiece/issues/678
