### ISSUE TITLE
How to use EncodeAsIds for text that contains `<s>/</s>'

### ISSUE THREAD

**Issue by vgoklani** [google/sentencepiece#940]
Hey there,

I'm using the reference implementation of the Mistral 7B model with the trained sentencepiece tokenizer. 

I would like to tokenize this instruction and preserve the `<s>` & `</s>` tokens in the middle of the text, and have them mapped correctly to 1 & 2.

    text = "<s>[INST] Instruction [/INST] Model answer</s>[INST] Follow-up instruction [/INST]"

Unfortunately the code below chews up the tokens:

```python
import sentencepiece

t = sentencepiece.SentencePieceProcessor("/models/mistral-7B-v0.1/tokenizer.model")
text = "<s>[INST] Instruction [/INST] Model answer</s>[INST] Follow-up instruction [/INST]"
t.EncodeAsPieces(text)
```

```bash
['▁<',
 's',
 '>',
 '[',
 'INST',
 ']',
 '▁Inst',
 'ruction',
 '▁[',
 '/',
 'INST',
 ']',
 '▁Model',
 '▁answer',
 '</',
 's',
 '>',
 '[',
 'INST',
 ']',
 '▁Follow',
 '-',
 'up',
 '▁instruction',
 '▁[',
 '/',
 'INST',
 ']']
```

**Comment by taku910** [comment]
This is a FAQ. Please see https://github.com/google/sentencepiece/issues/215

**Comment by taku910** [comment]
These flags are stored in the model file, so you can modify the model (protobuf) at your-own-risk-basis.
