### ISSUE TITLE
Does bpe support num_threads parameter? 

### ISSUE THREAD

**Issue by Jieni05** [google/sentencepiece#941]
Does bpe support num_threads parameter? Why did I modify the num_threads parameter but found that only one cpu core was involved in the training process?

**Comment by Jieni05** [comment]
I tried to train sentencepiece on a 50 million row data set, but found that the speed was extremely slow. The training log did not update new information after "Tokenizing input sentences with whitespace: Done".

**Comment by taku910** [comment]
BPE doesn't support multi-threaded training. num_threads are not used.
