### ISSUE TITLE
Adding New Argument min_freq to SentencePieceTrainer.train in Python

### ISSUE THREAD

**Issue by hhwer** [google/sentencepiece#942]
Hello SentencePiece Team,

I am encountering an issue when trying to add a new argument `min_freq` to `SentencePieceTrainer.train` in Python. Below are the details of the changes I've made and the issue I'm facing.

### Changes Made
I have made the following modifications:

1. Added two lines in **spm_train_main.cc**:
   ```cpp
   SetTrainerSpecFromFlag(min_freq);
   ABSL_FLAG(int32, min_freq, kDefaultTrainerSpec.min_freq(), "min freq for threshold");
   ```
2. Added a line in **sentencepiece_model.proto**:
   ```proto
   optional int32 min_freq = 54 [default = 10]; // Under scope of message TrainerSpec {}
   ```
3. Then used the protoc command:
   ```bash
   protoc --python_out ../python/src/sentencepiece sentencepiece.proto sentencepiece_model.proto
   protoc --cpp_out ./builtin_pb/ sentencepiece.proto sentencepiece_model.proto
   ```
4. Finally, compiled the project with cmake and make -j $(nproc) & make install. After this, I'm **able to** pass the min_freq argument in the terminal:
   ```bash
   spm_train --min_freq=10 ...
   ```
### Issue in Python
However, I encounter a problem when using this new argument in Python. Specifically, when I try to use spm.SentencePieceTrainer.train(min_freq) in Python, it results in the following error:
   ```bash
   OSError: Not found: unknown field name "min_freq" in TrainerSpec
   ```

This occurs regardless of whether I use `pip install .` or `python setup.py install` in the sentencepiece/python directory.

### Additional Information
I noticed there is a SWIG file **'sentencepiece.i'** and a related file **'sentencepiece_wrap.cxx'**, but I'm unsure if I need to modify them.
I tried running `swig -python sentencepiece.i`, which created some new files that didn't exist before.

I would greatly appreciate any help or guidance on resolving this issue.

Thank you!

Best regards,

**Comment by taku910** [comment]
We need to add the rule in `src/spec_parser.h`

**Comment by taku910** [comment]
v0.2.0 introduced new parameters. you might check how the params are added by taking the diff between 0.1.99 and 0.2.0.
