### ISSUE TITLE
ImportError: cannot import name 'SentencePieceProcessor' from 'sentencepiece' (unknown location)

### ISSUE THREAD

**Issue by nikonikoni02** [google/sentencepiece#946]
code:
from transformers import AutoTokenizer, AutoModel
tokenizer = AutoTokenizer.from_pretrained("\models\THUDM_chatglm3-6b", trust_remote_code=True)
model = AutoModel.from_pretrained("\models\THUDM_chatglm3-6b", trust_remote_code=True, device='cuda')
model = model.eval()
response, history = model.chat(tokenizer, "你好", history=[])
print(response)

in Syper,it shows :
ImportError: cannot import name 'SentencePieceProcessor' from 'sentencepiece' (unknown location)

in jupyter network ,it shows that:
ImportError: This modeling file requires the following packages that were not found in your environment: sentencepiece. Run `pip install sentencepiece`

**Comment by nikonikoni02** [comment]
i have run pip install sentencepiece already

**Comment by taku910** [comment]
Questions about libraries using sentencepiece are not accepted here. Please ask the developer of AutoTokenizer directly.
