### ISSUE TITLE
c++ API compilation problem

### ISSUE THREAD

**Issue by wangning7149** [google/sentencepiece#953]
Hello, I saw in the readme that only c++11 is required. My gcc version is 4.8.5, which supports c++11. However, when I compiled, it prompted that there was no string_view file. I checked and found that c This file is only available in ++17, and it is not convenient for me to upgrade the gcc version. Is there any other way?

**Comment by taku910** [comment]
sentencepiece requires C++17 and std::string_view.　I am sorry, but the only way is to upgrade C++.
