### ISSUE TITLE
How to safely extend vocabulary?

### ISSUE THREAD

**Issue by ekurtulus** [google/sentencepiece#956]
How can I extend the vocabulary of a BPE tokenizer safely on a corpus?

**Comment by taku910** [comment]
What do "extend the vocab" and "safely" mean?

**Comment by ekurtulus** [comment]
> What do "extend the vocab" and "safely" mean?

I want to extend the vocab of [Mistral-7B's](https://huggingface.co/mistralai/Mistral-7B-v0.1) BPE tokenizer. However, when I do this by manually adding tokens to the vocab file, the tokenizer loses its ability to reconstruct the input. Below is an example
![image](https://github.com/google/sentencepiece/assets/66876436/bcd8ef50-161e-4fe4-a38a-96b206b7ffb4)

How can I take a pretrained tokenizer and extend its vocabulary such that it retains its ability to reconstruct the input.

**Comment by taku910** [comment]
The model file is stored as the serialized protobuf, so we can manually modify the model at-your-own-risk-basis.

Please check the following theads.
https://github.com/google/sentencepiece/issues/121
