### ISSUE TITLE
Merging tokenizers issue

### ISSUE THREAD

**Issue by gordicaleksa** [google/sentencepiece#964]
I was playing with [this merging code](https://github.com/ymcui/Chinese-LLaMA-Alpaca/blob/main/scripts/merge_tokenizer/merge_tokenizers.py#L35) copying it here as well:

```
llama_spm_tokens_set=set(p.piece for p in llama_spm.pieces)

for p in chinese_spm.pieces:
    piece = p.piece
    if piece not in llama_spm_tokens_set:
        new_p = sp_pb2_model.ModelProto().SentencePiece()
        new_p.piece = piece
        new_p.score = 0
        llama_spm.pieces.append(new_p)
print(f"New model pieces: {len(llama_spm.pieces)}")
```

and after some debugging I noticed that this final tokenizer's merge list is bloated.

Namely it's the sum of the llama_spm's merge rules, chinese_spm's merge rules + it added some new ones (10k+ of them).

1) How could this happen? 
2) And also how are the merge rules even propagated given that `new_p` is only initialized with the `piece` information which is simply a vocab item and no merge rules were set explicitly?

Is this intended behavior?

**Comment by taku910** [comment]
The basic premise is that model rewriting and merging are not officially supported. Please do everything at your own risk.
It is unclear what is intended behavior and what "bloated" means in this context, so we cannot answer.

**Comment by gordicaleksa** [comment]
Hey Taku!

The idea is quite simple: most tokenizers focus only on English language and subsequently LLMs are trained using those tokenizers thus rendering their embedding tables tied up to that tokenizer.

If you want to create a new LLM for a different non-English language without spending millions in compute you can extend the tokenizer and append new rows to the embedding table and then do continued pretraining instead of pretraining from scratch.

The idea here is to simply combine the merge rules from a new target language specific tokenizer and the old English one.

Can you maybe clarify the current behavior?

**Comment by taku910** [comment]
We can see the motivation, but were not sure of the meaning of the bloat list.

Assuming that BPE model is used, the set of pieces (tokens) are stored in the protobuf file with the merging priority (larger is better).  'score' field is the priority. In addition, BPE's vocab must be inclusionary relationship because of the bottom-up tokenization.  This is all the information we can currently provide and anything more is completely unsupported. Our apologies.

**Comment by rahul-sarvam** [comment]
@gordicaleksa I also had this question. How are the merge rules for the new tokens created if we don't give any? Why does this work well, but training a vanilla BPE tokenizer from say HF does not. So many questions. If you ever figure it out, please share 😄
