### ISSUE TITLE
coredump when build with CXXFLAG `-Wp,-D_GLIBCXX_ASSERTIONS`

### ISSUE THREAD

**Issue by samchugit** [google/sentencepiece#966]
coredump when build and test sentencepiece 0.1.99 with CXXFLAG `-Wp,-D_GLIBCXX_ASSERTIONS`

This is when it crashed.
![image](https://github.com/google/sentencepiece/assets/27361279/719978ad-0261-4e0f-8879-a8f51f9050a7)

This is gdb back trace.
![image](https://github.com/google/sentencepiece/assets/27361279/4af91761-daa1-44f5-b04d-0c3c7c56a7fa)

I wonder if this line will access out of bounds of the vector. https://github.com/google/sentencepiece/blob/3863f7648e5d8edb571ac592f3ac4f5f0695275a/src/unigram_model_trainer.cc#L236

**Comment by taku910** [comment]
Thank you for the report. Wil fix it in the next release.

**Comment by Henry-ZHR** [comment]
I still face coredump with v0.2.0.

![](https://github.com/google/sentencepiece/assets/51886614/bab341e1-84be-45db-8844-fde0a9766669)

Seems the same place?

**Comment by Henry-ZHR** [comment]
@taku910
