### ISSUE TITLE
Getting requirements to build wheel did not run successfully.

### ISSUE THREAD

**Issue by sapatmohit** [google/sentencepiece#971]
PS D:\Translator> pip install sentencepiece
Collecting sentencepiece
Using cached sentencepiece-0.1.99.tar.gz (2.6 MB)
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [27 lines of output]
Traceback (most recent call last):
File "", line 198, in _run_module_as_main
File "", line 88, in run_code
File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Scripts\cmake.exe_main.py", line 4, in
ModuleNotFoundError: No module named 'cmake'
Traceback (most recent call last):
File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 353, in
main()
File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip_vendor\pyproject_hooks_in_process_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Temp\pip-build-env-tr7cgws3\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\HP\AppData\Local\Temp\pip-build-env-tr7cgws3\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
self.run_setup()
File "C:\Users\HP\AppData\Local\Temp\pip-build-env-tr7cgws3\overlay\Lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
File "C:\Users\HP\AppData\Local\Temp\pip-build-env-tr7cgws3\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
exec(code, locals())
File "", line 126, in
File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 413, in check_call
raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'sentencepiece', '-A', 'x64', '-B', 'build', '-DSPM_ENABLE_SHARED=OFF', '-DCMAKE_INSTALL_PREFIX=build\root']' returned non-zero exit status 1.
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Help me with this, i was trying to install sentencepiece module

**Comment by severinsimmler** [comment]
Duplicate of https://github.com/google/sentencepiece/issues/932. You can try to install the pre-release of v0.2.0: https://github.com/google/sentencepiece/releases/tag/v0.2.0pre1

**Comment by sapatmohit** [comment]
It worked after downgrading python version to 3.10 from 3.12

**Comment by Ollie345** [comment]
i am having the same issue and i am using python version 3.8.10

**Comment by severinsimmler** [comment]
@Ollie345 Can you provide more information? Which version of sentencepiece are you trying to install? There are Python 3.8 wheels for v0.2.0: https://pypi.org/project/sentencepiece/0.2.0/#files

**Comment by vutuongvy101** [comment]
> i am having the same issue and i am using python version 3.8.10

same issue

**Comment by Davidogola** [comment]
Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      C:\Users\MWENYEJI\AppData\Local\Temp\pip-build-env-_74ga2n_\overlay\Lib\site-packages\setuptools\_distutils\dist.py:261: UserWarning: Unknown distribution option: 'test_suite'
        warnings.warn(msg)
      error in arabic_reshaper setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by diennd25** [comment]
> It worked after downgrading python version to 3.10 from 3.12

This worked for me as well

**Comment by Roja1303** [comment]
> Getting requirements to build wheel ... error error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> [49 lines of output] Compiling src/gevent/resolver/cares.pyx because it changed. [1/1] Cythonizing src/gevent/resolver/cares.pyx performance hint: src/gevent/libev/corecext.pyx:1325:0: Exception check on '_syserr_cb' will always require the GIL to be acquired. Possible solutions: 1. Declare '_syserr_cb' as 'noexcept' if you control the definition and you're sure you don't want the function to raise exceptions. 2. Use an 'int' return type on '_syserr_cb' to allow an error code to be returned.
> 
> ```
>   Error compiling Cython file:
>   ------------------------------------------------------------
>   ...
>   cdef tuple integer_types
>   
>   if sys.version_info[0] >= 3:
>       integer_types = int,
>   else:
>       integer_types = (int, long)
>                             ^
>   ------------------------------------------------------------
>   
>   src/gevent/libev/corecext.pyx:60:26: undeclared name not builtin: long
>   Compiling src/gevent/libev/corecext.pyx because it changed.
>   [1/1] Cythonizing src/gevent/libev/corecext.pyx
>   Traceback (most recent call last):
>     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 389, in <module>
>       main()
>     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 373, in main
>       json_out["return_val"] = hook(**hook_input["kwargs"])
>                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 143, in get_requires_for_build_wheel
>       return hook(config_settings)
>              ^^^^^^^^^^^^^^^^^^^^^
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
>       return self._get_build_requires(config_settings, requirements=[])
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
>       self.run_setup()
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 522, in run_setup
>       super().run_setup(setup_script=setup_script)
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 320, in run_setup
>       exec(code, locals())
>     File "<string>", line 50, in <module>
>     File "/tmp/pip-install-m7ujvz4h/gevent_0549b9fa80c94490b292d7f37c380a3d/_setuputils.py", line 237, in cythonize1
>       new_ext = cythonize(
>                 ^^^^^^^^^^
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/Cython/Build/Dependencies.py", line 1109, in cythonize
>       cythonize_one(*args)
>     File "/tmp/pip-build-env-03rqx993/overlay/local/lib/python3.11/dist-packages/Cython/Build/Dependencies.py", line 1256, in cythonize_one
>       raise CompileError(None, pyx_file)
>   Cython.Compiler.Errors.CompileError: src/gevent/libev/corecext.pyx
>   [end of output]
> ```
> 
> note: This error originates from a subprocess, and is likely not a problem with pip. error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully. │ exit code: 1 ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

even i am facing same issues

**Comment by Experimento002** [comment]
How i can install pygame in 2026?
