### ISSUE TITLE
HELP NEEDED Mask Token in SentencePiece tokenizer HELP NEEDED

### ISSUE THREAD

**Issue by debrupf2946** [google/sentencepiece#980]
T5 using **sentencepiece-tokenizer** ,I want to perform **masked language modeling**,
In SentencePiece only There are only BOS,EOS,UNK,PAD so **no mask token** ,so how to **create and add a mask token** when the **model is called from preteset**

**Comment by taku910** [comment]
See https://github.com/google/sentencepiece/blob/master/doc/special_symbols.md
https://github.com/google/sentencepiece/blob/master/python/sentencepiece_python_module_example.ipynb
