### ISSUE TITLE
Any api for setting  user defined symbols?

### ISSUE THREAD

**Issue by zhangyuhanjc** [google/sentencepiece#991]
is there any api to achieve --user_defined_symbols='' ?
i only find function SetEncodeExtraOptions which cannot set user_defined_symbols

**Comment by taku910** [comment]
Adding the user_defined_symbols to the pre-trained model is not officially supported, but possible at-your-own-risk-basis as it is stored as protobuf.

https://github.com/google/sentencepiece/issues/121
