### ISSUE TITLE
Error when running this command: pip install 'transformers[tf-cpu]' on mac

### ISSUE THREAD

**Issue by ambadumbuya** [google/sentencepiece#993]
Please can someone help with the above this error when I run this command pip install 'transformers[tf-cpu]' I have already tried to upgrade my pip and setup tools in addition I tries to follow the steps here: https://www.partitionwizard.com/partitionmanager/python-setup-py-egg-info-failed-with-error-code-1.html even installing ez_setup but the issue still persists. 

Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [2 lines of output]
      /bin/sh: pkg-config: command not found
      Failed to find sentencepiece pkgconfig
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by taku910** [comment]
Please check https://github.com/google/sentencepiece/issues/378
